var searchData=
[
  ['handle_20with_20extreme_20care_0',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md979',1,'']]],
  ['handles_20blocking_20and_20timeouts_1',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md145',1,'']]],
  ['handling_2',['Handling',['../group__udp.html#autotoc_md575',1,'⏱ Timeout Handling'],['../group__internal.html#autotoc_md506',1,'⚠️ Error Handling'],['../classjsocketpp_1_1Socket.html#autotoc_md810',1,'Error Handling'],['../group__udp.html#autotoc_md595',1,'IPv6 Handling'],['../group__udp.html#autotoc_md601',1,'IPv6 Handling'],['../group__udp.html#autotoc_md615',1,'IPv6 Handling']]],
  ['handling_3',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md83',1,'']]],
  ['handling_20socket_20exceptions_4',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md971',1,'']]],
  ['handling_20work_5',['How does error handling work?',['../index.html#autotoc_md439',1,'']]],
  ['happens_20when_20multiple_20sockets_20bind_20to_20the_20same_20port_6',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['haspendingdata_7',['hasPendingData',['../group__udp.html#gab844c09fb75f131bf6ba0bd004c63433',1,'jsocketpp::DatagramSocket']]],
  ['helpers_8',['Internal Helpers',['../group__internal.html',1,'']]],
  ['hints_20structure_20behavior_9',['Hints Structure Behavior',['../group__internal.html#autotoc_md490',1,'']]],
  ['hood_3a_20how_20socket_20types_20work_10',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['hood_3a_20how_20sockets_20operate_11',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md309',1,'']]],
  ['hooks_12',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md458',1,'']]],
  ['hooks_13',['Pre-commit hooks',['../index.html#autotoc_md428',1,'']]],
  ['how_20does_20error_20handling_20work_14',['How does error handling work?',['../index.html#autotoc_md439',1,'']]],
  ['how_20it_20works_20internally_15',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['how_20jsocketpp_20handles_20blocking_20and_20timeouts_16',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md145',1,'']]],
  ['how_20socket_20types_20work_17',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['how_20sockets_20operate_18',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md309',1,'']]],
  ['how_20sockets_20work_3a_20the_20lifecycle_19',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md305',1,'']]],
  ['how_20this_20relates_20to_20jsocketpp_20',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md278',1,'']]],
  ['hybrid_21',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md53',1,'']]]
];
