var searchData=
[
  ['echo_20server_0',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md459',1,'']]],
  ['echo_20server_20and_20client_1',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['enablebroadcast_2',['enableBroadcast',['../classjsocketpp_1_1DatagramSocket.html#ab3ad0faf65e430cc8867d76c6a84df87',1,'jsocketpp::DatagramSocket']]],
  ['enablekeepalive_3',['enableKeepAlive',['../classjsocketpp_1_1Socket.html#a4c37f604fb8534760e00e077f5c4c5cf',1,'jsocketpp::Socket']]],
  ['enablenodelay_4',['enableNoDelay',['../classjsocketpp_1_1Socket.html#ac2975ed8e1d02b5f823bc0af50c034c7',1,'jsocketpp::Socket']]],
  ['enforcement_5',['Enforcement',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md5',1,'']]],
  ['epoll_6',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md246',1,'']]],
  ['epoll_20as_20alternatives_7',['epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['error_20handling_8',['Error Handling',['../group__tcp.html#autotoc_md440',1,'Error Handling'],['../classjsocketpp_1_1Socket.html#autotoc_md451',1,'Error Handling']]],
  ['example_9',['Example',['../classjsocketpp_1_1SocketTimeoutException.html#autotoc_md457',1,'Example'],['../index.html#autotoc_md36',1,'TCP Example'],['../classjsocketpp_1_1Socket.html#autotoc_md449',1,'Typical Usage Example'],['../index.html#autotoc_md37',1,'UDP Example'],['../group__BUILD__AND__USAGE.html#autotoc_md66',1,'Usage Example'],['../group__tcp.html#autotoc_md435',1,'Usage Example'],['../group__tcp.html#autotoc_md441',1,'Usage Example']]],
  ['example_20behavior_10',['🛠️ Example behavior',['../group__address__reuse.html#autotoc_md118',1,'']]],
  ['example_20of_20a_20simple_20server_20client_20integration_20test_3a_11',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md394',1,'']]],
  ['example_20portfile_20cmake_12',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md410',1,'']]],
  ['example_20receiving_13',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md427',1,'']]],
  ['example_20sending_14',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md428',1,'']]],
  ['example_20usage_15',['7. Example Usage',['../group__ServerSocket__Lifecycle.html#autotoc_md96',1,'']]],
  ['example_20use_3a_16',['Example Use:',['../group__async__io.html#autotoc_md204',1,'']]],
  ['example_20vcpkg_20json_17',['Example &lt;span class=&quot;tt&quot;&gt;vcpkg.json&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md409',1,'']]],
  ['example_20with_20google_20mock_3a_18',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md398',1,'']]],
  ['example_3a_20binding_20to_20all_20interfaces_19',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md210',1,'']]],
  ['example_3a_20catching_20and_20handling_20socket_20exceptions_20',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md456',1,'']]],
  ['example_3a_20simple_20client_21',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md460',1,'']]],
  ['example_3a_20simple_20echo_20server_22',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md459',1,'']]],
  ['example_3a_20simple_20udp_20echo_20server_20and_20client_23',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['example_3a_20using_20google_20mock_20to_20mock_20recv_20and_20send_3a_24',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['examples_25',['Examples',['../group__underlying__socket__api.html#autotoc_md366',1,'5. Socket API in Action: Practical Examples'],['../group__socket-options.html#autotoc_md278',1,'Examples']]],
  ['exception_20classes_26',['Exception Classes',['../group__exceptions.html',1,'']]],
  ['exceptions_27',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md456',1,'']]],
  ['explicit_28',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md81',1,'']]],
  ['expose_20windows_20so_5freuseaddr_29',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md155',1,'']]]
];
