var searchData=
[
  ['udp_0',['UDP',['../group__sockets__theory.html#autotoc_md323',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md331',1,'Datagram Sockets (UDP)'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md422',1,'What is UDP?']]],
  ['udp_20and_20unix_20sockets_1',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md308',1,'']]],
  ['udp_20echo_20server_20and_20client_2',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['udp_20example_3',['UDP Example',['../index.html#autotoc_md37',1,'']]],
  ['udp_20server_20and_20client_20c_20af_5finet_4',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md368',1,'']]],
  ['udp_20sockets_5',['UDP Sockets',['../group__udp.html',1,'']]],
  ['udp_20sockets_20datagramsocket_20multicastsocket_6',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md269',1,'']]],
  ['under_20the_20hood_3a_20how_20socket_20types_20work_7',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md329',1,'']]],
  ['under_20the_20hood_3a_20how_20sockets_20operate_8',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md343',1,'']]],
  ['underlying_5fsocket_5fapi_2emd_9',['underlying_socket_api.md',['../underlying__socket__api_8md.html',1,'']]],
  ['understanding_20bind_20_3a_20binding_20to_20all_20interfaces_20vs_20specific_20interfaces_10',['Understanding bind : Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'Understanding &lt;tt&gt;bind()&lt;/tt&gt;: Binding to All Interfaces vs Specific Interfaces'],['../group__bind__interfaces.html#autotoc_md207',1,'Understanding <span class="tt">bind()</span>: Binding to All Interfaces vs Specific Interfaces']]],
  ['understanding_20socket_20states_11',['Understanding Socket States',['../group__socket__states.html',1,'Understanding Socket States'],['../group__socket__states.html#autotoc_md299',1,'Understanding Socket States']]],
  ['unit_20testing_20and_20integration_20guide_12',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'Unit Testing and Integration Guide'],['../group__unit__tests.html#autotoc_md386',1,'Unit Testing and Integration Guide']]],
  ['unit_20testing_20in_20c_2017_3a_13',['Tools for Unit Testing in C++17:',['../group__unit__tests.html#autotoc_md388',1,'']]],
  ['unit_20tests_3a_14',['Unit Tests:',['../group__unit__tests.html#autotoc_md387',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md397',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['unit_5ftests_2emd_15',['unit_tests.md',['../unit__tests_8md.html',1,'']]],
  ['unix_16',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md346',1,'']]],
  ['unix_20domain_20sockets_17',['Unix Domain Sockets',['../group__unix.html',1,'Unix Domain Sockets'],['../group__sockets__theory.html#autotoc_md333',1,'Unix Domain Sockets']]],
  ['unix_20domain_20sockets_20local_20ipc_18',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md325',1,'']]],
  ['unix_20domain_20sockets_20unixsocket_19',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md272',1,'']]],
  ['unix_20linux_20',['Unix/Linux',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['unix_20linux_20only_21',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['unix_20linux_3a_22',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['unix_20sockets_23',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md308',1,'']]],
  ['unixsocket_24',['UnixSocket',['../group__socket-options.html#autotoc_md272',1,'4. Unix Domain Sockets (<span class="tt">UnixSocket</span>)'],['../classjsocketpp_1_1UnixSocket.html',1,'jsocketpp::UnixSocket'],['../classjsocketpp_1_1UnixSocket.html#a48cbce97dc73550be231c15a2f07a22f',1,'jsocketpp::UnixSocket::UnixSocket(std::string_view path, std::size_t bufferSize=512)'],['../classjsocketpp_1_1UnixSocket.html#ade5b73a78542992dff1c6f4fd0df5562',1,'jsocketpp::UnixSocket::UnixSocket(const UnixSocket &amp;)=delete'],['../classjsocketpp_1_1UnixSocket.html#ac0df0f22e6396a2a76fd28be194f40d6',1,'jsocketpp::UnixSocket::UnixSocket(UnixSocket &amp;&amp;other) noexcept'],['../classjsocketpp_1_1UnixSocket.html#a4ae311fe42de02908c702eca2806debd',1,'jsocketpp::UnixSocket::UnixSocket()']]],
  ['unixsocket_2ecpp_25',['UnixSocket.cpp',['../UnixSocket_8cpp.html',1,'']]],
  ['unixsocket_2ehpp_26',['UnixSocket.hpp',['../UnixSocket_8hpp.html',1,'']]],
  ['up_20real_20server_20and_20client_3a_27',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['usage_28',['Usage',['../group__ServerSocket__Lifecycle.html#autotoc_md96',1,'7. Example Usage'],['../classjsocketpp_1_1Socket.html#autotoc_md454',1,'Advanced Usage'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md431',1,'Typical Usage']]],
  ['usage_20example_29',['Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md449',1,'Typical Usage Example'],['../group__BUILD__AND__USAGE.html#autotoc_md66',1,'Usage Example'],['../group__tcp.html#autotoc_md435',1,'Usage Example'],['../group__tcp.html#autotoc_md441',1,'Usage Example']]],
  ['usage_20example_20receiving_30',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md427',1,'']]],
  ['usage_20example_20sending_31',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md428',1,'']]],
  ['usage_20guide_32',['Usage Guide',['../group__BUILD__AND__USAGE.html',1,'jsocketpp: Build, Test, and Usage Guide'],['../group__BUILD__AND__USAGE.html#autotoc_md50',1,'jsocketpp: Build, Test, and Usage Guide']]],
  ['use_20case_33',['✅ Use Case',['../group__address__reuse.html#autotoc_md126',1,'']]],
  ['use_20cases_34',['📦 Common use cases',['../group__address__reuse.html#autotoc_md107',1,'']]],
  ['use_20cases_20and_20applications_35',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md375',1,'']]],
  ['use_20select_20for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_36',['use select for asynchronous I O operations Does it make sense to provide poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['use_3a_37',['Example Use:',['../group__async__io.html#autotoc_md204',1,'']]],
  ['used_38',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md240',1,'']]],
  ['user_20guides_39',['User Guides',['../group__docs.html',1,'']]],
  ['using_20cmake_20for_20platform_20specific_20tests_3a_40',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md396',1,'']]],
  ['using_20cmake_20presets_20recommended_41',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md57',1,'']]],
  ['using_20google_20mock_20to_20mock_20recv_20and_20send_3a_42',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['using_20the_20makefile_43',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md59',1,'']]]
];
