var searchData=
[
  ['⚙️_20behavior_0',['⚙️ Behavior',['../group__address__reuse.html#autotoc_md90',1,'⚙️ Behavior'],['../group__internal.html#autotoc_md591',1,'⚙️ Behavior'],['../group__internal.html#autotoc_md596',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md631',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md643',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md678',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md756',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md760',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md764',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md832',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md850',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md861',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1028',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1033',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1038',1,'⚙️ Behavior']]],
  ['⚙️_20configuration_1',['⚙️ Configuration',['../group__tcp.html#autotoc_md843',1,'']]],
  ['⚙️_20configuration_20of_20accepted_20socket_2',['⚙️ Configuration of Accepted Socket',['../group__tcp.html#autotoc_md794',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md803',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md812',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md823',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md856',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md869',1,'⚙️ Configuration of Accepted Socket']]],
  ['⚙️_20core_20behavior_3',['⚙️ Core Behavior',['../group__udp.html#autotoc_md648',1,'⚙️ Core Behavior'],['../group__udp.html#autotoc_md667',1,'⚙️ Core Behavior'],['../group__udp.html#autotoc_md684',1,'⚙️ Core Behavior'],['../group__udp.html#autotoc_md691',1,'⚙️ Core Behavior'],['../group__udp.html#autotoc_md740',1,'⚙️ Core Behavior']]],
  ['⚙️_20core_20behaviors_4',['⚙️ Core Behaviors',['../group__udp.html#autotoc_md710',1,'']]],
  ['⚙️_20implementation_20details_5',['⚙️ Implementation Details',['../group__udp.html#autotoc_md735',1,'']]],
  ['⚙️_20platform_20behavior_6',['⚙️ Platform Behavior',['../group__udp.html#autotoc_md726',1,'']]]
];
