var searchData=
[
  ['patterns_20and_20best_20practices_0',['Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['peer_20model_1',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md363',1,'']]],
  ['peer_20to_20peer_20model_2',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md363',1,'']]],
  ['performance_20considerations_3',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md335',1,'']]],
  ['platform_20api_20considerations_4',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md250',1,'']]],
  ['platform_20apis_5',['Platform APIs',['../group__sockets__theory.html',1,'Sockets: Theory, Types, and Platform APIs'],['../group__sockets__theory.html#autotoc_md316',1,'Sockets: Theory, Types, and Platform APIs']]],
  ['platform_20behavior_6',['Platform Behavior',['../group__tcp.html#autotoc_md445',1,'']]],
  ['platform_20notes_7',['Platform Notes',['../group__BUILD__AND__USAGE.html#autotoc_md72',1,'']]],
  ['platform_20socket_20library_8',['jsocketpp: Modern C++17 Cross-Platform Socket Library',['../index.html',1,'']]],
  ['platform_20socket_20library_9',['jsocketpp: C++17 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['platform_20specific_20apis_10',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md345',1,'']]],
  ['platform_20specific_20considerations_11',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md376',1,'']]],
  ['platform_20specific_20tests_3a_12',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md396',1,'']]],
  ['platform_20support_13',['Platform Support',['../group__socket-options.html#autotoc_md262',1,'Cross-Platform Support'],['../group__tcp.html#autotoc_md439',1,'Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md453',1,'Platform Support']]],
  ['platform_3a_14',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md395',1,'']]],
  ['pledge_15',['Our Pledge',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md1',1,'']]],
  ['poco_3a_3anet_16',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md290',1,'']]],
  ['poll_17',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md244',1,'']]],
  ['poll_20and_20epoll_20as_20alternatives_18',['poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['port_19',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['port_20',['port',['../classjsocketpp_1_1DatagramPacket.html#aaad70ff22977b851534e88b2b45af295',1,'jsocketpp::DatagramPacket']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_21',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md81',1,'']]],
  ['port_20in_20the_20constructor_22',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md82',1,'']]],
  ['port_20locally_23',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md412',1,'']]],
  ['portability_24',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md86',1,'']]],
  ['portfile_25',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md408',1,'']]],
  ['portfile_20cmake_26',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md410',1,'']]],
  ['posix_20approach_27',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md77',1,'']]],
  ['posix_20linux_20macos_20unix_28',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md346',1,'']]],
  ['posix_20style_29',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md91',1,'']]],
  ['posix_20winsock_20apis_30',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md294',1,'']]],
  ['practical_20considerations_31',['7. Practical Considerations',['../group__underlying__socket__api.html#autotoc_md384',1,'']]],
  ['practical_20examples_32',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md366',1,'']]],
  ['practical_20implications_33',['Practical Implications',['../group__socket__states.html#autotoc_md310',1,'']]],
  ['practical_20implications_34',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['practical_20recommendations_35',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md252',1,'']]],
  ['practices_36',['Practices',['../group__async__io.html#autotoc_md203',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md418',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md234',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md212',1,'Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['practices_20recap_37',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md167',1,'']]],
  ['pre_20commit_20hooks_38',['4. Pre-commit Hooks',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md15',1,'']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_39',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md227',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_40',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md406',1,'']]],
  ['prerequisites_41',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md219',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md404',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md54',1,'Prerequisites']]],
  ['presets_20recommended_42',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md57',1,'']]],
  ['problematic_20on_20windows_43',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md145',1,'']]],
  ['project_44',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md68',1,'']]],
  ['project_20conan_20friendly_45',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md223',1,'']]],
  ['pros_20and_20cons_46',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md89',1,'']]],
  ['protocols_20and_20the_20socket_20api_47',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md365',1,'']]],
  ['provide_20poll_20and_20epoll_20as_20alternatives_48',['provide poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['publishing_20jsocketpp_20to_20the_20conan_20center_20index_20cci_49',['Publishing jsocketpp to the Conan Center Index CCI',['../group__conan__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the Conan Center Index (CCI)'],['../group__conan__publish__guide.html#autotoc_md217',1,'Publishing <span class="tt">jsocketpp</span> to the Conan Center Index (CCI)']]],
  ['publishing_20jsocketpp_20to_20the_20vcpkg_20registry_50',['Publishing jsocketpp to the vcpkg Registry',['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry'],['../group__vcpkg__publish__guide.html#autotoc_md402',1,'Publishing <span class="tt">jsocketpp</span> to the vcpkg Registry']]],
  ['pull_20request_20to_20cci_51',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md230',1,'']]],
  ['pull_20requests_52',['2. Submitting Pull Requests',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md11',1,'']]],
  ['purpose_53',['🎯 Purpose',['../group__address__reuse.html#autotoc_md123',1,'']]],
  ['py_54',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md221',1,'']]],
  ['python_20af_5finet_55',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md367',1,'']]]
];
