var searchData=
[
  ['b_20fully_20step_20by_20step_20posix_20style_0',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['b_20portability_1',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md36',1,'']]],
  ['based_20on_20connection_20mode_2',['🔁 Behavior Based on Connection Mode',['../group__udp.html#autotoc_md531',1,'']]],
  ['basic_20api_3',['Basic API',['../classjsocketpp_1_1ServerSocket.html#autotoc_md599',1,'']]],
  ['basics_4',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['behavior_5',['Behavior',['../group__tcp.html#autotoc_md605',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md614',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md623',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md634',1,'⏱ Timeout Behavior'],['../group__address__reuse.html#autotoc_md67',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md645',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md663',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md674',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md836',1,'⚙️ Behavior'],['../group__socketopts.html#autotoc_md1004',1,'⚠️ Platform Behavior'],['../group__tcp.html#autotoc_md734',1,'🌍 Behavior'],['../group__socketopts.html#autotoc_md927',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md932',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md937',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md942',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md947',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md958',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md967',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md995',1,'🔀 Platform Behavior'],['../group__tcp.html#autotoc_md654',1,'🔁 Blocking Behavior'],['../group__socketopts.html#autotoc_md981',1,'🔐 Platform Behavior'],['../group__udp.html#autotoc_md478',1,'Behavior'],['../group__udp.html#autotoc_md485',1,'Behavior'],['../group__udp.html#autotoc_md500',1,'Behavior'],['../group__udp.html#autotoc_md502',1,'Behavior'],['../group__udp.html#autotoc_md504',1,'Behavior'],['../group__udp.html#autotoc_md510',1,'Behavior'],['../group__udp.html#autotoc_md554',1,'Behavior'],['../group__udp.html#autotoc_md561',1,'Behavior'],['../group__socketopts.html#autotoc_md914',1,'Behavior'],['../group__tcp.html#autotoc_md718',1,'IPv4-Mapped IPv6 Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md588',1,'Platform Behavior'],['../group__tcp.html#autotoc_md686',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md895',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md898',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md902',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md908',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md920',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md924',1,'Platform Behavior'],['../group__tcp.html#autotoc_md828',1,'Protocol Behavior'],['../group__address__reuse.html#autotoc_md95',1,'Recommended Behavior']]],
  ['behavior_20based_20on_20connection_20mode_6',['🔁 Behavior Based on Connection Mode',['../group__udp.html#autotoc_md531',1,'']]],
  ['behavior_20by_20connection_20mode_7',['Behavior by Connection Mode',['../group__udp.html#autotoc_md545',1,'']]],
  ['behavior_20by_20mode_8',['🔁 Behavior by Mode',['../group__udp.html#autotoc_md538',1,'']]],
  ['behavior_20characteristics_9',['Behavior &amp;amp; Characteristics',['../group__udp.html#autotoc_md471',1,'']]],
  ['behavior_20summary_20by_20operation_10',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md951',1,'']]],
  ['behavior_3a_11',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md332',1,'']]],
  ['behavior_3a_20connect_20accept_20recv_20and_20send_12',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['best_20practices_13',['Best Practices',['../group__async__io.html#autotoc_md146',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md155',1,'Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['best_20practices_20recap_14',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['better_20alternative_3a_20what_20jsocketpp_20does_15',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['beyond_20the_20basics_16',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['bind_17',['bind',['../group__udp.html#ga550b67d7ad08c5cb068bb2b66d2c2c49',1,'jsocketpp::DatagramSocket::bind()'],['../group__udp.html#ga6f4ba9267e5d2a48e0ab85553b55f03a',1,'jsocketpp::DatagramSocket::bind(Port port)'],['../group__udp.html#gaff03e4ff5f58f0440dec821c02355185',1,'jsocketpp::DatagramSocket::bind(std::string_view host, Port port)'],['../group__tcp.html#ga1ca989ba16d32862dd4fa9bbb2b165b5',1,'jsocketpp::ServerSocket::bind()'],['../group__tcp.html#gae9a523509c0b63f91a801613dec85b39',1,'jsocketpp::Socket::bind(std::string_view localHost, Port port)'],['../group__tcp.html#ga477422f8e69c0114cc539926b7f6bc68',1,'jsocketpp::Socket::bind(Port port)'],['../group__tcp.html#gace1da4f860ac0af46d702cb5fc875a51',1,'jsocketpp::Socket::bind()'],['../classjsocketpp_1_1UnixSocket.html#a2fc862db1f85250bf07465463b8d986a',1,'jsocketpp::UnixSocket::bind()']]],
  ['bind_20_3a_20binding_20to_20all_20interfaces_20vs_20specific_20interfaces_18',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['bind_20listen_20explicit_19',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['bind_20to_20the_20same_20port_20',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['bind_5finterfaces_2emd_21',['bind_interfaces.md',['../bind__interfaces_8md.html',1,'']]],
  ['binding_22',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1013',1,'']]],
  ['binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_23',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['binding_20to_20all_20interfaces_24',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['binding_20to_20all_20interfaces_20vs_20specific_20interfaces_25',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['blocking_26',['Blocking',['../group__async__io.html#autotoc_md115',1,'What is Blocking?'],['../group__async__io.html#autotoc_md116',1,'What is Non-Blocking?']]],
  ['blocking_20and_20timeouts_27',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md122',1,'']]],
  ['blocking_20behavior_28',['🔁 Blocking Behavior',['../group__tcp.html#autotoc_md654',1,'']]],
  ['blocking_20mode_20on_20a_20client_20socket_29',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md955',1,'']]],
  ['blocking_20mode_3a_30',['Blocking mode:',['../group__async__io.html#autotoc_md127',1,'Blocking mode:'],['../group__async__io.html#autotoc_md131',1,'Blocking mode:'],['../group__async__io.html#autotoc_md135',1,'Blocking mode:'],['../group__async__io.html#autotoc_md138',1,'Blocking mode:']]],
  ['blocking_20mode_3a_31',['blocking mode:',['../group__async__io.html#autotoc_md128',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md132',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md136',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md139',1,'Non-blocking mode:']]],
  ['blocking_20sockets_32',['Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md313',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md323',1,'6.1 Non-Blocking Sockets']]],
  ['blocking_20sockets_20in_20jsocketpp_33',['Blocking vs Non-Blocking Sockets in jsocketpp',['../group__async__io.html',1,'']]],
  ['blocking_20vs_20non_20blocking_20sockets_34',['🚦 Blocking vs Non-Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'']]],
  ['blocking_20vs_20non_20blocking_20sockets_20in_20jsocketpp_35',['Blocking vs Non-Blocking Sockets in jsocketpp',['../group__async__io.html',1,'']]],
  ['boost_20asio_36',['Boost Asio',['../index.html#autotoc_md376',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md231',1,'2. Boost.Asio']]],
  ['both_37',['Both',['../namespacejsocketpp.html#a0d2868e06cd95730d5088336f8c3c174a130c5b3473c57faa76e2a1c54e26f88e',1,'jsocketpp']]],
  ['branching_20code_20of_20conduct_38',['7. Branching &amp;amp; Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'']]],
  ['broadcast_39',['Broadcast',['../group__underlying__socket__api.html#autotoc_md315',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md325',1,'6.3 Multicast and Broadcast']]],
  ['bsd_20posix_20winsock_20apis_40',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['buffer_41',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md692',1,'']]],
  ['buffer_42',['buffer',['../classjsocketpp_1_1DatagramPacket.html#a5a52a853827976d996fb0f85ae54bfd9',1,'jsocketpp::DatagramPacket']]],
  ['buffer_20size_43',['buffer size',['../group__socketopts.html#autotoc_md876',1,'Example: Read configured receive buffer size'],['../index.html#autotoc_md422',1,'What is the default buffer size?']]],
  ['buffer_20size_20notes_44',['Buffer Size Notes',['../group__udp.html#autotoc_md490',1,'']]],
  ['buffering_45',['Buffering',['../group__udp.html#autotoc_md492',1,'']]],
  ['bufferview_46',['BufferView',['../structjsocketpp_1_1BufferView.html',1,'jsocketpp']]],
  ['bufferview_2ehpp_47',['BufferView.hpp',['../BufferView_8hpp.html',1,'']]],
  ['build_48',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['build_20test_20and_20usage_20guide_49',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['build_5fand_5fusage_2emd_50',['BUILD_AND_USAGE.md',['../BUILD__AND__USAGE_8md.html',1,'']]],
  ['builderrormessage_51',['buildErrorMessage',['../classjsocketpp_1_1SocketException.html#aad86355058becd22b3f405ba72ca6444',1,'jsocketpp::SocketException']]],
  ['building_20and_20running_20tests_52',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['building_20and_20testing_53',['🧪 Building and Testing',['../index.html#autotoc_md402',1,'']]],
  ['building_20the_20library_54',['Building the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'']]],
  ['by_20connection_20mode_55',['Behavior by Connection Mode',['../group__udp.html#autotoc_md545',1,'']]],
  ['by_20mode_56',['🔁 Behavior by Mode',['../group__udp.html#autotoc_md538',1,'']]],
  ['by_20operation_57',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md951',1,'']]],
  ['by_20socket_20type_58',['by Socket Type',['../group__socketopts.html#autotoc_md993',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1002',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md207',1,'Common Options by Socket Type']]],
  ['by_20step_20posix_20style_59',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]]
];
