var searchData=
[
  ['dangerous_20implications_0',['❗ Dangerous implications',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['datagram_20sockets_20udp_1',['Datagram Sockets UDP',['../group__sockets__theory.html#autotoc_md323',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md331',1,'Datagram Sockets (UDP)']]],
  ['datagrampacket_2',['DatagramPacket',['../classjsocketpp_1_1DatagramPacket.html',1,'jsocketpp::DatagramPacket'],['../classjsocketpp_1_1DatagramPacket.html#a867c818e26b61fa3c67ddbe787290360',1,'jsocketpp::DatagramPacket::DatagramPacket(const size_t size=0)'],['../classjsocketpp_1_1DatagramPacket.html#acd3c0fb7e9f6fd786cb5074f30752a60',1,'jsocketpp::DatagramPacket::DatagramPacket(std::string_view data, std::string addr, const unsigned short prt)'],['../classjsocketpp_1_1DatagramPacket.html#a0d06fb2c9daa1adb4f3f395dfca46f5b',1,'jsocketpp::DatagramPacket::DatagramPacket(const char *data, size_t len, std::string addr, unsigned short prt)'],['../classjsocketpp_1_1DatagramPacket.html#aa49b8c37fb337e2e5471b34a87a3b5fb',1,'jsocketpp::DatagramPacket::DatagramPacket(const DatagramPacket &amp;)=default'],['../classjsocketpp_1_1DatagramPacket.html#a5eaf290d360b39c612a4c8724a0d9e6f',1,'jsocketpp::DatagramPacket::DatagramPacket(DatagramPacket &amp;&amp;) noexcept=default']]],
  ['datagrampacket_2ehpp_3',['DatagramPacket.hpp',['../DatagramPacket_8hpp.html',1,'']]],
  ['datagramsocket_4',['DatagramSocket',['../classjsocketpp_1_1DatagramSocket.html',1,'jsocketpp::DatagramSocket'],['../classjsocketpp_1_1DatagramSocket.html#a204d6931f5ff07541d663c7204de49b9',1,'jsocketpp::DatagramSocket::DatagramSocket(unsigned short port, std::size_t bufferSize=2048)'],['../classjsocketpp_1_1DatagramSocket.html#aea81e5f97ccf96ac8369a3f129ba5cff',1,'jsocketpp::DatagramSocket::DatagramSocket(std::string_view host, unsigned short port, std::size_t bufferSize=2048)'],['../classjsocketpp_1_1DatagramSocket.html#a3d08597b24d9c7a3fe43dd291ee85148',1,'jsocketpp::DatagramSocket::DatagramSocket(const DatagramSocket &amp;)=delete'],['../classjsocketpp_1_1DatagramSocket.html#a9dc7555c20b961c642309a618379e254',1,'jsocketpp::DatagramSocket::DatagramSocket(DatagramSocket &amp;&amp;other) noexcept']]],
  ['datagramsocket_20multicastsocket_5',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md269',1,'']]],
  ['datagramsocket_2ecpp_6',['DatagramSocket.cpp',['../DatagramSocket_8cpp.html',1,'']]],
  ['datagramsocket_2ehpp_7',['DatagramSocket.hpp',['../DatagramSocket_8hpp.html',1,'']]],
  ['datagramsocket_3a_3aread_3c_20std_3a_3astring_20_3e_8',['read&lt; std::string &gt;',['../namespacejsocketpp.html#a30deb297e9c8fae8da50947d4a29c95f',1,'jsocketpp']]],
  ['datagramsocket_3a_3arecvfrom_3c_20std_3a_3astring_20_3e_9',['recvFrom&lt; std::string &gt;',['../namespacejsocketpp.html#ad284c11be5f348cea8af35a1b8487958',1,'jsocketpp']]],
  ['dedicated_20methods_20vs_20generic_20methods_10',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md276',1,'']]],
  ['default_20in_20jsocketpp_20_3a_11',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md139',1,'']]],
  ['default_20style_12',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md90',1,'']]],
  ['defaultbuffersize_13',['DefaultBufferSize',['../group__tcp.html#gac3918d461f3d297d6c7ea30f3ff8c3ad',1,'jsocketpp::ServerSocket']]],
  ['defaults_14',['Constructor Defaults',['../group__address__reuse.html#autotoc_md153',1,'']]],
  ['definition_15',['🔐 Definition',['../group__address__reuse.html#autotoc_md122',1,'']]],
  ['depth_16',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md321',1,'']]],
  ['depth_20overview_20of_20address_20reuse_20options_17',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md103',1,'']]],
  ['design_20patterns_20and_20best_20practices_18',['Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['design_20rationale_19',['Design Rationale',['../group__async__io.html#autotoc_md180',1,'']]],
  ['design_20recommendations_20',['Design Recommendations',['../group__socket-options.html#autotoc_md280',1,'']]],
  ['design_20trade_20off_21',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md147',1,'']]],
  ['designs_3a_20pros_20and_20cons_22',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md89',1,'']]],
  ['details_23',['Callback Details',['../group__tcp.html#autotoc_md443',1,'']]],
  ['developer_20control_24',['Developer Control',['../group__address__reuse.html#autotoc_md154',1,'']]],
  ['documentation_25',['Documentation',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md19',1,'6. Documentation'],['../index.html#autotoc_md41',1,'Documentation']]],
  ['does_26',['Does',['../group__address__reuse.html#autotoc_md149',1,'A Better Alternative: What <span class="tt">jsocketpp</span> Does'],['../group__address__reuse.html#autotoc_md144',1,'What Java Does']]],
  ['does_27',['does',['../group__address__reuse.html#autotoc_md106',1,'🔄 What it actually does'],['../group__address__reuse.html#autotoc_md114',1,'🧨 What it actually does']]],
  ['does_20“binding_20to_20all_20interfaces”_20mean_28',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md208',1,'']]],
  ['does_20all_20java_20default_20style_29',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md90',1,'']]],
  ['does_20all_20steps_30',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md79',1,'']]],
  ['does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_31',['Does it make sense to provide poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['domain_20sockets_32',['Domain Sockets',['../group__unix.html',1,'Unix Domain Sockets'],['../group__sockets__theory.html#autotoc_md333',1,'Unix Domain Sockets']]],
  ['domain_20sockets_20local_20ipc_33',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md325',1,'']]],
  ['domain_20sockets_20unixsocket_34',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md272',1,'']]],
  ['drawbacks_20of_20select_35',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md242',1,'']]]
];
