var searchData=
[
  ['safe_20for_20servers_0',['🚫 Not safe for servers',['../group__address__reuse.html#autotoc_md116',1,'']]],
  ['safety_1',['Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md85',1,'a) Flexibility and Safety'],['../group__tcp.html#autotoc_md437',1,'Thread Safety'],['../group__tcp.html#autotoc_md442',1,'Thread Safety'],['../group__tcp.html#autotoc_md447',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md452',1,'Thread Safety']]],
  ['same_20port_2',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['scenarios_3',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md94',1,'']]],
  ['scope_4',['Scope',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md4',1,'']]],
  ['security_20and_20performance_20considerations_5',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md335',1,'']]],
  ['security_20considerations_6',['7. Security Considerations',['../group__underlying__socket__api.html#autotoc_md374',1,'']]],
  ['see_20also_7',['See Also',['../classjsocketpp_1_1ServerSocket.html#autotoc_md434',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md455',1,'See Also']]],
  ['select_8',['select',['../group__select__poll__epoll__iocp.html#autotoc_md242',1,'2. <b>Drawbacks of <span class="tt">select</span></b>'],['../group__async__io.html#autotoc_md177',1,'Custom Timeouts via <span class="tt">select()</span>']]],
  ['select_20for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_9',['select for asynchronous I O operations Does it make sense to provide poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['select_20is_20used_10',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md240',1,'']]],
  ['select_5fpoll_5fepoll_5fiocp_2emd_11',['select_poll_epoll_iocp.md',['../select__poll__epoll__iocp_8md.html',1,'']]],
  ['semantics_12',['Timeout Semantics',['../group__tcp.html#autotoc_md446',1,'']]],
  ['send_13',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['send_20write_14',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md194',1,'']]],
  ['send_3a_15',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['sending_16',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md428',1,'']]],
  ['sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_17',['sense to provide poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['server_18',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md459',1,'']]],
  ['server_20and_20client_19',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['server_20and_20client_20c_20af_5finet_20',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md368',1,'']]],
  ['server_20and_20client_20python_20af_5finet_21',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md367',1,'']]],
  ['server_20and_20client_3a_22',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['server_20client_20integration_20test_3a_23',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md394',1,'']]],
  ['server_20model_24',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md362',1,'']]],
  ['server_20side_25',['4.1. Server Side',['../group__sockets__theory.html#autotoc_md340',1,'']]],
  ['server_2ecpp_26',['server.cpp',['../server_8cpp.html',1,'']]],
  ['servers_27',['🚫 Not safe for servers',['../group__address__reuse.html#autotoc_md116',1,'']]],
  ['serversocket_28',['ServerSocket',['../group__socket-options.html#autotoc_md267',1,'2. TCP Sockets (<span class="tt">Socket</span>, <span class="tt">ServerSocket</span>)'],['../classjsocketpp_1_1ServerSocket.html',1,'jsocketpp::ServerSocket'],['../classjsocketpp_1_1Socket.html#a11a8bb11feaafab939278a8285afa567',1,'jsocketpp::Socket::ServerSocket()'],['../group__tcp.html#gad39f5cb474532ee02539fb3eceaebda0',1,'jsocketpp::ServerSocket::ServerSocket(unsigned short port, std::string_view localAddress={}, bool autoBindListen=true, bool reuseAddress=true, int soTimeoutMillis=-1, bool dualStack=true)'],['../group__tcp.html#gac6eeb69e3b15334e7c224edf30248fe3',1,'jsocketpp::ServerSocket::ServerSocket(const ServerSocket &amp;rhs)=delete'],['../group__tcp.html#gace3560ea1b99e15c1564e430e8848500',1,'jsocketpp::ServerSocket::ServerSocket(ServerSocket &amp;&amp;rhs) noexcept']]],
  ['serversocket_20construction_20binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_29',['ServerSocket Construction Binding and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['serversocket_2ecpp_30',['ServerSocket.cpp',['../ServerSocket_8cpp.html',1,'']]],
  ['serversocket_2ehpp_31',['ServerSocket.hpp',['../ServerSocket_8hpp.html',1,'']]],
  ['serversocket_3a_20constructor_20does_20all_20steps_32',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md79',1,'']]],
  ['serversocket_5flifecycle_2emd_33',['ServerSocket_Lifecycle.md',['../ServerSocket__Lifecycle_8md.html',1,'']]],
  ['setbuffersize_34',['setBufferSize',['../classjsocketpp_1_1Socket.html#a69c03ae3850cd5d55a5e42ff63472009',1,'jsocketpp::Socket']]],
  ['setdefaultreceivebuffersize_35',['setDefaultReceiveBufferSize',['../group__tcp.html#gaf644d3fccaebced95dd6bc2055bbed3e',1,'jsocketpp::ServerSocket']]],
  ['setdefaultsendbuffersize_36',['setDefaultSendBufferSize',['../group__tcp.html#gadbeecdd1d47fb8244dab210fa297fcf9',1,'jsocketpp::ServerSocket']]],
  ['setipv6only_37',['setIPv6Only',['../group__tcp.html#ga41b156c31f7b6d0ce08112c466a32719',1,'jsocketpp::ServerSocket']]],
  ['setloopbackmode_38',['setLoopbackMode',['../classjsocketpp_1_1MulticastSocket.html#ab6608be5d1aff24ad5077f6ea9a9168a',1,'jsocketpp::MulticastSocket']]],
  ['setmulticastinterface_39',['setMulticastInterface',['../classjsocketpp_1_1MulticastSocket.html#af0d5d684dcbfcf62907482ae3ac98948',1,'jsocketpp::MulticastSocket']]],
  ['setnonblocking_40',['setNonBlocking',['../classjsocketpp_1_1DatagramSocket.html#ac341be6110a71d3fbe5438dd342b69eb',1,'jsocketpp::DatagramSocket::setNonBlocking()'],['../group__tcp.html#ga6da405f0212b736e027c7d2e16222b44',1,'jsocketpp::ServerSocket::setNonBlocking()'],['../classjsocketpp_1_1Socket.html#a6cc57c26e230cb7ed7fa0174028811d5',1,'jsocketpp::Socket::setNonBlocking()'],['../classjsocketpp_1_1UnixSocket.html#ab5e5db3a3b7945d5fa15507265a7c657',1,'jsocketpp::UnixSocket::setNonBlocking()']]],
  ['setoption_41',['setOption',['../classjsocketpp_1_1DatagramSocket.html#a2b519a124c72ca57d29ab4f04f66af2b',1,'jsocketpp::DatagramSocket::setOption()'],['../group__tcp.html#ga06c2651d2b46a22ca1a80dde4a74016e',1,'jsocketpp::ServerSocket::setOption()'],['../classjsocketpp_1_1Socket.html#aeb2c85baf767c3e362b1a9de64bada3c',1,'jsocketpp::Socket::setOption()'],['../classjsocketpp_1_1UnixSocket.html#a571420e517267586cbd7f223f7b01ebd',1,'jsocketpp::UnixSocket::setOption()']]],
  ['setreuseaddress_42',['setReuseAddress',['../group__tcp.html#ga32d53c151cb8b7aecc8da81f9e9aa1b6',1,'jsocketpp::ServerSocket']]],
  ['setreuseport_43',['setReusePort',['../group__tcp.html#ga6276b89030ccf50a67501f429a14e3a3',1,'jsocketpp::ServerSocket']]],
  ['setsotimeout_44',['setSoTimeout',['../group__tcp.html#ga91f77d98b601507dbdcfac412e79f52d',1,'jsocketpp::ServerSocket::setSoTimeout()'],['../classjsocketpp_1_1Socket.html#a3369e71b7e6f2c8aaf8c090379f8f843',1,'jsocketpp::Socket::setSoTimeout()']]],
  ['settimeout_45',['setTimeout',['../classjsocketpp_1_1DatagramSocket.html#a540c0e48e02529eec6b9605e141433c5',1,'jsocketpp::DatagramSocket::setTimeout()'],['../classjsocketpp_1_1UnixSocket.html#a4b599e3ea9497908dbf3d7a2cc79f1c8',1,'jsocketpp::UnixSocket::setTimeout()']]],
  ['settimetolive_46',['setTimeToLive',['../classjsocketpp_1_1MulticastSocket.html#a72172a10bc5ba13a908f31c791c90ec5',1,'jsocketpp::MulticastSocket']]],
  ['setting_20up_20real_20server_20and_20client_3a_47',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['shutdown_48',['shutdown',['../classjsocketpp_1_1Socket.html#aacbacf59cf8239e66c80c66a09243ec3',1,'jsocketpp::Socket']]],
  ['shutdownmode_49',['ShutdownMode',['../namespacejsocketpp.html#a0d2868e06cd95730d5088336f8c3c174',1,'jsocketpp']]],
  ['side_50',['Side',['../group__sockets__theory.html#autotoc_md340',1,'4.1. Server Side'],['../group__sockets__theory.html#autotoc_md341',1,'4.2. Client Side']]],
  ['simple_20client_51',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md460',1,'']]],
  ['simple_20echo_20server_52',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md459',1,'']]],
  ['simple_20server_20client_20integration_20test_3a_53',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md394',1,'']]],
  ['simple_20udp_20echo_20server_20and_20client_54',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['size_55',['size',['../classjsocketpp_1_1DatagramPacket.html#a56c2fe4797d236c1453be540e1fa5c6c',1,'jsocketpp::DatagramPacket']]],
  ['smarter_20strategy_20for_20jsocketpp_56',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md151',1,'']]],
  ['so_5fexclusiveaddruse_57',['SO_EXCLUSIVEADDRUSE',['../group__address__reuse.html#autotoc_md117',1,'🔐 Correct approach on Windows: <span class="tt">SO_EXCLUSIVEADDRUSE</span>'],['../group__address__reuse.html',1,'Address Reuse in Sockets: &lt;tt&gt;SO_REUSEADDR&lt;/tt&gt; vs &lt;tt&gt;SO_EXCLUSIVEADDRUSE&lt;/tt&gt;'],['../group__address__reuse.html#autotoc_md101',1,'Address Reuse in Sockets: <span class="tt">SO_REUSEADDR</span> vs <span class="tt">SO_EXCLUSIVEADDRUSE</span>']]],
  ['so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_58',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md139',1,'']]],
  ['so_5fexclusiveaddruse_20windows_20only_59',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md121',1,'']]],
  ['so_5freuseaddr_60',['SO_REUSEADDR',['../group__address__reuse.html#autotoc_md104',1,'<span class="tt">SO_REUSEADDR</span>'],['../group__address__reuse.html#autotoc_md155',1,'Why Not Expose Windows <span class="tt">SO_REUSEADDR</span>?']]],
  ['so_5freuseaddr_20only_3a_61',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md134',1,'']]],
  ['so_5freuseaddr_20so_5freuseport_3a_62',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md135',1,'']]],
  ['so_5freuseaddr_20vs_20so_5fexclusiveaddruse_63',['SO_REUSEADDR vs SO_EXCLUSIVEADDRUSE',['../group__address__reuse.html',1,'Address Reuse in Sockets: &lt;tt&gt;SO_REUSEADDR&lt;/tt&gt; vs &lt;tt&gt;SO_EXCLUSIVEADDRUSE&lt;/tt&gt;'],['../group__address__reuse.html#autotoc_md101',1,'Address Reuse in Sockets: <span class="tt">SO_REUSEADDR</span> vs <span class="tt">SO_EXCLUSIVEADDRUSE</span>']]],
  ['so_5freuseaddr_3a_64',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md138',1,'']]],
  ['so_5freuseport_65',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['so_5freuseport_20unix_20linux_20only_66',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['so_5freuseport_3a_67',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md135',1,'']]],
  ['sockaddr_5fun_68',['SOCKADDR_UN',['../namespacejsocketpp.html#a981f7d65e550398e8ab29db83092f119',1,'jsocketpp']]],
  ['socket_69',['SOCKET',['../namespacejsocketpp.html#ac484f9eb8a74658aa491da1d1bc15eda',1,'jsocketpp']]],
  ['socket_70',['Socket',['../group__sockets__theory.html#autotoc_md319',1,'1. What is a Socket?'],['../classjsocketpp_1_1Socket.html',1,'jsocketpp::Socket'],['../classjsocketpp_1_1Socket.html#a35351a964f0ff1df19dfbe630afb7167',1,'jsocketpp::Socket::Socket(SOCKET client, const sockaddr_storage &amp;addr, socklen_t len, std::size_t recvBufferSize, std::size_t sendBufferSize)'],['../classjsocketpp_1_1Socket.html#a0b2a699505298870f70a1c97f716d645',1,'jsocketpp::Socket::Socket(std::string_view host, unsigned short port, std::size_t bufferSize=512)'],['../classjsocketpp_1_1Socket.html#af5a4ddebfbca7bfe6c9a88462cc9ada8',1,'jsocketpp::Socket::Socket(const Socket &amp;rhs)=delete'],['../classjsocketpp_1_1Socket.html#ad0612bda82c378dbaf99e0839f5aa815',1,'jsocketpp::Socket::Socket(Socket &amp;&amp;rhs) noexcept']]],
  ['socket_20address_20families_71',['3. Socket Address Families',['../group__sockets__theory.html#autotoc_md337',1,'']]],
  ['socket_20api_72',['Socket API',['../group__underlying__socket__api.html#autotoc_md356',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md357',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md365',1,'4. Protocols and the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API'],['../group__underlying__socket__api.html#autotoc_md355',1,'Comprehensive Guide to the Socket API']]],
  ['socket_20api_20features_73',['Socket API Features',['../group__underlying__socket__api.html#autotoc_md369',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md379',1,'Advanced Socket API Features']]],
  ['socket_20api_20for_20unit_20tests_3a_74',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md397',1,'']]],
  ['socket_20api_20in_20action_3a_20practical_20examples_75',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md366',1,'']]],
  ['socket_20behavior_3a_76',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md389',1,'']]],
  ['socket_20communication_77',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md364',1,'']]],
  ['socket_20exceptions_78',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md456',1,'']]],
  ['socket_20initialization_20and_20cleanup_3a_79',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md391',1,'']]],
  ['socket_20initialization_3a_20posix_20approach_80',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md77',1,'']]],
  ['socket_20libraries_81',['Socket Libraries',['../group__socket__library__comparison.html',1,'Comparison: &lt;tt&gt;jsocketpp&lt;/tt&gt; vs Other C++ Socket Libraries'],['../group__socket__library__comparison.html#autotoc_md284',1,'Comparison: <span class="tt">jsocketpp</span> vs Other C++ Socket Libraries']]],
  ['socket_20library_82',['jsocketpp: Modern C++17 Cross-Platform Socket Library',['../index.html',1,'']]],
  ['socket_20library_83',['jsocketpp: C++17 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['socket_20lifecycle_84',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md303',1,'']]],
  ['socket_20options_85',['Socket Options',['../group__underlying__socket__api.html#autotoc_md371',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md381',1,'6.2 Socket Options'],['../group__socket-options.html#autotoc_md260',1,'What Are Socket Options?']]],
  ['socket_20options_20in_20jsocketpp_86',['Socket Options in jsocketpp',['../group__socket-options.html',1,'Socket Options in jsocketpp'],['../group__socket-options.html#autotoc_md257',1,'Socket Options in jsocketpp']]],
  ['socket_20serversocket_87',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md267',1,'']]],
  ['socket_20state_88',['What is a Socket State?',['../group__socket__states.html#autotoc_md301',1,'']]],
  ['socket_20state_20handling_89',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['socket_20states_90',['Socket States',['../group__socket__states.html#autotoc_md304',1,'Main TCP Socket States'],['../group__socket__states.html',1,'Understanding Socket States'],['../group__socket__states.html#autotoc_md299',1,'Understanding Socket States']]],
  ['socket_20timeouts_91',['🕐 Socket Timeouts',['../group__async__io.html#autotoc_md175',1,'']]],
  ['socket_20type_92',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md264',1,'']]],
  ['socket_20types_93',['Socket Types',['../group__underlying__socket__api.html#autotoc_md360',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md327',1,'2.5. Comparison Table: Socket Types']]],
  ['socket_20types_20work_94',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md329',1,'']]],
  ['socket_2doptions_2emd_95',['socket-options.md',['../socket-options_8md.html',1,'']]],
  ['socket_2ecpp_96',['Socket.cpp',['../Socket_8cpp.html',1,'']]],
  ['socket_2ehpp_97',['Socket.hpp',['../Socket_8hpp.html',1,'']]],
  ['socket_5ferror_98',['SOCKET_ERROR',['../namespacejsocketpp.html#adc2dd9860dec2a3c3189e756288d5ba2',1,'jsocketpp']]],
  ['socket_5fgtest_2ecpp_99',['socket_gtest.cpp',['../socket__gtest_8cpp.html',1,'']]],
  ['socket_5flibrary_5fcomparison_2emd_100',['socket_library_comparison.md',['../socket__library__comparison_8md.html',1,'']]],
  ['socket_5fstates_2emd_101',['socket_states.md',['../socket__states_8md.html',1,'']]],
  ['socketerrormessage_102',['SocketErrorMessage',['../namespacejsocketpp.html#a1d0357025eb782be52907801696556ca',1,'jsocketpp']]],
  ['socketerrormessagewrap_103',['SocketErrorMessageWrap',['../namespacejsocketpp.html#a2eae999aa2ba7973dc6c3acc40e51e5a',1,'jsocketpp']]],
  ['socketexception_104',['SocketException',['../classjsocketpp_1_1SocketException.html',1,'jsocketpp::SocketException'],['../classjsocketpp_1_1SocketException.html#a60e8542fe737e4ab26f9f6bb99bd848e',1,'jsocketpp::SocketException::SocketException()']]],
  ['socketexception_2ehpp_105',['SocketException.hpp',['../SocketException_8hpp.html',1,'']]],
  ['socketinitializer_106',['SocketInitializer',['../classjsocketpp_1_1SocketInitializer.html',1,'jsocketpp::SocketInitializer'],['../classjsocketpp_1_1SocketInitializer.html#a4ff790d2289ffdbef65a5cce8c06a112',1,'jsocketpp::SocketInitializer::SocketInitializer()'],['../classjsocketpp_1_1SocketInitializer.html#a6bc3398c7814e3a54c2032a021ee20eb',1,'jsocketpp::SocketInitializer::SocketInitializer(const SocketInitializer &amp;rhs)=delete']]],
  ['socketinitializer_2ehpp_107',['SocketInitializer.hpp',['../SocketInitializer_8hpp.html',1,'']]],
  ['sockets_108',['Sockets',['../group__async__io.html#autotoc_md171',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__socket-options.html#autotoc_md265',1,'1. Options for All Sockets'],['../group__sockets__theory.html#autotoc_md324',1,'2.3. Raw Sockets'],['../group__underlying__socket__api.html#autotoc_md370',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md380',1,'6.1 Non-Blocking Sockets'],['../group__sockets__theory.html#autotoc_md332',1,'Raw Sockets'],['../group__tcp.html',1,'TCP Sockets'],['../group__udp.html',1,'UDP Sockets'],['../group__unix.html',1,'Unix Domain Sockets'],['../group__sockets__theory.html#autotoc_md333',1,'Unix Domain Sockets'],['../group__socket__states.html#autotoc_md308',1,'What About UDP and UNIX Sockets?']]],
  ['sockets_20bind_20to_20the_20same_20port_109',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['sockets_20datagramsocket_20multicastsocket_110',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md269',1,'']]],
  ['sockets_20in_20depth_111',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md321',1,'']]],
  ['sockets_20in_20jsocketpp_112',['Sockets in jsocketpp',['../group__async__io.html',1,'Blocking vs Non-Blocking Sockets in jsocketpp'],['../group__async__io.html#autotoc_md169',1,'Blocking vs Non-Blocking Sockets in jsocketpp']]],
  ['sockets_20local_20ipc_113',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md325',1,'']]],
  ['sockets_20operate_114',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md343',1,'']]],
  ['sockets_20socket_20serversocket_115',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md267',1,'']]],
  ['sockets_20tcp_116',['Sockets TCP',['../group__sockets__theory.html#autotoc_md322',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md330',1,'Stream Sockets (TCP)']]],
  ['sockets_20udp_117',['Sockets UDP',['../group__sockets__theory.html#autotoc_md323',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md331',1,'Datagram Sockets (UDP)']]],
  ['sockets_20unixsocket_118',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md272',1,'']]],
  ['sockets_20work_3a_20the_20lifecycle_119',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md339',1,'']]],
  ['sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_120',['Sockets: SO_REUSEADDR vs SO_EXCLUSIVEADDRUSE',['../group__address__reuse.html',1,'Address Reuse in Sockets: &lt;tt&gt;SO_REUSEADDR&lt;/tt&gt; vs &lt;tt&gt;SO_EXCLUSIVEADDRUSE&lt;/tt&gt;'],['../group__address__reuse.html#autotoc_md101',1,'Address Reuse in Sockets: <span class="tt">SO_REUSEADDR</span> vs <span class="tt">SO_EXCLUSIVEADDRUSE</span>']]],
  ['sockets_3a_20theory_20types_20and_20platform_20apis_121',['Sockets: Theory Types and Platform APIs',['../group__sockets__theory.html',1,'Sockets: Theory, Types, and Platform APIs'],['../group__sockets__theory.html#autotoc_md316',1,'Sockets: Theory, Types, and Platform APIs']]],
  ['sockets_5ftheory_2emd_122',['sockets_theory.md',['../sockets__theory_8md.html',1,'']]],
  ['sockettimeoutexception_123',['SocketTimeoutException',['../classjsocketpp_1_1SocketTimeoutException.html',1,'jsocketpp::SocketTimeoutException'],['../classjsocketpp_1_1SocketTimeoutException.html#a60f25c80265801631f7808b84980f59d',1,'jsocketpp::SocketTimeoutException::SocketTimeoutException()']]],
  ['sockettimeoutexception_2ehpp_124',['SocketTimeoutException.hpp',['../SocketTimeoutException_8hpp.html',1,'']]],
  ['specific_20apis_125',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md345',1,'']]],
  ['specific_20behavior_3a_20connect_20accept_20recv_20and_20send_126',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['specific_20considerations_127',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md376',1,'']]],
  ['specific_20interfaces_128',['Specific Interfaces',['../group__bind__interfaces.html',1,'Understanding &lt;tt&gt;bind()&lt;/tt&gt;: Binding to All Interfaces vs Specific Interfaces'],['../group__bind__interfaces.html#autotoc_md207',1,'Understanding <span class="tt">bind()</span>: Binding to All Interfaces vs Specific Interfaces']]],
  ['specific_20tests_3a_129',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md396',1,'']]],
  ['standards_130',['Our Standards',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md2',1,'']]],
  ['start_131',['Quick Start',['../index.html#autotoc_md35',1,'']]],
  ['state_132',['What is a Socket State?',['../group__socket__states.html#autotoc_md301',1,'']]],
  ['state_20handling_133',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['state_20implications_134',['🧪 TCP state implications',['../group__address__reuse.html#autotoc_md119',1,'']]],
  ['state_20transitions_135',['TCP State Transitions',['../group__socket__states.html#autotoc_md306',1,'']]],
  ['states_136',['States',['../group__socket__states.html#autotoc_md304',1,'Main TCP Socket States'],['../group__socket__states.html',1,'Understanding Socket States'],['../group__socket__states.html#autotoc_md299',1,'Understanding Socket States']]],
  ['step_20by_20step_20posix_20style_137',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md91',1,'']]],
  ['step_20posix_20style_138',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md91',1,'']]],
  ['steps_139',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md79',1,'']]],
  ['strategy_20for_20jsocketpp_140',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md151',1,'']]],
  ['stream_20sockets_20tcp_141',['Stream Sockets TCP',['../group__sockets__theory.html#autotoc_md322',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md330',1,'Stream Sockets (TCP)']]],
  ['stringtoaddress_142',['stringToAddress',['../classjsocketpp_1_1Socket.html#a68f996973d1497cb476c44025aac401b',1,'jsocketpp::Socket']]],
  ['stubbing_20socket_20api_20for_20unit_20tests_3a_143',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md397',1,'']]],
  ['style_144',['Style',['../group__ServerSocket__Lifecycle.html#autotoc_md90',1,'<b>a) Constructor Does All (Java Default Style)</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md91',1,'<b>b) Fully Step-by-Step (POSIX Style)</b>']]],
  ['style_20guidelines_145',['3. Code Style Guidelines',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md13',1,'']]],
  ['submission_146',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md227',1,'']]],
  ['submit_20a_20pull_20request_20to_20cci_147',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md230',1,'']]],
  ['submit_20to_20the_20vcpkg_20registry_148',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md414',1,'']]],
  ['submitting_20pull_20requests_149',['2. Submitting Pull Requests',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md11',1,'']]],
  ['summary_150',['Summary',['../group__address__reuse.html#autotoc_md120',1,'🧠 Summary'],['../group__address__reuse.html#autotoc_md128',1,'🧠 Summary'],['../group__ServerSocket__Lifecycle.html#autotoc_md100',1,'9. Summary']]],
  ['summary_20of_20java’s_20design_20trade_20off_151',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md147',1,'']]],
  ['summary_20table_152',['Summary Table',['../group__address__reuse.html#autotoc_md157',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md274',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md254',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md351',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md141',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md296',1,'Summary Table']]],
  ['summary_20table_3a_20waiting_20for_20readiness_153',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md198',1,'']]],
  ['support_154',['Support',['../group__socket-options.html#autotoc_md262',1,'Cross-Platform Support'],['../group__tcp.html#autotoc_md439',1,'Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md453',1,'Platform Support']]]
];
