var searchData=
[
  ['c_0',['C',['../group__multicast__sockets.html#autotoc_md297',1,'Example: Receiver in C'],['../group__multicast__sockets.html#autotoc_md296',1,'Example: Sender (Broadcaster) in C']]],
  ['c_2020_1',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['c_2020_20cross_20platform_20socket_20library_2',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['c_2020_3a_3',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['c_20af_5finet_4',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md453',1,'']]],
  ['c_20clear_20api_5',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md66',1,'']]],
  ['c_20jsocketpp_20hybrid_6',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md71',1,'']]],
  ['c_20socket_20libraries_7',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['c_20winsock_8',['C Winsock',['../group__multicast__sockets.html#autotoc_md302',1,'Example: Receiver in C++ (Winsock)'],['../group__multicast__sockets.html#autotoc_md301',1,'Example: Sender in C++ (Winsock)']]],
  ['cachelocalendpoint_9',['cacheLocalEndpoint',['../group__udp.html#ga465ec84374a81fa09cf486e054863673',1,'jsocketpp::DatagramSocket']]],
  ['callback_20signature_10',['🔁 Callback Signature',['../group__tcp.html#autotoc_md819',1,'']]],
  ['can_20i_20use_20jsocketpp_20in_20production_11',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['cap_12',['Why a &quot;safe&quot; cap?',['../group__core.html#autotoc_md608',1,'']]],
  ['capabilities_13',['Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['care_14',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md1008',1,'']]],
  ['case_15',['Case',['../group__address__reuse.html#autotoc_md110',1,'✅ Use Case'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md730',1,'Use Case']]],
  ['cases_16',['Cases',['../group__internal.html#autotoc_md630',1,'✅ Use Cases'],['../group__udp.html#autotoc_md681',1,'✅ Use Cases'],['../group__socketopts.html#autotoc_md1111',1,'✅ Use Cases'],['../group__socketopts.html#autotoc_md1123',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md1155',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md1014',1,'🔧 Common Use Cases'],['../group__socketopts.html#autotoc_md1032',1,'🔧 Use Cases'],['../group__socketopts.html#autotoc_md1043',1,'🔧 Use Cases'],['../group__tcp.html#autotoc_md848',1,'🛠 Use Cases'],['../group__socketopts.html#autotoc_md1023',1,'🧩 Use Cases'],['../index.html#autotoc_md510',1,'🧰 Typical Use Cases'],['../group__multicast__sockets.html#autotoc_md311',1,'Applications and Use Cases'],['../group__udp.html#autotoc_md668',1,'Common Use Cases'],['../group__udp.html#autotoc_md670',1,'Common Use Cases'],['../group__udp.html#autotoc_md672',1,'Common Use Cases'],['../group__socketopts.html#autotoc_md1054',1,'Protocol Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md233',1,'Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md245',1,'Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md256',1,'Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md267',1,'Use Cases'],['../group__udp.html#autotoc_md696',1,'Use Cases'],['../group__tcp.html#autotoc_md868',1,'Use Cases'],['../group__tcp.html#autotoc_md872',1,'Use Cases'],['../group__tcp.html#autotoc_md878',1,'Use Cases'],['../group__tcp.html#autotoc_md884',1,'Use Cases'],['../group__tcp.html#autotoc_md888',1,'Use Cases'],['../group__tcp.html#autotoc_md894',1,'Use Cases'],['../group__tcp.html#autotoc_md978',1,'Use Cases'],['../group__tcp.html#autotoc_md979',1,'Use Cases'],['../group__socketopts.html#autotoc_md1118',1,'Use Cases'],['../group__socketopts.html#autotoc_md1132',1,'Use Cases'],['../group__socketopts.html#autotoc_md1141',1,'Use Cases']]],
  ['cases_17',['📦 Common use cases',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['cases_20and_20applications_18',['Cases and Applications',['../group__underlying__socket__api.html#autotoc_md460',1,'8. Use Cases and Applications'],['../group__network__data__units.html#autotoc_md320',1,'Use Cases and Applications']]],
  ['cases_20and_20windows_20support_19',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['cases_20to_20consider_3a_20',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md485',1,'']]],
  ['cases_3a_21',['Cases:',['../group__tcp.html#autotoc_md862',1,'Common Use Cases:'],['../structjsocketpp_1_1DatagramReadResult.html#autotoc_md650',1,'Use Cases:']]],
  ['catching_20and_20handling_20socket_20exceptions_22',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md1000',1,'']]],
  ['caveats_23',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md99',1,'']]],
  ['cci_24',['CCI',['../group__conan__publish__guide.html#autotoc_md214',1,'6. Submit a Pull Request to CCI'],['../group__conan__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the Conan Center Index (CCI)']]],
  ['cci_20submission_25',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['center_20index_20cci_26',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['center_20index_20cci_20submission_27',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['chaining_28',['Exception Chaining',['../classjsocketpp_1_1SocketException.html#autotoc_md999',1,'']]],
  ['check_20if_20socket_20is_20ipv6_20only_29',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['choosereceivesize_30',['chooseReceiveSize',['../group__udp.html#ga1ff1dc3fb9ed36e31bc62941edf1d44c',1,'jsocketpp::DatagramSocket']]],
  ['cidr_20in_20ipv6_3a_20flexible_20address_20allocation_31',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['cidr_3a_20the_20shift_20to_20classless_20routing_32',['CIDR: The Shift to Classless Routing',['../group__mastering__ipv4.html#autotoc_md38',1,'']]],
  ['class_20mapping_33',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md540',1,'']]],
  ['classes_34',['Classes',['../group__exceptions.html',1,'Exception Classes'],['../classjsocketpp_1_1SocketOptions.html#autotoc_md1003',1,'Supported Classes']]],
  ['classless_20routing_35',['CIDR: The Shift to Classless Routing',['../group__mastering__ipv4.html#autotoc_md38',1,'']]],
  ['cleanup_36',['Resource Cleanup',['../group__tcp.html#autotoc_md745',1,'']]],
  ['cleanup_37',['cleanup',['../group__udp.html#gaa0727094596347aa858629f6e5c7febf',1,'jsocketpp::DatagramSocket::cleanup()'],['../group__tcp.html#ga2a630f28a613224176ff17f7ee0c6a4c',1,'jsocketpp::ServerSocket::cleanup()'],['../group__tcp.html#ga744a91706b9510d266b7c07e31f3e028',1,'jsocketpp::Socket::cleanup()']]],
  ['cleanup_3a_38',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md476',1,'']]],
  ['cleanupandrethrow_39',['cleanupAndRethrow',['../group__udp.html#ga6608c56d08ccdb2807bd47cc862af24a',1,'jsocketpp::DatagramSocket::cleanupAndRethrow()'],['../group__tcp.html#ga33183210cdc2a1e281006e325cc2a173',1,'jsocketpp::ServerSocket::cleanupAndRethrow()'],['../group__tcp.html#ga8bc150c503e051c12165680e74b5ae48',1,'jsocketpp::Socket::cleanupAndRethrow()']]],
  ['cleanupandthrow_40',['cleanupAndThrow',['../group__udp.html#ga1973415ece2f77f191b250b9e9690733',1,'jsocketpp::DatagramSocket::cleanupAndThrow()'],['../group__tcp.html#gab5572cb795d9b45ee50a0ddf9cb9c075',1,'jsocketpp::ServerSocket::cleanupAndThrow()'],['../group__tcp.html#gaf80aa30f2806a17b930878841dfab7ad',1,'jsocketpp::Socket::cleanupAndThrow()']]],
  ['cleanupsockets_41',['CleanupSockets',['../namespacejsocketpp.html#a027103bbab1364c1f878d5c49c0af67c',1,'jsocketpp']]],
  ['clear_42',['clear',['../classjsocketpp_1_1DatagramPacket.html#a7853459de9f4e83363ed341bb465930a',1,'jsocketpp::DatagramPacket']]],
  ['clear_20api_43',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md66',1,'']]],
  ['client_44',['Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1186',1,'Example: Simple Client'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md654',1,'Example: Simple UDP Echo Server and Client']]],
  ['client_20c_20af_5finet_45',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md453',1,'']]],
  ['client_20integration_20test_3a_46',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md479',1,'']]],
  ['client_20python_20af_5finet_47',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md452',1,'']]],
  ['client_20server_20model_48',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md447',1,'']]],
  ['client_20side_49',['4.2. Client Side',['../group__sockets__theory.html#autotoc_md426',1,'']]],
  ['client_20socket_50',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1113',1,'']]],
  ['client_2ecpp_51',['client.cpp',['../client_8cpp.html',1,'']]],
  ['client_3a_52',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md478',1,'']]],
  ['close_53',['close',['../group__udp.html#ga9d0a9582b3a2a72bf62f182dbc33c352',1,'jsocketpp::DatagramSocket::close()'],['../group__tcp.html#ga0245d40096ca089255c67303eebf17e6',1,'jsocketpp::ServerSocket::close()'],['../group__tcp.html#ga75ee749264ccbcfc4dfbf5442e55dcb8',1,'jsocketpp::Socket::close()'],['../classjsocketpp_1_1UnixSocket.html#a3f87192fe9d9c81a3d78e007bfc40179',1,'jsocketpp::UnixSocket::close()'],['../group__socketopts.html#autotoc_md1025',1,'Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close']]],
  ['closeorthrow_54',['closeOrThrow',['../group__internal.html#gab3b8ac088a7936657681c6de9a4400e1',1,'jsocketpp::internal']]],
  ['closesocket_55',['CloseSocket',['../namespacejsocketpp.html#a12fd46ba498b19d6102220bc100ef931',1,'jsocketpp']]],
  ['cmake_56',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md495',1,'']]],
  ['cmake_20build_57',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['cmake_20for_20platform_20specific_20tests_3a_58',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md481',1,'']]],
  ['cmake_20integration_20in_20your_20project_59',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['cmake_20presets_20recommended_60',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['cmake_20project_20conan_20friendly_61',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md207',1,'']]],
  ['code_20of_20conduct_62',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md583',1,'7. Branching &amp;amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20structure_63',['Request Code Structure',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md229',1,'']]],
  ['code_20style_20guidelines_64',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md575',1,'']]],
  ['code_5fof_5fconduct_2emd_65',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['combining_20with_20so_5freuseport_66',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md102',1,'']]],
  ['commands_67',['Commands',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md232',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md242',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md253',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md264',1,'Common Commands']]],
  ['commands_20use_20cases_20and_20windows_20support_68',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['commit_20hooks_69',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md577',1,'']]],
  ['commit_20hooks_70',['Pre-commit hooks',['../index.html#autotoc_md547',1,'']]],
  ['common_20commands_71',['Common Commands',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md232',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md242',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md253',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md264',1,'Common Commands']]],
  ['common_20errors_72',['Common Errors',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md231',1,'Common Errors'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md244',1,'Common Errors'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md255',1,'Common Errors'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md266',1,'Common Errors']]],
  ['common_20issues_73',['Troubleshooting Common Issues',['../group__multicast__sockets.html#autotoc_md310',1,'']]],
  ['common_20options_20by_20socket_20type_74',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md349',1,'']]],
  ['common_20scenarios_75',['Common Scenarios',['../group__udp.html#autotoc_md699',1,'']]],
  ['common_20use_20cases_76',['Common Use Cases',['../group__socketopts.html#autotoc_md1014',1,'🔧 Common Use Cases'],['../group__udp.html#autotoc_md668',1,'Common Use Cases'],['../group__udp.html#autotoc_md670',1,'Common Use Cases'],['../group__udp.html#autotoc_md672',1,'Common Use Cases']]],
  ['common_20use_20cases_77',['📦 Common use cases',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['common_20use_20cases_3a_78',['Common Use Cases:',['../group__tcp.html#autotoc_md862',1,'']]],
  ['common_2ecpp_79',['common.cpp',['../common_8cpp.html',1,'']]],
  ['common_2ehpp_80',['common.hpp',['../common_8hpp.html',1,'']]],
  ['communication_81',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md449',1,'']]],
  ['communication_20models_82',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md446',1,'']]],
  ['comparison_83',['📚 Java Comparison',['../group__async__io.html#autotoc_md184',1,'']]],
  ['comparison_20table_3a_20socket_20types_84',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md412',1,'']]],
  ['comparison_20with_20acceptnonblocking_85',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md790',1,'']]],
  ['comparison_3a_20jsocketpp_20vs_20other_20c_20socket_20libraries_86',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['compilation_87',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['complete_20guide_20to_20its_20features_20structure_20and_20capabilities_88',['Complete Guide to Its Features Structure and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['components_89',['Key Components',['../namespacejsocketpp_1_1detail.html#autotoc_md727',1,'']]],
  ['components_20of_20the_20socket_20api_90',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md442',1,'']]],
  ['comprehensive_20guide_20to_20ioctl_20fcntl_20ioctlsocket_91',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['comprehensive_20guide_20to_20ioctl_20fcntl_20ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_92',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['comprehensive_20guide_20to_20multicast_20sockets_93',['Comprehensive Guide to Multicast Sockets',['../group__multicast__sockets.html',1,'']]],
  ['comprehensive_20guide_20to_20the_20socket_20api_94',['Comprehensive Guide to the Socket API',['../group__underlying__socket__api.html',1,'']]],
  ['comprehensive_20list_20of_20socket_20programming_20functions_95',['Comprehensive List of Socket Programming Functions',['../group__list__bsd__socket__functions.html',1,'']]],
  ['comprehensive_20list_20of_20socket_20programming_20functions_2emd_96',['Comprehensive List of Socket Programming Functions.md',['../Comprehensive_01List_01of_01Socket_01Programming_01Functions_8md.html',1,'']]],
  ['conan_97',['✅ Conan',['../index.html#autotoc_md527',1,'']]],
  ['conan_20center_20index_20cci_98',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['conan_20center_20index_20cci_20submission_99',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['conan_20friendly_100',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md207',1,'']]],
  ['conan_20recipe_20conanfile_20py_101',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md205',1,'']]],
  ['conan_5fpublish_5fguide_2emd_102',['conan_publish_guide.md',['../conan__publish__guide_8md.html',1,'']]],
  ['conanfile_20py_103',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md205',1,'']]],
  ['concepts_104',['Concepts',['../buffer__traits_8hpp.html#autotoc_md725',1,'Key Concepts'],['../group__network__data__units.html#autotoc_md319',1,'Related Concepts']]],
  ['conclusion_105',['Conclusion',['../group__address__reuse.html#autotoc_md147',1,'✅ Conclusion'],['../group__underlying__socket__api.html#autotoc_md462',1,'10. Conclusion'],['../group__underlying__socket__api.html#autotoc_md470',1,'8. Conclusion'],['../group__list__bsd__socket__functions.html#autotoc_md35',1,'Conclusion'],['../group__bind__interfaces.html#autotoc_md200',1,'Conclusion'],['../group__multicast__sockets.html#autotoc_md312',1,'Conclusion'],['../group__network__data__units.html#autotoc_md322',1,'Conclusion'],['../group__socket__library__comparison.html#autotoc_md383',1,'Conclusion']]],
  ['conclusion_20advice_106',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md341',1,'']]],
  ['conclusion_3a_107',['Conclusion:',['../group__unit__tests.html#autotoc_md486',1,'']]],
  ['condition_20warning_108',['⚠️ Race Condition Warning',['../group__tcp.html#autotoc_md781',1,'']]],
  ['conduct_109',['Conduct',['../md_CONTRIBUTING.html#autotoc_md583',1,'7. Branching &amp;amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['configuration_110',['Configuration',['../group__tcp.html#autotoc_md799',1,'⚙️ Configuration'],['../group__list__bsd__socket__functions.html#autotoc_md30',1,'5. Socket Information and Configuration']]],
  ['configuration_20of_20accepted_20socket_111',['Configuration of Accepted Socket',['../group__tcp.html#autotoc_md750',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md759',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md768',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md779',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md812',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md825',1,'⚙️ Configuration of Accepted Socket']]],
  ['configuration_20parameters_112',['Configuration Parameters',['../group__tcp.html#autotoc_md856',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md659',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md850',1,'Configuration Parameters']]],
  ['configured_20receive_20buffer_20size_113',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md1034',1,'']]],
  ['connect_114',['connect',['../group__async__io.html#autotoc_md167',1,'🔌 &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;'],['../group__udp.html#ga915c790c7cfde485e680ddec2edb2e74',1,'jsocketpp::DatagramSocket::connect()'],['../group__tcp.html#ga93cc325113abb7433288338ca3facde1',1,'jsocketpp::Socket::connect()'],['../classjsocketpp_1_1UnixSocket.html#a6a5359f3b15c37556b8e2cd558760603',1,'jsocketpp::UnixSocket::connect()']]],
  ['connect_20accept_20recv_20and_20send_115',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md166',1,'']]],
  ['connect_20bind_20to_20a_20local_20address_116',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['connect_20function_117',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md83',1,'']]],
  ['connection_118',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['connection_20modes_119',['Connection Modes',['../group__tcp.html#autotoc_md898',1,'']]],
  ['connectionless_20approach_120',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md316',1,'']]],
  ['connections_121',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['cons_122',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md68',1,'']]],
  ['consider_3a_123',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md485',1,'']]],
  ['considerations_124',['Considerations',['../group__sockets__theory.html#autotoc_md420',1,'2.7. Security and Performance Considerations'],['../group__select__poll__epoll__iocp.html#autotoc_md335',1,'6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;'],['../group__underlying__socket__api.html#autotoc_md469',1,'7. Practical Considerations'],['../group__underlying__socket__api.html#autotoc_md459',1,'7. Security Considerations'],['../group__underlying__socket__api.html#autotoc_md461',1,'9. Platform-Specific Considerations'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md281',1,'Practical Considerations'],['../group__multicast__sockets.html#autotoc_md307',1,'Security Considerations']]],
  ['construction_20binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_125',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['constructor_126',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['constructor_20bind_20listen_20explicit_127',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['constructor_20defaults_128',['Constructor Defaults',['../group__address__reuse.html#autotoc_md137',1,'']]],
  ['constructor_20does_20all_20java_20default_20style_129',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md69',1,'']]],
  ['constructor_20does_20all_20steps_130',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md58',1,'']]],
  ['contents_131',['Contents',['../namespacejsocketpp_1_1internal.html#autotoc_md728',1,'Contents'],['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md343',1,'Table of Contents']]],
  ['context_132',['Example Usage Context',['../group__list__bsd__socket__functions.html#autotoc_md34',1,'']]],
  ['contributing_133',['🤝 Contributing',['../index.html#autotoc_md549',1,'']]],
  ['contributing_20to_20jsocketpp_134',['Contributing to jsocketpp',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_135',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['control_136',['Control',['../group__address__reuse.html#autotoc_md138',1,'Developer Control'],['../group__multicast__sockets.html#autotoc_md305',1,'TTL and Scope Control']]],
  ['convertipv4mappedipv6toipv4_137',['convertIPv4MappedIPv6ToIPv4',['../group__core.html#ga4da3763b1f8385b27ebbe44cdcfdfc8d',1,'jsocketpp']]],
  ['core_20behavior_138',['⚙️ Core Behavior',['../group__udp.html#autotoc_md691',1,'']]],
  ['core_20components_20of_20the_20socket_20api_139',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md442',1,'']]],
  ['core_20socket_20creation_20and_20management_140',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['core_20utilities_20and_20types_141',['Core Utilities and Types',['../group__core.html',1,'']]],
  ['counterpart_20in_20tcp_142',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md317',1,'']]],
  ['counterparts_143',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md333',1,'']]],
  ['coverage_20for_20cross_20platform_3a_144',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['create_20a_20vcpkg_20portfile_145',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md493',1,'']]],
  ['creating_20a_20multicast_20socket_146',['Creating a Multicast Socket',['../group__multicast__sockets.html#autotoc_md292',1,'']]],
  ['creation_20and_20management_147',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['cross_20platform_20api_20considerations_148',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md335',1,'']]],
  ['cross_20platform_20socket_20library_149',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['cross_20platform_20socket_20library_20for_20modern_20c_2020_150',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['cross_20platform_20support_151',['Cross-Platform Support',['../group__socket-options.html#autotoc_md347',1,'']]],
  ['cross_20platform_3a_152',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['custom_20device_20driver_20linux_153',['Example: Custom Device Driver (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md235',1,'']]],
  ['custom_20timeouts_20via_20select_154',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md161',1,'']]],
  ['customization_155',['Customization',['../group__core.html#autotoc_md601',1,'Customization'],['../group__core.html#autotoc_md606',1,'Customization']]]
];
