var searchData=
[
  ['i_20o_0',['I O',['../group__underlying__socket__api.html#autotoc_md316',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md326',1,'6.4 Asynchronous I/O']]],
  ['i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_1',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['i_20use_20jsocketpp_20in_20production_2',['Can I use jsocketpp in production?',['../index.html#autotoc_md418',1,'']]],
  ['if_20socket_20is_20ipv6_20only_3',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1029',1,'']]],
  ['implementation_20details_4',['Implementation Details',['../group__udp.html#autotoc_md583',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md515',1,'Implementation Details'],['../group__udp.html#autotoc_md574',1,'Implementation Details'],['../group__udp.html#autotoc_md594',1,'Implementation Details'],['../group__tcp.html#autotoc_md712',1,'Implementation Details'],['../group__tcp.html#autotoc_md764',1,'Implementation Details'],['../group__tcp.html#autotoc_md767',1,'Implementation Details'],['../group__tcp.html#autotoc_md772',1,'Implementation Details'],['../group__tcp.html#autotoc_md774',1,'Implementation Details'],['../group__tcp.html#autotoc_md777',1,'Implementation Details'],['../group__tcp.html#autotoc_md779',1,'Implementation Details'],['../group__tcp.html#autotoc_md781',1,'Implementation Details'],['../group__tcp.html#autotoc_md783',1,'Implementation Details'],['../group__tcp.html#autotoc_md785',1,'Implementation Details'],['../group__tcp.html#autotoc_md788',1,'Implementation Details'],['../group__tcp.html#autotoc_md791',1,'Implementation Details'],['../group__tcp.html#autotoc_md793',1,'Implementation Details'],['../group__tcp.html#autotoc_md797',1,'Implementation Details'],['../group__tcp.html#autotoc_md799',1,'Implementation Details'],['../group__tcp.html#autotoc_md801',1,'Implementation Details'],['../group__tcp.html#autotoc_md807',1,'Implementation Details'],['../group__tcp.html#autotoc_md808',1,'Implementation Details'],['../group__tcp.html#autotoc_md810',1,'Implementation Details'],['../group__tcp.html#autotoc_md812',1,'Implementation Details'],['../group__tcp.html#autotoc_md815',1,'Implementation Details'],['../group__tcp.html#autotoc_md818',1,'Implementation Details'],['../group__tcp.html#autotoc_md820',1,'Implementation Details'],['../group__tcp.html#autotoc_md822',1,'Implementation Details'],['../group__tcp.html#autotoc_md826',1,'Implementation Details'],['../group__tcp.html#autotoc_md828',1,'Implementation Details'],['../group__tcp.html#autotoc_md832',1,'Implementation Details'],['../group__tcp.html#autotoc_md835',1,'Implementation Details'],['../group__tcp.html#autotoc_md837',1,'Implementation Details'],['../group__tcp.html#autotoc_md847',1,'Implementation Details']]],
  ['implementation_20notes_5',['Implementation Notes',['../group__tcp.html#autotoc_md839',1,'']]],
  ['implications_6',['Practical Implications',['../group__socket__states.html#autotoc_md253',1,'']]],
  ['implications_7',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md59',1,'']]],
  ['in_20action_3a_20practical_20examples_8',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['in_20c_2020_3a_9',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['in_20constructor_20bind_20listen_20explicit_10',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['in_20depth_11',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_12',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['in_20jsocketpp_13',['in jsocketpp',['../group__async__io.html',1,'Blocking vs Non-Blocking Sockets in jsocketpp'],['../group__socket-options.html',1,'Socket Options in jsocketpp']]],
  ['in_20jsocketpp_20_3a_14',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['in_20production_15',['Can I use jsocketpp in production?',['../index.html#autotoc_md418',1,'']]],
  ['in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_16',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['in_20the_20constructor_17',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['in_20your_20project_18',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_19',['Includes:',['../group__core.html#autotoc_md453',1,'']]],
  ['incompatibility_20',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md68',1,'']]],
  ['index_20cci_21',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['index_20cci_20submission_22',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['index_2emd_23',['index.md',['../index_8md.html',1,'']]],
  ['inet_5fntop_5faux_24',['inet_ntop_aux',['../namespacejsocketpp.html#a403588c277f89591897408faed72a910',1,'jsocketpp']]],
  ['initialization_20and_20cleanup_3a_25',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['initialization_3a_20posix_20approach_26',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['initsockets_27',['InitSockets',['../namespacejsocketpp.html#aef7428a3f4d80452442ecf3edfdbc89a',1,'jsocketpp']]],
  ['installation_28',['📦 Installation',['../index.html#autotoc_md382',1,'']]],
  ['integration_29',['🔧 Manual Integration',['../index.html#autotoc_md387',1,'']]],
  ['integration_20guide_30',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['integration_20in_20your_20project_31',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_32',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['integration_20test_3a_33',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['integration_20tests_3a_34',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md335',1,'']]],
  ['intended_20usage_35',['Intended Usage',['../classjsocketpp_1_1SocketOptions.html#autotoc_md867',1,'']]],
  ['interfaces”_20mean_36',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['interfaces_37',['Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'Example: Binding to All Interfaces'],['../group__bind__interfaces.html',1,'Understanding &lt;tt&gt;bind()&lt;/tt&gt;: Binding to All Interfaces vs Specific Interfaces']]],
  ['interfaces_20vs_20specific_20interfaces_38',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['internal_20buffer_39',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md705',1,'']]],
  ['internal_20helpers_40',['Internal Helpers',['../group__internal.html',1,'']]],
  ['internally_41',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['introduction_42',['Introduction',['../group__sockets__theory.html#autotoc_md260',1,'']]],
  ['introduction_20to_20the_20socket_20api_43',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'']]],
  ['invalid_5fsocket_44',['INVALID_SOCKET',['../namespacejsocketpp.html#a3ddf4938a63ed33a5e2f7d2625cb4405',1,'jsocketpp']]],
  ['ioctlsocket_45',['ioctlsocket',['../namespacejsocketpp.html#a771a44f3967222b2e3221ed3120220af',1,'jsocketpp']]],
  ['ipc_46',['IPC',['../index.html#autotoc_md396',1,'🧷 UNIX Domain Socket (IPC)'],['../group__sockets__theory.html#autotoc_md268',1,'2.4. Unix Domain Sockets (Local IPC)']]],
  ['ipfromsockaddr_47',['ipFromSockaddr',['../namespacejsocketpp.html#a18428d088b7f3b2e55efe9adc49e10a9',1,'jsocketpp']]],
  ['ipv4_20mapped_20ipv6_20behavior_48',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md731',1,'']]],
  ['ipv6_20behavior_49',['IPv6 Behavior',['../group__udp.html#autotoc_md495',1,'🌐 Dual-Stack and IPv6 Behavior'],['../group__tcp.html#autotoc_md731',1,'IPv4-Mapped IPv6 Behavior']]],
  ['ipv6_20handling_50',['IPv6 Handling',['../group__udp.html#autotoc_md535',1,'IPv6 Handling'],['../group__udp.html#autotoc_md541',1,'IPv6 Handling'],['../group__udp.html#autotoc_md555',1,'IPv6 Handling']]],
  ['ipv6_20only_51',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1029',1,'']]],
  ['is_20a_20socket_52',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['is_20a_20socket_20state_53',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['is_20blocking_54',['What is Blocking?',['../group__async__io.html#autotoc_md115',1,'']]],
  ['is_20ipv6_20only_55',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1029',1,'']]],
  ['is_20jsocketpp_20async_56',['Is jsocketpp async?',['../index.html#autotoc_md414',1,'']]],
  ['is_20multicast_57',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md604',1,'']]],
  ['is_20non_20blocking_58',['What is Non-Blocking?',['../group__async__io.html#autotoc_md116',1,'']]],
  ['is_20problematic_20on_20windows_59',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['is_20the_20default_20buffer_20size_60',['What is the default buffer size?',['../index.html#autotoc_md422',1,'']]],
  ['is_20transferred_61',['What Is Transferred',['../group__udp.html#autotoc_md502',1,'']]],
  ['is_20udp_62',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md464',1,'']]],
  ['is_20used_63',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['isbound_64',['isBound',['../group__udp.html#gadd6a72af69e4e8e1e8701c60a7e728f1',1,'jsocketpp::DatagramSocket::isBound()'],['../group__tcp.html#ga0b3a5cb732c669b678e03549e5af2427',1,'jsocketpp::ServerSocket::isBound()'],['../group__tcp.html#gac5d9708cad057d6d608fb732eb1bb117',1,'jsocketpp::Socket::isBound()']]],
  ['isclosed_65',['isClosed',['../group__tcp.html#gae91f746fb4cffa0eb8460c816a476d65',1,'jsocketpp::DatagramSocket::isClosed()'],['../group__tcp.html#gaeb5adb24bd7f50eaf8b52aa4441ffe71',1,'jsocketpp::ServerSocket::isClosed()'],['../group__tcp.html#ga368ea24012b68fcf6db4f9a75d6d1940',1,'jsocketpp::Socket::isClosed()']]],
  ['isconnected_66',['isConnected',['../group__udp.html#gac3b7c4a5fc5a21372c4a9cadb3e85efb',1,'jsocketpp::DatagramSocket::isConnected()'],['../group__tcp.html#gab1e4f32614be9a3609820f75dbcb4fc2',1,'jsocketpp::Socket::isConnected() const noexcept']]],
  ['isinputshutdown_67',['isInputShutdown',['../group__tcp.html#ga402fc4a398e670854cbb4edf791c1916',1,'jsocketpp::Socket']]],
  ['isipv4mappedipv6_68',['isIPv4MappedIPv6',['../group__core.html#gab0ac1b9850480abafeb047a4f96792a0',1,'jsocketpp']]],
  ['islistening_69',['isListening',['../group__tcp.html#ga1717f9859e5aeeba77c3d463ec53e735',1,'jsocketpp::ServerSocket']]],
  ['isoutputshutdown_70',['isOutputShutdown',['../group__tcp.html#gad2b2992b358d3656a2e0d3e854c897bc',1,'jsocketpp::Socket']]],
  ['ispassivesocket_71',['isPassiveSocket',['../group__socketopts.html#gad113886a7cc6100e5ef2c25ea504696e',1,'jsocketpp::ServerSocket::isPassiveSocket()'],['../group__socketopts.html#gaace6c3364b4016979537571b36c58727',1,'jsocketpp::SocketOptions::isPassiveSocket()']]],
  ['ispathinuse_72',['isPathInUse',['../classjsocketpp_1_1UnixSocket.html#a0b8200b52a5ed8c66c84ee52ba9f98e6',1,'jsocketpp::UnixSocket']]],
  ['issues_73',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md429',1,'']]],
  ['isvalid_74',['isValid',['../group__udp.html#gab33da807656e2ab920707d60605844f5',1,'jsocketpp::DatagramSocket::isValid()'],['../group__tcp.html#ga4e3ff54722a55e7500fdd76f26c53dac',1,'jsocketpp::ServerSocket::isValid()'],['../group__tcp.html#gae2b10ef466023b380a34b062359c0f65',1,'jsocketpp::Socket::isValid()'],['../classjsocketpp_1_1UnixSocket.html#acb7ad274be98890ca17dfa5deb86024b',1,'jsocketpp::UnixSocket::isValid()']]],
  ['it_20actually_20does_75',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_76',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['it_20work_20on_20windows_77',['Does it work on Windows?',['../index.html#autotoc_md420',1,'']]],
  ['it_20works_20internally_78',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['its_20limitations_79',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md86',1,'']]]
];
