var searchData=
[
  ['macos_0',['POSIX/BSD API (Unix/Linux/MacOS)',['../group__multicast__sockets.html#autotoc_md273',1,'']]],
  ['macos_20unix_1',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md413',1,'']]],
  ['main_2',['main',['../client_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4',1,'main():&#160;client.cpp'],['../server_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4',1,'main():&#160;server.cpp']]],
  ['main_20features_3',['Main Features',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1166',1,'']]],
  ['main_20tcp_20socket_20states_4',['Main TCP Socket States',['../group__socket__states.html#autotoc_md371',1,'']]],
  ['make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_5',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['make_20your_20cmake_20project_20conan_20friendly_6',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['makefile_7',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['management_8',['Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'1. Core Socket Creation and Management'],['../group__tcp.html#autotoc_md921',1,'Resource Management']]],
  ['management_20protocol_20igmp_9',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md268',1,'']]],
  ['manual_20cmake_20build_10',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['manual_20compilation_11',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['manual_20integration_12',['🔧 Manual Integration',['../index.html#autotoc_md511',1,'']]],
  ['manual_20nesting_13',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md983',1,'']]],
  ['mapped_20ipv6_20behavior_14',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md848',1,'']]],
  ['mapping_15',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md522',1,'']]],
  ['matters_16',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md617',1,'']]],
  ['matters_17',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md817',1,'']]],
  ['maxdatagrampayloadsafe_18',['MaxDatagramPayloadSafe',['../group__core.html#ga25eb16703a608853bca500682345bb89',1,'jsocketpp']]],
  ['maxudppayloadipv4_19',['MaxUdpPayloadIPv4',['../group__core.html#ga63ed4637719268844616341e0f8908cb',1,'jsocketpp']]],
  ['maxudppayloadipv6_20',['MaxUdpPayloadIPv6',['../group__core.html#ga041bcd9d09d1d8e134c7b8af72523d66',1,'jsocketpp']]],
  ['mean_21',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['mechanism_22',['🔧 Internal Mechanism',['../group__internal.html#autotoc_md610',1,'']]],
  ['methods_23',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md343',1,'']]],
  ['methods_20vs_20generic_20methods_24',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md343',1,'']]],
  ['miscellaneous_25',['7. Miscellaneous',['../group__list__bsd__socket__functions.html#autotoc_md32',1,'']]],
  ['misconceptions_20and_20caveats_26',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['mock_20example_20with_20google_20mock_3a_27',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md465',1,'']]],
  ['mock_20recv_20and_20send_3a_28',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md457',1,'']]],
  ['mock_20to_20mock_20recv_20and_20send_3a_29',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md457',1,'']]],
  ['mock_3a_30',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md465',1,'']]],
  ['mocking_20or_20stubbing_20socket_20api_20for_20unit_20tests_3a_31',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md464',1,'']]],
  ['mocking_20socket_20behavior_3a_32',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md456',1,'']]],
  ['mocking_3a_33',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md466',1,'']]],
  ['mode_34',['🔁 Behavior Based on Mode',['../group__udp.html#autotoc_md684',1,'']]],
  ['mode_35',['mode',['../structjsocketpp_1_1DatagramReadOptions.html#aa343a807611fa5b42e9663c4890d4cca',1,'jsocketpp::DatagramReadOptions']]],
  ['mode_20on_20a_20client_20socket_36',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1095',1,'']]],
  ['mode_3a_37',['mode:',['../group__async__io.html#autotoc_md150',1,'Blocking mode:'],['../group__async__io.html#autotoc_md154',1,'Blocking mode:'],['../group__async__io.html#autotoc_md158',1,'Blocking mode:'],['../group__async__io.html#autotoc_md161',1,'Blocking mode:'],['../group__async__io.html#autotoc_md151',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md155',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md159',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md162',1,'Non-blocking mode:']]],
  ['model_38',['Model',['../group__underlying__socket__api.html#autotoc_md429',1,'3.1 Client-Server Model'],['../group__underlying__socket__api.html#autotoc_md430',1,'3.2 Peer-to-Peer Model']]],
  ['models_39',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md428',1,'']]],
  ['models_20and_20data_20encapsulation_40',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md296',1,'']]],
  ['modern_20c_2020_41',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['modes_42',['Modes',['../group__tcp.html#autotoc_md880',1,'Connection Modes'],['../group__tcp.html#autotoc_md922',1,'Shutdown Modes'],['../group__udp.html#autotoc_md639',1,'Usage Modes']]],
  ['modes_20of_20operation_43',['Modes of Operation',['../group__tcp.html#autotoc_md962',1,'']]],
  ['module_44',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md359',1,'']]],
  ['more_20resources_45',['More Resources',['../group__socket__states.html#autotoc_md381',1,'']]],
  ['move_20assignment_46',['Example: Move assignment',['../group__socketopts.html#autotoc_md1163',1,'']]],
  ['mtu_47',['🔍 What is the MTU?',['../group__udp.html#autotoc_md659',1,'']]],
  ['multicast_48',['Multicast',['../group__multicast__sockets.html#autotoc_md271',1,'IPv6 Multicast'],['../classjsocketpp_1_1MulticastSocket.html#autotoc_md716',1,'What is Multicast?']]],
  ['multicast_20addressing_49',['Multicast Addressing',['../group__multicast__sockets.html#autotoc_md267',1,'']]],
  ['multicast_20and_20broadcast_50',['Multicast and Broadcast',['../group__underlying__socket__api.html#autotoc_md439',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md449',1,'6.3 Multicast and Broadcast']]],
  ['multicast_20data_51',['Multicast Data',['../group__multicast__sockets.html#autotoc_md277',1,'Receiving Multicast Data'],['../group__multicast__sockets.html#autotoc_md276',1,'Sending Multicast Data']]],
  ['multicast_20fundamentals_52',['IP Multicast Fundamentals',['../group__multicast__sockets.html#autotoc_md266',1,'']]],
  ['multicast_20programming_53',['IPv6 Multicast Programming',['../group__multicast__sockets.html#autotoc_md291',1,'']]],
  ['multicast_20receiver_54',['🌐 Multicast Receiver',['../index.html#autotoc_md518',1,'']]],
  ['multicast_20routing_55',['Multicast Routing',['../group__multicast__sockets.html#autotoc_md269',1,'']]],
  ['multicast_20socket_56',['Creating a Multicast Socket',['../group__multicast__sockets.html#autotoc_md274',1,'']]],
  ['multicast_20socket_20programming_57',['Multicast Socket Programming',['../group__multicast__sockets.html#autotoc_md272',1,'']]],
  ['multicast_20sockets_58',['Multicast Sockets',['../group__multicast__sockets.html',1,'Comprehensive Guide to Multicast Sockets'],['../group__multicast__sockets.html#autotoc_md265',1,'Introduction to Multicast Sockets']]],
  ['multicast_20ssm_59',['Source-Specific Multicast (SSM)',['../group__multicast__sockets.html#autotoc_md270',1,'']]],
  ['multicast_3a_60',['For Multicast:',['../group__socket-options.html#autotoc_md337',1,'']]],
  ['multicasting_2emd_61',['multicasting.md',['../multicasting_8md.html',1,'']]],
  ['multicastsocket_62',['MulticastSocket',['../group__socket-options.html#autotoc_md336',1,'3. UDP Sockets (<span class="tt">DatagramSocket</span>, <span class="tt">MulticastSocket</span>)'],['../classjsocketpp_1_1MulticastSocket.html',1,'jsocketpp::MulticastSocket'],['../group__udp.html#ga996b99882efa863b01e0fff4a9782a82',1,'jsocketpp::MulticastSocket::MulticastSocket()']]],
  ['multicastsocket_2ecpp_63',['MulticastSocket.cpp',['../MulticastSocket_8cpp.html',1,'']]],
  ['multicastsocket_2ehpp_64',['MulticastSocket.hpp',['../MulticastSocket_8hpp.html',1,'']]],
  ['multiple_20interfaces_65',['Handling Multiple Interfaces',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['multiple_20sockets_20bind_20to_20the_20same_20port_66',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]]
];
