var searchData=
[
  ['families_0',['Families',['../group__underlying__socket__api.html#autotoc_md314',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md292',1,'3. Socket Address Families']]],
  ['faq_1',['❓ FAQ',['../index.html#autotoc_md425',1,'']]],
  ['features_2',['Features',['../group__underlying__socket__api.html#autotoc_md324',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md334',1,'Advanced Socket API Features'],['../classjsocketpp_1_1MulticastSocket.html#autotoc_md656',1,'Features'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md491',1,'Key Features'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md660',1,'Key Features'],['../classjsocketpp_1_1Socket.html#autotoc_md755',1,'Key Features'],['../group__tcp.html#autotoc_md763',1,'Key Features'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1103',1,'Main Features']]],
  ['features_20at_20a_20glance_3',['✨ Features at a Glance',['../index.html#autotoc_md384',1,'']]],
  ['fields_4',['Fields',['../structjsocketpp_1_1BufferView.html#autotoc_md463',1,'']]],
  ['final_20thoughts_20and_20best_20practices_5',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md158',1,'']]],
  ['flexibility_20and_20safety_6',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md35',1,'']]],
  ['footprint_7',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md390',1,'']]],
  ['for_205_20seconds_20on_20close_8',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md944',1,'']]],
  ['for_20all_20sockets_9',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md220',1,'']]],
  ['for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_10',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['for_20conan_20center_20index_20cci_20submission_11',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md182',1,'']]],
  ['for_20cross_20platform_3a_12',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md350',1,'']]],
  ['for_20jsocketpp_13',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md106',1,'']]],
  ['for_20library_20authors_14',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md114',1,'']]],
  ['for_20modern_20c_2020_15',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['for_20multicast_3a_16',['For Multicast:',['../group__socket-options.html#autotoc_md225',1,'']]],
  ['for_20platform_20specific_20tests_3a_17',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md351',1,'']]],
  ['for_20readiness_18',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md153',1,'']]],
  ['for_20the_20socket’s_20lifetime_19',['Does the Local Binding Persist for the Socket’s Lifetime?',['../md_docs_2markdown_2Understanding_01Socket_01Binding_01in_01TCP_01and_01UDP_01Connections.html#autotoc_md61',1,'']]],
  ['for_20unit_20testing_20in_20c_2020_3a_20',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['for_20unit_20tests_3a_21',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md352',1,'']]],
  ['for_20vcpkg_22',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md361',1,'']]],
  ['format_23',['Format',['../group__tcp.html#autotoc_md795',1,'Format'],['../group__tcp.html#autotoc_md811',1,'Format'],['../group__tcp.html#autotoc_md841',1,'Protocol Format'],['../group__tcp.html#autotoc_md844',1,'Protocol Format'],['../group__tcp.html#autotoc_md868',1,'Protocol Format'],['../group__tcp.html#autotoc_md871',1,'Protocol Format']]],
  ['friendly_24',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md178',1,'']]],
  ['fromnetwork_25',['fromNetwork',['../namespacejsocketpp_1_1net.html#adbc3d8ebcf4347173f61e55e236c8b37',1,'jsocketpp::net::fromNetwork(const uint16_t val)'],['../namespacejsocketpp_1_1net.html#acca9e860a0a33d2508bfa9986049db8c',1,'jsocketpp::net::fromNetwork(const uint32_t val)']]],
  ['fully_20step_20by_20step_20posix_20style_26',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['function_27',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../md_docs_2markdown_2Understanding_01Socket_01Binding_01in_01TCP_01and_01UDP_01Connections.html#autotoc_md54',1,'']]],
  ['functions_28',['2.1 Key Functions',['../group__underlying__socket__api.html#autotoc_md313',1,'']]],
  ['further_20reading_29',['Further Reading',['../group__socket-options.html#autotoc_md237',1,'']]]
];
