var searchData=
[
  ['waiting_20for_20readiness_0',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['waitready_1',['waitReady',['../group__udp.html#ga0deb65a2e7c215e0e46ace579c702f6e',1,'jsocketpp::DatagramSocket::waitReady()'],['../group__tcp.html#ga61c1904213b0971817ec917fd2a01ccf',1,'jsocketpp::ServerSocket::waitReady()'],['../group__tcp.html#ga6b39b1375048cc167409b5b513c3ad8c',1,'jsocketpp::Socket::waitReady()']]],
  ['warning_2',['Warning',['../group__tcp.html#autotoc_md841',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md854',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md812',1,'⚠️ Race Condition Warning']]],
  ['we_20use_20select_20for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_3',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['what_20about_20udp_20and_20unix_20sockets_4',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md334',1,'']]],
  ['what_20are_20socket_20options_5',['What Are Socket Options?',['../group__socket-options.html#autotoc_md286',1,'']]],
  ['what_20does_20“binding_20to_20all_20interfaces”_20mean_6',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['what_20happens_20when_20multiple_20sockets_20bind_20to_20the_20same_20port_7',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['what_20is_20a_20socket_8',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md345',1,'']]],
  ['what_20is_20a_20socket_20state_9',['What is a Socket State?',['../group__socket__states.html#autotoc_md327',1,'']]],
  ['what_20is_20blocking_10',['What is Blocking?',['../group__async__io.html#autotoc_md138',1,'']]],
  ['what_20is_20connected_20udp_11',['🔌 What Is Connected UDP?',['../group__udp.html#autotoc_md629',1,'']]],
  ['what_20is_20multicast_12',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md765',1,'']]],
  ['what_20is_20non_20blocking_13',['What is Non-Blocking?',['../group__async__io.html#autotoc_md139',1,'']]],
  ['what_20is_20socket_20binding_14',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md64',1,'']]],
  ['what_20is_20the_20default_20buffer_20size_15',['What is the default buffer size?',['../index.html#autotoc_md505',1,'']]],
  ['what_20is_20the_20mtu_16',['🔍 What is the MTU?',['../group__udp.html#autotoc_md714',1,'']]],
  ['what_20is_20transferred_17',['What Is Transferred',['../group__udp.html#autotoc_md616',1,'']]],
  ['what_20is_20udp_18',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md583',1,'']]],
  ['what_20it_20actually_20does_19',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['what_20java_20does_20',['What Java Does',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['what_20jsocketpp_20does_21',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['what_20jsocketpp_20gets_20right_22',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md130',1,'']]],
  ['when_20multiple_20sockets_20bind_20to_20the_20same_20port_23',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['when_20to_20adjust_24',['When to Adjust',['../group__core.html#autotoc_md543',1,'']]],
  ['when_20to_20use_25',['When to Use',['../group__socketopts.html#autotoc_md1211',1,'']]],
  ['when_20true_20matters_26',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md866',1,'']]],
  ['why_20jsocketpp_27',['💡 Why jsocketpp?',['../index.html#autotoc_md453',1,'']]],
  ['why_20not_20expose_20windows_20so_5freuseaddr_28',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md121',1,'']]],
  ['why_20require_20the_20port_20in_20the_20constructor_29',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['why_20select_20is_20used_30',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md266',1,'']]],
  ['why_20this_20is_20problematic_20on_20windows_31',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['why_20this_20matters_32',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md569',1,'']]],
  ['wildcard_20addresses_33',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md175',1,'']]],
  ['window_20size_20linux_34',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md216',1,'']]],
  ['windows_35',['Windows',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md232',1,'3. ioctlsocket (Windows)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md243',1,'4. WSAIoctl (Windows)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md257',1,'DeviceIoControl (Windows)'],['../index.html#autotoc_md503',1,'Does it work on Windows?'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md250',1,'Example: Get Interface List (Windows)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md239',1,'Example: Non-Blocking Socket (Windows)'],['../group__address__reuse.html#autotoc_md111',1,'Why This is Problematic on Windows'],['../group__address__reuse.html#autotoc_md103',1,'Windows']]],
  ['windows_20counterparts_36',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md274',1,'']]],
  ['windows_20only_37',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md87',1,'']]],
  ['windows_20so_5freuseaddr_38',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md121',1,'']]],
  ['windows_20support_39',['Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'Comprehensive Guide to &lt;tt&gt;ioctl&lt;/tt&gt;, &lt;tt&gt;fcntl&lt;/tt&gt;, &lt;tt&gt;ioctlsocket&lt;/tt&gt;, &lt;tt&gt;WSAIoctl&lt;/tt&gt;, and Related Functions: Commands, Use Cases, and Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md218',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md229',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md240',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md251',1,'Windows Support']]],
  ['windows_20version_20support_20summary_40',['Windows Version Support Summary',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md259',1,'']]],
  ['windows_20winsock_41',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md373',1,'']]],
  ['windows_3a_42',['Windows:',['../group__address__reuse.html#autotoc_md85',1,'On Windows:'],['../group__address__reuse.html#autotoc_md86',1,'On Windows:']]],
  ['winsock_43',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md373',1,'']]],
  ['winsock_20apis_44',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md320',1,'']]],
  ['with_20acceptnonblocking_45',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md821',1,'']]],
  ['with_20extreme_20care_46',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md1039',1,'']]],
  ['with_20google_20mock_3a_47',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['with_20mocking_3a_48',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md425',1,'']]],
  ['with_20select_49',['Example: Use with &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__socketopts.html#autotoc_md1043',1,'']]],
  ['with_20so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_50',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['with_20so_5freuseaddr_20only_3a_51',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['with_20so_5freuseaddr_20so_5freuseport_3a_52',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['with_20so_5freuseaddr_3a_53',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md104',1,'']]],
  ['with_20so_5freuseport_54',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md84',1,'']]],
  ['work_55',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md355',1,'']]],
  ['work_56',['How does error handling work?',['../index.html#autotoc_md499',1,'']]],
  ['work_20on_20windows_57',['Does it work on Windows?',['../index.html#autotoc_md503',1,'']]],
  ['work_3a_20the_20lifecycle_58',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['works_20internally_59',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['write_60',['Write',['../namespacejsocketpp.html#a0d2868e06cd95730d5088336f8c3c174a1129c0e4d43f2d121652a7302712cff6',1,'jsocketpp']]],
  ['write_61',['write',['../group__async__io.html#autotoc_md160',1,'📤 <span class="tt">send</span> / <span class="tt">write</span>'],['../group__udp.html#ga87c837cd891ddd8b4daeacc61e1326df',1,'jsocketpp::DatagramSocket::write(const T &amp;value)'],['../group__udp.html#gafb2439eddc4ce6db4915e02ed7946444',1,'jsocketpp::DatagramSocket::write(const DatagramPacket &amp;packet)'],['../group__udp.html#ga96bc239f42265d5c408c8f15046f24c8',1,'jsocketpp::DatagramSocket::write(std::string_view message) const'],['../group__udp.html#gab5aa2df14c7492cf16a165e6b4cd9426',1,'jsocketpp::DatagramSocket::write(std::string_view message, std::string_view host, Port port)'],['../group__tcp.html#ga8b952bd8912694754bb34ab763aa8daa',1,'jsocketpp::Socket::write()'],['../classjsocketpp_1_1UnixSocket.html#abecab540df2b16e50b09de7b8d38c43e',1,'jsocketpp::UnixSocket::write()']]],
  ['writeall_62',['writeAll',['../group__tcp.html#gad1803ae12c1562ec09c28d19c1067914',1,'jsocketpp::Socket']]],
  ['writeatmostwithtimeout_63',['writeAtMostWithTimeout',['../group__tcp.html#ga16bb8c36a3fd9a3a97a0d4f5d5036550',1,'jsocketpp::Socket']]],
  ['writefrom_64',['writeFrom',['../group__tcp.html#gab4484254fc3c113a373718198c382dd9',1,'jsocketpp::Socket']]],
  ['writefromall_65',['writeFromAll',['../group__tcp.html#ga686c95af72f4193d1a7c6dd6e658e4ba',1,'jsocketpp::Socket']]],
  ['writeprefixed_66',['writePrefixed',['../group__tcp.html#ga81f896d90e08fbfb1d63f1aabb21c970',1,'jsocketpp::Socket::writePrefixed(const std::string_view payload)'],['../group__tcp.html#gab0b48a69153c1ed31dd158ec7afb901c',1,'jsocketpp::Socket::writePrefixed(const void *data, std::size_t len) const']]],
  ['writeto_67',['writeTo',['../group__udp.html#gae61e0fd22b7a69d6b5f706141fff8934',1,'jsocketpp::DatagramSocket']]],
  ['writev_68',['writev',['../group__tcp.html#gadf5094228dfdef090b0d49a3a9e9e78d',1,'jsocketpp::Socket']]],
  ['writevall_69',['writevAll',['../group__tcp.html#ga804a69fa791fc8adb91f32ab37244a0a',1,'jsocketpp::Socket']]],
  ['writevfrom_70',['writevFrom',['../group__tcp.html#ga650e041e62870ef5710b0e45401e679d',1,'jsocketpp::Socket']]],
  ['writevfromall_71',['writevFromAll',['../group__tcp.html#ga7b3ab7a896b7fbfeba9b80672c41b236',1,'jsocketpp::Socket']]],
  ['writevfromwithtotaltimeout_72',['writevFromWithTotalTimeout',['../group__tcp.html#ga3e2b5bd60122d459134cd5b0a3a27077',1,'jsocketpp::Socket']]],
  ['writevwithtotaltimeout_73',['writevWithTotalTimeout',['../group__tcp.html#ga8e539c866c9fcad3578f9be78cbfdaf4',1,'jsocketpp::Socket']]],
  ['writewithtotaltimeout_74',['writeWithTotalTimeout',['../group__tcp.html#ga964bb0e901179bc5eac126d77b0590eb',1,'jsocketpp::Socket']]],
  ['wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_75',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['wsaioctl_20windows_76',['4. WSAIoctl (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md243',1,'']]]
];
