var searchData=
[
  ['c_0',['C',['../group__multicast__sockets.html#autotoc_md279',1,'Example: Receiver in C'],['../group__multicast__sockets.html#autotoc_md278',1,'Example: Sender (Broadcaster) in C']]],
  ['c_2020_1',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['c_2020_20cross_20platform_20socket_20library_2',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['c_2020_3a_3',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md455',1,'']]],
  ['c_20af_5finet_4',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md435',1,'']]],
  ['c_20clear_20api_5',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md48',1,'']]],
  ['c_20jsocketpp_20hybrid_6',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md53',1,'']]],
  ['c_20socket_20libraries_7',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['c_20winsock_8',['C Winsock',['../group__multicast__sockets.html#autotoc_md284',1,'Example: Receiver in C++ (Winsock)'],['../group__multicast__sockets.html#autotoc_md283',1,'Example: Sender in C++ (Winsock)']]],
  ['cachelocalendpoint_9',['cacheLocalEndpoint',['../group__udp.html#ga465ec84374a81fa09cf486e054863673',1,'jsocketpp::DatagramSocket']]],
  ['callback_20signature_10',['🔁 Callback Signature',['../group__tcp.html#autotoc_md801',1,'']]],
  ['can_20i_20use_20jsocketpp_20in_20production_11',['Can I use jsocketpp in production?',['../index.html#autotoc_md542',1,'']]],
  ['cap_12',['Why a &quot;safe&quot; cap?',['../group__core.html#autotoc_md590',1,'']]],
  ['care_13',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md990',1,'']]],
  ['case_14',['Case',['../group__address__reuse.html#autotoc_md92',1,'✅ Use Case'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md712',1,'Use Case']]],
  ['cases_15',['Cases',['../group__internal.html#autotoc_md612',1,'✅ Use Cases'],['../group__udp.html#autotoc_md663',1,'✅ Use Cases'],['../group__socketopts.html#autotoc_md1093',1,'✅ Use Cases'],['../group__socketopts.html#autotoc_md1105',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md1137',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md996',1,'🔧 Common Use Cases'],['../group__socketopts.html#autotoc_md1014',1,'🔧 Use Cases'],['../group__socketopts.html#autotoc_md1025',1,'🔧 Use Cases'],['../group__tcp.html#autotoc_md830',1,'🛠 Use Cases'],['../group__socketopts.html#autotoc_md1005',1,'🧩 Use Cases'],['../index.html#autotoc_md492',1,'🧰 Typical Use Cases'],['../group__multicast__sockets.html#autotoc_md293',1,'Applications and Use Cases'],['../group__udp.html#autotoc_md650',1,'Common Use Cases'],['../group__udp.html#autotoc_md652',1,'Common Use Cases'],['../group__udp.html#autotoc_md654',1,'Common Use Cases'],['../group__socketopts.html#autotoc_md1036',1,'Protocol Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md215',1,'Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md227',1,'Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md238',1,'Use Cases'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md249',1,'Use Cases'],['../group__udp.html#autotoc_md678',1,'Use Cases'],['../group__tcp.html#autotoc_md850',1,'Use Cases'],['../group__tcp.html#autotoc_md854',1,'Use Cases'],['../group__tcp.html#autotoc_md860',1,'Use Cases'],['../group__tcp.html#autotoc_md866',1,'Use Cases'],['../group__tcp.html#autotoc_md870',1,'Use Cases'],['../group__tcp.html#autotoc_md876',1,'Use Cases'],['../group__tcp.html#autotoc_md960',1,'Use Cases'],['../group__tcp.html#autotoc_md961',1,'Use Cases'],['../group__socketopts.html#autotoc_md1100',1,'Use Cases'],['../group__socketopts.html#autotoc_md1114',1,'Use Cases'],['../group__socketopts.html#autotoc_md1123',1,'Use Cases']]],
  ['cases_16',['📦 Common use cases',['../group__address__reuse.html#autotoc_md80',1,'']]],
  ['cases_20and_20applications_17',['Cases and Applications',['../group__underlying__socket__api.html#autotoc_md442',1,'8. Use Cases and Applications'],['../group__network__data__units.html#autotoc_md302',1,'Use Cases and Applications']]],
  ['cases_20and_20windows_20support_18',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['cases_20to_20consider_3a_19',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md467',1,'']]],
  ['cases_3a_20',['Cases:',['../group__tcp.html#autotoc_md844',1,'Common Use Cases:'],['../structjsocketpp_1_1DatagramReadResult.html#autotoc_md632',1,'Use Cases:']]],
  ['catching_20and_20handling_20socket_20exceptions_21',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md982',1,'']]],
  ['caveats_22',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['cci_23',['CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'6. Submit a Pull Request to CCI'],['../group__conan__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the Conan Center Index (CCI)']]],
  ['cci_20submission_24',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['center_20index_20cci_25',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['center_20index_20cci_20submission_26',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['chaining_27',['Exception Chaining',['../classjsocketpp_1_1SocketException.html#autotoc_md981',1,'']]],
  ['check_20if_20socket_20is_20ipv6_20only_28',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1146',1,'']]],
  ['choosereceivesize_29',['chooseReceiveSize',['../group__udp.html#ga1ff1dc3fb9ed36e31bc62941edf1d44c',1,'jsocketpp::DatagramSocket']]],
  ['class_20mapping_30',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md522',1,'']]],
  ['classes_31',['Classes',['../group__exceptions.html',1,'Exception Classes'],['../classjsocketpp_1_1SocketOptions.html#autotoc_md985',1,'Supported Classes']]],
  ['cleanup_32',['Resource Cleanup',['../group__tcp.html#autotoc_md727',1,'']]],
  ['cleanup_33',['cleanup',['../group__udp.html#gaa0727094596347aa858629f6e5c7febf',1,'jsocketpp::DatagramSocket::cleanup()'],['../group__tcp.html#ga2a630f28a613224176ff17f7ee0c6a4c',1,'jsocketpp::ServerSocket::cleanup()'],['../group__tcp.html#ga744a91706b9510d266b7c07e31f3e028',1,'jsocketpp::Socket::cleanup()']]],
  ['cleanup_3a_34',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md458',1,'']]],
  ['cleanupandrethrow_35',['cleanupAndRethrow',['../group__udp.html#ga6608c56d08ccdb2807bd47cc862af24a',1,'jsocketpp::DatagramSocket::cleanupAndRethrow()'],['../group__tcp.html#ga33183210cdc2a1e281006e325cc2a173',1,'jsocketpp::ServerSocket::cleanupAndRethrow()'],['../group__tcp.html#ga8bc150c503e051c12165680e74b5ae48',1,'jsocketpp::Socket::cleanupAndRethrow()']]],
  ['cleanupandthrow_36',['cleanupAndThrow',['../group__udp.html#ga1973415ece2f77f191b250b9e9690733',1,'jsocketpp::DatagramSocket::cleanupAndThrow()'],['../group__tcp.html#gab5572cb795d9b45ee50a0ddf9cb9c075',1,'jsocketpp::ServerSocket::cleanupAndThrow()'],['../group__tcp.html#gaf80aa30f2806a17b930878841dfab7ad',1,'jsocketpp::Socket::cleanupAndThrow()']]],
  ['cleanupsockets_37',['CleanupSockets',['../namespacejsocketpp.html#a027103bbab1364c1f878d5c49c0af67c',1,'jsocketpp']]],
  ['clear_38',['clear',['../classjsocketpp_1_1DatagramPacket.html#a7853459de9f4e83363ed341bb465930a',1,'jsocketpp::DatagramPacket']]],
  ['clear_20api_39',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md48',1,'']]],
  ['client_40',['Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1168',1,'Example: Simple Client'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md636',1,'Example: Simple UDP Echo Server and Client']]],
  ['client_20c_20af_5finet_41',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md435',1,'']]],
  ['client_20integration_20test_3a_42',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md461',1,'']]],
  ['client_20python_20af_5finet_43',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md434',1,'']]],
  ['client_20server_20model_44',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md429',1,'']]],
  ['client_20side_45',['4.2. Client Side',['../group__sockets__theory.html#autotoc_md408',1,'']]],
  ['client_20socket_46',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1095',1,'']]],
  ['client_2ecpp_47',['client.cpp',['../client_8cpp.html',1,'']]],
  ['client_3a_48',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md460',1,'']]],
  ['close_49',['close',['../group__udp.html#ga9d0a9582b3a2a72bf62f182dbc33c352',1,'jsocketpp::DatagramSocket::close()'],['../group__tcp.html#ga0245d40096ca089255c67303eebf17e6',1,'jsocketpp::ServerSocket::close()'],['../group__tcp.html#ga75ee749264ccbcfc4dfbf5442e55dcb8',1,'jsocketpp::Socket::close()'],['../classjsocketpp_1_1UnixSocket.html#a3f87192fe9d9c81a3d78e007bfc40179',1,'jsocketpp::UnixSocket::close()'],['../group__socketopts.html#autotoc_md1007',1,'Example: Set <span class="tt">SO_LINGER</span> to linger for 5 seconds on close']]],
  ['closeorthrow_50',['closeOrThrow',['../group__internal.html#gab3b8ac088a7936657681c6de9a4400e1',1,'jsocketpp::internal']]],
  ['closesocket_51',['CloseSocket',['../namespacejsocketpp.html#a12fd46ba498b19d6102220bc100ef931',1,'jsocketpp']]],
  ['cmake_52',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md477',1,'']]],
  ['cmake_20build_53',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['cmake_20for_20platform_20specific_20tests_3a_54',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md463',1,'']]],
  ['cmake_20integration_20in_20your_20project_55',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['cmake_20presets_20recommended_56',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['cmake_20project_20conan_20friendly_57',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['code_20of_20conduct_58',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md565',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20structure_59',['Request Code Structure',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md211',1,'']]],
  ['code_20style_20guidelines_60',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md557',1,'']]],
  ['code_5fof_5fconduct_2emd_61',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['combining_20with_20so_5freuseport_62',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md84',1,'']]],
  ['commands_63',['Commands',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md214',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md224',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md235',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md246',1,'Common Commands']]],
  ['commands_20use_20cases_20and_20windows_20support_64',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['commit_20hooks_65',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md559',1,'']]],
  ['commit_20hooks_66',['Pre-commit hooks',['../index.html#autotoc_md529',1,'']]],
  ['common_20commands_67',['Common Commands',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md214',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md224',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md235',1,'Common Commands'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md246',1,'Common Commands']]],
  ['common_20errors_68',['Common Errors',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md213',1,'Common Errors'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md226',1,'Common Errors'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md237',1,'Common Errors'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md248',1,'Common Errors']]],
  ['common_20issues_69',['Troubleshooting Common Issues',['../group__multicast__sockets.html#autotoc_md292',1,'']]],
  ['common_20options_20by_20socket_20type_70',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md331',1,'']]],
  ['common_20scenarios_71',['Common Scenarios',['../group__udp.html#autotoc_md681',1,'']]],
  ['common_20use_20cases_72',['Common Use Cases',['../group__socketopts.html#autotoc_md996',1,'🔧 Common Use Cases'],['../group__udp.html#autotoc_md650',1,'Common Use Cases'],['../group__udp.html#autotoc_md652',1,'Common Use Cases'],['../group__udp.html#autotoc_md654',1,'Common Use Cases']]],
  ['common_20use_20cases_73',['📦 Common use cases',['../group__address__reuse.html#autotoc_md80',1,'']]],
  ['common_20use_20cases_3a_74',['Common Use Cases:',['../group__tcp.html#autotoc_md844',1,'']]],
  ['common_2ecpp_75',['common.cpp',['../common_8cpp.html',1,'']]],
  ['common_2ehpp_76',['common.hpp',['../common_8hpp.html',1,'']]],
  ['communication_77',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md431',1,'']]],
  ['communication_20models_78',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md428',1,'']]],
  ['comparison_79',['📚 Java Comparison',['../group__async__io.html#autotoc_md166',1,'']]],
  ['comparison_20table_3a_20socket_20types_80',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md394',1,'']]],
  ['comparison_20with_20acceptnonblocking_81',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md772',1,'']]],
  ['comparison_3a_20jsocketpp_20vs_20other_20c_20socket_20libraries_82',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['compilation_83',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['components_84',['Key Components',['../namespacejsocketpp_1_1detail.html#autotoc_md709',1,'']]],
  ['components_20of_20the_20socket_20api_85',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md424',1,'']]],
  ['comprehensive_20guide_20to_20ioctl_20fcntl_20ioctlsocket_86',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['comprehensive_20guide_20to_20ioctl_20fcntl_20ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_87',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['comprehensive_20guide_20to_20multicast_20sockets_88',['Comprehensive Guide to Multicast Sockets',['../group__multicast__sockets.html',1,'']]],
  ['comprehensive_20guide_20to_20the_20socket_20api_89',['Comprehensive Guide to the Socket API',['../group__underlying__socket__api.html',1,'']]],
  ['comprehensive_20list_20of_20socket_20programming_20functions_90',['Comprehensive List of Socket Programming Functions',['../group__list__bsd__socket__functions.html',1,'']]],
  ['comprehensive_20list_20of_20socket_20programming_20functions_2emd_91',['Comprehensive List of Socket Programming Functions.md',['../Comprehensive_01List_01of_01Socket_01Programming_01Functions_8md.html',1,'']]],
  ['conan_92',['✅ Conan',['../index.html#autotoc_md509',1,'']]],
  ['conan_20center_20index_20cci_93',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['conan_20center_20index_20cci_20submission_94',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['conan_20friendly_95',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['conan_20recipe_20conanfile_20py_96',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md187',1,'']]],
  ['conan_5fpublish_5fguide_2emd_97',['conan_publish_guide.md',['../conan__publish__guide_8md.html',1,'']]],
  ['conanfile_20py_98',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md187',1,'']]],
  ['concepts_99',['Concepts',['../buffer__traits_8hpp.html#autotoc_md707',1,'Key Concepts'],['../group__network__data__units.html#autotoc_md301',1,'Related Concepts']]],
  ['conclusion_100',['Conclusion',['../group__address__reuse.html#autotoc_md129',1,'✅ Conclusion'],['../group__underlying__socket__api.html#autotoc_md444',1,'10. Conclusion'],['../group__underlying__socket__api.html#autotoc_md452',1,'8. Conclusion'],['../group__list__bsd__socket__functions.html#autotoc_md35',1,'Conclusion'],['../group__bind__interfaces.html#autotoc_md182',1,'Conclusion'],['../group__multicast__sockets.html#autotoc_md294',1,'Conclusion'],['../group__network__data__units.html#autotoc_md304',1,'Conclusion'],['../group__socket__library__comparison.html#autotoc_md365',1,'Conclusion']]],
  ['conclusion_20advice_101',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md323',1,'']]],
  ['conclusion_3a_102',['Conclusion:',['../group__unit__tests.html#autotoc_md468',1,'']]],
  ['condition_20warning_103',['⚠️ Race Condition Warning',['../group__tcp.html#autotoc_md763',1,'']]],
  ['conduct_104',['Conduct',['../md_CONTRIBUTING.html#autotoc_md565',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['configuration_105',['Configuration',['../group__tcp.html#autotoc_md781',1,'⚙️ Configuration'],['../group__list__bsd__socket__functions.html#autotoc_md30',1,'5. Socket Information and Configuration']]],
  ['configuration_20of_20accepted_20socket_106',['Configuration of Accepted Socket',['../group__tcp.html#autotoc_md732',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md741',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md750',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md761',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md794',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md807',1,'⚙️ Configuration of Accepted Socket']]],
  ['configuration_20parameters_107',['Configuration Parameters',['../group__tcp.html#autotoc_md838',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md641',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md832',1,'Configuration Parameters']]],
  ['configured_20receive_20buffer_20size_108',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md1016',1,'']]],
  ['connect_109',['connect',['../group__async__io.html#autotoc_md149',1,'🔌 <span class="tt">connect</span>'],['../group__udp.html#ga915c790c7cfde485e680ddec2edb2e74',1,'jsocketpp::DatagramSocket::connect()'],['../group__tcp.html#ga93cc325113abb7433288338ca3facde1',1,'jsocketpp::Socket::connect()'],['../classjsocketpp_1_1UnixSocket.html#a6a5359f3b15c37556b8e2cd558760603',1,'jsocketpp::UnixSocket::connect()']]],
  ['connect_20accept_20recv_20and_20send_110',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['connect_20bind_20to_20a_20local_20address_111',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['connect_20function_112',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['connection_113',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['connection_20modes_114',['Connection Modes',['../group__tcp.html#autotoc_md880',1,'']]],
  ['connectionless_20approach_115',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md298',1,'']]],
  ['connections_116',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['cons_117',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['consider_3a_118',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md467',1,'']]],
  ['considerations_119',['Considerations',['../group__sockets__theory.html#autotoc_md402',1,'2.7. Security and Performance Considerations'],['../group__select__poll__epoll__iocp.html#autotoc_md317',1,'6. <b>Cross-Platform API Considerations</b>'],['../group__underlying__socket__api.html#autotoc_md451',1,'7. Practical Considerations'],['../group__underlying__socket__api.html#autotoc_md441',1,'7. Security Considerations'],['../group__underlying__socket__api.html#autotoc_md443',1,'9. Platform-Specific Considerations'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md263',1,'Practical Considerations'],['../group__multicast__sockets.html#autotoc_md289',1,'Security Considerations']]],
  ['construction_20binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_120',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['constructor_121',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['constructor_20bind_20listen_20explicit_122',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['constructor_20defaults_123',['Constructor Defaults',['../group__address__reuse.html#autotoc_md119',1,'']]],
  ['constructor_20does_20all_20java_20default_20style_124',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['constructor_20does_20all_20steps_125',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['contents_126',['Contents',['../namespacejsocketpp_1_1internal.html#autotoc_md710',1,'Contents'],['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md325',1,'Table of Contents']]],
  ['context_127',['Example Usage Context',['../group__list__bsd__socket__functions.html#autotoc_md34',1,'']]],
  ['contributing_128',['🤝 Contributing',['../index.html#autotoc_md531',1,'']]],
  ['contributing_20to_20jsocketpp_129',['Contributing to jsocketpp',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_130',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['control_131',['Control',['../group__address__reuse.html#autotoc_md120',1,'Developer Control'],['../group__multicast__sockets.html#autotoc_md287',1,'TTL and Scope Control']]],
  ['convertipv4mappedipv6toipv4_132',['convertIPv4MappedIPv6ToIPv4',['../group__core.html#ga4da3763b1f8385b27ebbe44cdcfdfc8d',1,'jsocketpp']]],
  ['core_20behavior_133',['⚙️ Core Behavior',['../group__udp.html#autotoc_md673',1,'']]],
  ['core_20components_20of_20the_20socket_20api_134',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md424',1,'']]],
  ['core_20socket_20creation_20and_20management_135',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['core_20utilities_20and_20types_136',['Core Utilities and Types',['../group__core.html',1,'']]],
  ['counterpart_20in_20tcp_137',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md299',1,'']]],
  ['counterparts_138',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md315',1,'']]],
  ['coverage_20for_20cross_20platform_3a_139',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md462',1,'']]],
  ['create_20a_20vcpkg_20portfile_140',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md475',1,'']]],
  ['creating_20a_20multicast_20socket_141',['Creating a Multicast Socket',['../group__multicast__sockets.html#autotoc_md274',1,'']]],
  ['creation_20and_20management_142',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['cross_20platform_20api_20considerations_143',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md317',1,'']]],
  ['cross_20platform_20socket_20library_144',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['cross_20platform_20socket_20library_20for_20modern_20c_2020_145',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['cross_20platform_20support_146',['Cross-Platform Support',['../group__socket-options.html#autotoc_md329',1,'']]],
  ['cross_20platform_3a_147',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md462',1,'']]],
  ['custom_20device_20driver_20linux_148',['Example: Custom Device Driver (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md217',1,'']]],
  ['custom_20timeouts_20via_20select_149',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md143',1,'']]],
  ['customization_150',['Customization',['../group__core.html#autotoc_md583',1,'Customization'],['../group__core.html#autotoc_md588',1,'Customization']]]
];
