var searchData=
[
  ['patterns_20and_20best_20practices_0',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['peek_1',['peek',['../group__tcp.html#ga5c413ef976df1e89528d9b3df6484c89',1,'jsocketpp::Socket']]],
  ['peer_20model_2',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md306',1,'']]],
  ['peer_20to_20peer_20model_3',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md306',1,'']]],
  ['performance_20considerations_4',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md278',1,'']]],
  ['performance_20footprint_5',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md378',1,'']]],
  ['platform_20api_20considerations_6',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'']]],
  ['platform_20apis_7',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['platform_20behavior_8',['Platform Behavior',['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md463',1,'Platform Behavior'],['../group__tcp.html#autotoc_md477',1,'Platform Behavior']]],
  ['platform_20notes_9',['Platform Notes',['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md496',1,'Platform Notes']]],
  ['platform_20socket_20library_10',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['platform_20socket_20library_20for_20modern_20c_2020_11',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['platform_20specific_20apis_12',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md288',1,'']]],
  ['platform_20specific_20considerations_13',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md319',1,'']]],
  ['platform_20specific_20details_14',['Platform-Specific Details',['../group__tcp.html#autotoc_md593',1,'']]],
  ['platform_20specific_20tests_3a_15',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['platform_20support_16',['Platform Support',['../group__socket-options.html#autotoc_md205',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md485',1,'Platform Support']]],
  ['platform_20toolchain_20support_17',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md374',1,'']]],
  ['platform_3a_18',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['pledge_19',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md438',1,'']]],
  ['poco_3a_3anet_20',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md233',1,'']]],
  ['poll_21',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md187',1,'']]],
  ['poll_20and_20epoll_20as_20alternatives_22',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['port_23',['Port',['../group__address__reuse.html#autotoc_md74',1,'🧪 What Happens When Multiple Sockets Bind to the Same Port?'],['../group__core.html#ga1a7be273748ae3d91bc5ebe6499788a7',1,'jsocketpp::Port']]],
  ['port_24',['port',['../classjsocketpp_1_1DatagramPacket.html#a6619b7fcd476199e4a9c454d06f1bcd4',1,'jsocketpp::DatagramPacket']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_25',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['port_20in_20the_20constructor_26',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['port_20locally_27',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md355',1,'']]],
  ['portability_28',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md36',1,'']]],
  ['portfile_29',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md351',1,'']]],
  ['portfile_20cmake_30',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md353',1,'']]],
  ['portfromsockaddr_31',['portFromSockaddr',['../namespacejsocketpp.html#a71637861db9b297572bc1de3df56a59a',1,'jsocketpp::portFromSockaddr()'],['../common_8cpp.html#a9426d41e1d985314f67e7392e64cbbff',1,'portFromSockaddr():&#160;common.cpp']]],
  ['posix_20approach_32',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['posix_20linux_20macos_20unix_33',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md289',1,'']]],
  ['posix_20style_34',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['posix_20winsock_20apis_35',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['practical_20considerations_36',['7. Practical Considerations',['../group__underlying__socket__api.html#autotoc_md327',1,'']]],
  ['practical_20examples_37',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['practical_20implications_38',['Practical Implications',['../group__socket__states.html#autotoc_md253',1,'']]],
  ['practical_20implications_39',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md59',1,'']]],
  ['practical_20recommendations_40',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md195',1,'']]],
  ['practices_41',['Practices',['../group__async__io.html#autotoc_md146',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md155',1,'Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['practices_20recap_42',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['pre_20commit_20hooks_43',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md428',1,'']]],
  ['preconditions_44',['Preconditions',['../group__core.html#autotoc_md453',1,'']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_45',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_46',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md349',1,'']]],
  ['prerequisites_47',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md162',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md347',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md4',1,'Prerequisites']]],
  ['presets_20recommended_48',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['problematic_20on_20windows_49',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['production_50',['Can I use jsocketpp in production?',['../index.html#autotoc_md411',1,'']]],
  ['project_51',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['project_20conan_20friendly_52',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['pros_20and_20cons_53',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['protocol_20behavior_54',['Protocol Behavior',['../group__tcp.html#autotoc_md589',1,'']]],
  ['protocol_20format_55',['Protocol Format',['../group__tcp.html#autotoc_md518',1,'Protocol Format'],['../group__tcp.html#autotoc_md521',1,'Protocol Format'],['../group__tcp.html#autotoc_md545',1,'Protocol Format'],['../group__tcp.html#autotoc_md548',1,'Protocol Format']]],
  ['protocols_20and_20the_20socket_20api_56',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md308',1,'']]],
  ['provide_20poll_20and_20epoll_20as_20alternatives_57',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['publishing_20jsocketpp_20to_20the_20conan_20center_20index_20cci_58',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['publishing_20jsocketpp_20to_20the_20vcpkg_20registry_59',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the vcpkg Registry',['../group__vcpkg__publish__guide.html',1,'']]],
  ['pull_20request_20to_20cci_60',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['pull_20requests_61',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md424',1,'']]],
  ['purpose_62',['Purpose',['../group__address__reuse.html#autotoc_md66',1,'🎯 Purpose'],['../namespacejsocketpp_1_1net.html#autotoc_md447',1,'Purpose'],['../group__tcp.html#autotoc_md573',1,'Purpose']]],
  ['py_63',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['python_20af_5finet_64',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]]
];
