var searchData=
[
  ['larger_20send_20buffer_20for_20inter_20process_20communication_0',['Example: Set a larger send buffer for inter-process communication',['../group__socketopts.html#autotoc_md631',1,'']]],
  ['latency_20sensitive_20clients_1',['Example: Disable Nagle’s algorithm (for latency-sensitive clients)',['../group__socketopts.html#autotoc_md626',1,'']]],
  ['leavegroup_2',['leaveGroup',['../classjsocketpp_1_1MulticastSocket.html#af7317567ceae9b90967ec5a29d003af3',1,'jsocketpp::MulticastSocket']]],
  ['level_20timeouts_3',['OS-Level Timeouts',['../group__async__io.html#autotoc_md119',1,'']]],
  ['libraries_4',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['library_5',['Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['library_6',['library',['../group__socket__library__comparison.html#autotoc_md229',1,'1. jsocketpp (this library)'],['../group__jsocketpp.html',1,'jsocketpp: C++20 cross-platform socket library']]],
  ['library_20authors_7',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md102',1,'']]],
  ['library_20for_20modern_20c_2020_8',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['library_20for_20vcpkg_9',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md349',1,'']]],
  ['license_10',['LICENSE',['../LICENSE.html',1,'']]],
  ['license_11',['License',['../index.html#autotoc_md409',1,'⚖️ License'],['../group__BUILD__AND__USAGE.html#autotoc_md24',1,'License']]],
  ['lifecycle_12',['Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'4. How Sockets Work: The Lifecycle'],['../group__socket__states.html#autotoc_md246',1,'TCP Socket Lifecycle']]],
  ['limitations_13',['Limitations',['../group__address__reuse.html#autotoc_md86',1,'⚠️ Java’s Approach and Its Limitations'],['../index.html#autotoc_md380',1,'⚠️ Limitations'],['../group__tcp.html#autotoc_md511',1,'Limitations'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md645',1,'Limitations']]],
  ['limitations_3a_14',['Limitations:',['../group__async__io.html#autotoc_md144',1,'']]],
  ['linking_20the_20library_15',['Linking the Library',['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'']]],
  ['linux_16',['Unix/Linux',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['linux_20macos_20unix_17',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md289',1,'']]],
  ['linux_20only_18',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md72',1,'']]],
  ['linux_3a_19',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md55',1,'']]],
  ['listen_20',['listen',['../group__tcp.html#ga4780ea0cf2fb98d0081ed91d8dbecfa3',1,'jsocketpp::ServerSocket::listen()'],['../classjsocketpp_1_1UnixSocket.html#a9905fe17ae505295cac11707cef48371',1,'jsocketpp::UnixSocket::listen()']]],
  ['listen_20explicit_21',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['listening_3a_20design_20patterns_20and_20best_20practices_22',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['local_20ipc_23',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['locally_24',['Locally',['../group__vcpkg__publish__guide.html#autotoc_md355',1,'4. Test the Port Locally'],['../group__conan__publish__guide.html#autotoc_md168',1,'4. Test the Recipe Locally']]]
];
