var searchData=
[
  ['rationale_0',['Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md84',1,'4. Advantages and Rationale'],['../group__async__io.html#autotoc_md180',1,'Design Rationale']]],
  ['raw_20socket_20communication_1',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md364',1,'']]],
  ['raw_20sockets_2',['Raw Sockets',['../group__sockets__theory.html#autotoc_md324',1,'2.3. Raw Sockets'],['../group__sockets__theory.html#autotoc_md332',1,'Raw Sockets']]],
  ['read_3',['Read',['../namespacejsocketpp.html#a0d2868e06cd95730d5088336f8c3c174a7a1a5f3e79fdc91edf2f5ead9d66abb4',1,'jsocketpp']]],
  ['read_4',['read',['../group__async__io.html#autotoc_md191',1,'📥 <span class="tt">recv</span> / <span class="tt">read</span>'],['../classjsocketpp_1_1DatagramSocket.html#a58152e567e2d41ee6d612355ac0eb548',1,'jsocketpp::DatagramSocket::read(DatagramPacket &amp;packet, bool resizeBuffer=true) const'],['../classjsocketpp_1_1DatagramSocket.html#a61dfe82025f17e3041c5b5acca2369eb',1,'jsocketpp::DatagramSocket::read()'],['../classjsocketpp_1_1Socket.html#aa7498d51b547b52699055bdb16b9d68b',1,'jsocketpp::Socket::read()'],['../classjsocketpp_1_1UnixSocket.html#a7a0f2f8fdec5d7b48e53ed8560dcafaf',1,'jsocketpp::UnixSocket::read(char *buffer, std::size_t len) const'],['../classjsocketpp_1_1UnixSocket.html#a4d865d28f74d7552e6afc622f3732315',1,'jsocketpp::UnixSocket::read()'],['../classjsocketpp_1_1Socket.html#a634bfa30476b72bfa4cca63a93c558a9',1,'jsocketpp::Socket::read()'],['../classjsocketpp_1_1UnixSocket.html#af4b1f6c83e8b829f1bfe4217872e3c21',1,'jsocketpp::UnixSocket::read()']]],
  ['readiness_5',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md198',1,'']]],
  ['reading_6',['Further Reading',['../group__socket-options.html#autotoc_md282',1,'']]],
  ['readme_2emd_7',['README.md',['../README_8md.html',1,'']]],
  ['real_20server_20and_20client_3a_8',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['recap_9',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md167',1,'']]],
  ['receiving_10',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md427',1,'']]],
  ['recipe_20conanfile_20py_11',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md221',1,'']]],
  ['recipe_20locally_12',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md225',1,'']]],
  ['recommendations_13',['Recommendations',['../group__select__poll__epoll__iocp.html#autotoc_md252',1,'7. <b>Practical Recommendations</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md98',1,'8. Recommendations'],['../group__socket-options.html#autotoc_md280',1,'Design Recommendations']]],
  ['recommended_14',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md57',1,'']]],
  ['recommended_20behavior_15',['Recommended Behavior',['../group__address__reuse.html#autotoc_md152',1,'']]],
  ['recv_20and_20send_16',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['recv_20and_20send_3a_17',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['recv_20read_18',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md191',1,'']]],
  ['recvfrom_19',['recvFrom',['../classjsocketpp_1_1DatagramSocket.html#a67133e9ad368acfe004d7efb956778ea',1,'jsocketpp::DatagramSocket']]],
  ['references_20',['References',['../group__address__reuse.html#autotoc_md161',1,'🔗 References'],['../group__sockets__theory.html#autotoc_md353',1,'9. References'],['../group__conan__publish__guide.html#autotoc_md236',1,'References'],['../group__vcpkg__publish__guide.html#autotoc_md420',1,'References']]],
  ['registry_21',['Registry',['../group__vcpkg__publish__guide.html#autotoc_md414',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry'],['../group__vcpkg__publish__guide.html#autotoc_md402',1,'Publishing <span class="tt">jsocketpp</span> to the vcpkg Registry']]],
  ['relates_20to_20jsocketpp_22',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md312',1,'']]],
  ['reporting_20issues_23',['1. Reporting Issues',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md9',1,'']]],
  ['request_20to_20cci_24',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md230',1,'']]],
  ['requests_25',['2. Submitting Pull Requests',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md11',1,'']]],
  ['require_20the_20port_20in_20the_20constructor_26',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md82',1,'']]],
  ['resize_27',['resize',['../classjsocketpp_1_1DatagramPacket.html#a2c99540d2136dae10a56f781c1b20c5f',1,'jsocketpp::DatagramPacket']]],
  ['resources_28',['More Resources',['../group__socket__states.html#autotoc_md314',1,'']]],
  ['responsibilities_29',['Our Responsibilities',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md3',1,'']]],
  ['reuse_20in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_30',['Reuse in Sockets: SO_REUSEADDR vs SO_EXCLUSIVEADDRUSE',['../group__address__reuse.html',1,'Address Reuse in Sockets: &lt;tt&gt;SO_REUSEADDR&lt;/tt&gt; vs &lt;tt&gt;SO_EXCLUSIVEADDRUSE&lt;/tt&gt;'],['../group__address__reuse.html#autotoc_md101',1,'Address Reuse in Sockets: <span class="tt">SO_REUSEADDR</span> vs <span class="tt">SO_EXCLUSIVEADDRUSE</span>']]],
  ['reuse_20options_31',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md103',1,'']]],
  ['right_32',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md164',1,'']]],
  ['running_20tests_33',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md62',1,'']]]
];
