var searchData=
[
  ['a_20better_20alternative_3a_20what_20jsocketpp_20does_0',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['a_20constructor_20does_20all_20java_20default_20style_1',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['a_20flexibility_20and_20safety_2',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md35',1,'']]],
  ['a_20glance_3',['✨ Features at a Glance',['../index.html#autotoc_md372',1,'']]],
  ['a_20pull_20request_20to_20cci_4',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['a_20simple_20server_20client_20integration_20test_3a_5',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['a_20socket_6',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['a_20socket_20state_7',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['a_20vcpkg_20portfile_8',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md351',1,'']]],
  ['about_20udp_20and_20unix_20sockets_9',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md251',1,'']]],
  ['accept_10',['accept',['../group__async__io.html#autotoc_md130',1,'📞 <span class="tt">accept</span>'],['../group__tcp.html#ga88ad062242d5dfa9dd3c97e4460d04e3',1,'jsocketpp::ServerSocket::accept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt) const'],['../group__tcp.html#gade468e5107bb8b7138432b5d91fb8a87',1,'jsocketpp::ServerSocket::accept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt) const'],['../classjsocketpp_1_1UnixSocket.html#ad608f46c3272a83e33e3399ffb6b53cb',1,'jsocketpp::UnixSocket::accept()']]],
  ['accept_20recv_20and_20send_11',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['acceptance_12',['Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md359',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md175',1,'7. After Acceptance']]],
  ['acceptasync_13',['acceptAsync',['../group__tcp.html#ga65eb5c9d7e7fc3c198595b0015f0b8c5',1,'jsocketpp::ServerSocket::acceptAsync(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt) const'],['../group__tcp.html#gab3b87523e40aac5ac244b0e3db15988d',1,'jsocketpp::ServerSocket::acceptAsync(std::function&lt; void(std::optional&lt; Socket &gt;, std::exception_ptr)&gt; callback, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt) const']]],
  ['acceptblocking_14',['acceptBlocking',['../group__tcp.html#ga69c4a45146fc3d3854f2e5684bf65c55',1,'jsocketpp::ServerSocket']]],
  ['acceptnonblocking_15',['acceptNonBlocking',['../group__tcp.html#gadd605b49147b688c630d6d1b0aa5a6c0',1,'jsocketpp::ServerSocket']]],
  ['acknowledgements_16',['🙏 Acknowledgements',['../index.html#autotoc_md411',1,'']]],
  ['action_3a_20practical_20examples_17',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['actually_20does_18',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['address_19',['address',['../classjsocketpp_1_1DatagramPacket.html#a9f0c6f68dc00926fdea15ce77504e954',1,'jsocketpp::DatagramPacket']]],
  ['address_20families_20',['Address Families',['../group__underlying__socket__api.html#autotoc_md302',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md280',1,'3. Socket Address Families']]],
  ['address_20reuse_20in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_21',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['address_20reuse_20options_22',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['address_5freuse_2emd_23',['address_reuse.md',['../address__reuse_8md.html',1,'']]],
  ['addresses_24',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md152',1,'']]],
  ['addresstostring_25',['addressToString',['../classjsocketpp_1_1Socket.html#af3b50f84b3c8e869b9f8ff64da0bd315',1,'jsocketpp::Socket']]],
  ['addrinfodeleter_26',['AddrinfoDeleter',['../structjsocketpp_1_1internal_1_1AddrinfoDeleter.html',1,'jsocketpp::internal']]],
  ['addrinfoptr_27',['AddrinfoPtr',['../group__internal.html#ga62d9b0682386f85cca0aadbdfbb76646',1,'jsocketpp::internal']]],
  ['adjust_28',['When to Adjust',['../group__core.html#autotoc_md459',1,'']]],
  ['advanced_20scenarios_29',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md44',1,'']]],
  ['advanced_20socket_20api_20features_30',['Advanced Socket API Features',['../group__underlying__socket__api.html#autotoc_md312',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md322',1,'Advanced Socket API Features']]],
  ['advanced_20topics_31',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md292',1,'']]],
  ['advanced_20usage_32',['Advanced Usage',['../classjsocketpp_1_1Socket.html#autotoc_md493',1,'']]],
  ['advantages_20and_20rationale_33',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md34',1,'']]],
  ['advantages_20of_20epoll_34',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md189',1,'']]],
  ['advantages_20of_20poll_35',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md187',1,'']]],
  ['advice_36',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md199',1,'']]],
  ['af_5finet_37',['AF_INET',['../group__underlying__socket__api.html#autotoc_md310',1,'5.1 TCP Server and Client (Python, AF_INET)'],['../group__underlying__socket__api.html#autotoc_md311',1,'5.2 UDP Server and Client (C, AF_INET)']]],
  ['after_20acceptance_38',['After Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md359',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md175',1,'7. After Acceptance']]],
  ['all_20interfaces”_20mean_39',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['all_20interfaces_40',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['all_20interfaces_20vs_20specific_20interfaces_41',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['all_20java_20default_20style_42',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['all_20sockets_43',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md208',1,'']]],
  ['all_20steps_44',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['also_45',['Also',['../index.html#autotoc_md426',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md481',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md494',1,'See Also']]],
  ['alternative_20designs_3a_20pros_20and_20cons_46',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['alternative_3a_20what_20jsocketpp_20does_47',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['alternatives_48',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['and_20applications_49',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md318',1,'']]],
  ['and_20best_20practices_50',['and Best Practices',['../group__async__io.html#autotoc_md146',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['and_20broadcast_51',['and Broadcast',['../group__underlying__socket__api.html#autotoc_md315',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md325',1,'6.3 Multicast and Broadcast']]],
  ['and_20caveats_52',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md58',1,'']]],
  ['and_20cleanup_3a_53',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['and_20client_54',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md465',1,'']]],
  ['and_20client_20c_20af_5finet_55',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['and_20client_20python_20af_5finet_56',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['and_20client_3a_57',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['and_20cons_58',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['and_20epoll_20as_20alternatives_59',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['and_20handling_20socket_20exceptions_60',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md613',1,'']]],
  ['and_20integration_20guide_61',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['and_20its_20limitations_62',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md86',1,'']]],
  ['and_20listening_3a_20design_20patterns_20and_20best_20practices_63',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['and_20performance_20considerations_64',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md278',1,'']]],
  ['and_20platform_20apis_65',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['and_20rationale_66',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md34',1,'']]],
  ['and_20running_20tests_67',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['and_20safety_68',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md35',1,'']]],
  ['and_20send_69',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['and_20send_3a_70',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['and_20testing_71',['🧪 Building and Testing',['../index.html#autotoc_md402',1,'']]],
  ['and_20the_20socket_20api_72',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md308',1,'']]],
  ['and_20timeouts_73',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md122',1,'']]],
  ['and_20types_74',['Core Utilities and Types',['../group__core.html',1,'']]],
  ['and_20unix_20sockets_75',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md251',1,'']]],
  ['and_20usage_20guide_76',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['api_77',['API',['../group__underlying__socket__api.html#autotoc_md299',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md300',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md308',1,'4. Protocols and the Socket API'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md480',1,'Basic API'],['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'c) Clear API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['api_20considerations_78',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'']]],
  ['api_20features_79',['API Features',['../group__underlying__socket__api.html#autotoc_md312',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md322',1,'Advanced Socket API Features']]],
  ['api_20for_20unit_20tests_3a_80',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['api_20in_20action_3a_20practical_20examples_81',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['api_20notes_82',['jsocketpp API Notes',['../group__bind__interfaces.html#autotoc_md157',1,'']]],
  ['apis_83',['APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'5. Native BSD/POSIX/WinSock APIs'],['../group__sockets__theory.html#autotoc_md288',1,'6. Platform-Specific APIs'],['../group__sockets__theory.html',1,'Sockets: Theory, Types, and Platform APIs']]],
  ['applications_84',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md318',1,'']]],
  ['approach_85',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['approach_20and_20its_20limitations_86',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md86',1,'']]],
  ['approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_87',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['are_20socket_20options_88',['What Are Socket Options?',['../group__socket-options.html#autotoc_md203',1,'']]],
  ['as_20alternatives_89',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['asio_90',['Asio',['../index.html#autotoc_md376',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md231',1,'2. Boost.Asio']]],
  ['async_91',['Is jsocketpp async?',['../index.html#autotoc_md414',1,'']]],
  ['async_5fio_2emd_92',['async_io.md',['../async__io_8md.html',1,'']]],
  ['asynchronous_20i_20o_93',['Asynchronous I O',['../group__underlying__socket__api.html#autotoc_md316',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md326',1,'6.4 Asynchronous I/O']]],
  ['asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_94',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['at_20a_20glance_95',['✨ Features at a Glance',['../index.html#autotoc_md372',1,'']]],
  ['authors_96',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md102',1,'']]]
];
