var searchData=
[
  ['a_20better_20alternative_3a_20what_20jsocketpp_20does_0',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md149',1,'']]],
  ['a_20constructor_20does_20all_20java_20default_20style_1',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md90',1,'']]],
  ['a_20flexibility_20and_20safety_2',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md85',1,'']]],
  ['a_20pull_20request_20to_20cci_3',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md230',1,'']]],
  ['a_20simple_20server_20client_20integration_20test_3a_4',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md394',1,'']]],
  ['a_20socket_5',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md319',1,'']]],
  ['a_20socket_20state_6',['What is a Socket State?',['../group__socket__states.html#autotoc_md301',1,'']]],
  ['a_20vcpkg_20portfile_7',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md408',1,'']]],
  ['about_20udp_20and_20unix_20sockets_8',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md308',1,'']]],
  ['accept_9',['accept',['../group__async__io.html#autotoc_md187',1,'📞 <span class="tt">accept</span>'],['../group__tcp.html#ga51152280c07200cdbfa7a7bb81f19dbc',1,'jsocketpp::ServerSocket::accept(std::size_t recvBufferSize=0, std::size_t sendBufferSize=0) const'],['../group__tcp.html#ga745dcc9b06cd26ead23885adb7e6a950',1,'jsocketpp::ServerSocket::accept(int timeoutMillis, std::size_t recvBufferSize=0, std::size_t sendBufferSize=0) const'],['../classjsocketpp_1_1UnixSocket.html#ad608f46c3272a83e33e3399ffb6b53cb',1,'jsocketpp::UnixSocket::accept()']]],
  ['accept_20recv_20and_20send_10',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['acceptance_11',['Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md416',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md232',1,'7. After Acceptance']]],
  ['acceptasync_12',['acceptAsync',['../group__tcp.html#ga7f61b723de35525525e190efe194b978',1,'jsocketpp::ServerSocket::acceptAsync(std::size_t recvBufferSize=0, std::size_t sendBufferSize=0) const'],['../group__tcp.html#ga6790cf113dd3549a4e49df3bfa521f22',1,'jsocketpp::ServerSocket::acceptAsync(std::function&lt; void(std::optional&lt; Socket &gt;, std::exception_ptr)&gt; callback, std::size_t recvBufferSize=0, std::size_t sendBufferSize=0) const']]],
  ['acceptblocking_13',['acceptBlocking',['../group__tcp.html#ga6e38a6851982facf83077836c21aad79',1,'jsocketpp::ServerSocket']]],
  ['acceptnonblocking_14',['acceptNonBlocking',['../group__tcp.html#ga37b094ae1d37200cf79108f3f946cdc1',1,'jsocketpp::ServerSocket']]],
  ['acknowledgements_15',['Acknowledgements',['../index.html#autotoc_md49',1,'']]],
  ['action_3a_20practical_20examples_16',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md366',1,'']]],
  ['actually_20does_17',['actually does',['../group__address__reuse.html#autotoc_md106',1,'🔄 What it actually does'],['../group__address__reuse.html#autotoc_md114',1,'🧨 What it actually does']]],
  ['address_18',['address',['../classjsocketpp_1_1DatagramPacket.html#a9f0c6f68dc00926fdea15ce77504e954',1,'jsocketpp::DatagramPacket']]],
  ['address_20families_19',['Address Families',['../group__underlying__socket__api.html#autotoc_md359',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md337',1,'3. Socket Address Families']]],
  ['address_20reuse_20in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_20',['Address Reuse in Sockets: SO_REUSEADDR vs SO_EXCLUSIVEADDRUSE',['../group__address__reuse.html',1,'Address Reuse in Sockets: &lt;tt&gt;SO_REUSEADDR&lt;/tt&gt; vs &lt;tt&gt;SO_EXCLUSIVEADDRUSE&lt;/tt&gt;'],['../group__address__reuse.html#autotoc_md101',1,'Address Reuse in Sockets: <span class="tt">SO_REUSEADDR</span> vs <span class="tt">SO_EXCLUSIVEADDRUSE</span>']]],
  ['address_20reuse_20options_21',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md103',1,'']]],
  ['address_5freuse_2emd_22',['address_reuse.md',['../address__reuse_8md.html',1,'']]],
  ['addresses_23',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md209',1,'']]],
  ['addresstostring_24',['addressToString',['../classjsocketpp_1_1Socket.html#af3b50f84b3c8e869b9f8ff64da0bd315',1,'jsocketpp::Socket']]],
  ['advanced_20scenarios_25',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md94',1,'']]],
  ['advanced_20socket_20api_20features_26',['Advanced Socket API Features',['../group__underlying__socket__api.html#autotoc_md369',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md379',1,'Advanced Socket API Features']]],
  ['advanced_20topics_27',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md349',1,'']]],
  ['advanced_20usage_28',['Advanced Usage',['../classjsocketpp_1_1Socket.html#autotoc_md454',1,'']]],
  ['advantages_20and_20rationale_29',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md84',1,'']]],
  ['advantages_20of_20epoll_30',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md246',1,'']]],
  ['advantages_20of_20poll_31',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md244',1,'']]],
  ['advice_32',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md256',1,'']]],
  ['af_5finet_33',['AF_INET',['../group__underlying__socket__api.html#autotoc_md367',1,'5.1 TCP Server and Client (Python, AF_INET)'],['../group__underlying__socket__api.html#autotoc_md368',1,'5.2 UDP Server and Client (C, AF_INET)']]],
  ['after_20acceptance_34',['After Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md416',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md232',1,'7. After Acceptance']]],
  ['all_20interfaces”_20mean_35',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md208',1,'']]],
  ['all_20interfaces_36',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md210',1,'']]],
  ['all_20interfaces_20vs_20specific_20interfaces_37',['All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'Understanding &lt;tt&gt;bind()&lt;/tt&gt;: Binding to All Interfaces vs Specific Interfaces'],['../group__bind__interfaces.html#autotoc_md207',1,'Understanding <span class="tt">bind()</span>: Binding to All Interfaces vs Specific Interfaces']]],
  ['all_20java_20default_20style_38',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md90',1,'']]],
  ['all_20sockets_39',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md265',1,'']]],
  ['all_20steps_40',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md79',1,'']]],
  ['also_41',['Also',['../classjsocketpp_1_1ServerSocket.html#autotoc_md434',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md455',1,'See Also']]],
  ['alternative_20designs_3a_20pros_20and_20cons_42',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md89',1,'']]],
  ['alternative_3a_20what_20jsocketpp_20does_43',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md149',1,'']]],
  ['alternatives_44',['alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['and_20applications_45',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md375',1,'']]],
  ['and_20best_20practices_46',['and Best Practices',['../group__async__io.html#autotoc_md203',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md418',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md234',1,'8. Tips and Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['and_20broadcast_47',['and Broadcast',['../group__underlying__socket__api.html#autotoc_md372',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md382',1,'6.3 Multicast and Broadcast']]],
  ['and_20caveats_48',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['and_20cleanup_3a_49',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md391',1,'']]],
  ['and_20client_50',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['and_20client_20c_20af_5finet_51',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md368',1,'']]],
  ['and_20client_20python_20af_5finet_52',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md367',1,'']]],
  ['and_20client_3a_53',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['and_20cons_54',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md89',1,'']]],
  ['and_20epoll_20as_20alternatives_55',['and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['and_20handling_20socket_20exceptions_56',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md456',1,'']]],
  ['and_20integration_20guide_57',['and Integration Guide',['../group__unit__tests.html',1,'Unit Testing and Integration Guide'],['../group__unit__tests.html#autotoc_md386',1,'Unit Testing and Integration Guide']]],
  ['and_20its_20limitations_58',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md143',1,'']]],
  ['and_20listening_3a_20design_20patterns_20and_20best_20practices_59',['and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['and_20performance_20considerations_60',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md335',1,'']]],
  ['and_20platform_20apis_61',['and Platform APIs',['../group__sockets__theory.html',1,'Sockets: Theory, Types, and Platform APIs'],['../group__sockets__theory.html#autotoc_md316',1,'Sockets: Theory, Types, and Platform APIs']]],
  ['and_20rationale_62',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md84',1,'']]],
  ['and_20running_20tests_63',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md62',1,'']]],
  ['and_20safety_64',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md85',1,'']]],
  ['and_20send_65',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['and_20send_3a_66',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['and_20the_20socket_20api_67',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md365',1,'']]],
  ['and_20timeouts_68',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md179',1,'']]],
  ['and_20unix_20sockets_69',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md308',1,'']]],
  ['and_20usage_20guide_70',['and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'jsocketpp: Build, Test, and Usage Guide'],['../group__BUILD__AND__USAGE.html#autotoc_md50',1,'jsocketpp: Build, Test, and Usage Guide']]],
  ['api_71',['API',['../group__underlying__socket__api.html#autotoc_md356',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md357',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md365',1,'4. Protocols and the Socket API'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md433',1,'Basic API'],['../group__ServerSocket__Lifecycle.html#autotoc_md87',1,'c) Clear API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API'],['../group__underlying__socket__api.html#autotoc_md355',1,'Comprehensive Guide to the Socket API'],['../index.html#autotoc_md39',1,'Java-Inspired API']]],
  ['api_20considerations_72',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md250',1,'']]],
  ['api_20features_73',['API Features',['../group__underlying__socket__api.html#autotoc_md369',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md379',1,'Advanced Socket API Features']]],
  ['api_20for_20unit_20tests_3a_74',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md397',1,'']]],
  ['api_20in_20action_3a_20practical_20examples_75',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md366',1,'']]],
  ['api_20notes_76',['jsocketpp API Notes',['../group__bind__interfaces.html#autotoc_md214',1,'']]],
  ['apis_77',['APIs',['../group__socket__library__comparison.html#autotoc_md294',1,'5. Native BSD/POSIX/WinSock APIs'],['../group__sockets__theory.html#autotoc_md345',1,'6. Platform-Specific APIs'],['../group__sockets__theory.html',1,'Sockets: Theory, Types, and Platform APIs'],['../group__sockets__theory.html#autotoc_md316',1,'Sockets: Theory, Types, and Platform APIs']]],
  ['applications_78',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md375',1,'']]],
  ['approach_79',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md77',1,'']]],
  ['approach_20and_20its_20limitations_80',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md143',1,'']]],
  ['approach_20on_20windows_3a_20so_5fexclusiveaddruse_81',['🔐 Correct approach on Windows: &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_82',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md81',1,'']]],
  ['are_20socket_20options_83',['What Are Socket Options?',['../group__socket-options.html#autotoc_md260',1,'']]],
  ['as_20alternatives_84',['as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['asio_85',['2. Boost.Asio',['../group__socket__library__comparison.html#autotoc_md288',1,'']]],
  ['async_5fio_2emd_86',['async_io.md',['../async__io_8md.html',1,'']]],
  ['asynchronous_20i_20o_87',['Asynchronous I O',['../group__underlying__socket__api.html#autotoc_md373',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md383',1,'6.4 Asynchronous I/O']]],
  ['asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_88',['asynchronous I O operations Does it make sense to provide poll and epoll as alternatives',['../group__select__poll__epoll__iocp.html',1,'We use &lt;tt&gt;select&lt;/tt&gt; for asynchronous I/O operations. Does it make sense to provide &lt;tt&gt;poll&lt;/tt&gt; and &lt;tt&gt;epoll&lt;/tt&gt; as alternatives?'],['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'We use <span class="tt">select</span> for asynchronous I/O operations. Does it make sense to provide <span class="tt">poll</span> and <span class="tt">epoll</span> as alternatives?']]],
  ['authors_89',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md159',1,'']]]
];
