var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md141',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md359',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md339',1,'8. &lt;b&gt;Summary Table&lt;/b&gt;'],['../group__sockets__theory.html#autotoc_md436',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md125',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md381',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md343',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md412',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md182',1,'']]],
  ['tcgetattr_4',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md274',1,'']]],
  ['tcp_5',['TCP',['../group__sockets__theory.html#autotoc_md407',1,'2.1. Stream Sockets (TCP)'],['../group__network__data__units.html#autotoc_md317',1,'Segments: The Reliable Counterpart in TCP'],['../group__sockets__theory.html#autotoc_md415',1,'Stream Sockets (TCP)']]],
  ['tcp_20and_20udp_6',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['tcp_20and_20udp_20connections_7',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['tcp_20echo_20server_8',['🧵 TCP Echo Server',['../index.html#autotoc_md532',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_9',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md452',1,'']]],
  ['tcp_20socket_20lifecycle_10',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md388',1,'']]],
  ['tcp_20socket_20states_11',['Main TCP Socket States',['../group__socket__states.html#autotoc_md389',1,'']]],
  ['tcp_20sockets_12',['TCP Sockets',['../group__tcp.html',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md84',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md88',1,'TCP Sockets']]],
  ['tcp_20sockets_20socket_20serversocket_13',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md352',1,'']]],
  ['tcp_20state_20transitions_14',['TCP State Transitions',['../group__socket__states.html#autotoc_md391',1,'']]],
  ['tcsetattr_20tcgetattr_15',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md274',1,'']]],
  ['terminal_20window_20size_20linux_16',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md234',1,'']]],
  ['test_17',['TEST',['../socket__gtest_8cpp.html#af84a2f63791f9b4fd5ee14e6161ce2d9',1,'TEST(SocketTest, TcpConnectInvalid):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a385a2ab183d5626e9f7de45a6ff70e64',1,'TEST(SocketTest, TcpBindInvalidPort):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a88c3e6586ac2476e33803ecc48b48541',1,'TEST(SocketTest, UnixSocketInvalidPath):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aadbb6137575fbeb33208cb9f555b3a3d',1,'TEST(SocketTest, TcpConnectTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aac9350146074ace6dd63823149af8925',1,'TEST(SocketTest, TcpNonBlocking):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ae2a55900b16067f9197259a155c13835',1,'TEST(SocketTest, TcpSetGetOption):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ac6fe24ab1fa2e3fbf0d3d42e8c9247a6',1,'TEST(SocketTest, UdpSendRecvLoopback):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a013ef3192376c90badc588e9c69af993',1,'TEST(SocketTest, UdpTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a80cc9752601e3ded34d6d8e152b1737f',1,'TEST(SocketTest, UnixSocketBindConnect):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a7d49aecf9ef526bad3e69b943660ae73',1,'TEST(SocketTest, UnixSocketTimeoutAndNonBlocking):&#160;socket_gtest.cpp']]],
  ['test_20and_20usage_20guide_18',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['test_20cases_20to_20consider_3a_19',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md485',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_20',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['test_20the_20port_20locally_21',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'']]],
  ['test_20the_20recipe_20locally_22',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md209',1,'']]],
  ['test_20with_20mocking_3a_23',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md484',1,'']]],
  ['test_3a_24',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md479',1,'']]],
  ['test_5ferror_5fhandling_25',['test_error_handling',['../client_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;client.cpp'],['../server_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;server.cpp']]],
  ['test_5fpackage_26',['test_package',['../group__conan__publish__guide.html#autotoc_md212',1,'']]],
  ['test_5ftcp_27',['test_tcp',['../client_8cpp.html#a5c06bbffe96672a267fdf7a58d39b8c9',1,'test_tcp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a1de353166d8a8c39d1ecad7d6616e681',1,'test_tcp(const string &amp;ip, const Port port):&#160;client.cpp'],['../server_8cpp.html#a8348483da59fb305dfc63392f54bef3f',1,'test_tcp(const Port port):&#160;server.cpp']]],
  ['test_5fudp_28',['test_udp',['../client_8cpp.html#a42c921ec1646212ba1214248e51075cc',1,'test_udp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a8b01747ac0288562f1f5b721300bd338',1,'test_udp(const string &amp;ip, Port port):&#160;client.cpp'],['../server_8cpp.html#ad783a901702495179902ed7bf93f8178',1,'test_udp(const Port port):&#160;server.cpp']]],
  ['test_5funix_29',['test_unix',['../client_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;client.cpp'],['../client_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;client.cpp'],['../server_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;server.cpp'],['../server_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;server.cpp']]],
  ['testing_30',['Testing',['../index.html#autotoc_md544',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md579',1,'5. Testing'],['../group__multicast__sockets.html#autotoc_md306',1,'Loopback and Testing']]],
  ['testing_20and_20integration_20guide_31',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['testing_20in_20c_2020_3a_32',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_33',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md476',1,'']]],
  ['tests_34',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_35',['Tests:',['../group__unit__tests.html#autotoc_md472',1,'1. &lt;b&gt;Unit Tests&lt;/b&gt;:'],['../group__unit__tests.html#autotoc_md477',1,'2. &lt;b&gt;Integration Tests&lt;/b&gt;:'],['../group__unit__tests.html#autotoc_md481',1,'3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:'],['../group__unit__tests.html#autotoc_md482',1,'4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:']]],
  ['the_20basics_36',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md149',1,'']]],
  ['the_20conan_20center_20index_20cci_37',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['the_20connect_20function_38',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md83',1,'']]],
  ['the_20connectionless_20approach_39',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md316',1,'']]],
  ['the_20constructor_40',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['the_20default_20buffer_20size_41',['What is the default buffer size?',['../index.html#autotoc_md564',1,'']]],
  ['the_20foundation_42',['The Foundation',['../group__mastering__ipv4.html#autotoc_md37',1,'IPv4 Address Structure: The Foundation'],['../group__mastering__ipv6.html#autotoc_md46',1,'IPv6 Address Structure: The Foundation']]],
  ['the_20foundations_3a_20network_20models_20and_20data_20encapsulation_43',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md314',1,'']]],
  ['the_20full_20ipv4_20picture_44',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['the_20full_20ipv6_20picture_45',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_46',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md414',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_47',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md428',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_48',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['the_20library_49',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_50',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md424',1,'']]],
  ['the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_51',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['the_20makefile_52',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20mtu_53',['🔍 What is the MTU?',['../group__udp.html#autotoc_md677',1,'']]],
  ['the_20port_20in_20the_20constructor_54',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['the_20port_20locally_55',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'']]],
  ['the_20recipe_20locally_56',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md209',1,'']]],
  ['the_20reliable_20counterpart_20in_20tcp_57',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md317',1,'']]],
  ['the_20role_20of_20the_20connect_20function_58',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md83',1,'']]],
  ['the_20same_20port_59',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['the_20shift_20to_20classless_20routing_60',['CIDR: The Shift to Classless Routing',['../group__mastering__ipv4.html#autotoc_md38',1,'']]],
  ['the_20socket’s_20lifetime_61',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['the_20socket_20api_62',['the Socket API',['../group__underlying__socket__api.html#autotoc_md441',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md442',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md450',1,'4. Protocols and the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['the_20vcpkg_20registry_63',['the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md499',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['theory_20types_20and_20platform_20apis_64',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['this_20is_20problematic_20on_20windows_65',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['this_20library_66',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md371',1,'']]],
  ['this_20matters_67',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md635',1,'']]],
  ['this_20relates_20to_20jsocketpp_68',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md397',1,'']]],
  ['thoughts_20and_20best_20practices_69',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md187',1,'']]],
  ['thread_20safety_70',['Thread Safety',['../group__tcp.html#autotoc_md752',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md761',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md770',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md783',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md792',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md808',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md821',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md746',1,'Thread Safety'],['../group__tcp.html#autotoc_md831',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md840',1,'Thread Safety'],['../group__tcp.html#autotoc_md906',1,'Thread Safety']]],
  ['throwlastsockerror_71',['throwLastSockError',['../namespacejsocketpp_1_1internal.html#a8a49e143a6246874f572bde7254e09b6',1,'jsocketpp::internal']]],
  ['throws_72',['Throws',['../group__internal.html#autotoc_md622',1,'Throws'],['../group__udp.html#autotoc_md661',1,'Throws']]],
  ['throwsizemismatch_73',['throwSizeMismatch',['../group__udp.html#ga3f8607eac97767c09210d8836fdd860f',1,'jsocketpp::DatagramSocket']]],
  ['timeout_74',['timeout',['../group__socketopts.html#autotoc_md1087',1,'Example: Set a 3-second receive timeout'],['../group__socketopts.html#autotoc_md1092',1,'Example: Set a 5-second send timeout']]],
  ['timeout_20behavior_75',['Timeout Behavior',['../group__tcp.html#autotoc_md748',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md757',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md766',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md777',1,'⏱ Timeout Behavior']]],
  ['timeout_20semantics_76',['Timeout Semantics',['../group__tcp.html#autotoc_md830',1,'']]],
  ['timeouts_77',['Timeouts',['../group__async__io.html#autotoc_md163',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md159',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md160',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_78',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md161',1,'']]],
  ['tips_20and_20best_20practices_79',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md503',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md218',1,'8. Tips and Best Practices']]],
  ['to_80',['to',['../group__core.html#autotoc_md599',1,'Applies to'],['../group__core.html#autotoc_md603',1,'Applies to']]],
  ['to_20a_20local_20address_81',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['to_20adjust_82',['When to Adjust',['../group__core.html#autotoc_md602',1,'']]],
  ['to_20all_20interfaces”_20mean_83',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['to_20all_20interfaces_84',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md194',1,'']]],
  ['to_20all_20interfaces_20vs_20specific_20interfaces_85',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['to_20cci_86',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md214',1,'']]],
  ['to_20classless_20routing_87',['CIDR: The Shift to Classless Routing',['../group__mastering__ipv4.html#autotoc_md38',1,'']]],
  ['to_20consider_3a_88',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md485',1,'']]],
  ['to_20ioctl_20fcntl_20ioctlsocket_89',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['to_20ioctl_20fcntl_20ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_90',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['to_20its_20features_20structure_20and_20capabilities_91',['to Its Features Structure and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['to_20jsocketpp_92',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md397',1,'How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;']]],
  ['to_20linger_20for_205_20seconds_20on_20close_93',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1025',1,'']]],
  ['to_20mock_20recv_20and_20send_3a_94',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md475',1,'']]],
  ['to_20multicast_20sockets_95',['to Multicast Sockets',['../group__multicast__sockets.html',1,'Comprehensive Guide to Multicast Sockets'],['../group__multicast__sockets.html#autotoc_md283',1,'Introduction to Multicast Sockets']]],
  ['to_20peer_20model_96',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md448',1,'']]],
  ['to_20provide_20poll_20and_20epoll_20as_20alternatives_97',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['to_20reduce_20latency_98',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['to_20the_20conan_20center_20index_20cci_99',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['to_20the_20same_20port_100',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['to_20the_20socket_20api_101',['to the Socket API',['../group__underlying__socket__api.html#autotoc_md441',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['to_20the_20vcpkg_20registry_102',['to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md499',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['to_20use_103',['When to Use',['../group__socketopts.html#autotoc_md1180',1,'']]],
  ['toifindexfromstring_104',['toIfIndexFromString',['../classjsocketpp_1_1MulticastSocket.html#aa06a1e2928fa03913362fce33ff99329',1,'jsocketpp::MulticastSocket']]],
  ['toiovec_105',['toIOVec',['../group__internal.html#ga7701a273337a71485ba1583df464b178',1,'jsocketpp::internal::toIOVec(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#gacdd48d04c87ec69aff97c5d29dbfe1a1',1,'jsocketpp::internal::toIOVec(const std::span&lt; const BufferView &gt; buffers)']]],
  ['tonetwork_106',['toNetwork',['../namespacejsocketpp_1_1net.html#a30e0ea56a20c62070f079482d8cabfa5',1,'jsocketpp::net::toNetwork(const uint16_t val)'],['../namespacejsocketpp_1_1net.html#a933367ad91e111a4e6516e67d6e08c9a',1,'jsocketpp::net::toNetwork(const uint32_t val)']]],
  ['toolchain_20support_107',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md516',1,'']]],
  ['tooling_108',['🛠 Developer Tooling',['../index.html#autotoc_md546',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_109',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['topics_110',['Topics',['../group__sockets__theory.html#autotoc_md434',1,'7. Advanced Topics'],['../group__multicast__sockets.html#autotoc_md303',1,'Advanced Topics']]],
  ['towsabuf_111',['toWSABUF',['../group__internal.html#gae140ce724d1cfc733f3c2dbccf0cf60b',1,'jsocketpp::internal::toWSABUF(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#ga53db0a38699800e21866a0ded1b433ba',1,'jsocketpp::internal::toWSABUF(const std::span&lt; const BufferView &gt; buffers)']]],
  ['trade_20off_112',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_113',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'']]],
  ['traits_114',['Primary Traits',['../buffer__traits_8hpp.html#autotoc_md726',1,'']]],
  ['transfer_115',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['transferred_116',['Transferred',['../group__udp.html#autotoc_md665',1,'Ownership Transferred'],['../group__udp.html#autotoc_md663',1,'What Is Transferred']]],
  ['transitions_117',['TCP State Transitions',['../group__socket__states.html#autotoc_md391',1,'']]],
  ['troubleshooting_118',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['troubleshooting_20common_20issues_119',['Troubleshooting Common Issues',['../group__multicast__sockets.html#autotoc_md310',1,'']]],
  ['true_120',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['true_20matters_121',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md835',1,'']]],
  ['truncated_122',['truncated',['../structjsocketpp_1_1DatagramReadResult.html#a830a7a1e1451dd93f23f44ddb063c4f3',1,'jsocketpp::DatagramReadResult']]],
  ['tryaccept_123',['tryAccept',['../group__tcp.html#ga6eff2e5c775318cfd2813ee72e716571',1,'jsocketpp::ServerSocket::tryAccept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#ga93a186b3fcb925c3a6c30f1c5d5bf8a8',1,'jsocketpp::ServerSocket::tryAccept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const']]],
  ['tryclosenoexcept_124',['tryCloseNoexcept',['../group__internal.html#ga311f6b46f1941a20ab7e389787fc3bea',1,'jsocketpp::internal']]],
  ['trygetremotesockaddr_125',['tryGetRemoteSockaddr',['../group__udp.html#ga219654befe4bb7c3024e9fab59f0ca64',1,'jsocketpp::DatagramSocket']]],
  ['ttl_20and_20scope_20control_126',['TTL and Scope Control',['../group__multicast__sockets.html#autotoc_md305',1,'']]],
  ['type_127',['Type',['../group__socketopts.html#autotoc_md1151',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1160',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md349',1,'Common Options by Socket Type']]],
  ['types_128',['Types',['../group__socketopts.html#autotoc_md1107',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md445',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md412',1,'2.5. Comparison Table: Socket Types'],['../group__core.html',1,'Core Utilities and Types'],['../group__tcp.html#autotoc_md904',1,'Supported Types']]],
  ['types_20and_20platform_20apis_129',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['types_20of_20ip_20addresses_3a_20unicast_20multicast_20broadcast_20and_20anycast_130',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['types_20of_20sockets_20in_20depth_131',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md406',1,'']]],
  ['types_20work_132',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md414',1,'']]],
  ['types_3a_20unicast_20multicast_20anycast_20and_20more_133',['Address Types: Unicast, Multicast, Anycast, and More',['../group__mastering__ipv6.html#autotoc_md49',1,'']]],
  ['typical_20usage_134',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md740',1,'']]],
  ['typical_20usage_20example_135',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md837',1,'']]],
  ['typical_20use_20cases_136',['🧰 Typical Use Cases',['../index.html#autotoc_md510',1,'']]]
];
