var searchData=
[
  ['o_0',['O',['../group__underlying__socket__api.html#autotoc_md316',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md326',1,'6.4 Asynchronous I/O']]],
  ['o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_1',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['of_20a_20simple_20server_20client_20integration_20test_3a_2',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['of_20address_20reuse_20options_3',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['of_20conduct_4',['of Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['of_20contents_5',['of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['of_20epoll_6',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md189',1,'']]],
  ['of_20java’s_20design_20trade_20off_7',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['of_20operation_8',['Modes of Operation',['../group__tcp.html#autotoc_md610',1,'']]],
  ['of_20poll_9',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md187',1,'']]],
  ['of_20select_10',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md185',1,'']]],
  ['of_20sockets_20in_20depth_11',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['of_20the_20socket_20api_12',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['off_13',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['on_20unix_20linux_3a_14',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md55',1,'']]],
  ['on_20windows_15',['on Windows',['../index.html#autotoc_md420',1,'Does it work on Windows?'],['../group__address__reuse.html#autotoc_md88',1,'Why This is Problematic on Windows']]],
  ['on_20windows_3a_16',['On Windows:',['../group__address__reuse.html#autotoc_md62',1,'On Windows:'],['../group__address__reuse.html#autotoc_md63',1,'On Windows:']]],
  ['only_17',['only',['../group__address__reuse.html#autotoc_md64',1,'<span class="tt">SO_EXCLUSIVEADDRUSE</span> (Windows only)'],['../group__address__reuse.html#autotoc_md72',1,'<span class="tt">SO_REUSEPORT</span> (Unix/Linux only)']]],
  ['only_3a_18',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['operate_19',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['operation_20',['Modes of Operation',['../group__tcp.html#autotoc_md610',1,'']]],
  ['operation_20specific_20behavior_3a_20connect_20accept_20recv_20and_20send_21',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_22',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['operator_28_29_23',['operator()',['../structjsocketpp_1_1internal_1_1AddrinfoDeleter.html#a9717c2230739ecb2817a2837b4896e60',1,'jsocketpp::internal::AddrinfoDeleter']]],
  ['operator_3d_24',['operator=',['../classjsocketpp_1_1DatagramPacket.html#abd1c51c1ce6fcd7876053e25fdfdf1f3',1,'jsocketpp::DatagramPacket::operator=(const DatagramPacket &amp;)=default'],['../classjsocketpp_1_1DatagramPacket.html#aaf44c75672332653936e5223e5322749',1,'jsocketpp::DatagramPacket::operator=(DatagramPacket &amp;&amp;) noexcept=default'],['../classjsocketpp_1_1DatagramSocket.html#ab67aad3e2d477982f19d17ab80607417',1,'jsocketpp::DatagramSocket::operator=(const DatagramSocket &amp;)=delete'],['../classjsocketpp_1_1DatagramSocket.html#a2fe1f3577cdbe471088751818a051799',1,'jsocketpp::DatagramSocket::operator=(DatagramSocket &amp;&amp;other) noexcept'],['../group__tcp.html#ga82ef44f032a357bd470b4b756bdba37c',1,'jsocketpp::ServerSocket::operator=(const ServerSocket &amp;rhs)=delete'],['../group__tcp.html#ga9fb02efd71b7800a17f7dc64214a8e4a',1,'jsocketpp::ServerSocket::operator=(ServerSocket &amp;&amp;rhs) noexcept'],['../group__tcp.html#ga4d2721350ef6a3cad7edf7b778d436c4',1,'jsocketpp::Socket::operator=(const Socket &amp;rhs)=delete'],['../group__tcp.html#ga05b1ae2ec76833370c809c53fe550a95',1,'jsocketpp::Socket::operator=(Socket &amp;&amp;rhs) noexcept'],['../classjsocketpp_1_1SocketInitializer.html#a1b5888e66aad8e193d291943f47bafb2',1,'jsocketpp::SocketInitializer::operator=()'],['../classjsocketpp_1_1UnixSocket.html#a1151a5aa56fb60eace1f79b0f2e5e734',1,'jsocketpp::UnixSocket::operator=(const UnixSocket &amp;)=delete'],['../classjsocketpp_1_1UnixSocket.html#a391f1a3eabbaf06b4be401ee08ec7225',1,'jsocketpp::UnixSocket::operator=(UnixSocket &amp;&amp;other) noexcept']]],
  ['options_25',['Options',['../group__address__reuse.html#autotoc_md53',1,'🔍 In-Depth Overview of Address Reuse Options'],['../group__underlying__socket__api.html#autotoc_md314',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md324',1,'6.2 Socket Options'],['../group__socketopts.html',1,'Socket Options'],['../group__socket-options.html#autotoc_md203',1,'What Are Socket Options?']]],
  ['options_20by_20socket_20type_26',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['options_20for_20all_20sockets_27',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md208',1,'']]],
  ['options_20in_20jsocketpp_28',['Socket Options in jsocketpp',['../group__socket-options.html',1,'']]],
  ['or_20stubbing_20socket_20api_20for_20unit_20tests_3a_29',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['os_20level_20timeouts_30',['OS-Level Timeouts',['../group__async__io.html#autotoc_md119',1,'']]],
  ['other_20c_20socket_20libraries_31',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['our_20pledge_32',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md445',1,'']]],
  ['our_20responsibilities_33',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md447',1,'']]],
  ['our_20standards_34',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md446',1,'']]],
  ['overview_35',['Overview',['../index.html#autotoc_md367',1,'📘 Overview'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md477',1,'Overview']]],
  ['overview_20of_20address_20reuse_20options_36',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]]
];
