var searchData=
[
  ['c_2020_0',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['c_2020_20cross_20platform_20socket_20library_1',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['c_2020_3a_2',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['c_20af_5finet_3',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['c_20clear_20api_4',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'']]],
  ['c_20jsocketpp_20hybrid_5',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['c_20socket_20libraries_6',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['can_20i_20use_20jsocketpp_20in_20production_7',['Can I use jsocketpp in production?',['../index.html#autotoc_md418',1,'']]],
  ['care_8',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md609',1,'']]],
  ['case_9',['Case',['../group__address__reuse.html#autotoc_md69',1,'✅ Use Case'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md477',1,'Use Case']]],
  ['cases_10',['Cases',['../group__socketopts.html#autotoc_md712',1,'✅ Use Cases'],['../group__socketopts.html#autotoc_md724',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md742',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md615',1,'🔧 Common Use Cases'],['../group__socketopts.html#autotoc_md633',1,'🔧 Use Cases'],['../group__socketopts.html#autotoc_md644',1,'🔧 Use Cases'],['../group__socketopts.html#autotoc_md624',1,'🧩 Use Cases'],['../index.html#autotoc_md368',1,'🧰 Typical Use Cases'],['../group__socketopts.html#autotoc_md655',1,'Protocol Use Cases'],['../group__tcp.html#autotoc_md595',1,'Use Cases'],['../group__tcp.html#autotoc_md596',1,'Use Cases'],['../group__socketopts.html#autotoc_md719',1,'Use Cases'],['../group__socketopts.html#autotoc_md733',1,'Use Cases']]],
  ['cases_11',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['cases_20and_20applications_12',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md318',1,'']]],
  ['cases_20to_20consider_3a_13',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['cases_3a_14',['Common Use Cases:',['../group__tcp.html#autotoc_md512',1,'']]],
  ['catching_20and_20handling_20socket_20exceptions_15',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md601',1,'']]],
  ['caveats_16',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md58',1,'']]],
  ['cci_17',['CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'6. Submit a Pull Request to CCI'],['../group__conan__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the Conan Center Index (CCI)']]],
  ['cci_20submission_18',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['center_20index_20cci_19',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['center_20index_20cci_20submission_20',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['chaining_21',['Exception Chaining',['../classjsocketpp_1_1SocketException.html#autotoc_md600',1,'']]],
  ['check_20if_20socket_20is_20ipv6_20only_22',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md751',1,'']]],
  ['class_20mapping_23',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md398',1,'']]],
  ['classes_24',['Classes',['../group__exceptions.html',1,'Exception Classes'],['../classjsocketpp_1_1SocketOptions.html#autotoc_md604',1,'Supported Classes']]],
  ['cleanup_25',['Resource Cleanup',['../group__tcp.html#autotoc_md492',1,'']]],
  ['cleanup_3a_26',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['cleanupandthrow_27',['cleanupAndThrow',['../classjsocketpp_1_1DatagramSocket.html#a1973415ece2f77f191b250b9e9690733',1,'jsocketpp::DatagramSocket::cleanupAndThrow()'],['../group__tcp.html#gab5572cb795d9b45ee50a0ddf9cb9c075',1,'jsocketpp::ServerSocket::cleanupAndThrow()'],['../group__tcp.html#gaf80aa30f2806a17b930878841dfab7ad',1,'jsocketpp::Socket::cleanupAndThrow()']]],
  ['cleanupsockets_28',['CleanupSockets',['../namespacejsocketpp.html#a027103bbab1364c1f878d5c49c0af67c',1,'jsocketpp']]],
  ['clear_29',['clear',['../classjsocketpp_1_1DatagramPacket.html#a7853459de9f4e83363ed341bb465930a',1,'jsocketpp::DatagramPacket']]],
  ['clear_20api_30',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'']]],
  ['client_31',['Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md773',1,'Example: Simple Client'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md466',1,'Example: Simple UDP Echo Server and Client']]],
  ['client_20c_20af_5finet_32',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['client_20integration_20test_3a_33',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['client_20python_20af_5finet_34',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['client_20server_20model_35',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md305',1,'']]],
  ['client_20side_36',['4.2. Client Side',['../group__sockets__theory.html#autotoc_md284',1,'']]],
  ['client_20socket_37',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md714',1,'']]],
  ['client_2ecpp_38',['client.cpp',['../client_8cpp.html',1,'']]],
  ['client_3a_39',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['close_40',['close',['../classjsocketpp_1_1DatagramSocket.html#a9d0a9582b3a2a72bf62f182dbc33c352',1,'jsocketpp::DatagramSocket::close()'],['../group__tcp.html#ga0245d40096ca089255c67303eebf17e6',1,'jsocketpp::ServerSocket::close()'],['../group__tcp.html#ga75ee749264ccbcfc4dfbf5442e55dcb8',1,'jsocketpp::Socket::close()'],['../classjsocketpp_1_1UnixSocket.html#a3f87192fe9d9c81a3d78e007bfc40179',1,'jsocketpp::UnixSocket::close()'],['../group__socketopts.html#autotoc_md626',1,'Example: Set <span class="tt">SO_LINGER</span> to linger for 5 seconds on close']]],
  ['closesocket_41',['CloseSocket',['../namespacejsocketpp.html#a12fd46ba498b19d6102220bc100ef931',1,'jsocketpp']]],
  ['cmake_42',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md353',1,'']]],
  ['cmake_20build_43',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['cmake_20for_20platform_20specific_20tests_3a_44',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['cmake_20integration_20in_20your_20project_45',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['cmake_20presets_20recommended_46',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['cmake_20project_20conan_20friendly_47',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['code_20of_20conduct_48',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20style_20guidelines_49',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md433',1,'']]],
  ['code_5fof_5fconduct_2emd_50',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['combining_20with_20so_5freuseport_51',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['commit_20hooks_52',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md435',1,'']]],
  ['commit_20hooks_53',['Pre-commit hooks',['../index.html#autotoc_md405',1,'']]],
  ['common_20options_20by_20socket_20type_54',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['common_20use_20cases_55',['🔧 Common Use Cases',['../group__socketopts.html#autotoc_md615',1,'']]],
  ['common_20use_20cases_56',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['common_20use_20cases_3a_57',['Common Use Cases:',['../group__tcp.html#autotoc_md512',1,'']]],
  ['common_2ecpp_58',['common.cpp',['../common_8cpp.html',1,'']]],
  ['common_2ehpp_59',['common.hpp',['../common_8hpp.html',1,'']]],
  ['communication_60',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md307',1,'']]],
  ['communication_20models_61',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md304',1,'']]],
  ['comparison_62',['📚 Java Comparison',['../group__async__io.html#autotoc_md143',1,'']]],
  ['comparison_20table_3a_20socket_20types_63',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md270',1,'']]],
  ['comparison_3a_20jsocketpp_20vs_20other_20c_20socket_20libraries_64',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['compilation_65',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['components_20of_20the_20socket_20api_66',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['comprehensive_20guide_20to_20the_20socket_20api_67',['Comprehensive Guide to the Socket API',['../group__underlying__socket__api.html',1,'']]],
  ['conan_68',['✅ Conan',['../index.html#autotoc_md385',1,'']]],
  ['conan_20center_20index_20cci_69',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['conan_20center_20index_20cci_20submission_70',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['conan_20friendly_71',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['conan_20recipe_20conanfile_20py_72',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['conan_5fpublish_5fguide_2emd_73',['conan_publish_guide.md',['../conan__publish__guide_8md.html',1,'']]],
  ['conanfile_20py_74',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['conclusion_75',['Conclusion',['../group__address__reuse.html#autotoc_md106',1,'✅ Conclusion'],['../group__underlying__socket__api.html#autotoc_md320',1,'10. Conclusion'],['../group__underlying__socket__api.html#autotoc_md328',1,'8. Conclusion'],['../group__bind__interfaces.html#autotoc_md159',1,'Conclusion'],['../group__socket__library__comparison.html#autotoc_md241',1,'Conclusion']]],
  ['conclusion_20advice_76',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md199',1,'']]],
  ['conclusion_3a_77',['Conclusion:',['../group__unit__tests.html#autotoc_md344',1,'']]],
  ['conduct_78',['Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['configured_20receive_20buffer_20size_79',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md635',1,'']]],
  ['connect_80',['connect',['../group__async__io.html#autotoc_md126',1,'🔌 <span class="tt">connect</span>'],['../classjsocketpp_1_1DatagramSocket.html#a3fa731104100275903b074ba2b65b839',1,'jsocketpp::DatagramSocket::connect()'],['../group__tcp.html#ga93cc325113abb7433288338ca3facde1',1,'jsocketpp::Socket::connect()'],['../classjsocketpp_1_1UnixSocket.html#a6a5359f3b15c37556b8e2cd558760603',1,'jsocketpp::UnixSocket::connect()']]],
  ['connect_20accept_20recv_20and_20send_81',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['connection_20modes_82',['Connection Modes',['../group__tcp.html#autotoc_md515',1,'']]],
  ['cons_83',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['consider_3a_84',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['considerations_85',['Considerations',['../group__sockets__theory.html#autotoc_md278',1,'2.7. Security and Performance Considerations'],['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'6. <b>Cross-Platform API Considerations</b>'],['../group__underlying__socket__api.html#autotoc_md327',1,'7. Practical Considerations'],['../group__underlying__socket__api.html#autotoc_md317',1,'7. Security Considerations'],['../group__underlying__socket__api.html#autotoc_md319',1,'9. Platform-Specific Considerations']]],
  ['construction_20binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_86',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['constructor_87',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['constructor_20bind_20listen_20explicit_88',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['constructor_20defaults_89',['Constructor Defaults',['../group__address__reuse.html#autotoc_md96',1,'']]],
  ['constructor_20does_20all_20java_20default_20style_90',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['constructor_20does_20all_20steps_91',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['contents_92',['Contents',['../namespacejsocketpp_1_1internal.html#autotoc_md475',1,'Contents'],['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['contributing_93',['🤝 Contributing',['../index.html#autotoc_md407',1,'']]],
  ['contributing_20to_20jsocketpp_94',['Contributing to jsocketpp',['../md_CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_95',['CONTRIBUTING.md',['../CONTRIBUTING_8md.html',1,'']]],
  ['control_96',['Developer Control',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['convertipv4mappedipv6toipv4_97',['convertIPv4MappedIPv6ToIPv4',['../group__core.html#ga4da3763b1f8385b27ebbe44cdcfdfc8d',1,'jsocketpp']]],
  ['core_20components_20of_20the_20socket_20api_98',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['core_20utilities_20and_20types_99',['Core Utilities and Types',['../group__core.html',1,'']]],
  ['counterparts_100',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md191',1,'']]],
  ['coverage_20for_20cross_20platform_3a_101',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['create_20a_20vcpkg_20portfile_102',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md351',1,'']]],
  ['cross_20platform_20api_20considerations_103',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'']]],
  ['cross_20platform_20socket_20library_104',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['cross_20platform_20socket_20library_20for_20modern_20c_2020_105',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['cross_20platform_20support_106',['Cross-Platform Support',['../group__socket-options.html#autotoc_md205',1,'']]],
  ['cross_20platform_3a_107',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['custom_20timeouts_20via_20select_108',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md120',1,'']]],
  ['customization_109',['Customization',['../group__core.html#autotoc_md459',1,'']]]
];
