var searchData=
[
  ['i_20o_0',['I O',['../group__underlying__socket__api.html#autotoc_md316',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md326',1,'6.4 Asynchronous I/O']]],
  ['i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_1',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['implementation_20details_2',['Implementation Details',['../group__tcp.html#autotoc_md460',1,'Implementation Details'],['../group__tcp.html#autotoc_md466',1,'Implementation Details'],['../group__tcp.html#autotoc_md469',1,'Implementation Details'],['../group__tcp.html#autotoc_md474',1,'Implementation Details'],['../group__tcp.html#autotoc_md476',1,'Implementation Details'],['../group__tcp.html#autotoc_md479',1,'Implementation Details'],['../group__tcp.html#autotoc_md481',1,'Implementation Details'],['../group__tcp.html#autotoc_md483',1,'Implementation Details'],['../group__tcp.html#autotoc_md485',1,'Implementation Details'],['../group__tcp.html#autotoc_md487',1,'Implementation Details'],['../group__tcp.html#autotoc_md490',1,'Implementation Details'],['../group__tcp.html#autotoc_md493',1,'Implementation Details'],['../group__tcp.html#autotoc_md495',1,'Implementation Details'],['../group__tcp.html#autotoc_md499',1,'Implementation Details'],['../group__tcp.html#autotoc_md501',1,'Implementation Details'],['../group__tcp.html#autotoc_md503',1,'Implementation Details'],['../group__tcp.html#autotoc_md509',1,'Implementation Details'],['../group__tcp.html#autotoc_md510',1,'Implementation Details'],['../group__tcp.html#autotoc_md512',1,'Implementation Details'],['../group__tcp.html#autotoc_md514',1,'Implementation Details'],['../group__tcp.html#autotoc_md517',1,'Implementation Details'],['../group__tcp.html#autotoc_md520',1,'Implementation Details'],['../group__tcp.html#autotoc_md522',1,'Implementation Details'],['../group__tcp.html#autotoc_md524',1,'Implementation Details'],['../group__tcp.html#autotoc_md528',1,'Implementation Details'],['../group__tcp.html#autotoc_md530',1,'Implementation Details'],['../group__tcp.html#autotoc_md534',1,'Implementation Details'],['../group__tcp.html#autotoc_md536',1,'Implementation Details'],['../group__tcp.html#autotoc_md538',1,'Implementation Details'],['../group__tcp.html#autotoc_md540',1,'Implementation Details'],['../group__tcp.html#autotoc_md542',1,'Implementation Details'],['../group__tcp.html#autotoc_md545',1,'Implementation Details'],['../group__tcp.html#autotoc_md547',1,'Implementation Details'],['../group__tcp.html#autotoc_md549',1,'Implementation Details'],['../group__tcp.html#autotoc_md552',1,'Implementation Details'],['../classjsocketpp_1_1Socket.html#autotoc_md561',1,'Implementation Details'],['../group__tcp.html#autotoc_md568',1,'Implementation Details']]],
  ['implementation_20notes_3',['Implementation Notes',['../group__tcp.html#autotoc_md558',1,'']]],
  ['implications_4',['Practical Implications',['../group__socket__states.html#autotoc_md253',1,'']]],
  ['implications_5',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md59',1,'']]],
  ['in_20action_3a_20practical_20examples_6',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['in_20c_2020_3a_7',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['in_20constructor_20bind_20listen_20explicit_8',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['in_20depth_9',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_10',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['in_20jsocketpp_11',['in jsocketpp',['../group__async__io.html',1,'Blocking vs Non-Blocking Sockets in jsocketpp'],['../group__socket-options.html',1,'Socket Options in jsocketpp']]],
  ['in_20jsocketpp_20_3a_12',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_13',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['in_20the_20constructor_14',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['in_20your_20project_15',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_16',['Includes:',['../group__core.html#autotoc_md417',1,'']]],
  ['incompatibility_17',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md68',1,'']]],
  ['index_20cci_18',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['index_20cci_20submission_19',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['index_2emd_20',['index.md',['../index_8md.html',1,'']]],
  ['inet_5fntop_5faux_21',['inet_ntop_aux',['../namespacejsocketpp.html#a403588c277f89591897408faed72a910',1,'jsocketpp']]],
  ['initialization_20and_20cleanup_3a_22',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['initialization_20flow_23',['Initialization Flow',['../group__tcp.html#autotoc_md464',1,'']]],
  ['initialization_3a_20posix_20approach_24',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['initsockets_25',['InitSockets',['../namespacejsocketpp.html#aef7428a3f4d80452442ecf3edfdbc89a',1,'jsocketpp']]],
  ['inspired_20api_26',['Java-Inspired API',['../index.html#autotoc_md380',1,'']]],
  ['installation_27',['Installation',['../index.html#autotoc_md371',1,'']]],
  ['integration_20guide_28',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['integration_20in_20your_20project_29',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_30',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['integration_20test_3a_31',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['integration_20tests_3a_32',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md335',1,'']]],
  ['interfaces”_20mean_33',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['interfaces_34',['Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'Example: Binding to All Interfaces'],['../group__bind__interfaces.html',1,'Understanding &lt;tt&gt;bind()&lt;/tt&gt;: Binding to All Interfaces vs Specific Interfaces']]],
  ['interfaces_20vs_20specific_20interfaces_35',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['internal_20buffer_36',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md453',1,'']]],
  ['internal_20helpers_37',['Internal Helpers',['../group__internal.html',1,'']]],
  ['internally_38',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['introduction_39',['Introduction',['../group__sockets__theory.html#autotoc_md260',1,'']]],
  ['introduction_20to_20the_20socket_20api_40',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'']]],
  ['invalid_5fsocket_41',['INVALID_SOCKET',['../namespacejsocketpp.html#a3ddf4938a63ed33a5e2f7d2625cb4405',1,'jsocketpp']]],
  ['ioctlsocket_42',['ioctlsocket',['../namespacejsocketpp.html#a771a44f3967222b2e3221ed3120220af',1,'jsocketpp']]],
  ['ipc_43',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['is_20a_20socket_44',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['is_20a_20socket_20state_45',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['is_20blocking_46',['What is Blocking?',['../group__async__io.html#autotoc_md115',1,'']]],
  ['is_20multicast_47',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md437',1,'']]],
  ['is_20non_20blocking_48',['What is Non-Blocking?',['../group__async__io.html#autotoc_md116',1,'']]],
  ['is_20problematic_20on_20windows_49',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['is_20udp_50',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md427',1,'']]],
  ['is_20used_51',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['isbound_52',['isBound',['../group__tcp.html#ga0b3a5cb732c669b678e03549e5af2427',1,'jsocketpp::ServerSocket']]],
  ['isclosed_53',['isClosed',['../group__tcp.html#gaeb5adb24bd7f50eaf8b52aa4441ffe71',1,'jsocketpp::ServerSocket']]],
  ['isconnected_54',['isConnected',['../classjsocketpp_1_1DatagramSocket.html#a9962c2782fe6549bf5781f0301f70906',1,'jsocketpp::DatagramSocket::isConnected()'],['../classjsocketpp_1_1Socket.html#a969dad8dab10b5862aea7200af238d82',1,'jsocketpp::Socket::isConnected()']]],
  ['isipv4mappedipv6_55',['isIPv4MappedIPv6',['../group__core.html#gab0ac1b9850480abafeb047a4f96792a0',1,'jsocketpp']]],
  ['islistening_56',['isListening',['../group__tcp.html#ga1717f9859e5aeeba77c3d463ec53e735',1,'jsocketpp::ServerSocket']]],
  ['ispathinuse_57',['isPathInUse',['../classjsocketpp_1_1UnixSocket.html#a0b8200b52a5ed8c66c84ee52ba9f98e6',1,'jsocketpp::UnixSocket']]],
  ['issues_58',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md393',1,'']]],
  ['isvalid_59',['isValid',['../classjsocketpp_1_1DatagramSocket.html#ad22196f6878ce6d48bd8a133424d777a',1,'jsocketpp::DatagramSocket::isValid()'],['../group__tcp.html#ga4e3ff54722a55e7500fdd76f26c53dac',1,'jsocketpp::ServerSocket::isValid()'],['../group__tcp.html#gae2b10ef466023b380a34b062359c0f65',1,'jsocketpp::Socket::isValid()'],['../classjsocketpp_1_1UnixSocket.html#acb7ad274be98890ca17dfa5deb86024b',1,'jsocketpp::UnixSocket::isValid()']]],
  ['it_20actually_20does_60',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_61',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['it_20works_20internally_62',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['its_20limitations_63',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md86',1,'']]]
];
