var searchData=
[
  ['a_203_20second_20receive_20timeout_0',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1087',1,'']]],
  ['a_205_20second_20send_20timeout_1',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1092',1,'']]],
  ['a_20better_20alternative_3a_20what_20jsocketpp_20does_2',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['a_20client_20socket_3',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1113',1,'']]],
  ['a_20complete_20guide_20to_20its_20features_20structure_20and_20capabilities_4',['A Complete Guide to Its Features Structure and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['a_20constructor_20does_20all_20java_20default_20style_5',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md69',1,'']]],
  ['a_20flexibility_20and_20safety_6',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md64',1,'']]],
  ['a_20glance_7',['✨ Features at a Glance',['../index.html#autotoc_md514',1,'']]],
  ['a_20local_20address_8',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['a_20multicast_20socket_9',['Creating a Multicast Socket',['../group__multicast__sockets.html#autotoc_md292',1,'']]],
  ['a_20packet_10',['What is a Packet?',['../group__network__data__units.html#autotoc_md315',1,'']]],
  ['a_20pull_20request_20to_20cci_11',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md214',1,'']]],
  ['a_20safe_20cap_12',['Why a &quot;safe&quot; cap?',['../group__core.html#autotoc_md608',1,'']]],
  ['a_20simple_20server_20client_20integration_20test_3a_13',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md479',1,'']]],
  ['a_20socket_14',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md404',1,'']]],
  ['a_20socket_20state_15',['What is a Socket State?',['../group__socket__states.html#autotoc_md386',1,'']]],
  ['a_20vcpkg_20portfile_16',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md493',1,'']]],
  ['about_20udp_20and_20unix_20sockets_17',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md393',1,'']]],
  ['accept_18',['accept',['../group__async__io.html#autotoc_md171',1,'📞 &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;'],['../group__tcp.html#gac645e511797a5c5cffd1ee490ece0e96',1,'jsocketpp::ServerSocket::accept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#ga5a797cf5d657594189d4fc14fcb87788',1,'jsocketpp::ServerSocket::accept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../classjsocketpp_1_1UnixSocket.html#ad608f46c3272a83e33e3399ffb6b53cb',1,'jsocketpp::UnixSocket::accept()']]],
  ['accept_20recv_20and_20send_19',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md166',1,'']]],
  ['acceptance_20',['Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md501',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md216',1,'7. After Acceptance']]],
  ['acceptasync_21',['acceptAsync',['../group__tcp.html#gad31e3456825d69842685b8826a0ad346',1,'jsocketpp::ServerSocket::acceptAsync(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#gafc1d1883c490172751065d491001e049',1,'jsocketpp::ServerSocket::acceptAsync(std::function&lt; void(std::optional&lt; Socket &gt;, std::exception_ptr)&gt; callback, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const']]],
  ['acceptblocking_22',['acceptBlocking',['../group__tcp.html#ga4cc6cc771e29a9d1964cb8b351262318',1,'jsocketpp::ServerSocket']]],
  ['accepted_20socket_23',['Accepted Socket',['../group__tcp.html#autotoc_md750',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md759',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md768',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md779',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md812',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md825',1,'⚙️ Configuration of Accepted Socket']]],
  ['acceptnonblocking_24',['acceptNonBlocking',['../group__tcp.html#autotoc_md790',1,'🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;'],['../group__tcp.html#gaa825d267c5cba8febdd2824282869ac1',1,'jsocketpp::ServerSocket::acceptNonBlocking()']]],
  ['acknowledgements_25',['🙏 Acknowledgements',['../index.html#autotoc_md553',1,'']]],
  ['action_3a_20practical_20examples_26',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md451',1,'']]],
  ['actually_20does_27',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['address_28',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['address_29',['address',['../classjsocketpp_1_1DatagramPacket.html#a9f0c6f68dc00926fdea15ce77504e954',1,'jsocketpp::DatagramPacket']]],
  ['address_20allocation_30',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['address_20and_20name_20resolution_31',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['address_20binding_20and_20connection_32',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['address_20families_33',['Address Families',['../group__underlying__socket__api.html#autotoc_md444',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md422',1,'3. Socket Address Families']]],
  ['address_20reuse_20in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_34',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['address_20reuse_20options_35',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['address_20structure_3a_20the_20foundation_36',['Address Structure: The Foundation',['../group__mastering__ipv4.html#autotoc_md37',1,'IPv4 Address Structure: The Foundation'],['../group__mastering__ipv6.html#autotoc_md46',1,'IPv6 Address Structure: The Foundation']]],
  ['address_20types_3a_20unicast_20multicast_20anycast_20and_20more_37',['Address Types: Unicast, Multicast, Anycast, and More',['../group__mastering__ipv6.html#autotoc_md49',1,'']]],
  ['address_5freuse_2emd_38',['address_reuse.md',['../address__reuse_8md.html',1,'']]],
  ['addresses_39',['Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'Private vs. Public IP Addresses'],['../group__bind__interfaces.html#autotoc_md193',1,'Wildcard Addresses']]],
  ['addresses_20and_20224_200_200_200_204_40',['Deep Dive: Multicast Addresses and 224.0.0.0/4',['../group__mastering__ipv4.html#autotoc_md41',1,'']]],
  ['addresses_3a_20ff00_3a_3a_208_20in_20depth_41',['Multicast Addresses: &lt;span class=&quot;tt&quot;&gt;ff00::/8&lt;/span&gt; in Depth',['../group__mastering__ipv6.html#autotoc_md50',1,'']]],
  ['addresses_3a_20private_20networking_42',['Unique Local Addresses: Private Networking',['../group__mastering__ipv6.html#autotoc_md52',1,'']]],
  ['addresses_3a_20unicast_20multicast_20broadcast_20and_20anycast_43',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['addressing_44',['Addressing',['../group__mastering__ipv4.html#autotoc_md42',1,'Key IPv4 Features: Beyond Addressing'],['../group__mastering__ipv6.html#autotoc_md51',1,'Key IPv6 Features: Beyond Addressing'],['../group__multicast__sockets.html#autotoc_md285',1,'Multicast Addressing']]],
  ['addresstostring_45',['addressToString',['../group__utils.html#ga8501a7d31710bd7b0ef862f97ee318da',1,'jsocketpp']]],
  ['addrinfodeleter_46',['AddrinfoDeleter',['../structjsocketpp_1_1internal_1_1AddrinfoDeleter.html',1,'jsocketpp::internal']]],
  ['addrinfoptr_47',['AddrinfoPtr',['../group__internal.html#ga62d9b0682386f85cca0aadbdfbb76646',1,'jsocketpp::internal']]],
  ['adjust_48',['When to Adjust',['../group__core.html#autotoc_md602',1,'']]],
  ['advanced_20scenarios_49',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md73',1,'']]],
  ['advanced_20socket_20api_20features_50',['Advanced Socket API Features',['../group__underlying__socket__api.html#autotoc_md454',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md464',1,'Advanced Socket API Features']]],
  ['advanced_20topics_51',['Advanced Topics',['../group__sockets__theory.html#autotoc_md434',1,'7. Advanced Topics'],['../group__multicast__sockets.html#autotoc_md303',1,'Advanced Topics']]],
  ['advanced_20usage_52',['Advanced Usage',['../classjsocketpp_1_1Socket.html#autotoc_md842',1,'']]],
  ['advantages_20and_20disadvantages_53',['Advantages and Disadvantages',['../group__network__data__units.html#autotoc_md321',1,'']]],
  ['advantages_20and_20rationale_54',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md63',1,'']]],
  ['advantages_20of_20epoll_55',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md331',1,'']]],
  ['advantages_20of_20poll_56',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md329',1,'']]],
  ['advice_57',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md341',1,'']]],
  ['af_5finet_58',['AF_INET',['../group__underlying__socket__api.html#autotoc_md452',1,'5.1 TCP Server and Client (Python, AF_INET)'],['../group__underlying__socket__api.html#autotoc_md453',1,'5.2 UDP Server and Client (C, AF_INET)']]],
  ['after_20acceptance_59',['After Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md501',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md216',1,'7. After Acceptance']]],
  ['algorithm_20to_20reduce_20latency_60',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['all_20interfaces”_20mean_61',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['all_20interfaces_62',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md194',1,'']]],
  ['all_20interfaces_20vs_20specific_20interfaces_63',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['all_20java_20default_20style_64',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md69',1,'']]],
  ['all_20sockets_65',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md350',1,'']]],
  ['all_20steps_66',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md58',1,'']]],
  ['allocation_67',['Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'CIDR in IPv6: Flexible Address Allocation'],['../group__mastering__ipv4.html#autotoc_md39',1,'IANA: Guardians of IPv4 Allocation']]],
  ['allowgrow_68',['allowGrow',['../structjsocketpp_1_1DatagramReadOptions.html#a4253951c03481252f5c1e8928dcb1e9c',1,'jsocketpp::DatagramReadOptions']]],
  ['allowshrink_69',['allowShrink',['../structjsocketpp_1_1DatagramReadOptions.html#a133704136dd9f7b68ca2b954e705c8b2',1,'jsocketpp::DatagramReadOptions']]],
  ['also_70',['Also',['../index.html#autotoc_md568',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md743',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md843',1,'See Also']]],
  ['alternative_20designs_3a_20pros_20and_20cons_71',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md68',1,'']]],
  ['alternative_3a_20what_20jsocketpp_20does_72',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['alternatives_73',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['and_20224_200_200_200_204_74',['Deep Dive: Multicast Addresses and 224.0.0.0/4',['../group__mastering__ipv4.html#autotoc_md41',1,'']]],
  ['and_20anycast_75',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['and_20applications_76',['and Applications',['../group__underlying__socket__api.html#autotoc_md460',1,'8. Use Cases and Applications'],['../group__network__data__units.html#autotoc_md320',1,'Use Cases and Applications']]],
  ['and_20asynchronous_20i_20o_77',['6. Non-Blocking and Asynchronous I/O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'']]],
  ['and_20best_20practices_78',['and Best Practices',['../group__async__io.html#autotoc_md187',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md503',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md218',1,'8. Tips and Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['and_20beyond_79',['Understanding Network Data Units: Packets, Datagrams, Segments, and Beyond',['../group__network__data__units.html',1,'']]],
  ['and_20broadcast_80',['and Broadcast',['../group__underlying__socket__api.html#autotoc_md457',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md467',1,'6.3 Multicast and Broadcast']]],
  ['and_20capabilities_81',['and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['and_20caveats_82',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md99',1,'']]],
  ['and_20cleanup_3a_83',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md476',1,'']]],
  ['and_20client_84',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md654',1,'']]],
  ['and_20client_20c_20af_5finet_85',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md453',1,'']]],
  ['and_20client_20python_20af_5finet_86',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md452',1,'']]],
  ['and_20client_3a_87',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md478',1,'']]],
  ['and_20configuration_88',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['and_20connection_89',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['and_20cons_90',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md68',1,'']]],
  ['and_20data_20encapsulation_91',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md314',1,'']]],
  ['and_20disadvantages_92',['Advantages and Disadvantages',['../group__network__data__units.html#autotoc_md321',1,'']]],
  ['and_20epoll_20as_20alternatives_93',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['and_20handling_20socket_20exceptions_94',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md1000',1,'']]],
  ['and_20integration_20guide_95',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['and_20its_20limitations_96',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md127',1,'']]],
  ['and_20listening_3a_20design_20patterns_20and_20best_20practices_97',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['and_20management_98',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['and_20more_99',['Address Types: Unicast, Multicast, Anycast, and More',['../group__mastering__ipv6.html#autotoc_md49',1,'']]],
  ['and_20name_20resolution_100',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['and_20performance_20considerations_101',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md420',1,'']]],
  ['and_20platform_20apis_102',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['and_20rationale_103',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md63',1,'']]],
  ['and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_104',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['and_20running_20tests_105',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['and_20safety_106',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md64',1,'']]],
  ['and_20scaling_107',['Performance and Scaling',['../group__multicast__sockets.html#autotoc_md308',1,'']]],
  ['and_20scope_20control_108',['TTL and Scope Control',['../group__multicast__sockets.html#autotoc_md305',1,'']]],
  ['and_20segments_109',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md318',1,'']]],
  ['and_20send_110',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md166',1,'']]],
  ['and_20send_3a_111',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md475',1,'']]],
  ['and_20testing_112',['and Testing',['../index.html#autotoc_md544',1,'🧪 Building and Testing'],['../group__multicast__sockets.html#autotoc_md306',1,'Loopback and Testing']]],
  ['and_20the_20socket_20api_113',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md450',1,'']]],
  ['and_20timeouts_114',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md163',1,'']]],
  ['and_20types_115',['Core Utilities and Types',['../group__core.html',1,'']]],
  ['and_20udp_116',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['and_20udp_20connections_117',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['and_20unix_20sockets_118',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md393',1,'']]],
  ['and_20usage_20guide_119',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['and_20use_20cases_120',['Applications and Use Cases',['../group__multicast__sockets.html#autotoc_md311',1,'']]],
  ['and_20windows_20support_121',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['anycast_122',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['anycast_20and_20more_123',['Address Types: Unicast, Multicast, Anycast, and More',['../group__mastering__ipv6.html#autotoc_md49',1,'']]],
  ['api_124',['API',['../group__underlying__socket__api.html#autotoc_md441',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md442',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md450',1,'4. Protocols and the Socket API'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md742',1,'Basic API'],['../group__ServerSocket__Lifecycle.html#autotoc_md66',1,'c) Clear API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['api_20considerations_125',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md335',1,'']]],
  ['api_20features_126',['API Features',['../group__underlying__socket__api.html#autotoc_md454',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md464',1,'Advanced Socket API Features']]],
  ['api_20for_20unit_20tests_3a_127',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md482',1,'']]],
  ['api_20in_20action_3a_20practical_20examples_128',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md451',1,'']]],
  ['api_20notes_129',['jsocketpp API Notes',['../group__bind__interfaces.html#autotoc_md198',1,'']]],
  ['api_20unix_20linux_20macos_130',['POSIX/BSD API (Unix/Linux/MacOS)',['../group__multicast__sockets.html#autotoc_md291',1,'']]],
  ['api_20windows_131',['Winsock API (Windows)',['../group__multicast__sockets.html#autotoc_md298',1,'']]],
  ['apis_132',['APIs',['../group__socket__library__comparison.html#autotoc_md379',1,'5. Native BSD/POSIX/WinSock APIs'],['../group__sockets__theory.html#autotoc_md430',1,'6. Platform-Specific APIs'],['../group__sockets__theory.html',1,'Sockets: Theory, Types, and Platform APIs']]],
  ['applicability_133',['Applicability',['../group__socketopts.html#autotoc_md1137',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1167',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1174',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1071',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1074',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1077',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1081',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1130',1,'🔍 Applicability'],['../group__socketopts.html#autotoc_md1059',1,'Applicability'],['../group__socketopts.html#autotoc_md1062',1,'Applicability'],['../group__socketopts.html#autotoc_md1065',1,'Applicability'],['../group__socketopts.html#autotoc_md1068',1,'Applicability'],['../group__socketopts.html#autotoc_md1146',1,'Applicability'],['../group__socketopts.html#autotoc_md1057',1,'Protocol Applicability']]],
  ['applicability_20by_20socket_20type_134',['Applicability by Socket Type',['../group__socketopts.html#autotoc_md1151',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1160',1,'🌍 Applicability by Socket Type']]],
  ['applicable_20socket_20types_135',['📦 Applicable Socket Types',['../group__socketopts.html#autotoc_md1107',1,'']]],
  ['applications_136',['Applications',['../group__underlying__socket__api.html#autotoc_md460',1,'8. Use Cases and Applications'],['../group__network__data__units.html#autotoc_md320',1,'Use Cases and Applications']]],
  ['applications_20and_20use_20cases_137',['Applications and Use Cases',['../group__multicast__sockets.html#autotoc_md311',1,'']]],
  ['applies_20to_138',['Applies to',['../group__core.html#autotoc_md599',1,'Applies to'],['../group__core.html#autotoc_md603',1,'Applies to']]],
  ['approach_139',['Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'1. Traditional Socket Initialization: POSIX Approach'],['../group__network__data__units.html#autotoc_md316',1,'Datagrams: The Connectionless Approach']]],
  ['approach_20and_20its_20limitations_140',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md127',1,'']]],
  ['approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_141',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['are_20socket_20options_142',['What Are Socket Options?',['../group__socket-options.html#autotoc_md345',1,'']]],
  ['as_20alternatives_143',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['asbytes_144',['asBytes',['../group__udp.html#ga20eb26c65ff8d9c880494e028509e0a8',1,'jsocketpp::DatagramSocket']]],
  ['asio_145',['Asio',['../index.html#autotoc_md518',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md373',1,'2. Boost.Asio']]],
  ['assignment_146',['Example: Move assignment',['../group__socketopts.html#autotoc_md1181',1,'']]],
  ['async_147',['Is jsocketpp async?',['../index.html#autotoc_md556',1,'']]],
  ['async_5fio_2emd_148',['async_io.md',['../async__io_8md.html',1,'']]],
  ['asynchronous_20i_20o_149',['Asynchronous I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md458',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md468',1,'6.4 Asynchronous I/O']]],
  ['asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_150',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['at_20a_20glance_151',['✨ Features at a Glance',['../index.html#autotoc_md514',1,'']]],
  ['authors_152',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md143',1,'']]],
  ['autobind_20true_153',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['autoresizedynamic_154',['autoResizeDynamic',['../structjsocketpp_1_1ReadExactOptions.html#ade6b57f1416832fc093804eb907ce3cf',1,'jsocketpp::ReadExactOptions']]]
];
