var searchData=
[
  ['families_0',['Families',['../group__underlying__socket__api.html#autotoc_md395',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md373',1,'3. Socket Address Families']]],
  ['faq_1',['❓ FAQ',['../index.html#autotoc_md506',1,'']]],
  ['fcntl_20ioctlsocket_2',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['fcntl_20ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_3',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['fcntl_20unix_20linux_4',['2. fcntl (Unix/Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md221',1,'']]],
  ['features_5',['Features',['../group__underlying__socket__api.html#autotoc_md405',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md415',1,'Advanced Socket API Features'],['../classjsocketpp_1_1MulticastSocket.html#autotoc_md789',1,'Features'],['../structjsocketpp_1_1ReadExactOptions.html#autotoc_md602',1,'Key Features'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md604',1,'Key Features'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md793',1,'Key Features'],['../classjsocketpp_1_1Socket.html#autotoc_md888',1,'Key Features'],['../group__tcp.html#autotoc_md896',1,'Key Features'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1236',1,'Main Features']]],
  ['features_20at_20a_20glance_6',['✨ Features at a Glance',['../index.html#autotoc_md465',1,'']]],
  ['features_3a_7',['Key Features:',['../structjsocketpp_1_1DatagramReadOptions.html#autotoc_md600',1,'']]],
  ['fields_8',['Fields',['../structjsocketpp_1_1BufferView.html#autotoc_md544',1,'']]],
  ['final_20thoughts_20and_20best_20practices_9',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md169',1,'']]],
  ['fixed_20size_20container_10',['Example — fixed-size container',['../group__udp.html#autotoc_md708',1,'']]],
  ['fixed_20size_20container_20std_3a_3aarray_11',['Example — fixed-size container (&lt;span class=&quot;tt&quot;&gt;std::array&amp;lt;char, 512&amp;gt;&lt;/span&gt;)',['../group__udp.html#autotoc_md706',1,'']]],
  ['flexibility_20and_20safety_12',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'']]],
  ['footprint_13',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md471',1,'']]],
  ['for_205_20seconds_20on_20close_14',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1077',1,'']]],
  ['for_20all_20sockets_15',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md301',1,'']]],
  ['for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_16',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['for_20conan_20center_20index_20cci_20submission_17',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['for_20cross_20platform_3a_18',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md431',1,'']]],
  ['for_20jsocketpp_19',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['for_20library_20authors_20',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md125',1,'']]],
  ['for_20modern_20c_2020_21',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['for_20multicast_3a_22',['For Multicast:',['../group__socket-options.html#autotoc_md306',1,'']]],
  ['for_20platform_20specific_20tests_3a_23',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md432',1,'']]],
  ['for_20readiness_24',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['for_20the_20socket’s_20lifetime_25',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['for_20unit_20testing_20in_20c_2020_3a_26',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['for_20unit_20tests_3a_27',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md433',1,'']]],
  ['for_20vcpkg_28',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md442',1,'']]],
  ['format_29',['Format',['../group__tcp.html#autotoc_md928',1,'Format'],['../group__tcp.html#autotoc_md944',1,'Format'],['../group__tcp.html#autotoc_md974',1,'Protocol Format'],['../group__tcp.html#autotoc_md977',1,'Protocol Format'],['../group__tcp.html#autotoc_md1001',1,'Protocol Format'],['../group__tcp.html#autotoc_md1004',1,'Protocol Format']]],
  ['foundations_3a_20network_20models_20and_20data_20encapsulation_30',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md265',1,'']]],
  ['friendly_31',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['fromnetwork_32',['fromNetwork',['../namespacejsocketpp_1_1net.html#adbc3d8ebcf4347173f61e55e236c8b37',1,'jsocketpp::net::fromNetwork(const uint16_t val)'],['../namespacejsocketpp_1_1net.html#acca9e860a0a33d2508bfa9986049db8c',1,'jsocketpp::net::fromNetwork(const uint32_t val)']]],
  ['fully_20step_20by_20step_20posix_20style_33',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['function_34',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['functions_35',['Functions',['../group__underlying__socket__api.html#autotoc_md394',1,'2.1 Key Functions'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md254',1,'5. Related Functions'],['../group__list__bsd__socket__functions.html',1,'Comprehensive List of Socket Programming Functions'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md206',1,'Overview of Functions'],['../group__utils.html',1,'Utility Functions']]],
  ['functions_3a_20commands_20use_20cases_20and_20windows_20support_36',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['further_20reading_37',['Further Reading',['../group__socket-options.html#autotoc_md318',1,'']]]
];
