var searchData=
[
  ['packet_0',['What is a Packet?',['../group__network__data__units.html#autotoc_md315',1,'']]],
  ['packets_20datagrams_20and_20segments_1',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md318',1,'']]],
  ['packets_20datagrams_20segments_20and_20beyond_2',['Understanding Network Data Units: Packets, Datagrams, Segments, and Beyond',['../group__network__data__units.html',1,'']]],
  ['padifsmaller_3',['padIfSmaller',['../structjsocketpp_1_1ReadExactOptions.html#a1b3dca16ac543ff80a42b9468fd11759',1,'jsocketpp::ReadExactOptions']]],
  ['parameters_4',['Parameters',['../group__tcp.html#autotoc_md856',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md659',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md850',1,'Configuration Parameters'],['../group__internal.html#autotoc_md618',1,'Parameters']]],
  ['parameters_20used_20only_20if_20autobind_20true_5',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['patterns_20and_20best_20practices_6',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['peek_7',['peek',['../group__udp.html#gadfec1ac007add5eddeabee9c19a621cf',1,'jsocketpp::DatagramSocket::peek()'],['../group__tcp.html#ga5c413ef976df1e89528d9b3df6484c89',1,'jsocketpp::Socket::peek()']]],
  ['peer_20model_8',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md448',1,'']]],
  ['peer_20to_20peer_20model_9',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md448',1,'']]],
  ['performance_20and_20scaling_10',['Performance and Scaling',['../group__multicast__sockets.html#autotoc_md308',1,'']]],
  ['performance_20considerations_11',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md420',1,'']]],
  ['performance_20footprint_12',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md520',1,'']]],
  ['persist_20for_20the_20socket’s_20lifetime_13',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['picture_14',['Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'Wrapping It Up: The Full IPv4 Picture'],['../group__mastering__ipv6.html#autotoc_md53',1,'Wrapping It Up: The Full IPv6 Picture']]],
  ['platform_20api_20considerations_15',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md335',1,'']]],
  ['platform_20apis_16',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['platform_20behavior_17',['Platform Behavior',['../group__udp.html#autotoc_md679',1,'⚙️ Platform Behavior'],['../group__socketopts.html#autotoc_md1162',1,'⚠️ Platform Behavior'],['../group__socketopts.html#autotoc_md1085',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1090',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1095',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1100',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1105',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1116',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1125',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1153',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1139',1,'🔐 Platform Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md731',1,'Platform Behavior'],['../group__tcp.html#autotoc_md829',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1053',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1056',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1060',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1066',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1078',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1082',1,'Platform Behavior']]],
  ['platform_20notes_18',['Platform Notes',['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md900',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1063',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1069',1,'Platform Notes']]],
  ['platform_20socket_20library_19',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['platform_20socket_20library_20for_20modern_20c_2020_20',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['platform_20specific_20apis_21',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md430',1,'']]],
  ['platform_20specific_20considerations_22',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md461',1,'']]],
  ['platform_20specific_20tests_3a_23',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md481',1,'']]],
  ['platform_20support_24',['Platform Support',['../group__socketopts.html#autotoc_md1169',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1176',1,'🔀 Platform Support'],['../group__socket-options.html#autotoc_md347',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md841',1,'Platform Support']]],
  ['platform_20toolchain_20support_25',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md516',1,'']]],
  ['platform_3a_26',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['pledge_27',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md587',1,'']]],
  ['poco_3a_3anet_28',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md375',1,'']]],
  ['policy_29',['Semantics &amp;amp; policy',['../group__core.html#autotoc_md604',1,'']]],
  ['poll_30',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md329',1,'']]],
  ['poll_20and_20epoll_20as_20alternatives_31',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['port_32',['Port',['../group__address__reuse.html#autotoc_md115',1,'🧪 What Happens When Multiple Sockets Bind to the Same Port?'],['../group__core.html#ga1a7be273748ae3d91bc5ebe6499788a7',1,'jsocketpp::Port']]],
  ['port_33',['port',['../classjsocketpp_1_1DatagramPacket.html#a6619b7fcd476199e4a9c454d06f1bcd4',1,'jsocketpp::DatagramPacket']]],
  ['port_20binding_34',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1171',1,'']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_35',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['port_20in_20the_20constructor_36',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['port_20locally_37',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'']]],
  ['portability_38',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md65',1,'']]],
  ['portfile_39',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md493',1,'']]],
  ['portfile_20cmake_40',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md495',1,'']]],
  ['portfromsockaddr_41',['portFromSockaddr',['../namespacejsocketpp.html#a71637861db9b297572bc1de3df56a59a',1,'jsocketpp']]],
  ['posix_20approach_42',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'']]],
  ['posix_20bsd_43',['Differences from POSIX/BSD',['../group__multicast__sockets.html#autotoc_md299',1,'']]],
  ['posix_20bsd_20api_20unix_20linux_20macos_44',['POSIX/BSD API (Unix/Linux/MacOS)',['../group__multicast__sockets.html#autotoc_md291',1,'']]],
  ['posix_20linux_20macos_20unix_45',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md431',1,'']]],
  ['posix_20style_46',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md70',1,'']]],
  ['posix_20winsock_20apis_47',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md379',1,'']]],
  ['practical_20considerations_48',['Practical Considerations',['../group__underlying__socket__api.html#autotoc_md469',1,'7. Practical Considerations'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md281',1,'Practical Considerations']]],
  ['practical_20examples_49',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md451',1,'']]],
  ['practical_20implications_50',['Practical Implications',['../group__socket__states.html#autotoc_md395',1,'']]],
  ['practical_20implications_51',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['practical_20recommendations_52',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md337',1,'']]],
  ['practices_53',['Practices',['../group__async__io.html#autotoc_md187',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md503',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md218',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md196',1,'Best Practices'],['../group__ServerSocket__Lifecycle.html',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['practices_20recap_54',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md151',1,'']]],
  ['pre_20commit_20hooks_55',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md577',1,'']]],
  ['pre_20commit_20hooks_56',['Pre-commit hooks',['../index.html#autotoc_md547',1,'']]],
  ['preconditions_57',['Preconditions',['../group__core.html#autotoc_md610',1,'']]],
  ['preflightmax_58',['PreflightMax',['../group__udp.html#gga2124eae8cec6709a67be265f14da3bddac9a017cf1d4a5f3aff960a3f7e8bffd5',1,'jsocketpp']]],
  ['preflightsize_59',['PreflightSize',['../group__udp.html#gga2124eae8cec6709a67be265f14da3bdda0882ede215c2d76da1b71837ab80e9bd',1,'jsocketpp']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_60',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_61',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md491',1,'']]],
  ['prerequisites_62',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md203',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md489',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md4',1,'Prerequisites']]],
  ['presets_20recommended_63',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['primary_20traits_64',['Primary Traits',['../buffer__traits_8hpp.html#autotoc_md726',1,'']]],
  ['private_20networking_65',['Unique Local Addresses: Private Networking',['../group__mastering__ipv6.html#autotoc_md52',1,'']]],
  ['private_20vs_20public_20ip_20addresses_66',['Private vs. Public IP Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'']]],
  ['problematic_20on_20windows_67',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['production_68',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['programming_69',['Programming',['../group__multicast__sockets.html#autotoc_md309',1,'IPv6 Multicast Programming'],['../group__multicast__sockets.html#autotoc_md290',1,'Multicast Socket Programming']]],
  ['programming_20functions_70',['Comprehensive List of Socket Programming Functions',['../group__list__bsd__socket__functions.html',1,'']]],
  ['project_71',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['project_20conan_20friendly_72',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md207',1,'']]],
  ['pros_20and_20cons_73',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md68',1,'']]],
  ['protocol_20applicability_74',['Protocol Applicability',['../group__socketopts.html#autotoc_md1057',1,'']]],
  ['protocol_20behavior_75',['Protocol Behavior',['../group__tcp.html#autotoc_md976',1,'']]],
  ['protocol_20format_76',['Protocol Format',['../group__tcp.html#autotoc_md922',1,'Protocol Format'],['../group__tcp.html#autotoc_md925',1,'Protocol Format'],['../group__tcp.html#autotoc_md949',1,'Protocol Format'],['../group__tcp.html#autotoc_md952',1,'Protocol Format']]],
  ['protocol_20igmp_77',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['protocol_20use_20cases_78',['Protocol Use Cases',['../group__socketopts.html#autotoc_md1054',1,'']]],
  ['protocols_20and_20the_20socket_20api_79',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md450',1,'']]],
  ['provide_20poll_20and_20epoll_20as_20alternatives_80',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['public_20ip_20addresses_81',['Private vs. Public IP Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'']]],
  ['publishing_20jsocketpp_20to_20the_20conan_20center_20index_20cci_82',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['publishing_20jsocketpp_20to_20the_20vcpkg_20registry_83',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the vcpkg Registry',['../group__vcpkg__publish__guide.html',1,'']]],
  ['pull_20request_20to_20cci_84',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md214',1,'']]],
  ['pull_20requests_85',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md573',1,'']]],
  ['purpose_86',['Purpose',['../group__address__reuse.html#autotoc_md107',1,'🎯 Purpose'],['../group__udp.html#autotoc_md684',1,'🧠 Purpose'],['../namespacejsocketpp_1_1net.html#autotoc_md596',1,'Purpose'],['../group__tcp.html#autotoc_md969',1,'Purpose']]],
  ['py_87',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md205',1,'']]],
  ['python_20af_5finet_88',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md452',1,'']]]
];
