var searchData=
[
  ['nagle’s_20algorithm_20to_20reduce_20latency_0',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1157',1,'']]],
  ['name_20resolution_1',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['native_20bsd_20posix_20winsock_20apis_2',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md330',1,'']]],
  ['nesting_3',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md1031',1,'']]],
  ['network_20data_20units_3a_20packets_20datagrams_20segments_20and_20beyond_4',['Understanding Network Data Units: Packets, Datagrams, Segments, and Beyond',['../group__network__data__units.html',1,'']]],
  ['network_20models_20and_20data_20encapsulation_5',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md265',1,'']]],
  ['network_20module_6',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md328',1,'']]],
  ['network_5fdata_5funits_2emd_7',['network_data_units.md',['../network__data__units_8md.html',1,'']]],
  ['nextdatagramsize_8',['nextDatagramSize',['../namespacejsocketpp_1_1internal.html#a592175a5a77f541b400879a5a4ca8978',1,'jsocketpp::internal']]],
  ['non_20blocking_9',['What is Non-Blocking?',['../group__async__io.html#autotoc_md139',1,'']]],
  ['non_20blocking_20and_20asynchronous_20i_20o_10',['6. Non-Blocking and Asynchronous I/O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'']]],
  ['non_20blocking_20mode_20on_20a_20client_20socket_11',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1143',1,'']]],
  ['non_20blocking_20mode_3a_12',['Non blocking mode:',['../group__async__io.html#autotoc_md151',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md155',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md159',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md162',1,'Non-blocking mode:']]],
  ['non_20blocking_20socket_20linux_13',['Example: Set Non-Blocking Socket (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md228',1,'']]],
  ['non_20blocking_20socket_20windows_14',['Example: Non-Blocking Socket (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md239',1,'']]],
  ['non_20blocking_20sockets_15',['Non Blocking Sockets',['../group__async__io.html#autotoc_md137',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md406',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md416',1,'6.1 Non-Blocking Sockets']]],
  ['non_20blocking_20sockets_20in_20jsocketpp_16',['Blocking vs Non-Blocking Sockets in jsocketpp',['../group__async__io.html',1,'']]],
  ['nopreflight_17',['NoPreflight',['../group__udp.html#gga2124eae8cec6709a67be265f14da3bdda4f0bde0267e64be026814e98c423c47f',1,'jsocketpp']]],
  ['not_20expose_20windows_20so_5freuseaddr_18',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md121',1,'']]],
  ['notes_19',['Notes',['../group__tcp.html#autotoc_md831',1,'⚠️ Notes'],['../group__socketopts.html#autotoc_md1046',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1057',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1066',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1077',1,'⚠️ ServerSocket-specific Notes'],['../group__udp.html#autotoc_md752',1,'⚠️ Usage Notes'],['../group__tcp.html#autotoc_md1026',1,'⚠️ Usage Notes'],['../group__tcp.html#autotoc_md802',1,'💡 Notes'],['../group__socketopts.html#autotoc_md1048',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1058',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1068',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1079',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1050',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1059',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1070',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1081',1,'🧿 UnixSocket-specific Notes'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md261',1,'Detailed Notes'],['../group__tcp.html#autotoc_md1004',1,'Implementation Notes'],['../group__bind__interfaces.html#autotoc_md180',1,'jsocketpp API Notes'],['../group__list__bsd__socket__functions.html#autotoc_md33',1,'Notes'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md219',1,'Notes'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md230',1,'Notes'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md241',1,'Notes'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md252',1,'Notes'],['../group__internal.html#autotoc_md577',1,'Notes'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md606',1,'Notes'],['../group__udp.html#autotoc_md617',1,'Notes'],['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md930',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1093',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1099',1,'Platform Notes']]],
  ['notes_20for_20library_20authors_20',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md125',1,'']]]
];
