var searchData=
[
  ['i_20o_0',['I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md458',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md468',1,'6.4 Asynchronous I/O']]],
  ['i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_1',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['i_20use_20jsocketpp_20in_20production_2',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['iana_20s_20role_3a_20orchestrating_20ipv6_3',['IANA&apos;s Role: Orchestrating IPv6',['../group__mastering__ipv6.html#autotoc_md48',1,'']]],
  ['iana_3a_20guardians_20of_20ipv4_20allocation_4',['IANA: Guardians of IPv4 Allocation',['../group__mastering__ipv4.html#autotoc_md39',1,'']]],
  ['if_20autobind_20true_5',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['if_20socket_20is_20ipv6_20only_6',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['igmp_7',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['implementation_20details_8',['Implementation Details',['../group__udp.html#autotoc_md686',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md697',1,'Implementation Details'],['../group__tcp.html#autotoc_md845',1,'Implementation Details'],['../group__tcp.html#autotoc_md899',1,'Implementation Details'],['../group__tcp.html#autotoc_md902',1,'Implementation Details'],['../group__tcp.html#autotoc_md907',1,'Implementation Details'],['../group__tcp.html#autotoc_md909',1,'Implementation Details'],['../group__tcp.html#autotoc_md912',1,'Implementation Details'],['../group__tcp.html#autotoc_md914',1,'Implementation Details'],['../group__tcp.html#autotoc_md916',1,'Implementation Details'],['../group__tcp.html#autotoc_md918',1,'Implementation Details'],['../group__tcp.html#autotoc_md920',1,'Implementation Details'],['../group__tcp.html#autotoc_md923',1,'Implementation Details'],['../group__tcp.html#autotoc_md926',1,'Implementation Details'],['../group__tcp.html#autotoc_md928',1,'Implementation Details'],['../group__tcp.html#autotoc_md932',1,'Implementation Details'],['../group__tcp.html#autotoc_md934',1,'Implementation Details'],['../group__tcp.html#autotoc_md936',1,'Implementation Details'],['../group__tcp.html#autotoc_md942',1,'Implementation Details'],['../group__tcp.html#autotoc_md943',1,'Implementation Details'],['../group__tcp.html#autotoc_md945',1,'Implementation Details'],['../group__tcp.html#autotoc_md947',1,'Implementation Details'],['../group__tcp.html#autotoc_md950',1,'Implementation Details'],['../group__tcp.html#autotoc_md953',1,'Implementation Details'],['../group__tcp.html#autotoc_md955',1,'Implementation Details'],['../group__tcp.html#autotoc_md957',1,'Implementation Details'],['../group__tcp.html#autotoc_md961',1,'Implementation Details'],['../group__tcp.html#autotoc_md963',1,'Implementation Details'],['../group__tcp.html#autotoc_md967',1,'Implementation Details'],['../group__tcp.html#autotoc_md970',1,'Implementation Details'],['../group__tcp.html#autotoc_md972',1,'Implementation Details'],['../group__tcp.html#autotoc_md982',1,'Implementation Details']]],
  ['implementation_20notes_9',['Implementation Notes',['../group__tcp.html#autotoc_md974',1,'']]],
  ['implications_10',['Practical Implications',['../group__socket__states.html#autotoc_md395',1,'']]],
  ['implications_11',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['implicit_20binding_20in_20tcp_20and_20udp_12',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['in_20action_3a_20practical_20examples_13',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md451',1,'']]],
  ['in_20c_14',['in C',['../group__multicast__sockets.html#autotoc_md297',1,'Example: Receiver in C'],['../group__multicast__sockets.html#autotoc_md296',1,'Example: Sender (Broadcaster) in C']]],
  ['in_20c_2020_3a_15',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['in_20c_20winsock_16',['in C Winsock',['../group__multicast__sockets.html#autotoc_md302',1,'Example: Receiver in C++ (Winsock)'],['../group__multicast__sockets.html#autotoc_md301',1,'Example: Sender in C++ (Winsock)']]],
  ['in_20constructor_20bind_20listen_20explicit_17',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['in_20depth_18',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md406',1,'']]],
  ['in_20depth_19',['Multicast Addresses: &lt;span class=&quot;tt&quot;&gt;ff00::/8&lt;/span&gt; in Depth',['../group__mastering__ipv6.html#autotoc_md50',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_20',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['in_20ipv6_3a_20flexible_20address_20allocation_21',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['in_20jsocketpp_22',['in jsocketpp',['../group__async__io.html',1,'Blocking vs Non-Blocking Sockets in jsocketpp'],['../group__socket-options.html',1,'Socket Options in jsocketpp']]],
  ['in_20jsocketpp_20_3a_23',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md123',1,'']]],
  ['in_20production_24',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_25',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['in_20tcp_26',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md317',1,'']]],
  ['in_20tcp_20and_20udp_27',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['in_20tcp_20and_20udp_20connections_28',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['in_20the_20constructor_29',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['in_20your_20project_30',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_31',['Includes:',['../group__core.html#autotoc_md595',1,'']]],
  ['incompatibility_32',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['index_20cci_33',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['index_20cci_20submission_34',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['index_2emd_35',['index.md',['../index_8md.html',1,'']]],
  ['inet_5fntop_5faux_36',['inet_ntop_aux',['../namespacejsocketpp.html#a403588c277f89591897408faed72a910',1,'jsocketpp']]],
  ['information_20and_20configuration_37',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['initialization_20and_20cleanup_3a_38',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md476',1,'']]],
  ['initialization_3a_20posix_20approach_39',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'']]],
  ['initsockets_40',['InitSockets',['../namespacejsocketpp.html#aef7428a3f4d80452442ecf3edfdbc89a',1,'jsocketpp']]],
  ['inputs_41',['Supported Inputs',['../namespacejsocketpp_1_1internal.html#autotoc_md637',1,'']]],
  ['installation_42',['📦 Installation',['../index.html#autotoc_md524',1,'']]],
  ['integration_43',['🔧 Manual Integration',['../index.html#autotoc_md529',1,'']]],
  ['integration_20guide_44',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['integration_20in_20your_20project_45',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_46',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md484',1,'']]],
  ['integration_20test_3a_47',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md479',1,'']]],
  ['integration_20tests_3a_48',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md477',1,'']]],
  ['intended_20usage_49',['Intended Usage',['../classjsocketpp_1_1SocketOptions.html#autotoc_md1002',1,'']]],
  ['interface_20list_20windows_50',['Example: Get Interface List (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md268',1,'']]],
  ['interfaces”_20mean_51',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['interfaces_52',['Interfaces',['../group__bind__interfaces.html#autotoc_md194',1,'Example: Binding to All Interfaces'],['../group__multicast__sockets.html#autotoc_md304',1,'Handling Multiple Interfaces'],['../group__bind__interfaces.html',1,'Understanding &lt;tt&gt;bind()&lt;/tt&gt;: Binding to All Interfaces vs Specific Interfaces']]],
  ['interfaces_20vs_20specific_20interfaces_53',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['internal_20buffer_54',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md838',1,'']]],
  ['internal_20helpers_55',['Internal Helpers',['../group__internal.html',1,'']]],
  ['internal_20mechanism_56',['🔧 Internal Mechanism',['../group__internal.html#autotoc_md628',1,'']]],
  ['internal_20use_57',['Example (internal use)',['../group__udp.html#autotoc_md723',1,'']]],
  ['internally_58',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['internet_20group_20management_20protocol_20igmp_59',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['introduction_60',['Introduction',['../group__socket__binding.html#autotoc_md81',1,'Introduction'],['../group__sockets__theory.html#autotoc_md402',1,'Introduction']]],
  ['introduction_20to_20multicast_20sockets_61',['Introduction to Multicast Sockets',['../group__multicast__sockets.html#autotoc_md283',1,'']]],
  ['introduction_20to_20the_20socket_20api_62',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md441',1,'']]],
  ['invalid_5fsocket_63',['INVALID_SOCKET',['../namespacejsocketpp.html#a3ddf4938a63ed33a5e2f7d2625cb4405',1,'jsocketpp']]],
  ['ioctl_20fcntl_20ioctlsocket_64',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ioctl_20fcntl_20ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_65',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ioctl_20unix_20linux_66',['1. ioctl (Unix/Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md226',1,'']]],
  ['ioctl_5ffcntl_5fioctlsocket_5fguide_2emd_67',['ioctl_fcntl_ioctlsocket_guide.md',['../ioctl__fcntl__ioctlsocket__guide_8md.html',1,'']]],
  ['ioctlsocket_68',['ioctlsocket',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'Comprehensive Guide to &lt;tt&gt;ioctl&lt;/tt&gt;, &lt;tt&gt;fcntl&lt;/tt&gt;, &lt;tt&gt;ioctlsocket&lt;/tt&gt;,'],['../namespacejsocketpp.html#a771a44f3967222b2e3221ed3120220af',1,'jsocketpp::ioctlsocket()']]],
  ['ioctlsocket_20windows_69',['3. ioctlsocket (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md250',1,'']]],
  ['ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_70',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ip_20addresses_71',['Private vs. Public IP Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'']]],
  ['ip_20addresses_3a_20unicast_20multicast_20broadcast_20and_20anycast_72',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['ip_20multicast_20fundamentals_73',['IP Multicast Fundamentals',['../group__multicast__sockets.html#autotoc_md284',1,'']]],
  ['ipaddressesequal_74',['ipAddressesEqual',['../namespacejsocketpp_1_1internal.html#a9ec0f69551a2510b87db8ea21042ea42',1,'jsocketpp::internal']]],
  ['ipc_75',['IPC',['../index.html#autotoc_md538',1,'🧷 UNIX Domain Socket (IPC)'],['../group__sockets__theory.html#autotoc_md410',1,'2.4. Unix Domain Sockets (Local IPC)']]],
  ['ipfromsockaddr_76',['ipFromSockaddr',['../namespacejsocketpp.html#a18428d088b7f3b2e55efe9adc49e10a9',1,'jsocketpp']]],
  ['ipv4_20address_20structure_3a_20the_20foundation_77',['IPv4 Address Structure: The Foundation',['../group__mastering__ipv4.html#autotoc_md37',1,'']]],
  ['ipv4_20allocation_78',['IANA: Guardians of IPv4 Allocation',['../group__mastering__ipv4.html#autotoc_md39',1,'']]],
  ['ipv4_20features_3a_20beyond_20addressing_79',['Key IPv4 Features: Beyond Addressing',['../group__mastering__ipv4.html#autotoc_md42',1,'']]],
  ['ipv4_20mapped_20ipv6_20behavior_80',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md866',1,'']]],
  ['ipv4_20picture_81',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['ipv4_3a_20a_20complete_20guide_20to_20its_20features_20structure_20and_20capabilities_82',['Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities',['../group__mastering__ipv4.html',1,'']]],
  ['ipv6_83',['IANA&apos;s Role: Orchestrating IPv6',['../group__mastering__ipv6.html#autotoc_md48',1,'']]],
  ['ipv6_20address_20structure_3a_20the_20foundation_84',['IPv6 Address Structure: The Foundation',['../group__mastering__ipv6.html#autotoc_md46',1,'']]],
  ['ipv6_20behavior_85',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md866',1,'']]],
  ['ipv6_20features_3a_20beyond_20addressing_86',['Key IPv6 Features: Beyond Addressing',['../group__mastering__ipv6.html#autotoc_md51',1,'']]],
  ['ipv6_20multicast_87',['IPv6 Multicast',['../group__multicast__sockets.html#autotoc_md289',1,'']]],
  ['ipv6_20multicast_20programming_88',['IPv6 Multicast Programming',['../group__multicast__sockets.html#autotoc_md309',1,'']]],
  ['ipv6_20only_89',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['ipv6_20picture_90',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['ipv6_3a_20a_20complete_20guide_20to_20its_20features_20structure_20and_20capabilities_91',['Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities',['../group__mastering__ipv6.html',1,'']]],
  ['ipv6_3a_20flexible_20address_20allocation_92',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['is_20a_20packet_93',['What is a Packet?',['../group__network__data__units.html#autotoc_md315',1,'']]],
  ['is_20a_20socket_94',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md404',1,'']]],
  ['is_20a_20socket_20state_95',['What is a Socket State?',['../group__socket__states.html#autotoc_md386',1,'']]],
  ['is_20blocking_96',['What is Blocking?',['../group__async__io.html#autotoc_md156',1,'']]],
  ['is_20ipv6_20only_97',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['is_20jsocketpp_20async_98',['Is jsocketpp async?',['../index.html#autotoc_md556',1,'']]],
  ['is_20multicast_99',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md734',1,'']]],
  ['is_20non_20blocking_100',['What is Non-Blocking?',['../group__async__io.html#autotoc_md157',1,'']]],
  ['is_20problematic_20on_20windows_101',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['is_20socket_20binding_102',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md82',1,'']]],
  ['is_20the_20default_20buffer_20size_103',['What is the default buffer size?',['../index.html#autotoc_md564',1,'']]],
  ['is_20the_20mtu_104',['🔍 What is the MTU?',['../group__udp.html#autotoc_md677',1,'']]],
  ['is_20transferred_105',['What Is Transferred',['../group__udp.html#autotoc_md663',1,'']]],
  ['is_20udp_106',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md652',1,'']]],
  ['is_20used_107',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md325',1,'']]],
  ['is_5fbyte_5flike_108',['is_byte_like',['../structjsocketpp_1_1detail_1_1is__byte__like.html',1,'jsocketpp::detail']]],
  ['is_5fdynamic_5fbuffer_5fv_109',['is_dynamic_buffer_v',['../namespacejsocketpp_1_1detail.html#aa46a9243f021ef54b04645f354feea30',1,'jsocketpp::detail']]],
  ['is_5ffixed_5fbuffer_5fv_110',['is_fixed_buffer_v',['../namespacejsocketpp_1_1detail.html#a18306b136e94e5aaf18c6dd6d5f06f33',1,'jsocketpp::detail']]],
  ['is_5fipv4_5fmulticast_111',['is_ipv4_multicast',['../group__socketopts.html#ga10fe0331596fddffb6dbd483c95a2490',1,'jsocketpp::SocketOptions']]],
  ['is_5fipv6_5fmulticast_112',['is_ipv6_multicast',['../group__socketopts.html#ga10be210b19c0e6d6deb641cb74ed1c0a',1,'jsocketpp::SocketOptions']]],
  ['isbound_113',['isBound',['../group__udp.html#gadd6a72af69e4e8e1e8701c60a7e728f1',1,'jsocketpp::DatagramSocket::isBound()'],['../group__tcp.html#ga0b3a5cb732c669b678e03549e5af2427',1,'jsocketpp::ServerSocket::isBound()'],['../group__tcp.html#gac5d9708cad057d6d608fb732eb1bb117',1,'jsocketpp::Socket::isBound()']]],
  ['isclosed_114',['isClosed',['../group__udp.html#gae91f746fb4cffa0eb8460c816a476d65',1,'jsocketpp::DatagramSocket::isClosed()'],['../group__tcp.html#gaeb5adb24bd7f50eaf8b52aa4441ffe71',1,'jsocketpp::ServerSocket::isClosed()'],['../group__tcp.html#ga368ea24012b68fcf6db4f9a75d6d1940',1,'jsocketpp::Socket::isClosed()']]],
  ['isconnected_115',['isConnected',['../group__udp.html#gac3b7c4a5fc5a21372c4a9cadb3e85efb',1,'jsocketpp::DatagramSocket::isConnected()'],['../group__tcp.html#gab1e4f32614be9a3609820f75dbcb4fc2',1,'jsocketpp::Socket::isConnected() const noexcept']]],
  ['isinputshutdown_116',['isInputShutdown',['../group__tcp.html#ga402fc4a398e670854cbb4edf791c1916',1,'jsocketpp::Socket']]],
  ['isipv4mappedipv6_117',['isIPv4MappedIPv6',['../group__core.html#gab0ac1b9850480abafeb047a4f96792a0',1,'jsocketpp']]],
  ['islistening_118',['isListening',['../group__tcp.html#ga1717f9859e5aeeba77c3d463ec53e735',1,'jsocketpp::ServerSocket']]],
  ['isoutputshutdown_119',['isOutputShutdown',['../group__tcp.html#gad2b2992b358d3656a2e0d3e854c897bc',1,'jsocketpp::Socket']]],
  ['ispassivesocket_120',['isPassiveSocket',['../group__socketopts.html#gad113886a7cc6100e5ef2c25ea504696e',1,'jsocketpp::ServerSocket::isPassiveSocket()'],['../group__socketopts.html#gaace6c3364b4016979537571b36c58727',1,'jsocketpp::SocketOptions::isPassiveSocket()']]],
  ['ispathinuse_121',['isPathInUse',['../classjsocketpp_1_1UnixSocket.html#a0b8200b52a5ed8c66c84ee52ba9f98e6',1,'jsocketpp::UnixSocket']]],
  ['issues_122',['Issues',['../md_CONTRIBUTING.html#autotoc_md571',1,'1. Reporting Issues'],['../group__multicast__sockets.html#autotoc_md310',1,'Troubleshooting Common Issues']]],
  ['isvalid_123',['isValid',['../group__udp.html#gab33da807656e2ab920707d60605844f5',1,'jsocketpp::DatagramSocket::isValid()'],['../group__tcp.html#ga4e3ff54722a55e7500fdd76f26c53dac',1,'jsocketpp::ServerSocket::isValid()'],['../group__tcp.html#gae2b10ef466023b380a34b062359c0f65',1,'jsocketpp::Socket::isValid()'],['../classjsocketpp_1_1UnixSocket.html#acb7ad274be98890ca17dfa5deb86024b',1,'jsocketpp::UnixSocket::isValid()']]],
  ['it_20actually_20does_124',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_125',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['it_20up_3a_20the_20full_20ipv4_20picture_126',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['it_20up_3a_20the_20full_20ipv6_20picture_127',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['it_20work_20on_20windows_128',['Does it work on Windows?',['../index.html#autotoc_md562',1,'']]],
  ['it_20works_20internally_129',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['its_20features_20structure_20and_20capabilities_130',['Its Features Structure and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['its_20limitations_131',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md127',1,'']]]
];
