var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md123',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md310',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md290',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md387',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md107',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md332',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md294',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md363',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['tcgetattr_4',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md256',1,'']]],
  ['tcp_5',['TCP',['../group__sockets__theory.html#autotoc_md358',1,'2.1. Stream Sockets (TCP)'],['../group__network__data__units.html#autotoc_md268',1,'Segments: The Reliable Counterpart in TCP'],['../group__sockets__theory.html#autotoc_md366',1,'Stream Sockets (TCP)']]],
  ['tcp_20and_20udp_6',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['tcp_20and_20udp_20connections_7',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['tcp_20echo_20server_8',['🧵 TCP Echo Server',['../index.html#autotoc_md483',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_9',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md403',1,'']]],
  ['tcp_20socket_20lifecycle_10',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md339',1,'']]],
  ['tcp_20socket_20states_11',['Main TCP Socket States',['../group__socket__states.html#autotoc_md340',1,'']]],
  ['tcp_20sockets_12',['TCP Sockets',['../group__tcp.html',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md66',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md70',1,'TCP Sockets']]],
  ['tcp_20sockets_20socket_20serversocket_13',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md303',1,'']]],
  ['tcp_20state_20transitions_14',['TCP State Transitions',['../group__socket__states.html#autotoc_md342',1,'']]],
  ['tcsetattr_20tcgetattr_15',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md256',1,'']]],
  ['terminal_20window_20size_20linux_16',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md216',1,'']]],
  ['test_17',['TEST',['../socket__gtest_8cpp.html#af84a2f63791f9b4fd5ee14e6161ce2d9',1,'TEST(SocketTest, TcpConnectInvalid):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a385a2ab183d5626e9f7de45a6ff70e64',1,'TEST(SocketTest, TcpBindInvalidPort):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a88c3e6586ac2476e33803ecc48b48541',1,'TEST(SocketTest, UnixSocketInvalidPath):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aadbb6137575fbeb33208cb9f555b3a3d',1,'TEST(SocketTest, TcpConnectTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aac9350146074ace6dd63823149af8925',1,'TEST(SocketTest, TcpNonBlocking):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ae2a55900b16067f9197259a155c13835',1,'TEST(SocketTest, TcpSetGetOption):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ac6fe24ab1fa2e3fbf0d3d42e8c9247a6',1,'TEST(SocketTest, UdpSendRecvLoopback):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a013ef3192376c90badc588e9c69af993',1,'TEST(SocketTest, UdpTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a80cc9752601e3ded34d6d8e152b1737f',1,'TEST(SocketTest, UnixSocketBindConnect):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a7d49aecf9ef526bad3e69b943660ae73',1,'TEST(SocketTest, UnixSocketTimeoutAndNonBlocking):&#160;socket_gtest.cpp']]],
  ['test_20and_20usage_20guide_18',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['test_20cases_20to_20consider_3a_19',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md436',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_20',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md431',1,'']]],
  ['test_20the_20port_20locally_21',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md448',1,'']]],
  ['test_20the_20recipe_20locally_22',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['test_20with_20mocking_3a_23',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md435',1,'']]],
  ['test_3a_24',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md430',1,'']]],
  ['test_5ferror_5fhandling_25',['test_error_handling',['../client_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;client.cpp'],['../server_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;server.cpp']]],
  ['test_5fpackage_26',['test_package',['../group__conan__publish__guide.html#autotoc_md194',1,'']]],
  ['test_5ftcp_27',['test_tcp',['../client_8cpp.html#a5c06bbffe96672a267fdf7a58d39b8c9',1,'test_tcp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a1de353166d8a8c39d1ecad7d6616e681',1,'test_tcp(const string &amp;ip, const Port port):&#160;client.cpp'],['../server_8cpp.html#a8348483da59fb305dfc63392f54bef3f',1,'test_tcp(const Port port):&#160;server.cpp']]],
  ['test_5fudp_28',['test_udp',['../client_8cpp.html#a42c921ec1646212ba1214248e51075cc',1,'test_udp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a8b01747ac0288562f1f5b721300bd338',1,'test_udp(const string &amp;ip, Port port):&#160;client.cpp'],['../server_8cpp.html#ad783a901702495179902ed7bf93f8178',1,'test_udp(const Port port):&#160;server.cpp']]],
  ['test_5funix_29',['test_unix',['../client_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;client.cpp'],['../client_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;client.cpp'],['../server_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;server.cpp'],['../server_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;server.cpp']]],
  ['testing_30',['Testing',['../index.html#autotoc_md495',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md530',1,'5. Testing']]],
  ['testing_20and_20integration_20guide_31',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['testing_20in_20c_2020_3a_32',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_33',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md427',1,'']]],
  ['tests_34',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_35',['Tests:',['../group__unit__tests.html#autotoc_md423',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md428',1,'2. <b>Integration Tests</b>:'],['../group__unit__tests.html#autotoc_md432',1,'3.1 <b>Using CMake for Platform-Specific Tests</b>:'],['../group__unit__tests.html#autotoc_md433',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['the_20basics_36',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['the_20conan_20center_20index_20cci_37',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['the_20connect_20function_38',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20connectionless_20approach_39',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md267',1,'']]],
  ['the_20constructor_40',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20default_20buffer_20size_41',['What is the default buffer size?',['../index.html#autotoc_md515',1,'']]],
  ['the_20foundations_3a_20network_20models_20and_20data_20encapsulation_42',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md265',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_43',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_44',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md379',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_45',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['the_20library_46',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_47',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md375',1,'']]],
  ['the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_48',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20makefile_49',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20mtu_50',['🔍 What is the MTU?',['../group__udp.html#autotoc_md720',1,'']]],
  ['the_20port_20in_20the_20constructor_51',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20port_20locally_52',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md448',1,'']]],
  ['the_20recipe_20locally_53',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['the_20reliable_20counterpart_20in_20tcp_54',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md268',1,'']]],
  ['the_20role_20of_20the_20connect_20function_55',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20same_20port_56',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['the_20socket’s_20lifetime_57',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20socket_20api_58',['the Socket API',['../group__underlying__socket__api.html#autotoc_md392',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md393',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md401',1,'4. Protocols and the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['the_20vcpkg_20registry_59',['the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md450',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['theory_20types_20and_20platform_20apis_60',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['this_20is_20problematic_20on_20windows_61',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['this_20library_62',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md322',1,'']]],
  ['this_20matters_63',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md586',1,'']]],
  ['this_20relates_20to_20jsocketpp_64',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md348',1,'']]],
  ['thoughts_20and_20best_20practices_65',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md169',1,'']]],
  ['thread_20safety_66',['Thread Safety',['../group__tcp.html#autotoc_md792',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md801',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md810',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md823',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md832',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md848',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md861',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md786',1,'Thread Safety'],['../group__tcp.html#autotoc_md871',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md880',1,'Thread Safety'],['../group__tcp.html#autotoc_md946',1,'Thread Safety']]],
  ['throwlastsockerror_67',['throwLastSockError',['../namespacejsocketpp_1_1internal.html#a8a49e143a6246874f572bde7254e09b6',1,'jsocketpp::internal']]],
  ['throws_68',['Throws',['../group__internal.html#autotoc_md573',1,'Throws'],['../group__udp.html#autotoc_md625',1,'Throws']]],
  ['timeout_69',['timeout',['../group__socketopts.html#autotoc_md1127',1,'Example: Set a 3-second receive timeout'],['../group__socketopts.html#autotoc_md1132',1,'Example: Set a 5-second send timeout']]],
  ['timeout_20behavior_70',['Timeout Behavior',['../group__tcp.html#autotoc_md788',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md797',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md806',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md817',1,'⏱ Timeout Behavior']]],
  ['timeout_20handling_71',['⏱ Timeout Handling',['../group__udp.html#autotoc_md647',1,'']]],
  ['timeout_20semantics_72',['Timeout Semantics',['../group__tcp.html#autotoc_md870',1,'']]],
  ['timeouts_73',['Timeouts',['../group__async__io.html#autotoc_md145',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md141',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md142',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_74',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md143',1,'']]],
  ['tips_20and_20best_20practices_75',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md454',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices']]],
  ['to_76',['to',['../group__core.html#autotoc_md550',1,'Applies to'],['../group__core.html#autotoc_md554',1,'Applies to']]],
  ['to_20a_20local_20address_77',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['to_20adjust_78',['When to Adjust',['../group__core.html#autotoc_md553',1,'']]],
  ['to_20all_20interfaces”_20mean_79',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['to_20all_20interfaces_80',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['to_20all_20interfaces_20vs_20specific_20interfaces_81',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['to_20cci_82',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['to_20consider_3a_83',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md436',1,'']]],
  ['to_20ioctl_20fcntl_20ioctlsocket_84',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['to_20ioctl_20fcntl_20ioctlsocket_20wsaioctl_20and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_85',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['to_20jsocketpp_86',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md348',1,'How This Relates to <span class="tt">jsocketpp</span>']]],
  ['to_20linger_20for_205_20seconds_20on_20close_87',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1065',1,'']]],
  ['to_20mock_20recv_20and_20send_3a_88',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md426',1,'']]],
  ['to_20peer_20model_89',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md399',1,'']]],
  ['to_20provide_20poll_20and_20epoll_20as_20alternatives_90',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['to_20reduce_20latency_91',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1167',1,'']]],
  ['to_20the_20conan_20center_20index_20cci_92',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['to_20the_20same_20port_93',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['to_20the_20socket_20api_94',['to the Socket API',['../group__underlying__socket__api.html#autotoc_md392',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['to_20the_20vcpkg_20registry_95',['to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md450',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['to_20use_96',['When to Use',['../group__socketopts.html#autotoc_md1220',1,'']]],
  ['toiovec_97',['toIOVec',['../group__internal.html#ga7701a273337a71485ba1583df464b178',1,'jsocketpp::internal::toIOVec(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#gacdd48d04c87ec69aff97c5d29dbfe1a1',1,'jsocketpp::internal::toIOVec(const std::span&lt; const BufferView &gt; buffers)']]],
  ['tonetwork_98',['toNetwork',['../namespacejsocketpp_1_1net.html#a30e0ea56a20c62070f079482d8cabfa5',1,'jsocketpp::net::toNetwork(const uint16_t val)'],['../namespacejsocketpp_1_1net.html#a933367ad91e111a4e6516e67d6e08c9a',1,'jsocketpp::net::toNetwork(const uint32_t val)']]],
  ['toolchain_20support_99',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md467',1,'']]],
  ['tooling_100',['🛠 Developer Tooling',['../index.html#autotoc_md497',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_101',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['topics_102',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md385',1,'']]],
  ['towsabuf_103',['toWSABUF',['../group__internal.html#gae140ce724d1cfc733f3c2dbccf0cf60b',1,'jsocketpp::internal::toWSABUF(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#ga53db0a38699800e21866a0ded1b433ba',1,'jsocketpp::internal::toWSABUF(const std::span&lt; const BufferView &gt; buffers)']]],
  ['trade_20off_104',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_105',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['traits_106',['Primary Traits',['../buffer__traits_8hpp.html#autotoc_md766',1,'']]],
  ['transfer_107',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['transferred_108',['Transferred',['../group__udp.html#autotoc_md630',1,'Ownership Transferred'],['../group__udp.html#autotoc_md628',1,'What Is Transferred']]],
  ['transitions_109',['TCP State Transitions',['../group__socket__states.html#autotoc_md342',1,'']]],
  ['troubleshooting_110',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['true_111',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md898',1,'']]],
  ['true_20matters_112',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md875',1,'']]],
  ['truncated_113',['truncated',['../structjsocketpp_1_1DatagramReadResult.html#a830a7a1e1451dd93f23f44ddb063c4f3',1,'jsocketpp::DatagramReadResult']]],
  ['tryaccept_114',['tryAccept',['../group__tcp.html#ga6eff2e5c775318cfd2813ee72e716571',1,'jsocketpp::ServerSocket::tryAccept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#ga93a186b3fcb925c3a6c30f1c5d5bf8a8',1,'jsocketpp::ServerSocket::tryAccept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const']]],
  ['tryclosenoexcept_115',['tryCloseNoexcept',['../group__internal.html#ga311f6b46f1941a20ab7e389787fc3bea',1,'jsocketpp::internal']]],
  ['type_116',['Type',['../group__socketopts.html#autotoc_md1191',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1200',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md300',1,'Common Options by Socket Type']]],
  ['types_117',['Types',['../group__socketopts.html#autotoc_md1147',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md396',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md363',1,'2.5. Comparison Table: Socket Types'],['../group__core.html',1,'Core Utilities and Types'],['../group__tcp.html#autotoc_md944',1,'Supported Types']]],
  ['types_20and_20platform_20apis_118',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['types_20of_20sockets_20in_20depth_119',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md357',1,'']]],
  ['types_20work_120',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['typical_20usage_121',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md780',1,'']]],
  ['typical_20usage_20example_122',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md877',1,'']]],
  ['typical_20use_20cases_123',['🧰 Typical Use Cases',['../index.html#autotoc_md461',1,'']]]
];
