var searchData=
[
  ['safe_20usage_20guidelines_0',['✅ Safe Usage Guidelines',['../group__socketopts.html#autotoc_md1041',1,'']]],
  ['safety_1',['Safety',['../group__tcp.html#autotoc_md783',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md792',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md801',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md814',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md823',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md839',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md852',1,'⚠️ Thread Safety'],['../group__udp.html#autotoc_md748',1,'🔒 Safety'],['../group__tcp.html#autotoc_md1017',1,'🔒 Safety'],['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'a) Flexibility and Safety'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md763',1,'Safety'],['../group__tcp.html#autotoc_md777',1,'Thread Safety'],['../group__tcp.html#autotoc_md862',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md871',1,'Thread Safety'],['../group__tcp.html#autotoc_md937',1,'Thread Safety']]],
  ['same_20port_2',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['scenarios_3',['Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md55',1,'6. Advanced Scenarios'],['../group__tcp.html#autotoc_md738',1,'Common Scenarios']]],
  ['scope_4',['Scope',['../md_CODE__OF__CONDUCT.html#autotoc_md531',1,'']]],
  ['scopedblockingmode_5',['ScopedBlockingMode',['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html',1,'jsocketpp::internal::ScopedBlockingMode'],['../group__internal.html#ga606aec57de9374b5b0fc69f37504fedd',1,'jsocketpp::internal::ScopedBlockingMode::ScopedBlockingMode()']]],
  ['scopedblockingmode_2ehpp_6',['ScopedBlockingMode.hpp',['../ScopedBlockingMode_8hpp.html',1,'']]],
  ['second_20receive_20timeout_7',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1118',1,'']]],
  ['second_20send_20timeout_8',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1123',1,'']]],
  ['seconds_20on_20close_9',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1056',1,'']]],
  ['security_20and_20performance_20considerations_10',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md361',1,'']]],
  ['security_20considerations_11',['7. Security Considerations',['../group__underlying__socket__api.html#autotoc_md400',1,'']]],
  ['see_20also_12',['See Also',['../index.html#autotoc_md509',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md774',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md874',1,'See Also']]],
  ['select_13',['select',['../group__select__poll__epoll__iocp.html#autotoc_md268',1,'2. <b>Drawbacks of <span class="tt">select</span></b>'],['../group__async__io.html#autotoc_md143',1,'Custom Timeouts via <span class="tt">select()</span>'],['../group__socketopts.html#autotoc_md1043',1,'Example: Use with <span class="tt">select()</span>']]],
  ['select_20for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_14',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['select_20is_20used_15',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md266',1,'']]],
  ['select_5fpoll_5fepoll_5fiocp_2emd_16',['select_poll_epoll_iocp.md',['../select__poll__epoll__iocp_8md.html',1,'']]],
  ['semantics_17',['Timeout Semantics',['../group__tcp.html#autotoc_md861',1,'']]],
  ['send_18',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['send_20timeout_19',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1123',1,'']]],
  ['send_20write_20',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md160',1,'']]],
  ['send_3a_21',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md416',1,'']]],
  ['sendexact_22',['sendExact',['../group__internal.html#ga8826c90e1bb9e0023b75940ff4cd72f8',1,'jsocketpp::internal']]],
  ['sendexactto_23',['sendExactTo',['../group__internal.html#ga434728a067f6d58ea22b6d9c53824cd3',1,'jsocketpp::internal']]],
  ['sending_24',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md767',1,'']]],
  ['sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_25',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['serialization_20constraints_26',['📦 Serialization Constraints',['../group__udp.html#autotoc_md687',1,'']]],
  ['server_27',['Server',['../index.html#autotoc_md475',1,'📡 UDP Echo Server'],['../index.html#autotoc_md473',1,'🧵 TCP Echo Server'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1216',1,'Example: Simple Echo Server']]],
  ['server_20and_20client_28',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md585',1,'']]],
  ['server_20and_20client_20c_20af_5finet_29',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md394',1,'']]],
  ['server_20and_20client_20python_20af_5finet_30',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md393',1,'']]],
  ['server_20and_20client_3a_31',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md419',1,'']]],
  ['server_20client_20integration_20test_3a_32',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md420',1,'']]],
  ['server_20model_33',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md388',1,'']]],
  ['server_20side_34',['4.1. Server Side',['../group__sockets__theory.html#autotoc_md366',1,'']]],
  ['server_2ecpp_35',['server.cpp',['../server_8cpp.html',1,'']]],
  ['serversocket_36',['ServerSocket',['../group__socket-options.html#autotoc_md293',1,'2. TCP Sockets (<span class="tt">Socket</span>, <span class="tt">ServerSocket</span>)'],['../classjsocketpp_1_1ServerSocket.html',1,'jsocketpp::ServerSocket'],['../group__tcp.html#ga11a8bb11feaafab939278a8285afa567',1,'jsocketpp::Socket::ServerSocket()'],['../group__tcp.html#ga58290010ec759550485b8eeede8d931a',1,'jsocketpp::ServerSocket::ServerSocket()=delete'],['../group__tcp.html#gad389848c3e0fcadcfe5f581ab8c8fbb8',1,'jsocketpp::ServerSocket::ServerSocket(Port port, std::string_view localAddress={}, bool autoBindListen=true, bool reuseAddress=true, int soTimeoutMillis=-1, bool dualStack=true)'],['../group__tcp.html#gac6eeb69e3b15334e7c224edf30248fe3',1,'jsocketpp::ServerSocket::ServerSocket(const ServerSocket &amp;rhs)=delete'],['../group__tcp.html#gace3560ea1b99e15c1564e430e8848500',1,'jsocketpp::ServerSocket::ServerSocket(ServerSocket &amp;&amp;rhs) noexcept']]],
  ['serversocket_20construction_20binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_37',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['serversocket_20specific_20notes_38',['ServerSocket specific Notes',['../group__socketopts.html#autotoc_md1047',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1058',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1067',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1078',1,'⚠️ ServerSocket-specific Notes']]],
  ['serversocket_2ecpp_39',['ServerSocket.cpp',['../ServerSocket_8cpp.html',1,'']]],
  ['serversocket_2ehpp_40',['ServerSocket.hpp',['../ServerSocket_8hpp.html',1,'']]],
  ['serversocket_3a_20constructor_20does_20all_20steps_41',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['serversocket_5flifecycle_2emd_42',['ServerSocket_Lifecycle.md',['../ServerSocket__Lifecycle_8md.html',1,'']]],
  ['set_20a_203_20second_20receive_20timeout_43',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1118',1,'']]],
  ['set_20a_205_20second_20send_20timeout_44',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1123',1,'']]],
  ['set_20non_20blocking_20socket_20linux_45',['Example: Set Non-Blocking Socket (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md228',1,'']]],
  ['set_20so_5flinger_20to_20linger_20for_205_20seconds_20on_20close_46',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1056',1,'']]],
  ['setbroadcast_47',['setBroadcast',['../group__socketopts.html#gacb9e27d93d3107ad8641fa7a179658c6',1,'jsocketpp::SocketOptions']]],
  ['setdefaultinternalbuffersize_48',['setDefaultInternalBufferSize',['../group__tcp.html#gab42832248058c119c99ef60c4d72d478',1,'jsocketpp::ServerSocket']]],
  ['setdefaultreceivebuffersize_49',['setDefaultReceiveBufferSize',['../group__tcp.html#gaf644d3fccaebced95dd6bc2055bbed3e',1,'jsocketpp::ServerSocket']]],
  ['setdefaultsendbuffersize_50',['setDefaultSendBufferSize',['../group__tcp.html#gadbeecdd1d47fb8244dab210fa297fcf9',1,'jsocketpp::ServerSocket']]],
  ['setinternalbuffersize_51',['setInternalBufferSize',['../group__udp.html#ga1b017c1366655d32a2ec5d19deef9d37',1,'jsocketpp::DatagramSocket::setInternalBufferSize()'],['../group__tcp.html#ga3fb196157a1cde167c47a596c9235c91',1,'jsocketpp::Socket::setInternalBufferSize()']]],
  ['setipv6only_52',['setIPv6Only',['../group__socketopts.html#gab96d6fa640ac34113cb1f76bfbf970dc',1,'jsocketpp::SocketOptions']]],
  ['setkeepalive_53',['setKeepAlive',['../group__socketopts.html#gab3fbb8682b1313dc38abddd541ca4abf',1,'jsocketpp::SocketOptions']]],
  ['setloopbackmode_54',['setLoopbackMode',['../classjsocketpp_1_1MulticastSocket.html#ab6608be5d1aff24ad5077f6ea9a9168a',1,'jsocketpp::MulticastSocket']]],
  ['setmulticastinterface_55',['setMulticastInterface',['../classjsocketpp_1_1MulticastSocket.html#af0d5d684dcbfcf62907482ae3ac98948',1,'jsocketpp::MulticastSocket']]],
  ['setnonblocking_56',['setNonBlocking',['../group__socketopts.html#ga5f2dffc2949b06b1d945e590bce7f05b',1,'jsocketpp::SocketOptions::setNonBlocking()'],['../classjsocketpp_1_1UnixSocket.html#ab5e5db3a3b7945d5fa15507265a7c657',1,'jsocketpp::UnixSocket::setNonBlocking()']]],
  ['setoption_57',['setOption',['../group__socketopts.html#ga1b7061a0f4d13e8d33d3065b8ad4998b',1,'jsocketpp::SocketOptions::setOption(int level, int optName, int value)'],['../group__socketopts.html#ga04df6377e302cc0cedff070517021950',1,'jsocketpp::SocketOptions::setOption(int level, int optName, const void *value, socklen_t len)']]],
  ['setreceivebuffersize_58',['setReceiveBufferSize',['../group__socketopts.html#ga69fdecc0aaaef4bbd2826c448a8bbe1d',1,'jsocketpp::SocketOptions']]],
  ['setreuseaddress_59',['setReuseAddress',['../group__socketopts.html#gab358ea7ed49e95717b1e9438251b3d9a',1,'jsocketpp::SocketOptions']]],
  ['setreuseport_60',['setReusePort',['../group__socketopts.html#ga05c3ae5067a7d83965249d00c5d564c3',1,'jsocketpp::SocketOptions']]],
  ['setsendbuffersize_61',['setSendBufferSize',['../group__socketopts.html#ga8279b0c70f6a0fddf73d84aac691422b',1,'jsocketpp::SocketOptions']]],
  ['setsocketfd_62',['setSocketFd',['../group__socketopts.html#ga97706ddf21aab33a18db00bd0b8eb65d',1,'jsocketpp::SocketOptions']]],
  ['setsockopt_20getsockopt_63',['setsockopt/getsockopt',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md255',1,'']]],
  ['setsolinger_64',['setSoLinger',['../group__socketopts.html#ga707a637112e5ec1309da4e6dfe2fddb3',1,'jsocketpp::SocketOptions']]],
  ['setsorecvtimeout_65',['setSoRecvTimeout',['../group__socketopts.html#ga5ad18e598507d04059bdaff086b01721',1,'jsocketpp::SocketOptions']]],
  ['setsosendtimeout_66',['setSoSendTimeout',['../group__socketopts.html#ga7107a9da459b00bf39ec2fe4d3e83396',1,'jsocketpp::SocketOptions']]],
  ['setsotimeout_67',['setSoTimeout',['../group__socketopts.html#ga2087f337f22de16821132208b94b1441',1,'jsocketpp::ServerSocket']]],
  ['settcpnodelay_68',['setTcpNoDelay',['../group__socketopts.html#ga9839dd8837c7519a627f28b3a4c7a513',1,'jsocketpp::SocketOptions']]],
  ['settimeout_69',['setTimeout',['../classjsocketpp_1_1UnixSocket.html#a4b599e3ea9497908dbf3d7a2cc79f1c8',1,'jsocketpp::UnixSocket']]],
  ['settimetolive_70',['setTimeToLive',['../classjsocketpp_1_1MulticastSocket.html#a72172a10bc5ba13a908f31c791c90ec5',1,'jsocketpp::MulticastSocket']]],
  ['setting_71',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md1076',1,'']]],
  ['setting_20up_20real_20server_20and_20client_3a_72',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md419',1,'']]],
  ['shared_20port_20binding_73',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1202',1,'']]],
  ['shutdown_74',['shutdown',['../group__tcp.html#gaacbacf59cf8239e66c80c66a09243ec3',1,'jsocketpp::Socket']]],
  ['shutdown_20modes_75',['Shutdown Modes',['../group__tcp.html#autotoc_md971',1,'']]],
  ['shutdownmode_76',['ShutdownMode',['../namespacejsocketpp.html#a0d2868e06cd95730d5088336f8c3c174',1,'jsocketpp']]],
  ['side_77',['Side',['../group__sockets__theory.html#autotoc_md366',1,'4.1. Server Side'],['../group__sockets__theory.html#autotoc_md367',1,'4.2. Client Side']]],
  ['signature_78',['🔁 Callback Signature',['../group__tcp.html#autotoc_md850',1,'']]],
  ['simple_20client_79',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1217',1,'']]],
  ['simple_20echo_20server_80',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1216',1,'']]],
  ['simple_20server_20client_20integration_20test_3a_81',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md420',1,'']]],
  ['simple_20udp_20echo_20server_20and_20client_82',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md585',1,'']]],
  ['size_83',['size',['../group__socketopts.html#autotoc_md1065',1,'Example: Read configured receive buffer size'],['../structjsocketpp_1_1BufferView.html#ab394f54c74a9af0ca509add49c6aa229',1,'jsocketpp::BufferView::size'],['../classjsocketpp_1_1DatagramPacket.html#a56c2fe4797d236c1453be540e1fa5c6c',1,'jsocketpp::DatagramPacket::size()'],['../index.html#autotoc_md505',1,'What is the default buffer size?']]],
  ['size_20linux_84',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md216',1,'']]],
  ['smarter_20strategy_20for_20jsocketpp_85',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['so_5fexclusiveaddruse_86',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_87',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['so_5fexclusiveaddruse_20windows_20only_88',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md87',1,'']]],
  ['so_5flinger_20setting_89',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md1076',1,'']]],
  ['so_5flinger_20to_20linger_20for_205_20seconds_20on_20close_90',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1056',1,'']]],
  ['so_5freuseaddr_91',['SO_REUSEADDR',['../group__address__reuse.html#autotoc_md77',1,'<span class="tt">SO_REUSEADDR</span>'],['../group__address__reuse.html#autotoc_md121',1,'Why Not Expose Windows <span class="tt">SO_REUSEADDR</span>?']]],
  ['so_5freuseaddr_20only_3a_92',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['so_5freuseaddr_20so_5freuseport_3a_93',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['so_5freuseaddr_20vs_20so_5fexclusiveaddruse_94',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['so_5freuseaddr_3a_95',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md104',1,'']]],
  ['so_5freuseport_96',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md84',1,'']]],
  ['so_5freuseport_20unix_20linux_20only_97',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md95',1,'']]],
  ['so_5freuseport_3a_98',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['sockaddr_5fun_99',['SOCKADDR_UN',['../namespacejsocketpp.html#a981f7d65e550398e8ab29db83092f119',1,'jsocketpp']]],
  ['socket’s_20lifetime_100',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['socket_101',['SOCKET',['../namespacejsocketpp.html#ac484f9eb8a74658aa491da1d1bc15eda',1,'jsocketpp']]],
  ['socket_102',['Socket',['../group__tcp.html#autotoc_md781',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md790',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md799',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md810',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md843',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md856',1,'⚙️ Configuration of Accepted Socket'],['../group__sockets__theory.html#autotoc_md345',1,'1. What is a Socket?'],['../classjsocketpp_1_1Socket.html',1,'jsocketpp::Socket'],['../group__tcp.html#ga6da94c322a3ed5f85efd26a7fbadbe0a',1,'jsocketpp::Socket::Socket(SOCKET client, const sockaddr_storage &amp;addr, socklen_t len, std::size_t recvBufferSize=DefaultBufferSize, std::size_t sendBufferSize=DefaultBufferSize, std::size_t internalBufferSize=DefaultBufferSize, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false)'],['../group__tcp.html#gabc4e14475484e596ac62509e627a9baf',1,'jsocketpp::Socket::Socket()=delete'],['../group__tcp.html#ga201308e71110af1410e39920f02adf89',1,'jsocketpp::Socket::Socket(std::string_view host, Port port, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, bool reuseAddress=true, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool dualStack=true, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false, bool autoConnect=true, bool autoBind=false, std::string_view localAddress=&quot;&quot;, Port localPort=0)'],['../group__tcp.html#gaf5a4ddebfbca7bfe6c9a88462cc9ada8',1,'jsocketpp::Socket::Socket(const Socket &amp;rhs)=delete'],['../group__tcp.html#gad0612bda82c378dbaf99e0839f5aa815',1,'jsocketpp::Socket::Socket(Socket &amp;&amp;rhs) noexcept']]],
  ['socket_103',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1144',1,'']]],
  ['socket_20address_20families_104',['3. Socket Address Families',['../group__sockets__theory.html#autotoc_md363',1,'']]],
  ['socket_20api_105',['Socket API',['../group__underlying__socket__api.html#autotoc_md382',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md383',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md391',1,'4. Protocols and the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['socket_20api_20features_106',['Socket API Features',['../group__underlying__socket__api.html#autotoc_md395',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md405',1,'Advanced Socket API Features']]],
  ['socket_20api_20for_20unit_20tests_3a_107',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md423',1,'']]],
  ['socket_20api_20in_20action_3a_20practical_20examples_108',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md392',1,'']]],
  ['socket_20behavior_3a_109',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md415',1,'']]],
  ['socket_20binding_110',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md64',1,'']]],
  ['socket_20binding_20in_20tcp_20and_20udp_20connections_111',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['socket_20communication_112',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md390',1,'']]],
  ['socket_20creation_20and_20management_113',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['socket_20exceptions_114',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md1031',1,'']]],
  ['socket_20information_20and_20configuration_115',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['socket_20initialization_20and_20cleanup_3a_116',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md417',1,'']]],
  ['socket_20initialization_3a_20posix_20approach_117',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['socket_20ipc_118',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md479',1,'']]],
  ['socket_20is_20ipv6_20only_119',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1195',1,'']]],
  ['socket_20libraries_120',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['socket_20library_121',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['socket_20library_20for_20modern_20c_2020_122',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['socket_20lifecycle_123',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md329',1,'']]],
  ['socket_20linux_124',['Example: Set Non-Blocking Socket (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md228',1,'']]],
  ['socket_20options_125',['Socket Options',['../group__underlying__socket__api.html#autotoc_md397',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md407',1,'6.2 Socket Options'],['../group__socketopts.html',1,'Socket Options'],['../group__socket-options.html#autotoc_md286',1,'What Are Socket Options?']]],
  ['socket_20options_20in_20jsocketpp_126',['Socket Options in jsocketpp',['../group__socket-options.html',1,'']]],
  ['socket_20programming_20functions_127',['Comprehensive List of Socket Programming Functions',['../group__list__bsd__socket__functions.html',1,'']]],
  ['socket_20serversocket_128',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md293',1,'']]],
  ['socket_20state_129',['What is a Socket State?',['../group__socket__states.html#autotoc_md327',1,'']]],
  ['socket_20state_20handling_130',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md83',1,'']]],
  ['socket_20states_131',['Socket States',['../group__socket__states.html#autotoc_md330',1,'Main TCP Socket States'],['../group__socket__states.html',1,'Understanding Socket States']]],
  ['socket_20timeouts_132',['🕐 Socket Timeouts',['../group__async__io.html#autotoc_md141',1,'']]],
  ['socket_20type_133',['Socket Type',['../group__socketopts.html#autotoc_md1182',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1191',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md290',1,'Common Options by Socket Type']]],
  ['socket_20types_134',['Socket Types',['../group__socketopts.html#autotoc_md1138',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md386',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md353',1,'2.5. Comparison Table: Socket Types']]],
  ['socket_20types_20work_135',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md355',1,'']]],
  ['socket_20windows_136',['Example: Non-Blocking Socket (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md239',1,'']]],
  ['socket_2doptions_2emd_137',['socket-options.md',['../socket-options_8md.html',1,'']]],
  ['socket_2ecpp_138',['Socket.cpp',['../Socket_8cpp.html',1,'']]],
  ['socket_2ehpp_139',['Socket.hpp',['../Socket_8hpp.html',1,'']]],
  ['socket_5ferror_140',['SOCKET_ERROR',['../namespacejsocketpp.html#adc2dd9860dec2a3c3189e756288d5ba2',1,'jsocketpp']]],
  ['socket_5fgtest_2ecpp_141',['socket_gtest.cpp',['../socket__gtest_8cpp.html',1,'']]],
  ['socket_5flibrary_5fcomparison_2emd_142',['socket_library_comparison.md',['../socket__library__comparison_8md.html',1,'']]],
  ['socket_5fstates_2emd_143',['socket_states.md',['../socket__states_8md.html',1,'']]],
  ['socketerrormessage_144',['SocketErrorMessage',['../namespacejsocketpp.html#a1d0357025eb782be52907801696556ca',1,'jsocketpp']]],
  ['socketerrormessagewrap_145',['SocketErrorMessageWrap',['../namespacejsocketpp.html#a2eae999aa2ba7973dc6c3acc40e51e5a',1,'jsocketpp']]],
  ['socketexception_146',['SocketException',['../classjsocketpp_1_1SocketException.html',1,'jsocketpp::SocketException'],['../group__exceptions.html#ga05d0ab6631b95d88ca1c2c6f920c190e',1,'jsocketpp::SocketException::SocketException(const std::string &amp;message=&quot;SocketException&quot;)'],['../classjsocketpp_1_1SocketException.html#a60e8542fe737e4ab26f9f6bb99bd848e',1,'jsocketpp::SocketException::SocketException(const int code, const std::string &amp;message=&quot;SocketException&quot;)'],['../classjsocketpp_1_1SocketException.html#a04f64a2a2f336ac220c329b96d02e41a',1,'jsocketpp::SocketException::SocketException(const std::string &amp;message, std::exception_ptr nested)']]],
  ['socketexception_2ehpp_147',['SocketException.hpp',['../SocketException_8hpp.html',1,'']]],
  ['socketinitializer_148',['SocketInitializer',['../classjsocketpp_1_1SocketInitializer.html',1,'jsocketpp::SocketInitializer'],['../classjsocketpp_1_1SocketInitializer.html#a4ff790d2289ffdbef65a5cce8c06a112',1,'jsocketpp::SocketInitializer::SocketInitializer()'],['../classjsocketpp_1_1SocketInitializer.html#a6bc3398c7814e3a54c2032a021ee20eb',1,'jsocketpp::SocketInitializer::SocketInitializer(const SocketInitializer &amp;rhs)=delete']]],
  ['socketinitializer_2ehpp_149',['SocketInitializer.hpp',['../SocketInitializer_8hpp.html',1,'']]],
  ['socketoptions_150',['SocketOptions',['../classjsocketpp_1_1SocketOptions.html',1,'jsocketpp::SocketOptions'],['../group__socketopts.html#ga9e263722ea800db82c34769d8f49be3a',1,'jsocketpp::SocketOptions::SocketOptions()=delete'],['../group__socketopts.html#gab6fea2ad1b8aac819f3726ab8846527b',1,'jsocketpp::SocketOptions::SocketOptions(const SOCKET sock) noexcept'],['../group__socketopts.html#ga64de913573af3ff3cb6f40bcb71c1ba0',1,'jsocketpp::SocketOptions::SocketOptions(const SocketOptions &amp;)=delete'],['../group__socketopts.html#ga244a62ac8b74854e58066a242976793d',1,'jsocketpp::SocketOptions::SocketOptions(SocketOptions &amp;&amp;) noexcept=default']]],
  ['socketoptions_2ecpp_151',['SocketOptions.cpp',['../SocketOptions_8cpp.html',1,'']]],
  ['socketoptions_2ehpp_152',['SocketOptions.hpp',['../SocketOptions_8hpp.html',1,'']]],
  ['sockets_153',['Sockets',['../group__async__io.html#autotoc_md137',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__socket-options.html#autotoc_md291',1,'1. Options for All Sockets'],['../group__sockets__theory.html#autotoc_md350',1,'2.3. Raw Sockets'],['../group__underlying__socket__api.html#autotoc_md396',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md406',1,'6.1 Non-Blocking Sockets'],['../group__sockets__theory.html#autotoc_md358',1,'Raw Sockets'],['../group__tcp.html',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md66',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md70',1,'TCP Sockets'],['../group__udp.html',1,'UDP Sockets'],['../group__socket__binding.html#autotoc_md67',1,'UDP Sockets'],['../group__socket__binding.html#autotoc_md71',1,'UDP Sockets'],['../group__unix.html',1,'Unix Domain Sockets'],['../group__sockets__theory.html#autotoc_md359',1,'Unix Domain Sockets'],['../group__socket__states.html#autotoc_md334',1,'What About UDP and UNIX Sockets?']]],
  ['sockets_20bind_20to_20the_20same_20port_154',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['sockets_20datagramsocket_20multicastsocket_155',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md295',1,'']]],
  ['sockets_20in_20depth_156',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md347',1,'']]],
  ['sockets_20in_20jsocketpp_157',['Blocking vs Non-Blocking Sockets in jsocketpp',['../group__async__io.html',1,'']]],
  ['sockets_20local_20ipc_158',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md351',1,'']]],
  ['sockets_20operate_159',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md369',1,'']]],
  ['sockets_20socket_20serversocket_160',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md293',1,'']]],
  ['sockets_20tcp_161',['Sockets TCP',['../group__sockets__theory.html#autotoc_md348',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md356',1,'Stream Sockets (TCP)']]],
  ['sockets_20udp_162',['Sockets UDP',['../group__sockets__theory.html#autotoc_md349',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md357',1,'Datagram Sockets (UDP)']]],
  ['sockets_20unixsocket_163',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md298',1,'']]],
  ['sockets_20work_3a_20the_20lifecycle_164',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_165',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['sockets_3a_20theory_20types_20and_20platform_20apis_166',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['sockets_5ftheory_2emd_167',['sockets_theory.md',['../sockets__theory_8md.html',1,'']]],
  ['sockettimeoutexception_168',['SocketTimeoutException',['../classjsocketpp_1_1SocketTimeoutException.html',1,'jsocketpp::SocketTimeoutException'],['../classjsocketpp_1_1SocketTimeoutException.html#a83c08928ca631472282ca3b0ce3c952a',1,'jsocketpp::SocketTimeoutException::SocketTimeoutException()']]],
  ['sockettimeoutexception_2ehpp_169',['SocketTimeoutException.hpp',['../SocketTimeoutException_8hpp.html',1,'']]],
  ['specific_20apis_170',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md371',1,'']]],
  ['specific_20behavior_3a_20connect_20accept_20recv_20and_20send_171',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['specific_20considerations_172',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md402',1,'']]],
  ['specific_20interfaces_173',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['specific_20notes_174',['specific Notes',['../group__socketopts.html#autotoc_md1047',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1058',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1067',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1078',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1049',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1059',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1069',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1080',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1051',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1060',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1071',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1082',1,'🧿 UnixSocket-specific Notes']]],
  ['specific_20tests_3a_175',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md422',1,'']]],
  ['ssize_5ft_176',['ssize_t',['../namespacejsocketpp.html#af86a15acff146a3ea52fb1c09a598575',1,'jsocketpp']]],
  ['standards_177',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md529',1,'']]],
  ['start_20examples_178',['🚀 Quick Start Examples',['../index.html#autotoc_md472',1,'']]],
  ['state_179',['What is a Socket State?',['../group__socket__states.html#autotoc_md327',1,'']]],
  ['state_20handling_180',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md83',1,'']]],
  ['state_20transitions_181',['TCP State Transitions',['../group__socket__states.html#autotoc_md332',1,'']]],
  ['states_182',['States',['../group__socket__states.html#autotoc_md330',1,'Main TCP Socket States'],['../group__socket__states.html',1,'Understanding Socket States']]],
  ['step_20by_20step_20posix_20style_183',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['step_20posix_20style_184',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['steps_185',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['strategy_20for_20jsocketpp_186',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['stream_20sockets_20tcp_187',['Stream Sockets TCP',['../group__sockets__theory.html#autotoc_md348',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md356',1,'Stream Sockets (TCP)']]],
  ['stringtoaddress_188',['stringToAddress',['../group__utils.html#ga784e6ca4a095b32beb18d2378179cf0b',1,'jsocketpp']]],
  ['structure_189',['Request Code Structure',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md211',1,'']]],
  ['structure_20behavior_190',['Hints Structure Behavior',['../group__internal.html#autotoc_md550',1,'']]],
  ['stubbing_20socket_20api_20for_20unit_20tests_3a_191',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md423',1,'']]],
  ['style_192',['Style',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'<b>a) Constructor Does All (Java Default Style)</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'<b>b) Fully Step-by-Step (POSIX Style)</b>']]],
  ['style_20cross_20platform_20socket_20library_20for_20modern_20c_2020_193',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['style_20guidelines_194',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md516',1,'']]],
  ['submission_195',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['submit_20a_20pull_20request_20to_20cci_196',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['submit_20to_20the_20vcpkg_20registry_197',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md440',1,'']]],
  ['submitting_20pull_20requests_198',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md514',1,'']]],
  ['summary_199',['Summary',['../group__address__reuse.html#autotoc_md94',1,'🧠 Summary'],['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'9. Summary'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md259',1,'Windows Version Support Summary']]],
  ['summary_20by_20operation_200',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md1140',1,'']]],
  ['summary_20of_20java’s_20design_20trade_20off_201',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['summary_20table_202',['Summary Table',['../group__address__reuse.html#autotoc_md123',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md300',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md280',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md377',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md107',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md322',1,'Summary Table']]],
  ['summary_20table_3a_20waiting_20for_20readiness_203',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['support_204',['Support',['../group__socketopts.html#autotoc_md1200',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1207',1,'🔀 Platform Support'],['../index.html#autotoc_md457',1,'🔧 Platform &amp; Toolchain Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'Comprehensive Guide to &lt;tt&gt;ioctl&lt;/tt&gt;, &lt;tt&gt;fcntl&lt;/tt&gt;, &lt;tt&gt;ioctlsocket&lt;/tt&gt;, &lt;tt&gt;WSAIoctl&lt;/tt&gt;, and Related Functions: Commands, Use Cases, and Windows Support'],['../group__socket-options.html#autotoc_md288',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md872',1,'Platform Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md218',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md229',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md240',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md251',1,'Windows Support']]],
  ['support_20summary_205',['Windows Version Support Summary',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md259',1,'']]],
  ['supported_20classes_206',['Supported Classes',['../classjsocketpp_1_1SocketOptions.html#autotoc_md1034',1,'']]],
  ['supported_20inputs_207',['Supported Inputs',['../namespacejsocketpp_1_1internal.html#autotoc_md571',1,'']]],
  ['supported_20types_208',['Supported Types',['../group__tcp.html#autotoc_md935',1,'']]],
  ['syntax_209',['Syntax',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md210',1,'Syntax'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md223',1,'Syntax'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md234',1,'Syntax'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md245',1,'Syntax']]]
];
