var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md100',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md217',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md197',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md294',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md84',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md239',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md270',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['tcp_4',['TCP',['../group__sockets__theory.html#autotoc_md265',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md273',1,'Stream Sockets (TCP)']]],
  ['tcp_20echo_20server_5',['🧵 TCP Echo Server',['../index.html#autotoc_md390',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_6',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['tcp_20socket_20lifecycle_7',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md246',1,'']]],
  ['tcp_20socket_20states_8',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['tcp_20sockets_9',['TCP Sockets',['../group__tcp.html',1,'']]],
  ['tcp_20sockets_20socket_20serversocket_10',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['tcp_20state_20transitions_11',['TCP State Transitions',['../group__socket__states.html#autotoc_md249',1,'']]],
  ['test_12',['TEST',['../socket__gtest_8cpp.html#af84a2f63791f9b4fd5ee14e6161ce2d9',1,'TEST(SocketTest, TcpConnectInvalid):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a385a2ab183d5626e9f7de45a6ff70e64',1,'TEST(SocketTest, TcpBindInvalidPort):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a88c3e6586ac2476e33803ecc48b48541',1,'TEST(SocketTest, UnixSocketInvalidPath):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aadbb6137575fbeb33208cb9f555b3a3d',1,'TEST(SocketTest, TcpConnectTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aac9350146074ace6dd63823149af8925',1,'TEST(SocketTest, TcpNonBlocking):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ae2a55900b16067f9197259a155c13835',1,'TEST(SocketTest, TcpSetGetOption):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ac6fe24ab1fa2e3fbf0d3d42e8c9247a6',1,'TEST(SocketTest, UdpSendRecvLoopback):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a013ef3192376c90badc588e9c69af993',1,'TEST(SocketTest, UdpTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a80cc9752601e3ded34d6d8e152b1737f',1,'TEST(SocketTest, UnixSocketBindConnect):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a7d49aecf9ef526bad3e69b943660ae73',1,'TEST(SocketTest, UnixSocketTimeoutAndNonBlocking):&#160;socket_gtest.cpp']]],
  ['test_20and_20usage_20guide_13',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['test_20cases_20to_20consider_3a_14',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_15',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['test_20the_20port_20locally_16',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md355',1,'']]],
  ['test_20the_20recipe_20locally_17',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md168',1,'']]],
  ['test_20with_20mocking_3a_18',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['test_3a_19',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['test_5ferror_5fhandling_20',['test_error_handling',['../client_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;client.cpp'],['../server_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;server.cpp']]],
  ['test_5fpackage_21',['test_package',['../group__conan__publish__guide.html#autotoc_md171',1,'']]],
  ['test_5ftcp_22',['test_tcp',['../client_8cpp.html#a5c06bbffe96672a267fdf7a58d39b8c9',1,'test_tcp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a1de353166d8a8c39d1ecad7d6616e681',1,'test_tcp(const string &amp;ip, const Port port):&#160;client.cpp'],['../server_8cpp.html#a8348483da59fb305dfc63392f54bef3f',1,'test_tcp(const Port port):&#160;server.cpp']]],
  ['test_5fudp_23',['test_udp',['../client_8cpp.html#a42c921ec1646212ba1214248e51075cc',1,'test_udp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a8b01747ac0288562f1f5b721300bd338',1,'test_udp(const string &amp;ip, Port port):&#160;client.cpp'],['../server_8cpp.html#ad783a901702495179902ed7bf93f8178',1,'test_udp(const Port port):&#160;server.cpp']]],
  ['test_5funix_24',['test_unix',['../client_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;client.cpp'],['../client_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;client.cpp'],['../server_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;server.cpp'],['../server_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;server.cpp']]],
  ['testing_25',['Testing',['../index.html#autotoc_md402',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md437',1,'5. Testing']]],
  ['testing_20and_20integration_20guide_26',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['testing_20in_20c_2020_3a_27',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_28',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['tests_29',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_30',['Tests:',['../group__unit__tests.html#autotoc_md330',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md335',1,'2. <b>Integration Tests</b>:'],['../group__unit__tests.html#autotoc_md339',1,'3.1 <b>Using CMake for Platform-Specific Tests</b>:'],['../group__unit__tests.html#autotoc_md340',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['the_20actual_20receive_20buffer_20size_20used_20for_20a_20unix_20socket_31',['Example: Read the actual receive buffer size used for a Unix socket',['../group__socketopts.html#autotoc_md626',1,'']]],
  ['the_20basics_32',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['the_20conan_20center_20index_20cci_33',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['the_20configured_20receive_20buffer_20size_34',['Example: Read the configured receive buffer size',['../group__socketopts.html#autotoc_md618',1,'']]],
  ['the_20constructor_35',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['the_20default_20buffer_20size_36',['What is the default buffer size?',['../index.html#autotoc_md422',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_37',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_38',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_39',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['the_20library_40',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_41',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'']]],
  ['the_20makefile_42',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20port_20in_20the_20constructor_43',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['the_20port_20locally_44',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md355',1,'']]],
  ['the_20recipe_20locally_45',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md168',1,'']]],
  ['the_20same_20port_46',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['the_20socket_20api_47',['the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md300',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md308',1,'4. Protocols and the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['the_20vcpkg_20registry_48',['the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['theory_20types_20and_20platform_20apis_49',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['this_20is_20problematic_20on_20windows_50',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['this_20library_51',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md229',1,'']]],
  ['this_20relates_20to_20jsocketpp_52',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md255',1,'']]],
  ['thoughts_20and_20best_20practices_53',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md146',1,'']]],
  ['thread_20safety_54',['Thread Safety',['../group__tcp.html#autotoc_md483',1,'Thread Safety'],['../group__tcp.html#autotoc_md486',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md492',1,'Thread Safety'],['../group__tcp.html#autotoc_md513',1,'Thread Safety']]],
  ['timeout_20for_20receiving_55',['Example: Get current timeout for receiving',['../group__socketopts.html#autotoc_md623',1,'']]],
  ['timeout_20semantics_56',['Timeout Semantics',['../group__tcp.html#autotoc_md485',1,'']]],
  ['timeouts_57',['Timeouts',['../group__async__io.html#autotoc_md122',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md118',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md119',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_58',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md120',1,'']]],
  ['tips_20and_20best_20practices_59',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices']]],
  ['to_20adjust_60',['When to Adjust',['../group__core.html#autotoc_md459',1,'']]],
  ['to_20all_20interfaces”_20mean_61',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['to_20all_20interfaces_62',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['to_20all_20interfaces_20vs_20specific_20interfaces_63',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['to_20cci_64',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['to_20consider_3a_65',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['to_20jsocketpp_66',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md255',1,'How This Relates to <span class="tt">jsocketpp</span>']]],
  ['to_20mock_20recv_20and_20send_3a_67',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['to_20peer_20model_68',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md306',1,'']]],
  ['to_20provide_20poll_20and_20epoll_20as_20alternatives_69',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['to_20the_20conan_20center_20index_20cci_70',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['to_20the_20same_20port_71',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['to_20the_20socket_20api_72',['to the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['to_20the_20vcpkg_20registry_73',['to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['to_20use_74',['When to Use',['../group__socketopts.html#autotoc_md651',1,'']]],
  ['toiovec_75',['toIOVec',['../group__internal.html#ga7701a273337a71485ba1583df464b178',1,'jsocketpp::internal::toIOVec(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#gacdd48d04c87ec69aff97c5d29dbfe1a1',1,'jsocketpp::internal::toIOVec(const std::span&lt; const BufferView &gt; buffers)']]],
  ['tonetwork_76',['toNetwork',['../namespacejsocketpp_1_1net.html#a30e0ea56a20c62070f079482d8cabfa5',1,'jsocketpp::net::toNetwork(const uint16_t val)'],['../namespacejsocketpp_1_1net.html#a933367ad91e111a4e6516e67d6e08c9a',1,'jsocketpp::net::toNetwork(const uint32_t val)']]],
  ['toolchain_20support_77',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md374',1,'']]],
  ['tooling_78',['🛠 Developer Tooling',['../index.html#autotoc_md404',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_79',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['topics_80',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md292',1,'']]],
  ['towsabuf_81',['toWSABUF',['../group__internal.html#gae140ce724d1cfc733f3c2dbccf0cf60b',1,'jsocketpp::internal::toWSABUF(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#ga53db0a38699800e21866a0ded1b433ba',1,'jsocketpp::internal::toWSABUF(const std::span&lt; const BufferView &gt; buffers)']]],
  ['trade_20off_82',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_83',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['transitions_84',['TCP State Transitions',['../group__socket__states.html#autotoc_md249',1,'']]],
  ['troubleshooting_85',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['true_20matters_86',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md487',1,'']]],
  ['tryaccept_87',['tryAccept',['../group__tcp.html#ga91177064cad7d0c7f1fc63c4e1f34187',1,'jsocketpp::ServerSocket::tryAccept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt) const'],['../group__tcp.html#gaf6adb31c07e64787f2fcf17602619868',1,'jsocketpp::ServerSocket::tryAccept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt) const']]],
  ['type_88',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['types_89',['Types',['../group__underlying__socket__api.html#autotoc_md303',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md270',1,'2.5. Comparison Table: Socket Types'],['../group__core.html',1,'Core Utilities and Types'],['../group__tcp.html#autotoc_md511',1,'Supported Types']]],
  ['types_20and_20platform_20apis_90',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['types_20of_20sockets_20in_20depth_91',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['types_20work_92',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['typical_20usage_93',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md478',1,'']]],
  ['typical_20usage_20example_94',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md489',1,'']]],
  ['typical_20use_20cases_95',['🧰 Typical Use Cases',['../index.html#autotoc_md368',1,'']]]
];
