var searchData=
[
  ['java’s_20approach_20and_20its_20limitations_0',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md127',1,'']]],
  ['java’s_20design_20trade_20off_1',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['java_20↔_20jsocketpp_20class_20mapping_2',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md540',1,'']]],
  ['java_20comparison_3',['📚 Java Comparison',['../group__async__io.html#autotoc_md184',1,'']]],
  ['java_20default_20style_4',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md69',1,'']]],
  ['java_20does_5',['What Java Does',['../group__address__reuse.html#autotoc_md128',1,'']]],
  ['java_20serversocket_3a_20constructor_20does_20all_20steps_6',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md58',1,'']]],
  ['java_20style_20cross_20platform_20socket_20library_20for_20modern_20c_2020_7',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['java_3a_8',['Java:',['../group__async__io.html#autotoc_md170',1,'Java:'],['../group__async__io.html#autotoc_md174',1,'Java:']]],
  ['joingroup_9',['joinGroup',['../group__udp.html#ga7937b05ccae7d059b4fcfa4b6383c75c',1,'jsocketpp::MulticastSocket']]],
  ['joingroupipv4_10',['joinGroupIPv4',['../group__socketopts.html#ga65375075d5e7b8009730e0d28b199d73',1,'jsocketpp::SocketOptions']]],
  ['joingroupipv6_11',['joinGroupIPv6',['../group__socketopts.html#ga26253ae313b6ef1417af775668ffbf24',1,'jsocketpp::SocketOptions']]],
  ['jsocketpp_12',['jsocketpp',['../group__address__reuse.html#autotoc_md135',1,'✅ Smarter Strategy for jsocketpp'],['../index.html#autotoc_md512',1,'💡 Why jsocketpp?'],['../group__async__io.html',1,'Blocking vs Non-Blocking Sockets in jsocketpp'],['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md397',1,'How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;'],['../namespacejsocketpp.html',1,'jsocketpp'],['../group__socket-options.html',1,'Socket Options in jsocketpp']]],
  ['jsocketpp_20_3a_13',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md123',1,'']]],
  ['jsocketpp_20api_20notes_14',['jsocketpp API Notes',['../group__bind__interfaces.html#autotoc_md198',1,'']]],
  ['jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_15',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['jsocketpp_20async_16',['Is jsocketpp async?',['../index.html#autotoc_md556',1,'']]],
  ['jsocketpp_20class_20mapping_17',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md540',1,'']]],
  ['jsocketpp_20does_18',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['jsocketpp_20gets_20right_19',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md148',1,'']]],
  ['jsocketpp_20handles_20blocking_20and_20timeouts_20',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md163',1,'']]],
  ['jsocketpp_20hybrid_21',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md71',1,'']]],
  ['jsocketpp_20in_20production_22',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['jsocketpp_20this_20library_23',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md371',1,'']]],
  ['jsocketpp_20to_20the_20conan_20center_20index_20cci_24',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['jsocketpp_20to_20the_20vcpkg_20registry_25',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the vcpkg Registry',['../group__vcpkg__publish__guide.html',1,'']]],
  ['jsocketpp_20vs_20boost_20asio_26',['🔁 jsocketpp vs Boost.Asio',['../index.html#autotoc_md518',1,'']]],
  ['jsocketpp_20vs_20other_20c_20socket_20libraries_27',['Comparison: &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; vs Other C++ Socket Libraries',['../group__socket__library__comparison.html',1,'']]],
  ['jsocketpp_3a_20build_20test_20and_20usage_20guide_28',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['jsocketpp_3a_20c_2020_20cross_20platform_20socket_20library_29',['jsocketpp: C++20 cross-platform socket library',['../group__jsocketpp.html',1,'']]],
  ['jsocketpp_3a_20java_20style_20cross_20platform_20socket_20library_20for_20modern_20c_2020_30',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['jsocketpp_3a_3adetail_31',['detail',['../namespacejsocketpp_1_1detail.html',1,'jsocketpp']]],
  ['jsocketpp_3a_3ainternal_32',['internal',['../namespacejsocketpp_1_1internal.html',1,'jsocketpp']]],
  ['jsocketpp_3a_3anet_33',['net',['../namespacejsocketpp_1_1net.html',1,'jsocketpp']]],
  ['json_34',['Example &lt;span class=&quot;tt&quot;&gt;vcpkg.json&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md494',1,'']]]
];
