var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md123',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md240',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md220',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md317',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md107',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md262',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md224',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md293',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['tcp_4',['TCP',['../group__sockets__theory.html#autotoc_md288',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md296',1,'Stream Sockets (TCP)']]],
  ['tcp_20and_20udp_5',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['tcp_20and_20udp_20connections_6',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['tcp_20echo_20server_7',['🧵 TCP Echo Server',['../index.html#autotoc_md413',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_8',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md333',1,'']]],
  ['tcp_20socket_20lifecycle_9',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md269',1,'']]],
  ['tcp_20socket_20states_10',['Main TCP Socket States',['../group__socket__states.html#autotoc_md270',1,'']]],
  ['tcp_20sockets_11',['TCP Sockets',['../group__tcp.html',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md66',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md70',1,'TCP Sockets']]],
  ['tcp_20sockets_20socket_20serversocket_12',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md233',1,'']]],
  ['tcp_20state_20transitions_13',['TCP State Transitions',['../group__socket__states.html#autotoc_md272',1,'']]],
  ['test_14',['TEST',['../socket__gtest_8cpp.html#af84a2f63791f9b4fd5ee14e6161ce2d9',1,'TEST(SocketTest, TcpConnectInvalid):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a385a2ab183d5626e9f7de45a6ff70e64',1,'TEST(SocketTest, TcpBindInvalidPort):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a88c3e6586ac2476e33803ecc48b48541',1,'TEST(SocketTest, UnixSocketInvalidPath):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aadbb6137575fbeb33208cb9f555b3a3d',1,'TEST(SocketTest, TcpConnectTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#aac9350146074ace6dd63823149af8925',1,'TEST(SocketTest, TcpNonBlocking):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ae2a55900b16067f9197259a155c13835',1,'TEST(SocketTest, TcpSetGetOption):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#ac6fe24ab1fa2e3fbf0d3d42e8c9247a6',1,'TEST(SocketTest, UdpSendRecvLoopback):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a013ef3192376c90badc588e9c69af993',1,'TEST(SocketTest, UdpTimeout):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a80cc9752601e3ded34d6d8e152b1737f',1,'TEST(SocketTest, UnixSocketBindConnect):&#160;socket_gtest.cpp'],['../socket__gtest_8cpp.html#a7d49aecf9ef526bad3e69b943660ae73',1,'TEST(SocketTest, UnixSocketTimeoutAndNonBlocking):&#160;socket_gtest.cpp']]],
  ['test_20and_20usage_20guide_15',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['test_20cases_20to_20consider_3a_16',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md366',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_17',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md361',1,'']]],
  ['test_20the_20port_20locally_18',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md378',1,'']]],
  ['test_20the_20recipe_20locally_19',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['test_20with_20mocking_3a_20',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md365',1,'']]],
  ['test_3a_21',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md360',1,'']]],
  ['test_5ferror_5fhandling_22',['test_error_handling',['../client_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;client.cpp'],['../server_8cpp.html#a61749f92d7d24b6244ff5d301f889197',1,'test_error_handling():&#160;server.cpp']]],
  ['test_5fpackage_23',['test_package',['../group__conan__publish__guide.html#autotoc_md194',1,'']]],
  ['test_5ftcp_24',['test_tcp',['../client_8cpp.html#a5c06bbffe96672a267fdf7a58d39b8c9',1,'test_tcp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a1de353166d8a8c39d1ecad7d6616e681',1,'test_tcp(const string &amp;ip, const Port port):&#160;client.cpp'],['../server_8cpp.html#a8348483da59fb305dfc63392f54bef3f',1,'test_tcp(const Port port):&#160;server.cpp']]],
  ['test_5fudp_25',['test_udp',['../client_8cpp.html#a42c921ec1646212ba1214248e51075cc',1,'test_udp(const std::string &amp;ip, Port port):&#160;client.cpp'],['../client_8cpp.html#a8b01747ac0288562f1f5b721300bd338',1,'test_udp(const string &amp;ip, Port port):&#160;client.cpp'],['../server_8cpp.html#ad783a901702495179902ed7bf93f8178',1,'test_udp(const Port port):&#160;server.cpp']]],
  ['test_5funix_26',['test_unix',['../client_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;client.cpp'],['../client_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;client.cpp'],['../server_8cpp.html#a79ce93ece9993ed95743932c99227de8',1,'test_unix(const std::string &amp;path):&#160;server.cpp'],['../server_8cpp.html#a4857915d0f2802d2b82b314ff594f2b0',1,'test_unix(const string &amp;path):&#160;server.cpp']]],
  ['testing_27',['Testing',['../index.html#autotoc_md425',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md460',1,'5. Testing']]],
  ['testing_20and_20integration_20guide_28',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['testing_20in_20c_2020_3a_29',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md354',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_30',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md357',1,'']]],
  ['tests_31',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_32',['Tests:',['../group__unit__tests.html#autotoc_md353',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md358',1,'2. <b>Integration Tests</b>:'],['../group__unit__tests.html#autotoc_md362',1,'3.1 <b>Using CMake for Platform-Specific Tests</b>:'],['../group__unit__tests.html#autotoc_md363',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['the_20basics_33',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['the_20conan_20center_20index_20cci_34',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['the_20connect_20function_35',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20constructor_36',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20default_20buffer_20size_37',['What is the default buffer size?',['../index.html#autotoc_md445',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_38',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_39',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md309',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_40',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['the_20library_41',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_42',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md305',1,'']]],
  ['the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_43',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20makefile_44',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20mtu_45',['🔍 What is the MTU?',['../group__udp.html#autotoc_md647',1,'']]],
  ['the_20port_20in_20the_20constructor_46',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20port_20locally_47',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md378',1,'']]],
  ['the_20recipe_20locally_48',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['the_20role_20of_20the_20connect_20function_49',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20same_20port_50',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['the_20socket’s_20lifetime_51',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20socket_20api_52',['the Socket API',['../group__underlying__socket__api.html#autotoc_md322',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md323',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md331',1,'4. Protocols and the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['the_20vcpkg_20registry_53',['the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md380',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['theory_20types_20and_20platform_20apis_54',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['this_20is_20problematic_20on_20windows_55',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['this_20library_56',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md252',1,'']]],
  ['this_20matters_57',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md509',1,'']]],
  ['this_20relates_20to_20jsocketpp_58',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md278',1,'']]],
  ['thoughts_20and_20best_20practices_59',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md169',1,'']]],
  ['thread_20safety_60',['Thread Safety',['../group__tcp.html#autotoc_md711',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md720',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md729',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md742',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md751',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md767',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md780',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md705',1,'Thread Safety'],['../group__tcp.html#autotoc_md790',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md799',1,'Thread Safety'],['../group__tcp.html#autotoc_md865',1,'Thread Safety']]],
  ['throws_61',['Throws',['../group__internal.html#autotoc_md496',1,'Throws'],['../group__udp.html#autotoc_md544',1,'Throws']]],
  ['timeout_62',['timeout',['../group__socketopts.html#autotoc_md1046',1,'Example: Set a 3-second receive timeout'],['../group__socketopts.html#autotoc_md1051',1,'Example: Set a 5-second send timeout']]],
  ['timeout_20behavior_63',['Timeout Behavior',['../group__tcp.html#autotoc_md707',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md716',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md725',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md736',1,'⏱ Timeout Behavior']]],
  ['timeout_20handling_64',['⏱ Timeout Handling',['../group__udp.html#autotoc_md566',1,'']]],
  ['timeout_20semantics_65',['Timeout Semantics',['../group__tcp.html#autotoc_md789',1,'']]],
  ['timeouts_66',['Timeouts',['../group__async__io.html#autotoc_md145',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md141',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md142',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_67',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md143',1,'']]],
  ['tips_20and_20best_20practices_68',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md384',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices']]],
  ['to_69',['Applies to',['../group__core.html#autotoc_md480',1,'']]],
  ['to_20a_20local_20address_70',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['to_20adjust_71',['When to Adjust',['../group__core.html#autotoc_md483',1,'']]],
  ['to_20all_20interfaces”_20mean_72',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['to_20all_20interfaces_73',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['to_20all_20interfaces_20vs_20specific_20interfaces_74',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['to_20cci_75',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['to_20consider_3a_76',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md366',1,'']]],
  ['to_20jsocketpp_77',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md278',1,'How This Relates to <span class="tt">jsocketpp</span>']]],
  ['to_20linger_20for_205_20seconds_20on_20close_78',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md984',1,'']]],
  ['to_20mock_20recv_20and_20send_3a_79',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md356',1,'']]],
  ['to_20peer_20model_80',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md329',1,'']]],
  ['to_20provide_20poll_20and_20epoll_20as_20alternatives_81',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['to_20reduce_20latency_82',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1086',1,'']]],
  ['to_20the_20conan_20center_20index_20cci_83',['Publishing &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; to the Conan Center Index (CCI)',['../group__conan__publish__guide.html',1,'']]],
  ['to_20the_20same_20port_84',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['to_20the_20socket_20api_85',['to the Socket API',['../group__underlying__socket__api.html#autotoc_md322',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html',1,'Comprehensive Guide to the Socket API']]],
  ['to_20the_20vcpkg_20registry_86',['to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md380',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html',1,'Publishing &lt;tt&gt;jsocketpp&lt;/tt&gt; to the vcpkg Registry']]],
  ['to_20use_87',['When to Use',['../group__socketopts.html#autotoc_md1139',1,'']]],
  ['toiovec_88',['toIOVec',['../group__internal.html#ga7701a273337a71485ba1583df464b178',1,'jsocketpp::internal::toIOVec(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#gacdd48d04c87ec69aff97c5d29dbfe1a1',1,'jsocketpp::internal::toIOVec(const std::span&lt; const BufferView &gt; buffers)']]],
  ['tonetwork_89',['toNetwork',['../namespacejsocketpp_1_1net.html#a30e0ea56a20c62070f079482d8cabfa5',1,'jsocketpp::net::toNetwork(const uint16_t val)'],['../namespacejsocketpp_1_1net.html#a933367ad91e111a4e6516e67d6e08c9a',1,'jsocketpp::net::toNetwork(const uint32_t val)']]],
  ['toolchain_20support_90',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md397',1,'']]],
  ['tooling_91',['🛠 Developer Tooling',['../index.html#autotoc_md427',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_92',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md354',1,'']]],
  ['topics_93',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md315',1,'']]],
  ['towsabuf_94',['toWSABUF',['../group__internal.html#gae140ce724d1cfc733f3c2dbccf0cf60b',1,'jsocketpp::internal::toWSABUF(const BufferView *buffers, const std::size_t count)'],['../group__internal.html#ga53db0a38699800e21866a0ded1b433ba',1,'jsocketpp::internal::toWSABUF(const std::span&lt; const BufferView &gt; buffers)']]],
  ['trade_20off_95',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_96',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['transfer_97',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['transferred_98',['Transferred',['../group__udp.html#autotoc_md549',1,'Ownership Transferred'],['../group__udp.html#autotoc_md547',1,'What Is Transferred']]],
  ['transitions_99',['TCP State Transitions',['../group__socket__states.html#autotoc_md272',1,'']]],
  ['troubleshooting_100',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['true_101',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md817',1,'']]],
  ['true_20matters_102',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md794',1,'']]],
  ['tryaccept_103',['tryAccept',['../group__tcp.html#ga6eff2e5c775318cfd2813ee72e716571',1,'jsocketpp::ServerSocket::tryAccept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#ga93a186b3fcb925c3a6c30f1c5d5bf8a8',1,'jsocketpp::ServerSocket::tryAccept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const']]],
  ['type_104',['Type',['../group__socketopts.html#autotoc_md1110',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1119',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md230',1,'Common Options by Socket Type']]],
  ['types_105',['Types',['../group__socketopts.html#autotoc_md1066',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md326',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md293',1,'2.5. Comparison Table: Socket Types'],['../group__core.html',1,'Core Utilities and Types'],['../group__tcp.html#autotoc_md863',1,'Supported Types']]],
  ['types_20and_20platform_20apis_106',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['types_20of_20sockets_20in_20depth_107',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md287',1,'']]],
  ['types_20work_108',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['typical_20usage_109',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md699',1,'']]],
  ['typical_20usage_20example_110',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md796',1,'']]],
  ['typical_20use_20cases_111',['🧰 Typical Use Cases',['../index.html#autotoc_md391',1,'']]]
];
