var searchData=
[
  ['macos_20unix_0',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md301',1,'']]],
  ['main_1',['main',['../client_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4',1,'main():&#160;client.cpp'],['../server_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4',1,'main():&#160;server.cpp']]],
  ['main_20features_2',['Main Features',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1103',1,'']]],
  ['main_20tcp_20socket_20states_3',['Main TCP Socket States',['../group__socket__states.html#autotoc_md259',1,'']]],
  ['make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_4',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['make_20your_20cmake_20project_20conan_20friendly_5',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md178',1,'']]],
  ['makefile_6',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['management_7',['Resource Management',['../group__tcp.html#autotoc_md858',1,'']]],
  ['manual_20cmake_20build_8',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['manual_20compilation_9',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['manual_20integration_10',['🔧 Manual Integration',['../index.html#autotoc_md399',1,'']]],
  ['manual_20nesting_11',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md920',1,'']]],
  ['mapped_20ipv6_20behavior_12',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md785',1,'']]],
  ['mapping_13',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md410',1,'']]],
  ['matters_14',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md754',1,'']]],
  ['mean_15',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md163',1,'']]],
  ['methods_16',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md231',1,'']]],
  ['methods_20vs_20generic_20methods_17',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md231',1,'']]],
  ['misconceptions_20and_20caveats_18',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['mock_20example_20with_20google_20mock_3a_19',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md353',1,'']]],
  ['mock_20recv_20and_20send_3a_20',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md345',1,'']]],
  ['mock_20to_20mock_20recv_20and_20send_3a_21',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md345',1,'']]],
  ['mock_3a_22',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md353',1,'']]],
  ['mocking_20or_20stubbing_20socket_20api_20for_20unit_20tests_3a_23',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md352',1,'']]],
  ['mocking_20socket_20behavior_3a_24',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md344',1,'']]],
  ['mocking_3a_25',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md354',1,'']]],
  ['mode_26',['Mode',['../group__udp.html#autotoc_md567',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md574',1,'🔁 Behavior by Mode'],['../group__udp.html#autotoc_md581',1,'Behavior by Connection Mode'],['../group__udp.html#autotoc_md571',1,'Example (Unconnected Mode)']]],
  ['mode_20on_20a_20client_20socket_27',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1032',1,'']]],
  ['mode_3a_28',['mode:',['../group__async__io.html#autotoc_md139',1,'Blocking mode:'],['../group__async__io.html#autotoc_md143',1,'Blocking mode:'],['../group__async__io.html#autotoc_md147',1,'Blocking mode:'],['../group__async__io.html#autotoc_md150',1,'Blocking mode:'],['../group__async__io.html#autotoc_md140',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md144',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md148',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md151',1,'Non-blocking mode:']]],
  ['model_29',['Model',['../group__underlying__socket__api.html#autotoc_md317',1,'3.1 Client-Server Model'],['../group__underlying__socket__api.html#autotoc_md318',1,'3.2 Peer-to-Peer Model']]],
  ['models_30',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md316',1,'']]],
  ['modern_20c_2020_31',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['modes_32',['Modes',['../group__udp.html#autotoc_md495',1,'🔁 Connection Modes'],['../group__udp.html#autotoc_md607',1,'🔁 Connection Modes'],['../group__tcp.html#autotoc_md817',1,'Connection Modes'],['../group__tcp.html#autotoc_md859',1,'Shutdown Modes'],['../group__udp.html#autotoc_md517',1,'Usage Modes']]],
  ['modes_20of_20operation_33',['Modes of Operation',['../group__tcp.html#autotoc_md899',1,'']]],
  ['module_34',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md247',1,'']]],
  ['more_20resources_35',['More Resources',['../group__socket__states.html#autotoc_md269',1,'']]],
  ['move_20assignment_36',['Example: Move assignment',['../group__socketopts.html#autotoc_md1100',1,'']]],
  ['multicast_37',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md653',1,'']]],
  ['multicast_20and_20broadcast_38',['Multicast and Broadcast',['../group__underlying__socket__api.html#autotoc_md327',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md337',1,'6.3 Multicast and Broadcast']]],
  ['multicast_20receiver_39',['🌐 Multicast Receiver',['../index.html#autotoc_md406',1,'']]],
  ['multicast_3a_40',['For Multicast:',['../group__socket-options.html#autotoc_md225',1,'']]],
  ['multicastsocket_41',['MulticastSocket',['../group__socket-options.html#autotoc_md224',1,'3. UDP Sockets (<span class="tt">DatagramSocket</span>, <span class="tt">MulticastSocket</span>)'],['../classjsocketpp_1_1MulticastSocket.html',1,'jsocketpp::MulticastSocket'],['../group__udp.html#ga379ff0e20d62b5f0c815d48614597005',1,'jsocketpp::MulticastSocket::MulticastSocket()=delete'],['../classjsocketpp_1_1MulticastSocket.html#a4671cefd5b0b7f7e936b0d436c6fd308',1,'jsocketpp::MulticastSocket::MulticastSocket(Port port=0, std::size_t bufferSize=2048)']]],
  ['multicastsocket_2ecpp_42',['MulticastSocket.cpp',['../MulticastSocket_8cpp.html',1,'']]],
  ['multicastsocket_2ehpp_43',['MulticastSocket.hpp',['../MulticastSocket_8hpp.html',1,'']]],
  ['multiple_20sockets_20bind_20to_20the_20same_20port_44',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md86',1,'']]]
];
