var searchData=
[
  ['macos_20unix_0',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md372',1,'']]],
  ['main_1',['main',['../client_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4',1,'main():&#160;client.cpp'],['../server_8cpp.html#ae66f6b31b5ad750f1fe042a706a4e3d4',1,'main():&#160;server.cpp']]],
  ['main_20features_2',['Main Features',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1215',1,'']]],
  ['main_20tcp_20socket_20states_3',['Main TCP Socket States',['../group__socket__states.html#autotoc_md330',1,'']]],
  ['make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_4',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['make_20your_20cmake_20project_20conan_20friendly_5',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['makefile_6',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['management_7',['Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'1. Core Socket Creation and Management'],['../group__tcp.html#autotoc_md970',1,'Resource Management']]],
  ['manual_20cmake_20build_8',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['manual_20compilation_9',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['manual_20integration_10',['🔧 Manual Integration',['../index.html#autotoc_md470',1,'']]],
  ['manual_20nesting_11',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md1032',1,'']]],
  ['mapped_20ipv6_20behavior_12',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md897',1,'']]],
  ['mapping_13',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md481',1,'']]],
  ['matters_14',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md569',1,'']]],
  ['matters_15',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md866',1,'']]],
  ['mean_16',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['mechanism_17',['🔧 Internal Mechanism',['../group__internal.html#autotoc_md562',1,'']]],
  ['methods_18',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md302',1,'']]],
  ['methods_20vs_20generic_20methods_19',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md302',1,'']]],
  ['miscellaneous_20',['7. Miscellaneous',['../group__list__bsd__socket__functions.html#autotoc_md32',1,'']]],
  ['misconceptions_20and_20caveats_21',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['mock_20example_20with_20google_20mock_3a_22',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['mock_20recv_20and_20send_3a_23',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md416',1,'']]],
  ['mock_20to_20mock_20recv_20and_20send_3a_24',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md416',1,'']]],
  ['mock_3a_25',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['mocking_20or_20stubbing_20socket_20api_20for_20unit_20tests_3a_26',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md423',1,'']]],
  ['mocking_20socket_20behavior_3a_27',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md415',1,'']]],
  ['mocking_3a_28',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md425',1,'']]],
  ['mode_29',['Mode',['../group__udp.html#autotoc_md659',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md673',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md666',1,'🔁 Behavior Based on Mode'],['../group__udp.html#autotoc_md741',1,'🔁 Behavior Based on Mode'],['../group__udp.html#autotoc_md663',1,'Example (Unconnected Mode)'],['../group__udp.html#autotoc_md670',1,'Example (Unconnected Mode)'],['../group__udp.html#autotoc_md677',1,'Example (Unconnected Mode)']]],
  ['mode_20on_20a_20client_20socket_30',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1144',1,'']]],
  ['mode_3a_31',['mode:',['../group__async__io.html#autotoc_md150',1,'Blocking mode:'],['../group__async__io.html#autotoc_md154',1,'Blocking mode:'],['../group__async__io.html#autotoc_md158',1,'Blocking mode:'],['../group__async__io.html#autotoc_md161',1,'Blocking mode:'],['../group__async__io.html#autotoc_md151',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md155',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md159',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md162',1,'Non-blocking mode:']]],
  ['model_32',['Model',['../group__underlying__socket__api.html#autotoc_md388',1,'3.1 Client-Server Model'],['../group__underlying__socket__api.html#autotoc_md389',1,'3.2 Peer-to-Peer Model']]],
  ['models_33',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md387',1,'']]],
  ['modern_20c_2020_34',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['modes_35',['Modes',['../group__udp.html#autotoc_md588',1,'🔁 Connection Modes'],['../group__udp.html#autotoc_md697',1,'🔁 Connection Modes'],['../group__tcp.html#autotoc_md929',1,'Connection Modes'],['../group__tcp.html#autotoc_md971',1,'Shutdown Modes'],['../group__udp.html#autotoc_md609',1,'Usage Modes']]],
  ['modes_20of_20operation_36',['Modes of Operation',['../group__tcp.html#autotoc_md1011',1,'']]],
  ['module_37',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md318',1,'']]],
  ['more_20resources_38',['More Resources',['../group__socket__states.html#autotoc_md340',1,'']]],
  ['move_20assignment_39',['Example: Move assignment',['../group__socketopts.html#autotoc_md1212',1,'']]],
  ['mtu_40',['🔍 What is the MTU?',['../group__udp.html#autotoc_md714',1,'']]],
  ['multicast_41',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md765',1,'']]],
  ['multicast_20and_20broadcast_42',['Multicast and Broadcast',['../group__underlying__socket__api.html#autotoc_md398',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md408',1,'6.3 Multicast and Broadcast']]],
  ['multicast_20receiver_43',['🌐 Multicast Receiver',['../index.html#autotoc_md477',1,'']]],
  ['multicast_3a_44',['For Multicast:',['../group__socket-options.html#autotoc_md296',1,'']]],
  ['multicastsocket_45',['MulticastSocket',['../group__socket-options.html#autotoc_md295',1,'3. UDP Sockets (<span class="tt">DatagramSocket</span>, <span class="tt">MulticastSocket</span>)'],['../classjsocketpp_1_1MulticastSocket.html',1,'jsocketpp::MulticastSocket'],['../group__udp.html#ga996b99882efa863b01e0fff4a9782a82',1,'jsocketpp::MulticastSocket::MulticastSocket()']]],
  ['multicastsocket_2ecpp_46',['MulticastSocket.cpp',['../MulticastSocket_8cpp.html',1,'']]],
  ['multicastsocket_2ehpp_47',['MulticastSocket.hpp',['../MulticastSocket_8hpp.html',1,'']]],
  ['multiple_20sockets_20bind_20to_20the_20same_20port_48',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]]
];
