var searchData=
[
  ['accept_0',['accept',['../group__tcp.html#gac645e511797a5c5cffd1ee490ece0e96',1,'jsocketpp::ServerSocket::accept(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#ga5a797cf5d657594189d4fc14fcb87788',1,'jsocketpp::ServerSocket::accept(int timeoutMillis, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../classjsocketpp_1_1UnixSocket.html#ad608f46c3272a83e33e3399ffb6b53cb',1,'jsocketpp::UnixSocket::accept()']]],
  ['acceptasync_1',['acceptAsync',['../group__tcp.html#gad31e3456825d69842685b8826a0ad346',1,'jsocketpp::ServerSocket::acceptAsync(std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const'],['../group__tcp.html#gafc1d1883c490172751065d491001e049',1,'jsocketpp::ServerSocket::acceptAsync(std::function&lt; void(std::optional&lt; Socket &gt;, std::exception_ptr)&gt; callback, std::optional&lt; std::size_t &gt; recvBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; sendBufferSize=std::nullopt, std::optional&lt; std::size_t &gt; internalBufferSize=std::nullopt, int soRecvTimeoutMillis=-1, int soSendTimeoutMillis=-1, bool tcpNoDelay=true, bool keepAlive=false, bool nonBlocking=false) const']]],
  ['acceptblocking_2',['acceptBlocking',['../group__tcp.html#ga4cc6cc771e29a9d1964cb8b351262318',1,'jsocketpp::ServerSocket']]],
  ['acceptnonblocking_3',['acceptNonBlocking',['../group__tcp.html#gaa825d267c5cba8febdd2824282869ac1',1,'jsocketpp::ServerSocket']]],
  ['addresstostring_4',['addressToString',['../group__utils.html#ga8501a7d31710bd7b0ef862f97ee318da',1,'jsocketpp']]],
  ['asbytes_5',['asBytes',['../group__udp.html#ga20eb26c65ff8d9c880494e028509e0a8',1,'jsocketpp::DatagramSocket']]]
];
