var searchData=
[
  ['a_20complete_20guide_20to_20its_20features_20structure_20and_20capabilities_0',['A Complete Guide to Its Features Structure and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['address_20reuse_20in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_1',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html',1,'']]],
  ['all_20interfaces_20vs_20specific_20interfaces_2',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html',1,'']]],
  ['alternatives_3',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['and_20best_20practices_4',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['and_20beyond_5',['Understanding Network Data Units: Packets, Datagrams, Segments, and Beyond',['../group__network__data__units.html',1,'']]],
  ['and_20capabilities_6',['and Capabilities',['../group__mastering__ipv4.html',1,'Mastering IPv4: A Complete Guide to Its Features, Structure, and Capabilities'],['../group__mastering__ipv6.html',1,'Mastering IPv6: A Complete Guide to Its Features, Structure, and Capabilities']]],
  ['and_20epoll_20as_20alternatives_7',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['and_20integration_20guide_8',['Unit Testing and Integration Guide',['../group__unit__tests.html',1,'']]],
  ['and_20listening_3a_20design_20patterns_20and_20best_20practices_9',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html',1,'']]],
  ['and_20platform_20apis_10',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['and_20related_20functions_3a_20commands_20use_20cases_20and_20windows_20support_11',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['and_20types_12',['Core Utilities and Types',['../group__core.html',1,'']]],
  ['and_20udp_20connections_13',['Understanding Socket Binding in TCP and UDP Connections',['../group__socket__binding.html',1,'']]],
  ['and_20usage_20guide_14',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html',1,'']]],
  ['and_20windows_20support_15',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;WSAIoctl&lt;/span&gt;, and Related Functions: Commands, Use Cases, and Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['api_16',['Comprehensive Guide to the Socket API',['../group__underlying__socket__api.html',1,'']]],
  ['apis_17',['Sockets: Theory, Types, and Platform APIs',['../group__sockets__theory.html',1,'']]],
  ['as_20alternatives_18',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]],
  ['asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_19',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html',1,'']]]
];
