var searchData=
[
  ['i_20o_0',['I O',['../group__underlying__socket__api.html#autotoc_md316',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md326',1,'6.4 Asynchronous I/O']]],
  ['implementation_20details_1',['Implementation Details',['../group__tcp.html#autotoc_md458',1,'Implementation Details'],['../group__tcp.html#autotoc_md465',1,'Implementation Details'],['../group__tcp.html#autotoc_md466',1,'Implementation Details'],['../group__tcp.html#autotoc_md470',1,'Implementation Details'],['../group__tcp.html#autotoc_md472',1,'Implementation Details'],['../group__tcp.html#autotoc_md475',1,'Implementation Details'],['../group__tcp.html#autotoc_md477',1,'Implementation Details'],['../group__tcp.html#autotoc_md479',1,'Implementation Details'],['../group__tcp.html#autotoc_md481',1,'Implementation Details'],['../group__tcp.html#autotoc_md483',1,'Implementation Details'],['../group__tcp.html#autotoc_md486',1,'Implementation Details'],['../group__tcp.html#autotoc_md489',1,'Implementation Details'],['../group__tcp.html#autotoc_md491',1,'Implementation Details'],['../group__tcp.html#autotoc_md497',1,'Implementation Details'],['../group__tcp.html#autotoc_md503',1,'Implementation Details'],['../group__tcp.html#autotoc_md504',1,'Implementation Details'],['../group__tcp.html#autotoc_md506',1,'Implementation Details'],['../group__tcp.html#autotoc_md508',1,'Implementation Details'],['../group__tcp.html#autotoc_md511',1,'Implementation Details'],['../group__tcp.html#autotoc_md514',1,'Implementation Details'],['../group__tcp.html#autotoc_md516',1,'Implementation Details'],['../group__tcp.html#autotoc_md518',1,'Implementation Details'],['../group__tcp.html#autotoc_md522',1,'Implementation Details'],['../group__tcp.html#autotoc_md524',1,'Implementation Details'],['../group__tcp.html#autotoc_md529',1,'Implementation Details'],['../group__tcp.html#autotoc_md531',1,'Implementation Details'],['../group__tcp.html#autotoc_md533',1,'Implementation Details'],['../group__tcp.html#autotoc_md535',1,'Implementation Details'],['../group__tcp.html#autotoc_md538',1,'Implementation Details'],['../group__tcp.html#autotoc_md540',1,'Implementation Details'],['../group__tcp.html#autotoc_md542',1,'Implementation Details'],['../group__tcp.html#autotoc_md545',1,'Implementation Details'],['../group__tcp.html#autotoc_md548',1,'Implementation Details'],['../classjsocketpp_1_1Socket.html#autotoc_md550',1,'Implementation Details'],['../group__tcp.html#autotoc_md557',1,'Implementation Details']]],
  ['implications_2',['Practical Implications',['../group__socket__states.html#autotoc_md253',1,'']]],
  ['implications_3',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md59',1,'']]],
  ['in_20action_3a_20practical_20examples_4',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['in_20c_2020_3a_5',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['in_20constructor_20bind_20listen_20explicit_6',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['in_20depth_7',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_8',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['in_20jsocketpp_20_3a_9',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['in_20the_20constructor_10',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['in_20your_20project_11',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_12',['Includes:',['../group__core.html#autotoc_md417',1,'']]],
  ['incompatibility_13',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md68',1,'']]],
  ['index_20cci_20submission_14',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['initialization_20and_20cleanup_3a_15',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['initialization_20flow_16',['Initialization Flow',['../group__tcp.html#autotoc_md462',1,'']]],
  ['initialization_3a_20posix_20approach_17',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['inspired_20api_18',['Java-Inspired API',['../index.html#autotoc_md380',1,'']]],
  ['installation_19',['Installation',['../index.html#autotoc_md371',1,'']]],
  ['integration_20in_20your_20project_20',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_21',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['integration_20test_3a_22',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['integration_20tests_3a_23',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md335',1,'']]],
  ['interfaces”_20mean_24',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['interfaces_25',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['internal_20buffer_26',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md451',1,'']]],
  ['internally_27',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['introduction_28',['Introduction',['../group__sockets__theory.html#autotoc_md260',1,'']]],
  ['introduction_20to_20the_20socket_20api_29',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'']]],
  ['ipc_30',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['is_20a_20socket_31',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['is_20a_20socket_20state_32',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['is_20blocking_33',['What is Blocking?',['../group__async__io.html#autotoc_md115',1,'']]],
  ['is_20multicast_34',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md435',1,'']]],
  ['is_20non_20blocking_35',['What is Non-Blocking?',['../group__async__io.html#autotoc_md116',1,'']]],
  ['is_20problematic_20on_20windows_36',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['is_20udp_37',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md425',1,'']]],
  ['is_20used_38',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['issues_39',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md393',1,'']]],
  ['it_20actually_20does_40',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['it_20works_20internally_41',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['its_20limitations_42',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md86',1,'']]]
];
