var searchData=
[
  ['b_20fully_20step_20by_20step_20posix_20style_0',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md91',1,'']]],
  ['b_20portability_1',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md86',1,'']]],
  ['basic_20api_2',['Basic API',['../classjsocketpp_1_1ServerSocket.html#autotoc_md433',1,'']]],
  ['basics_3',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md165',1,'']]],
  ['behavior_4',['Behavior',['../group__address__reuse.html#autotoc_md124',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md445',1,'Platform Behavior'],['../group__address__reuse.html#autotoc_md152',1,'Recommended Behavior']]],
  ['behavior_5',['🛠️ Example behavior',['../group__address__reuse.html#autotoc_md118',1,'']]],
  ['behavior_3a_6',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md389',1,'']]],
  ['behavior_3a_20connect_20accept_20recv_20and_20send_7',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['best_20practices_8',['Best Practices',['../group__async__io.html#autotoc_md203',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md418',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md234',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md212',1,'Best Practices'],['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices']]],
  ['best_20practices_20recap_9',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md167',1,'']]],
  ['better_20alternative_3a_20what_20jsocketpp_20does_10',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md149',1,'']]],
  ['beyond_20the_20basics_11',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md165',1,'']]],
  ['bind_20_3a_20binding_20to_20all_20interfaces_20vs_20specific_20interfaces_12',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html#autotoc_md207',1,'']]],
  ['bind_20listen_20explicit_13',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md81',1,'']]],
  ['bind_20to_20the_20same_20port_14',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['binding_20and_20listening_3a_20design_20patterns_20and_20best_20practices_15',['ServerSocket Construction, Binding, and Listening: Design Patterns and Best Practices',['../group__ServerSocket__Lifecycle.html#autotoc_md75',1,'']]],
  ['binding_20to_20all_20interfaces_16',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md210',1,'']]],
  ['binding_20to_20all_20interfaces_20vs_20specific_20interfaces_17',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html#autotoc_md207',1,'']]],
  ['blocking_18',['Blocking',['../group__async__io.html#autotoc_md172',1,'What is Blocking?'],['../group__async__io.html#autotoc_md173',1,'What is Non-Blocking?']]],
  ['blocking_20and_20timeouts_19',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md179',1,'']]],
  ['blocking_20mode_3a_20',['Blocking mode:',['../group__async__io.html#autotoc_md184',1,'Blocking mode:'],['../group__async__io.html#autotoc_md188',1,'Blocking mode:'],['../group__async__io.html#autotoc_md192',1,'Blocking mode:'],['../group__async__io.html#autotoc_md195',1,'Blocking mode:']]],
  ['blocking_20mode_3a_21',['blocking mode:',['../group__async__io.html#autotoc_md185',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md189',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md193',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md196',1,'Non-blocking mode:']]],
  ['blocking_20sockets_22',['Blocking Sockets',['../group__async__io.html#autotoc_md171',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md370',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md380',1,'6.1 Non-Blocking Sockets']]],
  ['blocking_20sockets_20in_20jsocketpp_23',['Blocking vs Non-Blocking Sockets in jsocketpp',['../group__async__io.html#autotoc_md169',1,'']]],
  ['blocking_20vs_20non_20blocking_20sockets_24',['🚦 Blocking vs Non-Blocking Sockets',['../group__async__io.html#autotoc_md171',1,'']]],
  ['blocking_20vs_20non_20blocking_20sockets_20in_20jsocketpp_25',['Blocking vs Non-Blocking Sockets in jsocketpp',['../group__async__io.html#autotoc_md169',1,'']]],
  ['boost_20asio_26',['2. Boost.Asio',['../group__socket__library__comparison.html#autotoc_md288',1,'']]],
  ['branching_20code_20of_20conduct_27',['7. Branching &amp;amp; Code of Conduct',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md21',1,'']]],
  ['broadcast_28',['Broadcast',['../group__underlying__socket__api.html#autotoc_md372',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md382',1,'6.3 Multicast and Broadcast']]],
  ['bsd_20posix_20winsock_20apis_29',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md294',1,'']]],
  ['buffer_30',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md450',1,'']]],
  ['build_31',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md58',1,'']]],
  ['build_20test_20and_20usage_20guide_32',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html#autotoc_md50',1,'']]],
  ['building_20and_20running_20tests_33',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md62',1,'']]],
  ['building_20testing_34',['Building &amp;amp; Testing',['../index.html#autotoc_md43',1,'']]],
  ['building_20the_20library_35',['Building the Library',['../group__BUILD__AND__USAGE.html#autotoc_md56',1,'']]],
  ['by_20socket_20type_36',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md264',1,'']]],
  ['by_20step_20posix_20style_37',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md91',1,'']]]
];
