var searchData=
[
  ['rationale_0',['Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md84',1,'4. Advantages and Rationale'],['../group__async__io.html#autotoc_md180',1,'Design Rationale']]],
  ['raw_20socket_20communication_1',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md364',1,'']]],
  ['raw_20sockets_2',['Raw Sockets',['../group__sockets__theory.html#autotoc_md324',1,'2.3. Raw Sockets'],['../group__sockets__theory.html#autotoc_md332',1,'Raw Sockets']]],
  ['read_3',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md191',1,'']]],
  ['readiness_4',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md198',1,'']]],
  ['reading_5',['Further Reading',['../group__socket-options.html#autotoc_md282',1,'']]],
  ['real_20server_20and_20client_3a_6',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['recap_7',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md167',1,'']]],
  ['receiving_8',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md427',1,'']]],
  ['recipe_20conanfile_20py_9',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md221',1,'']]],
  ['recipe_20locally_10',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md225',1,'']]],
  ['recommendations_11',['Recommendations',['../group__select__poll__epoll__iocp.html#autotoc_md252',1,'7. <b>Practical Recommendations</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md98',1,'8. Recommendations'],['../group__socket-options.html#autotoc_md280',1,'Design Recommendations']]],
  ['recommended_12',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md57',1,'']]],
  ['recommended_20behavior_13',['Recommended Behavior',['../group__address__reuse.html#autotoc_md152',1,'']]],
  ['recv_20and_20send_14',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md182',1,'']]],
  ['recv_20and_20send_3a_15',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['recv_20read_16',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md191',1,'']]],
  ['references_17',['References',['../group__address__reuse.html#autotoc_md161',1,'🔗 References'],['../group__sockets__theory.html#autotoc_md353',1,'9. References'],['../group__conan__publish__guide.html#autotoc_md236',1,'References'],['../group__vcpkg__publish__guide.html#autotoc_md420',1,'References']]],
  ['registry_18',['Registry',['../group__vcpkg__publish__guide.html#autotoc_md414',1,'5. Submit to the vcpkg Registry'],['../group__vcpkg__publish__guide.html#autotoc_md402',1,'Publishing <span class="tt">jsocketpp</span> to the vcpkg Registry']]],
  ['relates_20to_20jsocketpp_19',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md312',1,'']]],
  ['reporting_20issues_20',['1. Reporting Issues',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md9',1,'']]],
  ['request_20to_20cci_21',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md230',1,'']]],
  ['requests_22',['2. Submitting Pull Requests',['../md_build_2md__files_2CONTRIBUTING.html#autotoc_md11',1,'']]],
  ['require_20the_20port_20in_20the_20constructor_23',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md82',1,'']]],
  ['resources_24',['More Resources',['../group__socket__states.html#autotoc_md314',1,'']]],
  ['responsibilities_25',['Our Responsibilities',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md3',1,'']]],
  ['reuse_20in_20sockets_3a_20so_5freuseaddr_20vs_20so_5fexclusiveaddruse_26',['Address Reuse in Sockets: &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt;',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['reuse_20options_27',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md103',1,'']]],
  ['right_28',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md164',1,'']]],
  ['running_20tests_29',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md62',1,'']]]
];
