var searchData=
[
  ['b_20fully_20step_20by_20step_20posix_20style_0',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['b_20portability_1',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md36',1,'']]],
  ['basic_20api_2',['Basic API',['../classjsocketpp_1_1ServerSocket.html#autotoc_md480',1,'']]],
  ['basics_3',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['behavior_4',['Behavior',['../group__address__reuse.html#autotoc_md67',1,'⚙️ Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md470',1,'Platform Behavior'],['../group__tcp.html#autotoc_md484',1,'Platform Behavior'],['../group__tcp.html#autotoc_md611',1,'Platform Behavior'],['../group__tcp.html#autotoc_md603',1,'Protocol Behavior'],['../group__address__reuse.html#autotoc_md95',1,'Recommended Behavior']]],
  ['behavior_3a_5',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md332',1,'']]],
  ['behavior_3a_6',['behavior:',['../group__socketopts.html#autotoc_md605',1,'Platform behavior:'],['../group__socketopts.html#autotoc_md607',1,'Platform behavior:']]],
  ['behavior_3a_20connect_20accept_20recv_20and_20send_7',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['best_20practices_8',['Best Practices',['../group__async__io.html#autotoc_md146',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md155',1,'Best Practices']]],
  ['best_20practices_20recap_9',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['better_20alternative_3a_20what_20jsocketpp_20does_10',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['beyond_20the_20basics_11',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['bind_20listen_20explicit_12',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['bind_20to_20the_20same_20port_13',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['binding_20to_20all_20interfaces_14',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['blocking_15',['Blocking',['../group__async__io.html#autotoc_md115',1,'What is Blocking?'],['../group__async__io.html#autotoc_md116',1,'What is Non-Blocking?']]],
  ['blocking_20and_20timeouts_16',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md122',1,'']]],
  ['blocking_20mode_3a_17',['Blocking mode:',['../group__async__io.html#autotoc_md127',1,'Blocking mode:'],['../group__async__io.html#autotoc_md131',1,'Blocking mode:'],['../group__async__io.html#autotoc_md135',1,'Blocking mode:'],['../group__async__io.html#autotoc_md138',1,'Blocking mode:']]],
  ['blocking_20mode_3a_18',['blocking mode:',['../group__async__io.html#autotoc_md128',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md132',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md136',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md139',1,'Non-blocking mode:']]],
  ['blocking_20sockets_19',['Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md313',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md323',1,'6.1 Non-Blocking Sockets']]],
  ['blocking_20vs_20non_20blocking_20sockets_20',['🚦 Blocking vs Non-Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'']]],
  ['boost_20asio_21',['Boost Asio',['../index.html#autotoc_md376',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md231',1,'2. Boost.Asio']]],
  ['branching_20code_20of_20conduct_22',['7. Branching &amp;amp; Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'']]],
  ['broadcast_23',['Broadcast',['../group__underlying__socket__api.html#autotoc_md315',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md325',1,'6.3 Multicast and Broadcast']]],
  ['broadcast_20for_20a_20datagram_20socket_24',['Example: Enable broadcast for a datagram socket',['../group__socketopts.html#autotoc_md629',1,'']]],
  ['bsd_20posix_20winsock_20apis_25',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['buffer_26',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md489',1,'']]],
  ['buffer_20for_20inter_20process_20communication_27',['Example: Set a larger send buffer for inter-process communication',['../group__socketopts.html#autotoc_md631',1,'']]],
  ['buffer_20size_28',['buffer size',['../group__socketopts.html#autotoc_md632',1,'Example: Read the configured receive buffer size'],['../index.html#autotoc_md422',1,'What is the default buffer size?']]],
  ['buffer_20size_20used_20for_20a_20unix_20socket_29',['Example: Read the actual receive buffer size used for a Unix socket',['../group__socketopts.html#autotoc_md640',1,'']]],
  ['build_30',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['building_20and_20running_20tests_31',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['building_20and_20testing_32',['🧪 Building and Testing',['../index.html#autotoc_md402',1,'']]],
  ['building_20the_20library_33',['Building the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'']]],
  ['by_20socket_20type_34',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['by_20step_20posix_20style_35',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]]
];
