var searchData=
[
  ['latency_0',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1046',1,'']]],
  ['level_20timeouts_1',['OS-Level Timeouts',['../group__async__io.html#autotoc_md131',1,'']]],
  ['library_2',['Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['library_3',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md241',1,'']]],
  ['library_20authors_4',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md114',1,'']]],
  ['library_20for_20modern_20c_2020_5',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['library_20for_20vcpkg_6',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md361',1,'']]],
  ['license_7',['License',['../index.html#autotoc_md421',1,'⚖️ License'],['../group__BUILD__AND__USAGE.html#autotoc_md24',1,'License']]],
  ['lifecycle_8',['Lifecycle',['../group__sockets__theory.html#autotoc_md294',1,'4. How Sockets Work: The Lifecycle'],['../group__socket__states.html#autotoc_md258',1,'TCP Socket Lifecycle']]],
  ['lifetime_9',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md61',1,'']]],
  ['lifetime_20warning_10',['Lifetime Warning',['../group__tcp.html#autotoc_md729',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md742',1,'⚠️ Lifetime Warning']]],
  ['limitations_11',['Limitations',['../group__address__reuse.html#autotoc_md98',1,'⚠️ Java’s Approach and Its Limitations'],['../index.html#autotoc_md392',1,'⚠️ Limitations'],['../group__tcp.html#autotoc_md824',1,'Limitations'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1106',1,'Limitations']]],
  ['limitations_3a_12',['Limitations:',['../group__async__io.html#autotoc_md156',1,'']]],
  ['linger_20for_205_20seconds_20on_20close_13',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md944',1,'']]],
  ['linking_20the_20library_14',['Linking the Library',['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'']]],
  ['linux_15',['Unix/Linux',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['linux_20macos_20unix_16',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md301',1,'']]],
  ['linux_20only_17',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md84',1,'']]],
  ['linux_3a_18',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md67',1,'']]],
  ['listen_20explicit_19',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['local_20address_20',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md57',1,'']]],
  ['local_20binding_20parameters_20used_20only_20if_20autobind_20true_21',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md777',1,'']]],
  ['local_20binding_20persist_20for_20the_20socket’s_20lifetime_22',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md61',1,'']]],
  ['local_20ipc_23',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md280',1,'']]],
  ['locally_24',['Locally',['../group__vcpkg__publish__guide.html#autotoc_md367',1,'4. Test the Port Locally'],['../group__conan__publish__guide.html#autotoc_md180',1,'4. Test the Recipe Locally']]]
];
