var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md123',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md310',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md290',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md387',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md107',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md332',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md294',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md363',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['tcgetattr_4',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md256',1,'']]],
  ['tcp_5',['TCP',['../group__sockets__theory.html#autotoc_md358',1,'2.1. Stream Sockets (TCP)'],['../group__network__data__units.html#autotoc_md268',1,'Segments: The Reliable Counterpart in TCP'],['../group__sockets__theory.html#autotoc_md366',1,'Stream Sockets (TCP)']]],
  ['tcp_20and_20udp_6',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['tcp_20echo_20server_7',['🧵 TCP Echo Server',['../index.html#autotoc_md483',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_8',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md403',1,'']]],
  ['tcp_20socket_20lifecycle_9',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md339',1,'']]],
  ['tcp_20socket_20states_10',['Main TCP Socket States',['../group__socket__states.html#autotoc_md340',1,'']]],
  ['tcp_20sockets_11',['TCP Sockets',['../group__socket__binding.html#autotoc_md66',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md70',1,'TCP Sockets']]],
  ['tcp_20sockets_20socket_20serversocket_12',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md303',1,'']]],
  ['tcp_20state_20transitions_13',['TCP State Transitions',['../group__socket__states.html#autotoc_md342',1,'']]],
  ['tcsetattr_20tcgetattr_14',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md256',1,'']]],
  ['terminal_20window_20size_20linux_15',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md216',1,'']]],
  ['test_20cases_20to_20consider_3a_16',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md436',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_17',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md431',1,'']]],
  ['test_20the_20port_20locally_18',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md448',1,'']]],
  ['test_20the_20recipe_20locally_19',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['test_20with_20mocking_3a_20',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md435',1,'']]],
  ['test_3a_21',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md430',1,'']]],
  ['test_5fpackage_22',['test_package',['../group__conan__publish__guide.html#autotoc_md194',1,'']]],
  ['testing_23',['Testing',['../index.html#autotoc_md495',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md530',1,'5. Testing']]],
  ['testing_20in_20c_2020_3a_24',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_25',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md427',1,'']]],
  ['tests_26',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_27',['Tests:',['../group__unit__tests.html#autotoc_md423',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md428',1,'2. <b>Integration Tests</b>:'],['../group__unit__tests.html#autotoc_md432',1,'3.1 <b>Using CMake for Platform-Specific Tests</b>:'],['../group__unit__tests.html#autotoc_md433',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['the_20basics_28',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['the_20connect_20function_29',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20connectionless_20approach_30',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md267',1,'']]],
  ['the_20constructor_31',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20default_20buffer_20size_32',['What is the default buffer size?',['../index.html#autotoc_md515',1,'']]],
  ['the_20foundations_3a_20network_20models_20and_20data_20encapsulation_33',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md265',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_34',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_35',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md379',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_36',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['the_20library_37',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_38',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md375',1,'']]],
  ['the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_39',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20makefile_40',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20mtu_41',['🔍 What is the MTU?',['../group__udp.html#autotoc_md724',1,'']]],
  ['the_20port_20in_20the_20constructor_42',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20port_20locally_43',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md448',1,'']]],
  ['the_20recipe_20locally_44',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['the_20reliable_20counterpart_20in_20tcp_45',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md268',1,'']]],
  ['the_20role_20of_20the_20connect_20function_46',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20same_20port_47',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['the_20socket’s_20lifetime_48',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20socket_20api_49',['the Socket API',['../group__underlying__socket__api.html#autotoc_md392',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md393',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md401',1,'4. Protocols and the Socket API']]],
  ['the_20vcpkg_20registry_50',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md450',1,'']]],
  ['this_20is_20problematic_20on_20windows_51',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['this_20library_52',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md322',1,'']]],
  ['this_20matters_53',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md579',1,'']]],
  ['this_20relates_20to_20jsocketpp_54',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md348',1,'']]],
  ['thoughts_20and_20best_20practices_55',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md169',1,'']]],
  ['thread_20safety_56',['Thread Safety',['../group__tcp.html#autotoc_md793',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md802',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md811',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md824',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md833',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md849',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md862',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md787',1,'Thread Safety'],['../group__tcp.html#autotoc_md872',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md881',1,'Thread Safety'],['../group__tcp.html#autotoc_md947',1,'Thread Safety']]],
  ['throws_57',['Throws',['../group__internal.html#autotoc_md566',1,'Throws'],['../group__udp.html#autotoc_md623',1,'Throws']]],
  ['timeout_58',['timeout',['../group__socketopts.html#autotoc_md1128',1,'Example: Set a 3-second receive timeout'],['../group__socketopts.html#autotoc_md1133',1,'Example: Set a 5-second send timeout']]],
  ['timeout_20behavior_59',['Timeout Behavior',['../group__tcp.html#autotoc_md789',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md798',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md807',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md818',1,'⏱ Timeout Behavior']]],
  ['timeout_20handling_60',['⏱ Timeout Handling',['../group__udp.html#autotoc_md645',1,'']]],
  ['timeout_20semantics_61',['Timeout Semantics',['../group__tcp.html#autotoc_md871',1,'']]],
  ['timeouts_62',['Timeouts',['../group__async__io.html#autotoc_md145',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md141',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md142',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_63',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md143',1,'']]],
  ['tips_20and_20best_20practices_64',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md454',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices']]],
  ['to_65',['Applies to',['../group__core.html#autotoc_md550',1,'']]],
  ['to_20a_20local_20address_66',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['to_20adjust_67',['When to Adjust',['../group__core.html#autotoc_md553',1,'']]],
  ['to_20all_20interfaces”_20mean_68',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['to_20all_20interfaces_69',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['to_20cci_70',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['to_20consider_3a_71',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md436',1,'']]],
  ['to_20ioctl_20fcntl_20ioctlsocket_72',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['to_20jsocketpp_73',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md348',1,'How This Relates to <span class="tt">jsocketpp</span>']]],
  ['to_20linger_20for_205_20seconds_20on_20close_74',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1066',1,'']]],
  ['to_20mock_20recv_20and_20send_3a_75',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md426',1,'']]],
  ['to_20peer_20model_76',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md399',1,'']]],
  ['to_20reduce_20latency_77',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1168',1,'']]],
  ['to_20the_20same_20port_78',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['to_20the_20socket_20api_79',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md392',1,'']]],
  ['to_20the_20vcpkg_20registry_80',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md450',1,'']]],
  ['to_20use_81',['When to Use',['../group__socketopts.html#autotoc_md1221',1,'']]],
  ['toolchain_20support_82',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md467',1,'']]],
  ['tooling_83',['🛠 Developer Tooling',['../index.html#autotoc_md497',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_84',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['topics_85',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md385',1,'']]],
  ['trade_20off_86',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_87',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['transfer_88',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['transferred_89',['Transferred',['../group__udp.html#autotoc_md628',1,'Ownership Transferred'],['../group__udp.html#autotoc_md626',1,'What Is Transferred']]],
  ['transitions_90',['TCP State Transitions',['../group__socket__states.html#autotoc_md342',1,'']]],
  ['troubleshooting_91',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['true_92',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md899',1,'']]],
  ['true_20matters_93',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md876',1,'']]],
  ['type_94',['Type',['../group__socketopts.html#autotoc_md1192',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1201',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md300',1,'Common Options by Socket Type']]],
  ['types_95',['Types',['../group__socketopts.html#autotoc_md1148',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md396',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md363',1,'2.5. Comparison Table: Socket Types'],['../group__tcp.html#autotoc_md945',1,'Supported Types']]],
  ['types_20of_20sockets_20in_20depth_96',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md357',1,'']]],
  ['types_20work_97',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['typical_20usage_98',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md781',1,'']]],
  ['typical_20usage_20example_99',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md878',1,'']]],
  ['typical_20use_20cases_100',['🧰 Typical Use Cases',['../index.html#autotoc_md461',1,'']]]
];
