var searchData=
[
  ['safe_20usage_20guidelines_0',['✅ Safe Usage Guidelines',['../group__socketopts.html#autotoc_md896',1,'']]],
  ['safety_1',['Safety',['../group__udp.html#autotoc_md497',1,'⚠️ Exception Safety'],['../group__tcp.html#autotoc_md640',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md649',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md658',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md671',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md680',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md696',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md709',1,'⚠️ Thread Safety'],['../group__udp.html#autotoc_md605',1,'🔒 Safety'],['../group__tcp.html#autotoc_md872',1,'🔒 Safety'],['../group__ServerSocket__Lifecycle.html#autotoc_md35',1,'a) Flexibility and Safety'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md620',1,'Safety'],['../group__tcp.html#autotoc_md634',1,'Thread Safety'],['../group__tcp.html#autotoc_md719',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md728',1,'Thread Safety'],['../group__tcp.html#autotoc_md792',1,'Thread Safety']]],
  ['same_20port_2',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['scenarios_3',['Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md44',1,'6. Advanced Scenarios'],['../group__tcp.html#autotoc_md600',1,'Common Scenarios']]],
  ['scope_4',['Scope',['../md_CODE__OF__CONDUCT.html#autotoc_md448',1,'']]],
  ['second_20receive_20timeout_5',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md973',1,'']]],
  ['second_20send_20timeout_6',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md978',1,'']]],
  ['seconds_20on_20close_7',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md911',1,'']]],
  ['security_20and_20performance_20considerations_8',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md278',1,'']]],
  ['security_20considerations_9',['7. Security Considerations',['../group__underlying__socket__api.html#autotoc_md317',1,'']]],
  ['see_20also_10',['See Also',['../index.html#autotoc_md426',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md631',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md731',1,'See Also']]],
  ['select_11',['select',['../group__select__poll__epoll__iocp.html#autotoc_md185',1,'2. <b>Drawbacks of <span class="tt">select</span></b>'],['../group__async__io.html#autotoc_md120',1,'Custom Timeouts via <span class="tt">select()</span>'],['../group__socketopts.html#autotoc_md898',1,'Example: Use with <span class="tt">select()</span>']]],
  ['select_20is_20used_12',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['semantics_13',['Timeout Semantics',['../group__tcp.html#autotoc_md718',1,'']]],
  ['send_14',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['send_20timeout_15',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md978',1,'']]],
  ['send_20write_16',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md137',1,'']]],
  ['send_3a_17',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['sending_18',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md624',1,'']]],
  ['serialization_20constraints_19',['📦 Serialization Constraints',['../group__udp.html#autotoc_md567',1,'']]],
  ['server_20',['Server',['../index.html#autotoc_md392',1,'📡 UDP Echo Server'],['../index.html#autotoc_md390',1,'🧵 TCP Echo Server'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1071',1,'Example: Simple Echo Server']]],
  ['server_20and_20client_21',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md466',1,'']]],
  ['server_20and_20client_20c_20af_5finet_22',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['server_20and_20client_20python_20af_5finet_23',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['server_20and_20client_3a_24',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['server_20client_20integration_20test_3a_25',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['server_20model_26',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md305',1,'']]],
  ['server_20side_27',['4.1. Server Side',['../group__sockets__theory.html#autotoc_md283',1,'']]],
  ['serversocket_28',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['serversocket_20specific_20notes_29',['ServerSocket specific Notes',['../group__socketopts.html#autotoc_md902',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md913',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md922',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md933',1,'⚠️ ServerSocket-specific Notes']]],
  ['serversocket_3a_20constructor_20does_20all_20steps_30',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['set_20a_203_20second_20receive_20timeout_31',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md973',1,'']]],
  ['set_20a_205_20second_20send_20timeout_32',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md978',1,'']]],
  ['set_20so_5flinger_20to_20linger_20for_205_20seconds_20on_20close_33',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md911',1,'']]],
  ['setting_34',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md931',1,'']]],
  ['setting_20up_20real_20server_20and_20client_3a_35',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['shared_20port_20binding_36',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1057',1,'']]],
  ['shutdown_20modes_37',['Shutdown Modes',['../group__tcp.html#autotoc_md826',1,'']]],
  ['side_38',['Side',['../group__sockets__theory.html#autotoc_md283',1,'4.1. Server Side'],['../group__sockets__theory.html#autotoc_md284',1,'4.2. Client Side']]],
  ['signature_39',['🔁 Callback Signature',['../group__tcp.html#autotoc_md707',1,'']]],
  ['simple_20client_40',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1072',1,'']]],
  ['simple_20echo_20server_41',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1071',1,'']]],
  ['simple_20server_20client_20integration_20test_3a_42',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['simple_20udp_20echo_20server_20and_20client_43',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md466',1,'']]],
  ['size_44',['size',['../group__socketopts.html#autotoc_md920',1,'Example: Read configured receive buffer size'],['../index.html#autotoc_md422',1,'What is the default buffer size?']]],
  ['smarter_20strategy_20for_20jsocketpp_45',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_46',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['so_5fexclusiveaddruse_20windows_20only_47',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md64',1,'']]],
  ['so_5flinger_20setting_48',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md931',1,'']]],
  ['so_5flinger_20to_20linger_20for_205_20seconds_20on_20close_49',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md911',1,'']]],
  ['so_5freuseaddr_50',['SO_REUSEADDR',['../group__address__reuse.html#autotoc_md54',1,'<span class="tt">SO_REUSEADDR</span>'],['../group__address__reuse.html#autotoc_md98',1,'Why Not Expose Windows <span class="tt">SO_REUSEADDR</span>?']]],
  ['so_5freuseaddr_20only_3a_51',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['so_5freuseaddr_20so_5freuseport_3a_52',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['so_5freuseaddr_3a_53',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['so_5freuseport_54',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['so_5freuseport_20unix_20linux_20only_55',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md72',1,'']]],
  ['so_5freuseport_3a_56',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['socket_57',['Socket',['../group__tcp.html#autotoc_md638',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md647',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md656',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md667',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md700',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md713',1,'⚙️ Configuration of Accepted Socket'],['../group__sockets__theory.html#autotoc_md262',1,'1. What is a Socket?']]],
  ['socket_58',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md999',1,'']]],
  ['socket_20address_20families_59',['3. Socket Address Families',['../group__sockets__theory.html#autotoc_md280',1,'']]],
  ['socket_20api_60',['Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md300',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md308',1,'4. Protocols and the Socket API']]],
  ['socket_20api_20features_61',['Socket API Features',['../group__underlying__socket__api.html#autotoc_md312',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md322',1,'Advanced Socket API Features']]],
  ['socket_20api_20for_20unit_20tests_3a_62',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['socket_20api_20in_20action_3a_20practical_20examples_63',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['socket_20behavior_3a_64',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md332',1,'']]],
  ['socket_20communication_65',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md307',1,'']]],
  ['socket_20exceptions_66',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md886',1,'']]],
  ['socket_20initialization_20and_20cleanup_3a_67',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['socket_20initialization_3a_20posix_20approach_68',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['socket_20ipc_69',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md396',1,'']]],
  ['socket_20is_20ipv6_20only_70',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1050',1,'']]],
  ['socket_20library_20for_20modern_20c_2020_71',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['socket_20lifecycle_72',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md246',1,'']]],
  ['socket_20options_73',['Socket Options',['../group__underlying__socket__api.html#autotoc_md314',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md324',1,'6.2 Socket Options'],['../group__socket-options.html#autotoc_md203',1,'What Are Socket Options?']]],
  ['socket_20serversocket_74',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['socket_20state_75',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['socket_20state_20handling_76',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md60',1,'']]],
  ['socket_20states_77',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['socket_20timeouts_78',['🕐 Socket Timeouts',['../group__async__io.html#autotoc_md118',1,'']]],
  ['socket_20type_79',['Socket Type',['../group__socketopts.html#autotoc_md1037',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1046',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md207',1,'Common Options by Socket Type']]],
  ['socket_20types_80',['Socket Types',['../group__socketopts.html#autotoc_md993',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md303',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md270',1,'2.5. Comparison Table: Socket Types']]],
  ['socket_20types_20work_81',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['sockets_82',['Sockets',['../group__async__io.html#autotoc_md114',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__socket-options.html#autotoc_md208',1,'1. Options for All Sockets'],['../group__sockets__theory.html#autotoc_md267',1,'2.3. Raw Sockets'],['../group__underlying__socket__api.html#autotoc_md313',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md323',1,'6.1 Non-Blocking Sockets'],['../group__sockets__theory.html#autotoc_md275',1,'Raw Sockets'],['../group__sockets__theory.html#autotoc_md276',1,'Unix Domain Sockets'],['../group__socket__states.html#autotoc_md251',1,'What About UDP and UNIX Sockets?']]],
  ['sockets_20bind_20to_20the_20same_20port_83',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['sockets_20datagramsocket_20multicastsocket_84',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md212',1,'']]],
  ['sockets_20in_20depth_85',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['sockets_20local_20ipc_86',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['sockets_20operate_87',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['sockets_20socket_20serversocket_88',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['sockets_20tcp_89',['Sockets TCP',['../group__sockets__theory.html#autotoc_md265',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md273',1,'Stream Sockets (TCP)']]],
  ['sockets_20udp_90',['Sockets UDP',['../group__sockets__theory.html#autotoc_md266',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md274',1,'Datagram Sockets (UDP)']]],
  ['sockets_20unixsocket_91',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md215',1,'']]],
  ['sockets_20work_3a_20the_20lifecycle_92',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'']]],
  ['specific_20apis_93',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md288',1,'']]],
  ['specific_20behavior_3a_20connect_20accept_20recv_20and_20send_94',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['specific_20considerations_95',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md319',1,'']]],
  ['specific_20notes_96',['specific Notes',['../group__socketopts.html#autotoc_md902',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md913',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md922',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md933',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md904',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md914',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md924',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md935',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md906',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md915',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md926',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md937',1,'🧿 UnixSocket-specific Notes']]],
  ['specific_20tests_3a_97',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['stack_20and_20ipv6_20behavior_98',['🌐 Dual-Stack and IPv6 Behavior',['../group__udp.html#autotoc_md495',1,'']]],
  ['standards_99',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md446',1,'']]],
  ['start_20examples_100',['🚀 Quick Start Examples',['../index.html#autotoc_md389',1,'']]],
  ['state_101',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['state_20handling_102',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md60',1,'']]],
  ['state_20transitions_103',['TCP State Transitions',['../group__socket__states.html#autotoc_md249',1,'']]],
  ['states_104',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['step_20by_20step_20posix_20style_105',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['step_20posix_20style_106',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['steps_107',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['strategy_20for_20jsocketpp_108',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['stream_20sockets_20tcp_109',['Stream Sockets TCP',['../group__sockets__theory.html#autotoc_md265',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md273',1,'Stream Sockets (TCP)']]],
  ['stubbing_20socket_20api_20for_20unit_20tests_3a_110',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['style_111',['Style',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'<b>a) Constructor Does All (Java Default Style)</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'<b>b) Fully Step-by-Step (POSIX Style)</b>']]],
  ['style_20cross_20platform_20socket_20library_20for_20modern_20c_2020_112',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['style_20guidelines_113',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md433',1,'']]],
  ['submission_114',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['submit_20a_20pull_20request_20to_20cci_115',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['submit_20to_20the_20vcpkg_20registry_116',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'']]],
  ['submitting_20pull_20requests_117',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md431',1,'']]],
  ['summary_118',['Summary',['../group__address__reuse.html#autotoc_md71',1,'🧠 Summary'],['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'9. Summary']]],
  ['summary_20by_20operation_119',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md995',1,'']]],
  ['summary_20of_20java’s_20design_20trade_20off_120',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['summary_20table_121',['Summary Table',['../group__address__reuse.html#autotoc_md100',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md217',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md197',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md294',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md84',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md239',1,'Summary Table']]],
  ['summary_20table_3a_20waiting_20for_20readiness_122',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['support_123',['Support',['../group__socketopts.html#autotoc_md1055',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1062',1,'🔀 Platform Support'],['../index.html#autotoc_md374',1,'🔧 Platform &amp; Toolchain Support'],['../group__socket-options.html#autotoc_md205',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md729',1,'Platform Support']]],
  ['supported_20classes_124',['Supported Classes',['../classjsocketpp_1_1SocketOptions.html#autotoc_md889',1,'']]],
  ['supported_20types_125',['Supported Types',['../group__tcp.html#autotoc_md790',1,'']]]
];
