var searchData=
[
  ['⚙️_20behavior_0',['⚙️ Behavior',['../group__address__reuse.html#autotoc_md90',1,'⚙️ Behavior'],['../group__internal.html#autotoc_md591',1,'⚙️ Behavior'],['../group__internal.html#autotoc_md596',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md646',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md658',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md663',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md700',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md764',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md768',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md772',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md840',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md858',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md869',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1036',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1041',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1046',1,'⚙️ Behavior']]],
  ['⚙️_20configuration_1',['⚙️ Configuration',['../group__tcp.html#autotoc_md851',1,'']]],
  ['⚙️_20configuration_20of_20accepted_20socket_2',['⚙️ Configuration of Accepted Socket',['../group__tcp.html#autotoc_md802',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md811',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md820',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md831',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md864',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md877',1,'⚙️ Configuration of Accepted Socket']]],
  ['⚙️_20core_20behaviors_3',['⚙️ Core Behaviors',['../group__udp.html#autotoc_md718',1,'']]],
  ['⚙️_20implementation_20details_4',['⚙️ Implementation Details',['../group__udp.html#autotoc_md743',1,'']]],
  ['⚙️_20platform_20behavior_5',['⚙️ Platform Behavior',['../group__udp.html#autotoc_md734',1,'']]]
];
