var searchData=
[
  ['packet_0',['What is a Packet?',['../group__network__data__units.html#autotoc_md266',1,'']]],
  ['packets_20datagrams_20and_20segments_1',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md269',1,'']]],
  ['parameters_2',['Parameters',['../group__tcp.html#autotoc_md896',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md623',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md890',1,'Configuration Parameters'],['../group__internal.html#autotoc_md569',1,'Parameters'],['../group__udp.html#autotoc_md727',1,'Parameters']]],
  ['parameters_20used_20only_20if_20autobind_20true_3',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md898',1,'']]],
  ['peer_20model_4',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md399',1,'']]],
  ['peer_20to_20peer_20model_5',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md399',1,'']]],
  ['performance_20considerations_6',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md371',1,'']]],
  ['performance_20footprint_7',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md471',1,'']]],
  ['persist_20for_20the_20socket’s_20lifetime_8',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['platform_20api_20considerations_9',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md286',1,'']]],
  ['platform_20behavior_10',['Platform Behavior',['../group__udp.html#autotoc_md722',1,'⚙️ Platform Behavior'],['../group__socketopts.html#autotoc_md1202',1,'⚠️ Platform Behavior'],['../group__socketopts.html#autotoc_md1125',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1130',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1135',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1140',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1145',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1156',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1165',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1193',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1179',1,'🔐 Platform Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md771',1,'Platform Behavior'],['../group__tcp.html#autotoc_md869',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1093',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1096',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1100',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1106',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1118',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1122',1,'Platform Behavior']]],
  ['platform_20notes_11',['Platform Notes',['../group__udp.html#autotoc_md738',1,'💡 Platform Notes'],['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md940',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1103',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1109',1,'Platform Notes']]],
  ['platform_20socket_20library_20for_20modern_20c_2020_12',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['platform_20specific_20apis_13',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md381',1,'']]],
  ['platform_20specific_20considerations_14',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md412',1,'']]],
  ['platform_20specific_20tests_3a_15',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md432',1,'']]],
  ['platform_20support_16',['Platform Support',['../group__socketopts.html#autotoc_md1209',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1216',1,'🔀 Platform Support'],['../group__socket-options.html#autotoc_md298',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md881',1,'Platform Support']]],
  ['platform_20toolchain_20support_17',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md467',1,'']]],
  ['platform_3a_18',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md431',1,'']]],
  ['pledge_19',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md538',1,'']]],
  ['poco_3a_3anet_20',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md326',1,'']]],
  ['policy_21',['Semantics &amp;amp; policy',['../group__core.html#autotoc_md555',1,'']]],
  ['poll_22',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md280',1,'']]],
  ['port_23',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['port_20binding_24',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1211',1,'']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_25',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['port_20in_20the_20constructor_26',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['port_20locally_27',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md448',1,'']]],
  ['portability_28',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md47',1,'']]],
  ['portfile_29',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md444',1,'']]],
  ['portfile_20cmake_30',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md446',1,'']]],
  ['posix_20approach_31',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['posix_20linux_20macos_20unix_32',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md382',1,'']]],
  ['posix_20style_33',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['posix_20winsock_20apis_34',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md330',1,'']]],
  ['practical_20considerations_35',['Practical Considerations',['../group__underlying__socket__api.html#autotoc_md420',1,'7. Practical Considerations'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md263',1,'Practical Considerations']]],
  ['practical_20examples_36',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md402',1,'']]],
  ['practical_20implications_37',['Practical Implications',['../group__socket__states.html#autotoc_md346',1,'']]],
  ['practical_20implications_38',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['practical_20recommendations_39',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md288',1,'']]],
  ['practices_40',['Practices',['../group__async__io.html#autotoc_md169',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md454',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md178',1,'Best Practices']]],
  ['practices_20recap_41',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['pre_20commit_20hooks_42',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md528',1,'']]],
  ['pre_20commit_20hooks_43',['Pre-commit hooks',['../index.html#autotoc_md498',1,'']]],
  ['preconditions_44',['Preconditions',['../group__core.html#autotoc_md561',1,'']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_45',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_46',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md442',1,'']]],
  ['prerequisites_47',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md185',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md440',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md4',1,'Prerequisites']]],
  ['presets_20recommended_48',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['primary_20traits_49',['Primary Traits',['../buffer__traits_8hpp.html#autotoc_md766',1,'']]],
  ['problematic_20on_20windows_50',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['production_51',['Can I use jsocketpp in production?',['../index.html#autotoc_md511',1,'']]],
  ['project_52',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['project_20conan_20friendly_53',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['pros_20and_20cons_54',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['protocol_20applicability_55',['Protocol Applicability',['../group__socketopts.html#autotoc_md1097',1,'']]],
  ['protocol_20behavior_56',['Protocol Behavior',['../group__tcp.html#autotoc_md1016',1,'']]],
  ['protocol_20format_57',['Protocol Format',['../group__tcp.html#autotoc_md962',1,'Protocol Format'],['../group__tcp.html#autotoc_md965',1,'Protocol Format'],['../group__tcp.html#autotoc_md989',1,'Protocol Format'],['../group__tcp.html#autotoc_md992',1,'Protocol Format']]],
  ['protocol_20use_20cases_58',['Protocol Use Cases',['../group__socketopts.html#autotoc_md1094',1,'']]],
  ['protocols_20and_20the_20socket_20api_59',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md401',1,'']]],
  ['pull_20request_20to_20cci_60',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['pull_20requests_61',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md524',1,'']]],
  ['purpose_62',['Purpose',['../group__address__reuse.html#autotoc_md89',1,'🎯 Purpose'],['../group__udp.html#autotoc_md729',1,'🧠 Purpose'],['../namespacejsocketpp_1_1net.html#autotoc_md547',1,'Purpose'],['../group__tcp.html#autotoc_md1009',1,'Purpose']]],
  ['py_63',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md187',1,'']]],
  ['python_20af_5finet_64',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md403',1,'']]]
];
