var searchData=
[
  ['i_20o_0',['I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md409',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md419',1,'6.4 Asynchronous I/O']]],
  ['i_20use_20jsocketpp_20in_20production_1',['Can I use jsocketpp in production?',['../index.html#autotoc_md511',1,'']]],
  ['if_20autobind_20true_2',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md900',1,'']]],
  ['if_20socket_20is_20ipv6_20only_3',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1206',1,'']]],
  ['implementation_20details_4',['Implementation Details',['../group__udp.html#autotoc_md733',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md744',1,'Implementation Details'],['../group__tcp.html#autotoc_md887',1,'Implementation Details'],['../group__tcp.html#autotoc_md941',1,'Implementation Details'],['../group__tcp.html#autotoc_md944',1,'Implementation Details'],['../group__tcp.html#autotoc_md949',1,'Implementation Details'],['../group__tcp.html#autotoc_md951',1,'Implementation Details'],['../group__tcp.html#autotoc_md954',1,'Implementation Details'],['../group__tcp.html#autotoc_md956',1,'Implementation Details'],['../group__tcp.html#autotoc_md958',1,'Implementation Details'],['../group__tcp.html#autotoc_md960',1,'Implementation Details'],['../group__tcp.html#autotoc_md962',1,'Implementation Details'],['../group__tcp.html#autotoc_md965',1,'Implementation Details'],['../group__tcp.html#autotoc_md968',1,'Implementation Details'],['../group__tcp.html#autotoc_md970',1,'Implementation Details'],['../group__tcp.html#autotoc_md974',1,'Implementation Details'],['../group__tcp.html#autotoc_md976',1,'Implementation Details'],['../group__tcp.html#autotoc_md978',1,'Implementation Details'],['../group__tcp.html#autotoc_md984',1,'Implementation Details'],['../group__tcp.html#autotoc_md985',1,'Implementation Details'],['../group__tcp.html#autotoc_md987',1,'Implementation Details'],['../group__tcp.html#autotoc_md989',1,'Implementation Details'],['../group__tcp.html#autotoc_md992',1,'Implementation Details'],['../group__tcp.html#autotoc_md995',1,'Implementation Details'],['../group__tcp.html#autotoc_md997',1,'Implementation Details'],['../group__tcp.html#autotoc_md999',1,'Implementation Details'],['../group__tcp.html#autotoc_md1003',1,'Implementation Details'],['../group__tcp.html#autotoc_md1005',1,'Implementation Details'],['../group__tcp.html#autotoc_md1009',1,'Implementation Details'],['../group__tcp.html#autotoc_md1012',1,'Implementation Details'],['../group__tcp.html#autotoc_md1014',1,'Implementation Details'],['../group__tcp.html#autotoc_md1024',1,'Implementation Details']]],
  ['implementation_20notes_5',['Implementation Notes',['../group__tcp.html#autotoc_md1016',1,'']]],
  ['implications_6',['Practical Implications',['../group__socket__states.html#autotoc_md346',1,'']]],
  ['implications_7',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['implicit_20binding_20in_20tcp_20and_20udp_8',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['in_20action_3a_20practical_20examples_9',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md402',1,'']]],
  ['in_20c_2020_3a_10',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['in_20constructor_20bind_20listen_20explicit_11',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['in_20depth_12',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md357',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_13',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['in_20jsocketpp_20_3a_14',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['in_20production_15',['Can I use jsocketpp in production?',['../index.html#autotoc_md511',1,'']]],
  ['in_20tcp_16',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md268',1,'']]],
  ['in_20tcp_20and_20udp_17',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['in_20the_20constructor_18',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['in_20your_20project_19',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_20',['Includes:',['../group__core.html#autotoc_md546',1,'']]],
  ['incompatibility_21',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md91',1,'']]],
  ['index_20cci_20submission_22',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['information_20and_20configuration_23',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['initialization_20and_20cleanup_3a_24',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md427',1,'']]],
  ['initialization_3a_20posix_20approach_25',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['inputs_26',['Supported Inputs',['../namespacejsocketpp_1_1internal.html#autotoc_md588',1,'']]],
  ['installation_27',['📦 Installation',['../index.html#autotoc_md475',1,'']]],
  ['integration_28',['🔧 Manual Integration',['../index.html#autotoc_md480',1,'']]],
  ['integration_20in_20your_20project_29',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_30',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md435',1,'']]],
  ['integration_20test_3a_31',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md430',1,'']]],
  ['integration_20tests_3a_32',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md428',1,'']]],
  ['intended_20usage_33',['Intended Usage',['../classjsocketpp_1_1SocketOptions.html#autotoc_md1044',1,'']]],
  ['interface_20list_20windows_34',['Example: Get Interface List (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md250',1,'']]],
  ['interfaces”_20mean_35',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['interfaces_36',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['internal_20buffer_37',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md880',1,'']]],
  ['internal_20mechanism_38',['🔧 Internal Mechanism',['../group__internal.html#autotoc_md579',1,'']]],
  ['internally_39',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['introduction_40',['Introduction',['../group__socket__binding.html#autotoc_md63',1,'Introduction'],['../group__sockets__theory.html#autotoc_md353',1,'Introduction']]],
  ['introduction_20to_20the_20socket_20api_41',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md392',1,'']]],
  ['ioctl_20fcntl_20ioctlsocket_42',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ioctl_20unix_20linux_43',['1. ioctl (Unix/Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md208',1,'']]],
  ['ioctlsocket_44',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ioctlsocket_20windows_45',['3. ioctlsocket (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md232',1,'']]],
  ['ipc_46',['IPC',['../index.html#autotoc_md489',1,'🧷 UNIX Domain Socket (IPC)'],['../group__sockets__theory.html#autotoc_md361',1,'2.4. Unix Domain Sockets (Local IPC)']]],
  ['ipv4_20mapped_20ipv6_20behavior_47',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md908',1,'']]],
  ['ipv6_20behavior_48',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md908',1,'']]],
  ['ipv6_20handling_49',['IPv6 Handling',['../group__udp.html#autotoc_md667',1,'IPv6 Handling'],['../group__udp.html#autotoc_md674',1,'IPv6 Handling']]],
  ['ipv6_20only_50',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1206',1,'']]],
  ['is_20a_20packet_51',['What is a Packet?',['../group__network__data__units.html#autotoc_md266',1,'']]],
  ['is_20a_20socket_52',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md355',1,'']]],
  ['is_20a_20socket_20state_53',['What is a Socket State?',['../group__socket__states.html#autotoc_md337',1,'']]],
  ['is_20blocking_54',['What is Blocking?',['../group__async__io.html#autotoc_md138',1,'']]],
  ['is_20connected_20udp_55',['🔌 What Is Connected UDP?',['../group__udp.html#autotoc_md639',1,'']]],
  ['is_20ipv6_20only_56',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1206',1,'']]],
  ['is_20jsocketpp_20async_57',['Is jsocketpp async?',['../index.html#autotoc_md507',1,'']]],
  ['is_20multicast_58',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md776',1,'']]],
  ['is_20non_20blocking_59',['What is Non-Blocking?',['../group__async__io.html#autotoc_md139',1,'']]],
  ['is_20problematic_20on_20windows_60',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['is_20socket_20binding_61',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md64',1,'']]],
  ['is_20the_20default_20buffer_20size_62',['What is the default buffer size?',['../index.html#autotoc_md515',1,'']]],
  ['is_20the_20mtu_63',['🔍 What is the MTU?',['../group__udp.html#autotoc_md722',1,'']]],
  ['is_20transferred_64',['What Is Transferred',['../group__udp.html#autotoc_md626',1,'']]],
  ['is_20udp_65',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md603',1,'']]],
  ['is_20used_66',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md276',1,'']]],
  ['issues_67',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md522',1,'']]],
  ['it_20actually_20does_68',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['it_20work_20on_20windows_69',['Does it work on Windows?',['../index.html#autotoc_md513',1,'']]],
  ['it_20works_20internally_70',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['its_20limitations_71',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md109',1,'']]]
];
