var searchData=
[
  ['safe_20cap_0',['Why a &quot;safe&quot; cap?',['../group__core.html#autotoc_md559',1,'']]],
  ['safe_20usage_20guidelines_1',['✅ Safe Usage Guidelines',['../group__socketopts.html#autotoc_md1050',1,'']]],
  ['safety_2',['Safety',['../group__tcp.html#autotoc_md792',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md801',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md810',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md823',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md832',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md848',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md861',1,'⚠️ Thread Safety'],['../group__udp.html#autotoc_md754',1,'🔒 Safety'],['../group__tcp.html#autotoc_md1026',1,'🔒 Safety'],['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'a) Flexibility and Safety'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md772',1,'Safety'],['../group__tcp.html#autotoc_md786',1,'Thread Safety'],['../group__tcp.html#autotoc_md871',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md880',1,'Thread Safety'],['../group__tcp.html#autotoc_md946',1,'Thread Safety']]],
  ['same_20port_3',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['scenarios_4',['Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md55',1,'6. Advanced Scenarios'],['../group__tcp.html#autotoc_md744',1,'Common Scenarios']]],
  ['scope_5',['Scope',['../md_CODE__OF__CONDUCT.html#autotoc_md541',1,'']]],
  ['second_20receive_20timeout_6',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['second_20send_20timeout_7',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1132',1,'']]],
  ['seconds_20on_20close_8',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1065',1,'']]],
  ['security_20and_20performance_20considerations_9',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md371',1,'']]],
  ['security_20considerations_10',['7. Security Considerations',['../group__underlying__socket__api.html#autotoc_md410',1,'']]],
  ['see_20also_11',['See Also',['../index.html#autotoc_md519',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md783',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md883',1,'See Also']]],
  ['segments_12',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md269',1,'']]],
  ['segments_3a_20the_20reliable_20counterpart_20in_20tcp_13',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md268',1,'']]],
  ['select_14',['select',['../group__select__poll__epoll__iocp.html#autotoc_md278',1,'2. <b>Drawbacks of <span class="tt">select</span></b>'],['../group__async__io.html#autotoc_md143',1,'Custom Timeouts via <span class="tt">select()</span>'],['../group__socketopts.html#autotoc_md1052',1,'Example: Use with <span class="tt">select()</span>']]],
  ['select_20is_20used_15',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md276',1,'']]],
  ['semantics_16',['Timeout Semantics',['../group__tcp.html#autotoc_md870',1,'']]],
  ['semantics_20policy_17',['Semantics &amp;amp; policy',['../group__core.html#autotoc_md555',1,'']]],
  ['send_18',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['send_20timeout_19',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1132',1,'']]],
  ['send_20write_20',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md160',1,'']]],
  ['send_3a_21',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md426',1,'']]],
  ['sending_22',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md776',1,'']]],
  ['serialization_20constraints_23',['📦 Serialization Constraints',['../group__udp.html#autotoc_md699',1,'']]],
  ['server_24',['Server',['../index.html#autotoc_md485',1,'📡 UDP Echo Server'],['../index.html#autotoc_md483',1,'🧵 TCP Echo Server'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1225',1,'Example: Simple Echo Server']]],
  ['server_20and_20client_25',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md604',1,'']]],
  ['server_20and_20client_20c_20af_5finet_26',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md404',1,'']]],
  ['server_20and_20client_20python_20af_5finet_27',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md403',1,'']]],
  ['server_20and_20client_3a_28',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md429',1,'']]],
  ['server_20client_20integration_20test_3a_29',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md430',1,'']]],
  ['server_20model_30',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md398',1,'']]],
  ['server_20side_31',['4.1. Server Side',['../group__sockets__theory.html#autotoc_md376',1,'']]],
  ['serversocket_32',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md303',1,'']]],
  ['serversocket_20specific_20notes_33',['ServerSocket specific Notes',['../group__socketopts.html#autotoc_md1056',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1067',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1076',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1087',1,'⚠️ ServerSocket-specific Notes']]],
  ['serversocket_3a_20constructor_20does_20all_20steps_34',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['set_20a_203_20second_20receive_20timeout_35',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['set_20a_205_20second_20send_20timeout_36',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1132',1,'']]],
  ['set_20non_20blocking_20socket_20linux_37',['Example: Set Non-Blocking Socket (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md228',1,'']]],
  ['set_20so_5flinger_20to_20linger_20for_205_20seconds_20on_20close_38',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1065',1,'']]],
  ['setsockopt_20getsockopt_39',['setsockopt/getsockopt',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md255',1,'']]],
  ['setting_40',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md1085',1,'']]],
  ['setting_20up_20real_20server_20and_20client_3a_41',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md429',1,'']]],
  ['shared_20port_20binding_42',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1211',1,'']]],
  ['shutdown_20modes_43',['Shutdown Modes',['../group__tcp.html#autotoc_md980',1,'']]],
  ['side_44',['Side',['../group__sockets__theory.html#autotoc_md376',1,'4.1. Server Side'],['../group__sockets__theory.html#autotoc_md377',1,'4.2. Client Side']]],
  ['signature_45',['🔁 Callback Signature',['../group__tcp.html#autotoc_md859',1,'']]],
  ['simple_20client_46',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1226',1,'']]],
  ['simple_20echo_20server_47',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1225',1,'']]],
  ['simple_20server_20client_20integration_20test_3a_48',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md430',1,'']]],
  ['simple_20udp_20echo_20server_20and_20client_49',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md604',1,'']]],
  ['size_50',['size',['../group__socketopts.html#autotoc_md1074',1,'Example: Read configured receive buffer size'],['../index.html#autotoc_md515',1,'What is the default buffer size?']]],
  ['size_20linux_51',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md216',1,'']]],
  ['size_20std_3a_3aarray_52',['Example: Reading into a fixed-size &lt;span class=&quot;tt&quot;&gt;std::array&lt;/span&gt;',['../group__udp.html#autotoc_md710',1,'']]],
  ['smarter_20strategy_20for_20jsocketpp_53',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_54',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['so_5fexclusiveaddruse_20windows_20only_55',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md87',1,'']]],
  ['so_5flinger_20setting_56',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md1085',1,'']]],
  ['so_5flinger_20to_20linger_20for_205_20seconds_20on_20close_57',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1065',1,'']]],
  ['so_5freuseaddr_58',['SO_REUSEADDR',['../group__address__reuse.html#autotoc_md77',1,'<span class="tt">SO_REUSEADDR</span>'],['../group__address__reuse.html#autotoc_md121',1,'Why Not Expose Windows <span class="tt">SO_REUSEADDR</span>?']]],
  ['so_5freuseaddr_20only_3a_59',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['so_5freuseaddr_20so_5freuseport_3a_60',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['so_5freuseaddr_3a_61',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md104',1,'']]],
  ['so_5freuseport_62',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md84',1,'']]],
  ['so_5freuseport_20unix_20linux_20only_63',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md95',1,'']]],
  ['so_5freuseport_3a_64',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['socket’s_20lifetime_65',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['socket_66',['Socket',['../group__tcp.html#autotoc_md790',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md799',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md808',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md819',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md852',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md865',1,'⚙️ Configuration of Accepted Socket'],['../group__sockets__theory.html#autotoc_md355',1,'1. What is a Socket?']]],
  ['socket_67',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1153',1,'']]],
  ['socket_20address_20families_68',['3. Socket Address Families',['../group__sockets__theory.html#autotoc_md373',1,'']]],
  ['socket_20api_69',['Socket API',['../group__underlying__socket__api.html#autotoc_md392',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md393',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md401',1,'4. Protocols and the Socket API']]],
  ['socket_20api_20features_70',['Socket API Features',['../group__underlying__socket__api.html#autotoc_md405',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md415',1,'Advanced Socket API Features']]],
  ['socket_20api_20for_20unit_20tests_3a_71',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md433',1,'']]],
  ['socket_20api_20in_20action_3a_20practical_20examples_72',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md402',1,'']]],
  ['socket_20behavior_3a_73',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md425',1,'']]],
  ['socket_20binding_74',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md64',1,'']]],
  ['socket_20communication_75',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md400',1,'']]],
  ['socket_20creation_20and_20management_76',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['socket_20exceptions_77',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md1040',1,'']]],
  ['socket_20information_20and_20configuration_78',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['socket_20initialization_20and_20cleanup_3a_79',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md427',1,'']]],
  ['socket_20initialization_3a_20posix_20approach_80',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['socket_20ipc_81',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md489',1,'']]],
  ['socket_20is_20ipv6_20only_82',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1204',1,'']]],
  ['socket_20library_20for_20modern_20c_2020_83',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['socket_20lifecycle_84',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md339',1,'']]],
  ['socket_20linux_85',['Example: Set Non-Blocking Socket (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md228',1,'']]],
  ['socket_20options_86',['Socket Options',['../group__underlying__socket__api.html#autotoc_md407',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md417',1,'6.2 Socket Options'],['../group__socket-options.html#autotoc_md296',1,'What Are Socket Options?']]],
  ['socket_20serversocket_87',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md303',1,'']]],
  ['socket_20state_88',['What is a Socket State?',['../group__socket__states.html#autotoc_md337',1,'']]],
  ['socket_20state_20handling_89',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md83',1,'']]],
  ['socket_20states_90',['Main TCP Socket States',['../group__socket__states.html#autotoc_md340',1,'']]],
  ['socket_20timeouts_91',['🕐 Socket Timeouts',['../group__async__io.html#autotoc_md141',1,'']]],
  ['socket_20type_92',['Socket Type',['../group__socketopts.html#autotoc_md1191',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1200',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md300',1,'Common Options by Socket Type']]],
  ['socket_20types_93',['Socket Types',['../group__socketopts.html#autotoc_md1147',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md396',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md363',1,'2.5. Comparison Table: Socket Types']]],
  ['socket_20types_20work_94',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md365',1,'']]],
  ['socket_20windows_95',['Example: Non-Blocking Socket (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md239',1,'']]],
  ['sockets_96',['Sockets',['../group__async__io.html#autotoc_md137',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__socket-options.html#autotoc_md301',1,'1. Options for All Sockets'],['../group__sockets__theory.html#autotoc_md360',1,'2.3. Raw Sockets'],['../group__underlying__socket__api.html#autotoc_md406',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md416',1,'6.1 Non-Blocking Sockets'],['../group__sockets__theory.html#autotoc_md368',1,'Raw Sockets'],['../group__socket__binding.html#autotoc_md66',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md70',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md67',1,'UDP Sockets'],['../group__socket__binding.html#autotoc_md71',1,'UDP Sockets'],['../group__sockets__theory.html#autotoc_md369',1,'Unix Domain Sockets'],['../group__socket__states.html#autotoc_md344',1,'What About UDP and UNIX Sockets?']]],
  ['sockets_20bind_20to_20the_20same_20port_97',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['sockets_20datagramsocket_20multicastsocket_98',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md305',1,'']]],
  ['sockets_20in_20depth_99',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md357',1,'']]],
  ['sockets_20local_20ipc_100',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md361',1,'']]],
  ['sockets_20operate_101',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md379',1,'']]],
  ['sockets_20socket_20serversocket_102',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md303',1,'']]],
  ['sockets_20tcp_103',['Sockets TCP',['../group__sockets__theory.html#autotoc_md358',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md366',1,'Stream Sockets (TCP)']]],
  ['sockets_20udp_104',['Sockets UDP',['../group__sockets__theory.html#autotoc_md359',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md367',1,'Datagram Sockets (UDP)']]],
  ['sockets_20unixsocket_105',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md308',1,'']]],
  ['sockets_20work_3a_20the_20lifecycle_106',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md375',1,'']]],
  ['specific_20apis_107',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md381',1,'']]],
  ['specific_20behavior_3a_20connect_20accept_20recv_20and_20send_108',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['specific_20considerations_109',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md412',1,'']]],
  ['specific_20notes_110',['specific Notes',['../group__socketopts.html#autotoc_md1056',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1067',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1076',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1087',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md1058',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1068',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1078',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1089',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1060',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1069',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1080',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md1091',1,'🧿 UnixSocket-specific Notes']]],
  ['specific_20tests_3a_111',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md432',1,'']]],
  ['standards_112',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md539',1,'']]],
  ['start_20examples_113',['🚀 Quick Start Examples',['../index.html#autotoc_md482',1,'']]],
  ['state_114',['What is a Socket State?',['../group__socket__states.html#autotoc_md337',1,'']]],
  ['state_20handling_115',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md83',1,'']]],
  ['state_20transitions_116',['TCP State Transitions',['../group__socket__states.html#autotoc_md342',1,'']]],
  ['states_117',['Main TCP Socket States',['../group__socket__states.html#autotoc_md340',1,'']]],
  ['std_3a_3aarray_118',['Example: Reading into a fixed-size &lt;span class=&quot;tt&quot;&gt;std::array&lt;/span&gt;',['../group__udp.html#autotoc_md710',1,'']]],
  ['std_3a_3astring_119',['Example: Reading into a &lt;span class=&quot;tt&quot;&gt;std::string&lt;/span&gt;',['../group__udp.html#autotoc_md708',1,'']]],
  ['std_3a_3avector_120',['Example: Reading into a &lt;span class=&quot;tt&quot;&gt;std::vector&amp;lt;std::byte&amp;gt;&lt;/span&gt;',['../group__udp.html#autotoc_md709',1,'']]],
  ['step_20by_20step_20posix_20style_121',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['step_20posix_20style_122',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['steps_123',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['strategy_20for_20jsocketpp_124',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['stream_20sockets_20tcp_125',['Stream Sockets TCP',['../group__sockets__theory.html#autotoc_md358',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md366',1,'Stream Sockets (TCP)']]],
  ['structure_126',['Request Code Structure',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md211',1,'']]],
  ['structure_20behavior_127',['Hints Structure Behavior',['../group__internal.html#autotoc_md567',1,'']]],
  ['stubbing_20socket_20api_20for_20unit_20tests_3a_128',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md433',1,'']]],
  ['style_129',['Style',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'<b>a) Constructor Does All (Java Default Style)</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'<b>b) Fully Step-by-Step (POSIX Style)</b>']]],
  ['style_20cross_20platform_20socket_20library_20for_20modern_20c_2020_130',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['style_20guidelines_131',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md526',1,'']]],
  ['submission_132',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['submit_20a_20pull_20request_20to_20cci_133',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['submit_20to_20the_20vcpkg_20registry_134',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md450',1,'']]],
  ['submitting_20pull_20requests_135',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md524',1,'']]],
  ['summary_136',['Summary',['../group__address__reuse.html#autotoc_md94',1,'🧠 Summary'],['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'9. Summary'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md259',1,'Windows Version Support Summary']]],
  ['summary_20by_20operation_137',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md1149',1,'']]],
  ['summary_20of_20java’s_20design_20trade_20off_138',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['summary_20table_139',['Summary Table',['../group__address__reuse.html#autotoc_md123',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md310',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md290',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md387',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md107',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md332',1,'Summary Table']]],
  ['summary_20table_3a_20waiting_20for_20readiness_140',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['support_141',['Support',['../group__socketopts.html#autotoc_md1209',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1216',1,'🔀 Platform Support'],['../index.html#autotoc_md467',1,'🔧 Platform &amp; Toolchain Support'],['../group__socket-options.html#autotoc_md298',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md881',1,'Platform Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md218',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md229',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md240',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md251',1,'Windows Support']]],
  ['support_20summary_142',['Windows Version Support Summary',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md259',1,'']]],
  ['supported_20classes_143',['Supported Classes',['../classjsocketpp_1_1SocketOptions.html#autotoc_md1043',1,'']]],
  ['supported_20inputs_144',['Supported Inputs',['../namespacejsocketpp_1_1internal.html#autotoc_md588',1,'']]],
  ['supported_20types_145',['Supported Types',['../group__tcp.html#autotoc_md944',1,'']]],
  ['syntax_146',['Syntax',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md210',1,'Syntax'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md223',1,'Syntax'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md234',1,'Syntax'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md245',1,'Syntax']]]
];
