var searchData=
[
  ['families_0',['Families',['../group__underlying__socket__api.html#autotoc_md395',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md373',1,'3. Socket Address Families']]],
  ['faq_1',['❓ FAQ',['../index.html#autotoc_md506',1,'']]],
  ['fcntl_20ioctlsocket_2',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['fcntl_20unix_20linux_3',['2. fcntl (Unix/Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md221',1,'']]],
  ['features_4',['Features',['../group__underlying__socket__api.html#autotoc_md405',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md415',1,'Advanced Socket API Features'],['../classjsocketpp_1_1MulticastSocket.html#autotoc_md776',1,'Features'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md603',1,'Key Features'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md780',1,'Key Features'],['../classjsocketpp_1_1Socket.html#autotoc_md875',1,'Key Features'],['../group__tcp.html#autotoc_md883',1,'Key Features'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1223',1,'Main Features']]],
  ['features_20at_20a_20glance_5',['✨ Features at a Glance',['../index.html#autotoc_md465',1,'']]],
  ['features_3a_6',['Key Features:',['../structjsocketpp_1_1DatagramReadOptions.html#autotoc_md600',1,'']]],
  ['fields_7',['Fields',['../structjsocketpp_1_1BufferView.html#autotoc_md544',1,'']]],
  ['final_20thoughts_20and_20best_20practices_8',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md169',1,'']]],
  ['fixed_20size_20container_20std_3a_3aarray_9',['Example — fixed-size container (&lt;span class=&quot;tt&quot;&gt;std::array&amp;lt;char, 512&amp;gt;&lt;/span&gt;)',['../group__udp.html#autotoc_md709',1,'']]],
  ['flexibility_20and_20safety_10',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'']]],
  ['footprint_11',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md471',1,'']]],
  ['for_205_20seconds_20on_20close_12',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1064',1,'']]],
  ['for_20all_20sockets_13',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md301',1,'']]],
  ['for_20conan_20center_20index_20cci_20submission_14',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['for_20cross_20platform_3a_15',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md431',1,'']]],
  ['for_20jsocketpp_16',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md117',1,'']]],
  ['for_20library_20authors_17',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md125',1,'']]],
  ['for_20modern_20c_2020_18',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['for_20multicast_3a_19',['For Multicast:',['../group__socket-options.html#autotoc_md306',1,'']]],
  ['for_20platform_20specific_20tests_3a_20',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md432',1,'']]],
  ['for_20readiness_21',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['for_20the_20socket’s_20lifetime_22',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['for_20unit_20testing_20in_20c_2020_3a_23',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md424',1,'']]],
  ['for_20unit_20tests_3a_24',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md433',1,'']]],
  ['for_20vcpkg_25',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md442',1,'']]],
  ['format_26',['Format',['../group__tcp.html#autotoc_md915',1,'Format'],['../group__tcp.html#autotoc_md931',1,'Format'],['../group__tcp.html#autotoc_md961',1,'Protocol Format'],['../group__tcp.html#autotoc_md964',1,'Protocol Format'],['../group__tcp.html#autotoc_md988',1,'Protocol Format'],['../group__tcp.html#autotoc_md991',1,'Protocol Format']]],
  ['foundations_3a_20network_20models_20and_20data_20encapsulation_27',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md265',1,'']]],
  ['friendly_28',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['fully_20step_20by_20step_20posix_20style_29',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['function_30',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['functions_31',['Functions',['../group__underlying__socket__api.html#autotoc_md394',1,'2.1 Key Functions'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md254',1,'5. Related Functions'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md206',1,'Overview of Functions']]],
  ['further_20reading_32',['Further Reading',['../group__socket-options.html#autotoc_md318',1,'']]]
];
