var searchData=
[
  ['data_0',['Data',['../group__multicast__sockets.html#autotoc_md277',1,'Receiving Multicast Data'],['../group__multicast__sockets.html#autotoc_md276',1,'Sending Multicast Data']]],
  ['data_20encapsulation_1',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md296',1,'']]],
  ['data_20transfer_2',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['datagram_20sockets_20udp_3',['Datagram Sockets UDP',['../group__sockets__theory.html#autotoc_md390',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md398',1,'Datagram Sockets (UDP)']]],
  ['datagrams_20and_20segments_4',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md300',1,'']]],
  ['datagrams_3a_20the_20connectionless_20approach_5',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md298',1,'']]],
  ['datagramsocket_20multicastsocket_6',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md336',1,'']]],
  ['datagramsocket_20specific_20notes_7',['DatagramSocket specific Notes',['../group__socketopts.html#autotoc_md1000',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1010',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1020',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1031',1,'📡 DatagramSocket-specific Notes']]],
  ['dedicated_20methods_20vs_20generic_20methods_8',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md343',1,'']]],
  ['default_20buffer_20size_9',['What is the default buffer size?',['../index.html#autotoc_md546',1,'']]],
  ['default_20in_20jsocketpp_20_3a_10',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['default_20style_11',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['default_3a_208192_208_20kib_12',['Rationale (default: 8192 / 8 KiB)',['../group__core.html#autotoc_md587',1,'']]],
  ['defaults_13',['Constructor Defaults',['../group__address__reuse.html#autotoc_md119',1,'']]],
  ['definition_14',['🔐 Definition',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['demonstrating_20binding_20behavior_15',['Example: Demonstrating Binding Behavior',['../group__socket__binding.html#autotoc_md73',1,'']]],
  ['depth_16',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md388',1,'']]],
  ['depth_20overview_20of_20address_20reuse_20options_17',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['description_18',['Description',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md209',1,'Description'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md222',1,'Description'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md233',1,'Description'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md244',1,'Description']]],
  ['design_20rationale_19',['Design Rationale',['../group__async__io.html#autotoc_md146',1,'']]],
  ['design_20recommendations_20',['Design Recommendations',['../group__socket-options.html#autotoc_md347',1,'']]],
  ['design_20trade_20off_21',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['designs_3a_20pros_20and_20cons_22',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['detailed_20notes_23',['Detailed Notes',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md261',1,'']]],
  ['details_24',['Details',['../group__udp.html#autotoc_md668',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md679',1,'Implementation Details'],['../group__tcp.html#autotoc_md827',1,'Implementation Details'],['../group__tcp.html#autotoc_md881',1,'Implementation Details'],['../group__tcp.html#autotoc_md884',1,'Implementation Details'],['../group__tcp.html#autotoc_md889',1,'Implementation Details'],['../group__tcp.html#autotoc_md891',1,'Implementation Details'],['../group__tcp.html#autotoc_md894',1,'Implementation Details'],['../group__tcp.html#autotoc_md896',1,'Implementation Details'],['../group__tcp.html#autotoc_md898',1,'Implementation Details'],['../group__tcp.html#autotoc_md900',1,'Implementation Details'],['../group__tcp.html#autotoc_md902',1,'Implementation Details'],['../group__tcp.html#autotoc_md905',1,'Implementation Details'],['../group__tcp.html#autotoc_md908',1,'Implementation Details'],['../group__tcp.html#autotoc_md910',1,'Implementation Details'],['../group__tcp.html#autotoc_md914',1,'Implementation Details'],['../group__tcp.html#autotoc_md916',1,'Implementation Details'],['../group__tcp.html#autotoc_md918',1,'Implementation Details'],['../group__tcp.html#autotoc_md924',1,'Implementation Details'],['../group__tcp.html#autotoc_md925',1,'Implementation Details'],['../group__tcp.html#autotoc_md927',1,'Implementation Details'],['../group__tcp.html#autotoc_md929',1,'Implementation Details'],['../group__tcp.html#autotoc_md932',1,'Implementation Details'],['../group__tcp.html#autotoc_md935',1,'Implementation Details'],['../group__tcp.html#autotoc_md937',1,'Implementation Details'],['../group__tcp.html#autotoc_md939',1,'Implementation Details'],['../group__tcp.html#autotoc_md943',1,'Implementation Details'],['../group__tcp.html#autotoc_md945',1,'Implementation Details'],['../group__tcp.html#autotoc_md949',1,'Implementation Details'],['../group__tcp.html#autotoc_md952',1,'Implementation Details'],['../group__tcp.html#autotoc_md954',1,'Implementation Details'],['../group__tcp.html#autotoc_md964',1,'Implementation Details']]],
  ['developer_20control_25',['Developer Control',['../group__address__reuse.html#autotoc_md120',1,'']]],
  ['developer_20tooling_26',['🛠 Developer Tooling',['../index.html#autotoc_md528',1,'']]],
  ['device_20driver_20linux_27',['Example: Custom Device Driver (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md217',1,'']]],
  ['deviceiocontrol_20windows_28',['DeviceIoControl (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md257',1,'']]],
  ['differences_20from_20posix_20bsd_29',['Differences from POSIX/BSD',['../group__multicast__sockets.html#autotoc_md281',1,'']]],
  ['differences_3a_20packets_20datagrams_20and_20segments_30',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md300',1,'']]],
  ['disable_20nagle’s_20algorithm_20to_20reduce_20latency_31',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1109',1,'']]],
  ['disadvantages_32',['Advantages and Disadvantages',['../group__network__data__units.html#autotoc_md303',1,'']]],
  ['documentation_33',['Documentation',['../index.html#autotoc_md524',1,'📚 Documentation'],['../md_CONTRIBUTING.html#autotoc_md563',1,'6. Documentation']]],
  ['does_34',['Does',['../group__address__reuse.html#autotoc_md115',1,'A Better Alternative: What <span class="tt">jsocketpp</span> Does'],['../group__address__reuse.html#autotoc_md110',1,'What Java Does']]],
  ['does_35',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['does_20“binding_20to_20all_20interfaces”_20mean_36',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['does_20all_20java_20default_20style_37',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['does_20all_20steps_38',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['does_20connect_20bind_20to_20a_20local_20address_39',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['does_20error_20handling_20work_40',['How does error handling work?',['../index.html#autotoc_md540',1,'']]],
  ['does_20it_20work_20on_20windows_41',['Does it work on Windows?',['../index.html#autotoc_md544',1,'']]],
  ['does_20the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_42',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['domain_20socket_20ipc_43',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md520',1,'']]],
  ['domain_20sockets_44',['Unix Domain Sockets',['../group__sockets__theory.html#autotoc_md400',1,'']]],
  ['domain_20sockets_20local_20ipc_45',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md392',1,'']]],
  ['domain_20sockets_20unixsocket_46',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md339',1,'']]],
  ['drawbacks_20of_20select_47',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md309',1,'']]],
  ['driver_20linux_48',['Example: Custom Device Driver (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md217',1,'']]]
];
