var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md123',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md240',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md220',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md317',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md107',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md262',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md224',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md293',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['tcp_4',['TCP',['../group__sockets__theory.html#autotoc_md288',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md296',1,'Stream Sockets (TCP)']]],
  ['tcp_20and_20udp_5',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['tcp_20echo_20server_6',['🧵 TCP Echo Server',['../index.html#autotoc_md413',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_7',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md333',1,'']]],
  ['tcp_20socket_20lifecycle_8',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md269',1,'']]],
  ['tcp_20socket_20states_9',['Main TCP Socket States',['../group__socket__states.html#autotoc_md270',1,'']]],
  ['tcp_20sockets_10',['TCP Sockets',['../group__socket__binding.html#autotoc_md66',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md70',1,'TCP Sockets']]],
  ['tcp_20sockets_20socket_20serversocket_11',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md233',1,'']]],
  ['tcp_20state_20transitions_12',['TCP State Transitions',['../group__socket__states.html#autotoc_md272',1,'']]],
  ['test_20cases_20to_20consider_3a_13',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md366',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_14',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md361',1,'']]],
  ['test_20the_20port_20locally_15',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md378',1,'']]],
  ['test_20the_20recipe_20locally_16',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['test_20with_20mocking_3a_17',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md365',1,'']]],
  ['test_3a_18',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md360',1,'']]],
  ['test_5fpackage_19',['test_package',['../group__conan__publish__guide.html#autotoc_md194',1,'']]],
  ['testing_20',['Testing',['../index.html#autotoc_md425',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md460',1,'5. Testing']]],
  ['testing_20in_20c_2020_3a_21',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md354',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_22',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md357',1,'']]],
  ['tests_23',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_24',['Tests:',['../group__unit__tests.html#autotoc_md353',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md358',1,'2. <b>Integration Tests</b>:'],['../group__unit__tests.html#autotoc_md362',1,'3.1 <b>Using CMake for Platform-Specific Tests</b>:'],['../group__unit__tests.html#autotoc_md363',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['the_20basics_25',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['the_20connect_20function_26',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20constructor_27',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20default_20buffer_20size_28',['What is the default buffer size?',['../index.html#autotoc_md445',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_29',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_30',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md309',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_31',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['the_20library_32',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_33',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md305',1,'']]],
  ['the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_34',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20makefile_35',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20port_20in_20the_20constructor_36',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['the_20port_20locally_37',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md378',1,'']]],
  ['the_20recipe_20locally_38',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['the_20role_20of_20the_20connect_20function_39',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['the_20same_20port_40',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['the_20socket’s_20lifetime_41',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['the_20socket_20api_42',['the Socket API',['../group__underlying__socket__api.html#autotoc_md322',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md323',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md331',1,'4. Protocols and the Socket API']]],
  ['the_20vcpkg_20registry_43',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md380',1,'']]],
  ['this_20is_20problematic_20on_20windows_44',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['this_20library_45',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md252',1,'']]],
  ['this_20relates_20to_20jsocketpp_46',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md278',1,'']]],
  ['thoughts_20and_20best_20practices_47',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md169',1,'']]],
  ['thread_20safety_48',['Thread Safety',['../group__tcp.html#autotoc_md682',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md691',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md700',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md713',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md722',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md738',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md751',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md676',1,'Thread Safety'],['../group__tcp.html#autotoc_md761',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md770',1,'Thread Safety'],['../group__tcp.html#autotoc_md836',1,'Thread Safety']]],
  ['throws_49',['Throws',['../group__internal.html#autotoc_md496',1,'Throws'],['../group__udp.html#autotoc_md532',1,'Throws']]],
  ['timeout_50',['timeout',['../group__socketopts.html#autotoc_md1017',1,'Example: Set a 3-second receive timeout'],['../group__socketopts.html#autotoc_md1022',1,'Example: Set a 5-second send timeout']]],
  ['timeout_20behavior_51',['Timeout Behavior',['../group__tcp.html#autotoc_md678',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md687',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md696',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md707',1,'⏱ Timeout Behavior']]],
  ['timeout_20handling_52',['⏱ Timeout Handling',['../group__udp.html#autotoc_md554',1,'']]],
  ['timeout_20semantics_53',['Timeout Semantics',['../group__tcp.html#autotoc_md760',1,'']]],
  ['timeouts_54',['Timeouts',['../group__async__io.html#autotoc_md145',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md141',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md142',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_55',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md143',1,'']]],
  ['tips_20and_20best_20practices_56',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md384',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices']]],
  ['to_57',['Applies to',['../group__core.html#autotoc_md480',1,'']]],
  ['to_20a_20local_20address_58',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['to_20adjust_59',['When to Adjust',['../group__core.html#autotoc_md483',1,'']]],
  ['to_20all_20interfaces”_20mean_60',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['to_20all_20interfaces_61',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['to_20cci_62',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['to_20consider_3a_63',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md366',1,'']]],
  ['to_20jsocketpp_64',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md278',1,'How This Relates to <span class="tt">jsocketpp</span>']]],
  ['to_20linger_20for_205_20seconds_20on_20close_65',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md955',1,'']]],
  ['to_20mock_20recv_20and_20send_3a_66',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md356',1,'']]],
  ['to_20peer_20model_67',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md329',1,'']]],
  ['to_20reduce_20latency_68',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1057',1,'']]],
  ['to_20the_20same_20port_69',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['to_20the_20socket_20api_70',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md322',1,'']]],
  ['to_20the_20vcpkg_20registry_71',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md380',1,'']]],
  ['to_20use_72',['When to Use',['../group__socketopts.html#autotoc_md1110',1,'']]],
  ['toolchain_20support_73',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md397',1,'']]],
  ['tooling_74',['🛠 Developer Tooling',['../index.html#autotoc_md427',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_75',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md354',1,'']]],
  ['topics_76',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md315',1,'']]],
  ['trade_20off_77',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_78',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['transfer_79',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['transferred_80',['Transferred',['../group__udp.html#autotoc_md537',1,'Ownership Transferred'],['../group__udp.html#autotoc_md535',1,'What Is Transferred']]],
  ['transitions_81',['TCP State Transitions',['../group__socket__states.html#autotoc_md272',1,'']]],
  ['troubleshooting_82',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['true_83',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md788',1,'']]],
  ['true_20matters_84',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md765',1,'']]],
  ['type_85',['Type',['../group__socketopts.html#autotoc_md1081',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1090',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md230',1,'Common Options by Socket Type']]],
  ['types_86',['Types',['../group__socketopts.html#autotoc_md1037',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md326',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md293',1,'2.5. Comparison Table: Socket Types'],['../group__tcp.html#autotoc_md834',1,'Supported Types']]],
  ['types_20of_20sockets_20in_20depth_87',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md287',1,'']]],
  ['types_20work_88',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['typical_20usage_89',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md670',1,'']]],
  ['typical_20usage_20example_90',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md767',1,'']]],
  ['typical_20use_20cases_91',['🧰 Typical Use Cases',['../index.html#autotoc_md391',1,'']]]
];
