var searchData=
[
  ['b_20fully_20step_20by_20step_20posix_20style_0',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['b_20portability_1',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md36',1,'']]],
  ['based_20on_20connection_20mode_2',['🔁 Behavior Based on Connection Mode',['../group__udp.html#autotoc_md531',1,'']]],
  ['basic_20api_3',['Basic API',['../classjsocketpp_1_1ServerSocket.html#autotoc_md599',1,'']]],
  ['basics_4',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['behavior_5',['Behavior',['../group__tcp.html#autotoc_md605',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md614',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md623',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md634',1,'⏱ Timeout Behavior'],['../group__address__reuse.html#autotoc_md67',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md645',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md663',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md674',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md836',1,'⚙️ Behavior'],['../group__socketopts.html#autotoc_md1004',1,'⚠️ Platform Behavior'],['../group__tcp.html#autotoc_md734',1,'🌍 Behavior'],['../group__socketopts.html#autotoc_md927',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md932',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md937',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md942',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md947',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md958',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md967',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md995',1,'🔀 Platform Behavior'],['../group__tcp.html#autotoc_md654',1,'🔁 Blocking Behavior'],['../group__socketopts.html#autotoc_md981',1,'🔐 Platform Behavior'],['../group__udp.html#autotoc_md478',1,'Behavior'],['../group__udp.html#autotoc_md485',1,'Behavior'],['../group__udp.html#autotoc_md500',1,'Behavior'],['../group__udp.html#autotoc_md502',1,'Behavior'],['../group__udp.html#autotoc_md504',1,'Behavior'],['../group__udp.html#autotoc_md510',1,'Behavior'],['../group__udp.html#autotoc_md554',1,'Behavior'],['../group__udp.html#autotoc_md561',1,'Behavior'],['../group__socketopts.html#autotoc_md914',1,'Behavior'],['../group__tcp.html#autotoc_md718',1,'IPv4-Mapped IPv6 Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md588',1,'Platform Behavior'],['../group__tcp.html#autotoc_md686',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md895',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md898',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md902',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md908',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md920',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md924',1,'Platform Behavior'],['../group__tcp.html#autotoc_md828',1,'Protocol Behavior'],['../group__address__reuse.html#autotoc_md95',1,'Recommended Behavior']]],
  ['behavior_20based_20on_20connection_20mode_6',['🔁 Behavior Based on Connection Mode',['../group__udp.html#autotoc_md531',1,'']]],
  ['behavior_20by_20connection_20mode_7',['Behavior by Connection Mode',['../group__udp.html#autotoc_md545',1,'']]],
  ['behavior_20by_20mode_8',['🔁 Behavior by Mode',['../group__udp.html#autotoc_md538',1,'']]],
  ['behavior_20characteristics_9',['Behavior &amp;amp; Characteristics',['../group__udp.html#autotoc_md471',1,'']]],
  ['behavior_20summary_20by_20operation_10',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md951',1,'']]],
  ['behavior_3a_11',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md332',1,'']]],
  ['behavior_3a_20connect_20accept_20recv_20and_20send_12',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['best_20practices_13',['Best Practices',['../group__async__io.html#autotoc_md146',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md155',1,'Best Practices']]],
  ['best_20practices_20recap_14',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['better_20alternative_3a_20what_20jsocketpp_20does_15',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['beyond_20the_20basics_16',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['bind_20listen_20explicit_17',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['bind_20to_20the_20same_20port_18',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['binding_19',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1013',1,'']]],
  ['binding_20to_20all_20interfaces_20',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['blocking_21',['Blocking',['../group__async__io.html#autotoc_md115',1,'What is Blocking?'],['../group__async__io.html#autotoc_md116',1,'What is Non-Blocking?']]],
  ['blocking_20and_20timeouts_22',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md122',1,'']]],
  ['blocking_20behavior_23',['🔁 Blocking Behavior',['../group__tcp.html#autotoc_md654',1,'']]],
  ['blocking_20mode_20on_20a_20client_20socket_24',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md955',1,'']]],
  ['blocking_20mode_3a_25',['Blocking mode:',['../group__async__io.html#autotoc_md127',1,'Blocking mode:'],['../group__async__io.html#autotoc_md131',1,'Blocking mode:'],['../group__async__io.html#autotoc_md135',1,'Blocking mode:'],['../group__async__io.html#autotoc_md138',1,'Blocking mode:']]],
  ['blocking_20mode_3a_26',['blocking mode:',['../group__async__io.html#autotoc_md128',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md132',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md136',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md139',1,'Non-blocking mode:']]],
  ['blocking_20sockets_27',['Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md313',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md323',1,'6.1 Non-Blocking Sockets']]],
  ['blocking_20vs_20non_20blocking_20sockets_28',['🚦 Blocking vs Non-Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'']]],
  ['boost_20asio_29',['Boost Asio',['../index.html#autotoc_md376',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md231',1,'2. Boost.Asio']]],
  ['branching_20code_20of_20conduct_30',['7. Branching &amp;amp; Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'']]],
  ['broadcast_31',['Broadcast',['../group__underlying__socket__api.html#autotoc_md315',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md325',1,'6.3 Multicast and Broadcast']]],
  ['bsd_20posix_20winsock_20apis_32',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['buffer_33',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md692',1,'']]],
  ['buffer_20size_34',['buffer size',['../group__socketopts.html#autotoc_md876',1,'Example: Read configured receive buffer size'],['../index.html#autotoc_md422',1,'What is the default buffer size?']]],
  ['buffer_20size_20notes_35',['Buffer Size Notes',['../group__udp.html#autotoc_md490',1,'']]],
  ['buffering_36',['Buffering',['../group__udp.html#autotoc_md492',1,'']]],
  ['build_37',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['building_20and_20running_20tests_38',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['building_20and_20testing_39',['🧪 Building and Testing',['../index.html#autotoc_md402',1,'']]],
  ['building_20the_20library_40',['Building the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'']]],
  ['by_20connection_20mode_41',['Behavior by Connection Mode',['../group__udp.html#autotoc_md545',1,'']]],
  ['by_20mode_42',['🔁 Behavior by Mode',['../group__udp.html#autotoc_md538',1,'']]],
  ['by_20operation_43',['⏱️ Behavior Summary by Operation',['../group__socketopts.html#autotoc_md951',1,'']]],
  ['by_20socket_20type_44',['by Socket Type',['../group__socketopts.html#autotoc_md993',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1002',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md207',1,'Common Options by Socket Type']]],
  ['by_20step_20posix_20style_45',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]]
];
