var searchData=
[
  ['i_20o_0',['I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md339',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md349',1,'6.4 Asynchronous I/O']]],
  ['i_20use_20jsocketpp_20in_20production_1',['Can I use jsocketpp in production?',['../index.html#autotoc_md441',1,'']]],
  ['if_20autobind_20true_2',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md788',1,'']]],
  ['if_20socket_20is_20ipv6_20only_3',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1094',1,'']]],
  ['implementation_20details_4',['Implementation Details',['../group__udp.html#autotoc_md629',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md620',1,'Implementation Details'],['../group__udp.html#autotoc_md640',1,'Implementation Details'],['../group__tcp.html#autotoc_md775',1,'Implementation Details'],['../group__tcp.html#autotoc_md829',1,'Implementation Details'],['../group__tcp.html#autotoc_md832',1,'Implementation Details'],['../group__tcp.html#autotoc_md837',1,'Implementation Details'],['../group__tcp.html#autotoc_md839',1,'Implementation Details'],['../group__tcp.html#autotoc_md842',1,'Implementation Details'],['../group__tcp.html#autotoc_md844',1,'Implementation Details'],['../group__tcp.html#autotoc_md846',1,'Implementation Details'],['../group__tcp.html#autotoc_md848',1,'Implementation Details'],['../group__tcp.html#autotoc_md850',1,'Implementation Details'],['../group__tcp.html#autotoc_md853',1,'Implementation Details'],['../group__tcp.html#autotoc_md856',1,'Implementation Details'],['../group__tcp.html#autotoc_md858',1,'Implementation Details'],['../group__tcp.html#autotoc_md862',1,'Implementation Details'],['../group__tcp.html#autotoc_md864',1,'Implementation Details'],['../group__tcp.html#autotoc_md866',1,'Implementation Details'],['../group__tcp.html#autotoc_md872',1,'Implementation Details'],['../group__tcp.html#autotoc_md873',1,'Implementation Details'],['../group__tcp.html#autotoc_md875',1,'Implementation Details'],['../group__tcp.html#autotoc_md877',1,'Implementation Details'],['../group__tcp.html#autotoc_md880',1,'Implementation Details'],['../group__tcp.html#autotoc_md883',1,'Implementation Details'],['../group__tcp.html#autotoc_md885',1,'Implementation Details'],['../group__tcp.html#autotoc_md887',1,'Implementation Details'],['../group__tcp.html#autotoc_md891',1,'Implementation Details'],['../group__tcp.html#autotoc_md893',1,'Implementation Details'],['../group__tcp.html#autotoc_md897',1,'Implementation Details'],['../group__tcp.html#autotoc_md900',1,'Implementation Details'],['../group__tcp.html#autotoc_md902',1,'Implementation Details'],['../group__tcp.html#autotoc_md912',1,'Implementation Details']]],
  ['implementation_20notes_5',['Implementation Notes',['../group__tcp.html#autotoc_md904',1,'']]],
  ['implications_6',['Practical Implications',['../group__socket__states.html#autotoc_md276',1,'']]],
  ['implications_7',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['implicit_20binding_20in_20tcp_20and_20udp_8',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['in_20action_3a_20practical_20examples_9',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md332',1,'']]],
  ['in_20c_2020_3a_10',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md354',1,'']]],
  ['in_20constructor_20bind_20listen_20explicit_11',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['in_20depth_12',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md287',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_13',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['in_20jsocketpp_20_3a_14',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['in_20production_15',['Can I use jsocketpp in production?',['../index.html#autotoc_md441',1,'']]],
  ['in_20tcp_20and_20udp_16',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['in_20the_20constructor_17',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['in_20your_20project_18',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_19',['Includes:',['../group__core.html#autotoc_md476',1,'']]],
  ['incompatibility_20',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md91',1,'']]],
  ['index_20cci_20submission_21',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['information_20and_20configuration_22',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['initialization_20and_20cleanup_3a_23',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md357',1,'']]],
  ['initialization_3a_20posix_20approach_24',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['installation_25',['📦 Installation',['../index.html#autotoc_md405',1,'']]],
  ['integration_26',['🔧 Manual Integration',['../index.html#autotoc_md410',1,'']]],
  ['integration_20in_20your_20project_27',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_28',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md365',1,'']]],
  ['integration_20test_3a_29',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md360',1,'']]],
  ['integration_20tests_3a_30',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md358',1,'']]],
  ['intended_20usage_31',['Intended Usage',['../classjsocketpp_1_1SocketOptions.html#autotoc_md932',1,'']]],
  ['interfaces”_20mean_32',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['interfaces_33',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['internal_20buffer_34',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md768',1,'']]],
  ['internally_35',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['introduction_36',['Introduction',['../group__socket__binding.html#autotoc_md63',1,'Introduction'],['../group__sockets__theory.html#autotoc_md283',1,'Introduction']]],
  ['introduction_20to_20the_20socket_20api_37',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md322',1,'']]],
  ['ipc_38',['IPC',['../index.html#autotoc_md419',1,'🧷 UNIX Domain Socket (IPC)'],['../group__sockets__theory.html#autotoc_md291',1,'2.4. Unix Domain Sockets (Local IPC)']]],
  ['ipv4_20mapped_20ipv6_20behavior_39',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md796',1,'']]],
  ['ipv6_20behavior_40',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md796',1,'']]],
  ['ipv6_20handling_41',['IPv6 Handling',['../group__udp.html#autotoc_md574',1,'IPv6 Handling'],['../group__udp.html#autotoc_md580',1,'IPv6 Handling'],['../group__udp.html#autotoc_md594',1,'IPv6 Handling']]],
  ['ipv6_20only_42',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1094',1,'']]],
  ['is_20a_20socket_43',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md285',1,'']]],
  ['is_20a_20socket_20state_44',['What is a Socket State?',['../group__socket__states.html#autotoc_md267',1,'']]],
  ['is_20blocking_45',['What is Blocking?',['../group__async__io.html#autotoc_md138',1,'']]],
  ['is_20connected_20udp_46',['🔌 What Is Connected UDP?',['../group__udp.html#autotoc_md548',1,'']]],
  ['is_20ipv6_20only_47',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1094',1,'']]],
  ['is_20jsocketpp_20async_48',['Is jsocketpp async?',['../index.html#autotoc_md437',1,'']]],
  ['is_20multicast_49',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md664',1,'']]],
  ['is_20non_20blocking_50',['What is Non-Blocking?',['../group__async__io.html#autotoc_md139',1,'']]],
  ['is_20problematic_20on_20windows_51',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['is_20socket_20binding_52',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md64',1,'']]],
  ['is_20the_20default_20buffer_20size_53',['What is the default buffer size?',['../index.html#autotoc_md445',1,'']]],
  ['is_20transferred_54',['What Is Transferred',['../group__udp.html#autotoc_md535',1,'']]],
  ['is_20udp_55',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md501',1,'']]],
  ['is_20used_56',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md206',1,'']]],
  ['issues_57',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md452',1,'']]],
  ['it_20actually_20does_58',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['it_20work_20on_20windows_59',['Does it work on Windows?',['../index.html#autotoc_md443',1,'']]],
  ['it_20works_20internally_60',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['its_20limitations_61',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md109',1,'']]]
];
