var searchData=
[
  ['i_20o_0',['I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md458',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md468',1,'6.4 Asynchronous I/O']]],
  ['i_20use_20jsocketpp_20in_20production_1',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['iana_20s_20role_3a_20orchestrating_20ipv6_2',['IANA&apos;s Role: Orchestrating IPv6',['../group__mastering__ipv6.html#autotoc_md48',1,'']]],
  ['iana_3a_20guardians_20of_20ipv4_20allocation_3',['IANA: Guardians of IPv4 Allocation',['../group__mastering__ipv4.html#autotoc_md39',1,'']]],
  ['if_20autobind_20true_4',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['if_20socket_20is_20ipv6_20only_5',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['igmp_6',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['implementation_20details_7',['Implementation Details',['../group__udp.html#autotoc_md686',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md697',1,'Implementation Details'],['../group__tcp.html#autotoc_md845',1,'Implementation Details'],['../group__tcp.html#autotoc_md899',1,'Implementation Details'],['../group__tcp.html#autotoc_md902',1,'Implementation Details'],['../group__tcp.html#autotoc_md907',1,'Implementation Details'],['../group__tcp.html#autotoc_md909',1,'Implementation Details'],['../group__tcp.html#autotoc_md912',1,'Implementation Details'],['../group__tcp.html#autotoc_md914',1,'Implementation Details'],['../group__tcp.html#autotoc_md916',1,'Implementation Details'],['../group__tcp.html#autotoc_md918',1,'Implementation Details'],['../group__tcp.html#autotoc_md920',1,'Implementation Details'],['../group__tcp.html#autotoc_md923',1,'Implementation Details'],['../group__tcp.html#autotoc_md926',1,'Implementation Details'],['../group__tcp.html#autotoc_md928',1,'Implementation Details'],['../group__tcp.html#autotoc_md932',1,'Implementation Details'],['../group__tcp.html#autotoc_md934',1,'Implementation Details'],['../group__tcp.html#autotoc_md936',1,'Implementation Details'],['../group__tcp.html#autotoc_md942',1,'Implementation Details'],['../group__tcp.html#autotoc_md943',1,'Implementation Details'],['../group__tcp.html#autotoc_md945',1,'Implementation Details'],['../group__tcp.html#autotoc_md947',1,'Implementation Details'],['../group__tcp.html#autotoc_md950',1,'Implementation Details'],['../group__tcp.html#autotoc_md953',1,'Implementation Details'],['../group__tcp.html#autotoc_md955',1,'Implementation Details'],['../group__tcp.html#autotoc_md957',1,'Implementation Details'],['../group__tcp.html#autotoc_md961',1,'Implementation Details'],['../group__tcp.html#autotoc_md963',1,'Implementation Details'],['../group__tcp.html#autotoc_md967',1,'Implementation Details'],['../group__tcp.html#autotoc_md970',1,'Implementation Details'],['../group__tcp.html#autotoc_md972',1,'Implementation Details'],['../group__tcp.html#autotoc_md982',1,'Implementation Details']]],
  ['implementation_20notes_8',['Implementation Notes',['../group__tcp.html#autotoc_md974',1,'']]],
  ['implications_9',['Practical Implications',['../group__socket__states.html#autotoc_md395',1,'']]],
  ['implications_10',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['implicit_20binding_20in_20tcp_20and_20udp_11',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['in_20action_3a_20practical_20examples_12',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md451',1,'']]],
  ['in_20c_13',['in C',['../group__multicast__sockets.html#autotoc_md297',1,'Example: Receiver in C'],['../group__multicast__sockets.html#autotoc_md296',1,'Example: Sender (Broadcaster) in C']]],
  ['in_20c_2020_3a_14',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['in_20c_20winsock_15',['in C Winsock',['../group__multicast__sockets.html#autotoc_md302',1,'Example: Receiver in C++ (Winsock)'],['../group__multicast__sockets.html#autotoc_md301',1,'Example: Sender in C++ (Winsock)']]],
  ['in_20constructor_20bind_20listen_20explicit_16',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['in_20depth_17',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md406',1,'']]],
  ['in_20depth_18',['Multicast Addresses: &lt;span class=&quot;tt&quot;&gt;ff00::/8&lt;/span&gt; in Depth',['../group__mastering__ipv6.html#autotoc_md50',1,'']]],
  ['in_20depth_20overview_20of_20address_20reuse_20options_19',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['in_20ipv6_3a_20flexible_20address_20allocation_20',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['in_20jsocketpp_20_3a_21',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md123',1,'']]],
  ['in_20production_22',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['in_20tcp_23',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md317',1,'']]],
  ['in_20tcp_20and_20udp_24',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['in_20the_20constructor_25',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['in_20your_20project_26',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['includes_3a_27',['Includes:',['../group__core.html#autotoc_md595',1,'']]],
  ['incompatibility_28',['⚠️ Incompatibility',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['index_20cci_20submission_29',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['information_20and_20configuration_30',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['initialization_20and_20cleanup_3a_31',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md476',1,'']]],
  ['initialization_3a_20posix_20approach_32',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'']]],
  ['inputs_33',['Supported Inputs',['../namespacejsocketpp_1_1internal.html#autotoc_md637',1,'']]],
  ['installation_34',['📦 Installation',['../index.html#autotoc_md524',1,'']]],
  ['integration_35',['🔧 Manual Integration',['../index.html#autotoc_md529',1,'']]],
  ['integration_20in_20your_20project_36',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['integration_20test_20with_20mocking_3a_37',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md484',1,'']]],
  ['integration_20test_3a_38',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md479',1,'']]],
  ['integration_20tests_3a_39',['2. &lt;b&gt;Integration Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md477',1,'']]],
  ['intended_20usage_40',['Intended Usage',['../classjsocketpp_1_1SocketOptions.html#autotoc_md1002',1,'']]],
  ['interface_20list_20windows_41',['Example: Get Interface List (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md268',1,'']]],
  ['interfaces”_20mean_42',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['interfaces_43',['Interfaces',['../group__bind__interfaces.html#autotoc_md194',1,'Example: Binding to All Interfaces'],['../group__multicast__sockets.html#autotoc_md304',1,'Handling Multiple Interfaces']]],
  ['internal_20buffer_44',['Internal Buffer',['../classjsocketpp_1_1Socket.html#autotoc_md838',1,'']]],
  ['internal_20mechanism_45',['🔧 Internal Mechanism',['../group__internal.html#autotoc_md628',1,'']]],
  ['internal_20use_46',['Example (internal use)',['../group__udp.html#autotoc_md723',1,'']]],
  ['internally_47',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['internet_20group_20management_20protocol_20igmp_48',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['introduction_49',['Introduction',['../group__socket__binding.html#autotoc_md81',1,'Introduction'],['../group__sockets__theory.html#autotoc_md402',1,'Introduction']]],
  ['introduction_20to_20multicast_20sockets_50',['Introduction to Multicast Sockets',['../group__multicast__sockets.html#autotoc_md283',1,'']]],
  ['introduction_20to_20the_20socket_20api_51',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md441',1,'']]],
  ['ioctl_20fcntl_20ioctlsocket_52',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ioctl_20unix_20linux_53',['1. ioctl (Unix/Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md226',1,'']]],
  ['ioctlsocket_54',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['ioctlsocket_20windows_55',['3. ioctlsocket (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md250',1,'']]],
  ['ip_20addresses_56',['Private vs. Public IP Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'']]],
  ['ip_20addresses_3a_20unicast_20multicast_20broadcast_20and_20anycast_57',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['ip_20multicast_20fundamentals_58',['IP Multicast Fundamentals',['../group__multicast__sockets.html#autotoc_md284',1,'']]],
  ['ipc_59',['IPC',['../index.html#autotoc_md538',1,'🧷 UNIX Domain Socket (IPC)'],['../group__sockets__theory.html#autotoc_md410',1,'2.4. Unix Domain Sockets (Local IPC)']]],
  ['ipv4_20address_20structure_3a_20the_20foundation_60',['IPv4 Address Structure: The Foundation',['../group__mastering__ipv4.html#autotoc_md37',1,'']]],
  ['ipv4_20allocation_61',['IANA: Guardians of IPv4 Allocation',['../group__mastering__ipv4.html#autotoc_md39',1,'']]],
  ['ipv4_20features_3a_20beyond_20addressing_62',['Key IPv4 Features: Beyond Addressing',['../group__mastering__ipv4.html#autotoc_md42',1,'']]],
  ['ipv4_20mapped_20ipv6_20behavior_63',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md866',1,'']]],
  ['ipv4_20picture_64',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['ipv6_65',['IANA&apos;s Role: Orchestrating IPv6',['../group__mastering__ipv6.html#autotoc_md48',1,'']]],
  ['ipv6_20address_20structure_3a_20the_20foundation_66',['IPv6 Address Structure: The Foundation',['../group__mastering__ipv6.html#autotoc_md46',1,'']]],
  ['ipv6_20behavior_67',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md866',1,'']]],
  ['ipv6_20features_3a_20beyond_20addressing_68',['Key IPv6 Features: Beyond Addressing',['../group__mastering__ipv6.html#autotoc_md51',1,'']]],
  ['ipv6_20multicast_69',['IPv6 Multicast',['../group__multicast__sockets.html#autotoc_md289',1,'']]],
  ['ipv6_20multicast_20programming_70',['IPv6 Multicast Programming',['../group__multicast__sockets.html#autotoc_md309',1,'']]],
  ['ipv6_20only_71',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['ipv6_20picture_72',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['ipv6_3a_20flexible_20address_20allocation_73',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['is_20a_20packet_74',['What is a Packet?',['../group__network__data__units.html#autotoc_md315',1,'']]],
  ['is_20a_20socket_75',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md404',1,'']]],
  ['is_20a_20socket_20state_76',['What is a Socket State?',['../group__socket__states.html#autotoc_md386',1,'']]],
  ['is_20blocking_77',['What is Blocking?',['../group__async__io.html#autotoc_md156',1,'']]],
  ['is_20ipv6_20only_78',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1164',1,'']]],
  ['is_20jsocketpp_20async_79',['Is jsocketpp async?',['../index.html#autotoc_md556',1,'']]],
  ['is_20multicast_80',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md734',1,'']]],
  ['is_20non_20blocking_81',['What is Non-Blocking?',['../group__async__io.html#autotoc_md157',1,'']]],
  ['is_20problematic_20on_20windows_82',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['is_20socket_20binding_83',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md82',1,'']]],
  ['is_20the_20default_20buffer_20size_84',['What is the default buffer size?',['../index.html#autotoc_md564',1,'']]],
  ['is_20the_20mtu_85',['🔍 What is the MTU?',['../group__udp.html#autotoc_md677',1,'']]],
  ['is_20transferred_86',['What Is Transferred',['../group__udp.html#autotoc_md663',1,'']]],
  ['is_20udp_87',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md652',1,'']]],
  ['is_20used_88',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md325',1,'']]],
  ['issues_89',['Issues',['../md_CONTRIBUTING.html#autotoc_md571',1,'1. Reporting Issues'],['../group__multicast__sockets.html#autotoc_md310',1,'Troubleshooting Common Issues']]],
  ['it_20actually_20does_90',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['it_20up_3a_20the_20full_20ipv4_20picture_91',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['it_20up_3a_20the_20full_20ipv6_20picture_92',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['it_20work_20on_20windows_93',['Does it work on Windows?',['../index.html#autotoc_md562',1,'']]],
  ['it_20works_20internally_94',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['its_20limitations_95',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md127',1,'']]]
];
