var searchData=
[
  ['datagram_20sockets_20udp_0',['Datagram Sockets UDP',['../group__sockets__theory.html#autotoc_md266',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md274',1,'Datagram Sockets (UDP)']]],
  ['datagramsocket_20multicastsocket_1',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md212',1,'']]],
  ['datagramsocket_20specific_20notes_2',['DatagramSocket specific Notes',['../group__socketopts.html#autotoc_md860',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md870',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md880',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md891',1,'📡 DatagramSocket-specific Notes']]],
  ['dedicated_20methods_20vs_20generic_20methods_3',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md219',1,'']]],
  ['default_20buffer_20size_4',['What is the default buffer size?',['../index.html#autotoc_md422',1,'']]],
  ['default_20in_20jsocketpp_20_3a_5',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['default_20style_6',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['defaults_7',['Constructor Defaults',['../group__address__reuse.html#autotoc_md96',1,'']]],
  ['definition_8',['🔐 Definition',['../group__address__reuse.html#autotoc_md65',1,'']]],
  ['depth_9',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['depth_20overview_20of_20address_20reuse_20options_10',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['design_20rationale_11',['Design Rationale',['../group__async__io.html#autotoc_md123',1,'']]],
  ['design_20recommendations_12',['Design Recommendations',['../group__socket-options.html#autotoc_md223',1,'']]],
  ['design_20trade_20off_13',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['designs_3a_20pros_20and_20cons_14',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['details_15',['Details',['../group__udp.html#autotoc_md507',1,'Implementation Details'],['../group__udp.html#autotoc_md568',1,'Implementation Details'],['../group__udp.html#autotoc_md581',1,'Implementation Details'],['../group__tcp.html#autotoc_md699',1,'Implementation Details'],['../group__tcp.html#autotoc_md751',1,'Implementation Details'],['../group__tcp.html#autotoc_md754',1,'Implementation Details'],['../group__tcp.html#autotoc_md759',1,'Implementation Details'],['../group__tcp.html#autotoc_md761',1,'Implementation Details'],['../group__tcp.html#autotoc_md764',1,'Implementation Details'],['../group__tcp.html#autotoc_md766',1,'Implementation Details'],['../group__tcp.html#autotoc_md768',1,'Implementation Details'],['../group__tcp.html#autotoc_md770',1,'Implementation Details'],['../group__tcp.html#autotoc_md772',1,'Implementation Details'],['../group__tcp.html#autotoc_md775',1,'Implementation Details'],['../group__tcp.html#autotoc_md778',1,'Implementation Details'],['../group__tcp.html#autotoc_md780',1,'Implementation Details'],['../group__tcp.html#autotoc_md784',1,'Implementation Details'],['../group__tcp.html#autotoc_md786',1,'Implementation Details'],['../group__tcp.html#autotoc_md788',1,'Implementation Details'],['../group__tcp.html#autotoc_md794',1,'Implementation Details'],['../group__tcp.html#autotoc_md795',1,'Implementation Details'],['../group__tcp.html#autotoc_md797',1,'Implementation Details'],['../group__tcp.html#autotoc_md799',1,'Implementation Details'],['../group__tcp.html#autotoc_md802',1,'Implementation Details'],['../group__tcp.html#autotoc_md805',1,'Implementation Details'],['../group__tcp.html#autotoc_md807',1,'Implementation Details'],['../group__tcp.html#autotoc_md809',1,'Implementation Details'],['../group__tcp.html#autotoc_md813',1,'Implementation Details'],['../group__tcp.html#autotoc_md815',1,'Implementation Details'],['../group__tcp.html#autotoc_md819',1,'Implementation Details'],['../group__tcp.html#autotoc_md822',1,'Implementation Details'],['../group__tcp.html#autotoc_md824',1,'Implementation Details'],['../group__tcp.html#autotoc_md834',1,'Implementation Details']]],
  ['developer_20control_16',['Developer Control',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['developer_20tooling_17',['🛠 Developer Tooling',['../index.html#autotoc_md404',1,'']]],
  ['disable_20nagle’s_20algorithm_20to_20reduce_20latency_18',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md969',1,'']]],
  ['documentation_19',['Documentation',['../index.html#autotoc_md400',1,'📚 Documentation'],['../md_CONTRIBUTING.html#autotoc_md439',1,'6. Documentation']]],
  ['does_20',['Does',['../group__address__reuse.html#autotoc_md92',1,'A Better Alternative: What <span class="tt">jsocketpp</span> Does'],['../group__address__reuse.html#autotoc_md87',1,'What Java Does']]],
  ['does_21',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['does_20“binding_20to_20all_20interfaces”_20mean_22',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['does_20all_20java_20default_20style_23',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['does_20all_20steps_24',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['does_20error_20handling_20work_25',['How does error handling work?',['../index.html#autotoc_md416',1,'']]],
  ['does_20it_20work_20on_20windows_26',['Does it work on Windows?',['../index.html#autotoc_md420',1,'']]],
  ['domain_20socket_20ipc_27',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md396',1,'']]],
  ['domain_20sockets_28',['Unix Domain Sockets',['../group__sockets__theory.html#autotoc_md276',1,'']]],
  ['domain_20sockets_20local_20ipc_29',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['domain_20sockets_20unixsocket_30',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md215',1,'']]],
  ['drawbacks_20of_20select_31',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md185',1,'']]]
];
