var searchData=
[
  ['o_0',['O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md409',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md419',1,'6.4 Asynchronous I/O']]],
  ['of_20a_20simple_20server_20client_20integration_20test_3a_1',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md430',1,'']]],
  ['of_20accepted_20socket_2',['of Accepted Socket',['../group__tcp.html#autotoc_md792',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md801',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md810',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md821',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md854',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md867',1,'⚙️ Configuration of Accepted Socket']]],
  ['of_20address_20reuse_20options_3',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['of_20conduct_4',['of Conduct',['../md_CONTRIBUTING.html#autotoc_md534',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['of_20contents_5',['of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md294',1,'Table of Contents']]],
  ['of_20epoll_6',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md282',1,'']]],
  ['of_20functions_7',['Overview of Functions',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md206',1,'']]],
  ['of_20java’s_20design_20trade_20off_8',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['of_20operation_9',['Modes of Operation',['../group__tcp.html#autotoc_md1022',1,'']]],
  ['of_20poll_10',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md280',1,'']]],
  ['of_20select_11',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md278',1,'']]],
  ['of_20sockets_20in_20depth_12',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md357',1,'']]],
  ['of_20the_20connect_20function_13',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['of_20the_20socket_20api_14',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md393',1,'']]],
  ['off_15',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['on_20a_20client_20socket_16',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1155',1,'']]],
  ['on_20close_17',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1067',1,'']]],
  ['on_20connection_20mode_18',['on Connection Mode',['../group__udp.html#autotoc_md665',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md672',1,'🔁 Behavior Based on Connection Mode']]],
  ['on_20mode_19',['🔁 Behavior Based on Mode',['../group__udp.html#autotoc_md749',1,'']]],
  ['on_20unix_20linux_3a_20',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['on_20windows_21',['on Windows',['../index.html#autotoc_md513',1,'Does it work on Windows?'],['../group__address__reuse.html#autotoc_md111',1,'Why This is Problematic on Windows']]],
  ['on_20windows_3a_22',['On Windows:',['../group__address__reuse.html#autotoc_md85',1,'On Windows:'],['../group__address__reuse.html#autotoc_md86',1,'On Windows:']]],
  ['only_23',['only',['../group__address__reuse.html#autotoc_md87',1,'<span class="tt">SO_EXCLUSIVEADDRUSE</span> (Windows only)'],['../group__address__reuse.html#autotoc_md95',1,'<span class="tt">SO_REUSEPORT</span> (Unix/Linux only)'],['../group__socketopts.html#autotoc_md1206',1,'Example: Check if socket is IPv6-only']]],
  ['only_20if_20autobind_20true_24',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md900',1,'']]],
  ['only_3a_25',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['operate_26',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md379',1,'']]],
  ['operation_27',['Operation',['../group__socketopts.html#autotoc_md1151',1,'⏱️ Behavior Summary by Operation'],['../group__tcp.html#autotoc_md1022',1,'Modes of Operation']]],
  ['operation_20specific_20behavior_3a_20connect_20accept_20recv_20and_20send_28',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['options_29',['Options',['../group__address__reuse.html#autotoc_md76',1,'🔍 In-Depth Overview of Address Reuse Options'],['../group__underlying__socket__api.html#autotoc_md407',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md417',1,'6.2 Socket Options'],['../group__socket-options.html#autotoc_md296',1,'What Are Socket Options?']]],
  ['options_20by_20socket_20type_30',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md300',1,'']]],
  ['options_20for_20all_20sockets_31',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md301',1,'']]],
  ['or_20stubbing_20socket_20api_20for_20unit_20tests_3a_32',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md433',1,'']]],
  ['os_20level_20timeouts_33',['OS-Level Timeouts',['../group__async__io.html#autotoc_md142',1,'']]],
  ['our_20pledge_34',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md538',1,'']]],
  ['our_20responsibilities_35',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md540',1,'']]],
  ['our_20standards_36',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md539',1,'']]],
  ['overview_37',['Overview',['../index.html#autotoc_md460',1,'📘 Overview'],['../group__internal.html#autotoc_md565',1,'Overview'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md781',1,'Overview']]],
  ['overview_20of_20address_20reuse_20options_38',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['overview_20of_20functions_39',['Overview of Functions',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md206',1,'']]],
  ['ownership_20transferred_40',['Ownership Transferred',['../group__udp.html#autotoc_md628',1,'']]]
];
