var searchData=
[
  ['families_0',['Families',['../group__underlying__socket__api.html#autotoc_md444',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md422',1,'3. Socket Address Families']]],
  ['faq_1',['❓ FAQ',['../index.html#autotoc_md555',1,'']]],
  ['fcntl_20ioctlsocket_2',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['fcntl_20unix_20linux_3',['2. fcntl (Unix/Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md239',1,'']]],
  ['features_4',['Features',['../group__underlying__socket__api.html#autotoc_md454',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md464',1,'Advanced Socket API Features'],['../classjsocketpp_1_1MulticastSocket.html#autotoc_md737',1,'Features'],['../structjsocketpp_1_1ReadExactOptions.html#autotoc_md651',1,'Key Features'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md653',1,'Key Features'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md741',1,'Key Features'],['../classjsocketpp_1_1Socket.html#autotoc_md836',1,'Key Features'],['../group__tcp.html#autotoc_md844',1,'Key Features'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1184',1,'Main Features']]],
  ['features_20at_20a_20glance_5',['✨ Features at a Glance',['../index.html#autotoc_md514',1,'']]],
  ['features_3a_6',['Key Features:',['../structjsocketpp_1_1DatagramReadOptions.html#autotoc_md649',1,'']]],
  ['features_3a_20beyond_20addressing_7',['Features: Beyond Addressing',['../group__mastering__ipv4.html#autotoc_md42',1,'Key IPv4 Features: Beyond Addressing'],['../group__mastering__ipv6.html#autotoc_md51',1,'Key IPv6 Features: Beyond Addressing']]],
  ['ff00_3a_3a_208_20in_20depth_8',['Multicast Addresses: &lt;span class=&quot;tt&quot;&gt;ff00::/8&lt;/span&gt; in Depth',['../group__mastering__ipv6.html#autotoc_md50',1,'']]],
  ['fields_9',['Fields',['../structjsocketpp_1_1BufferView.html#autotoc_md593',1,'']]],
  ['final_20thoughts_20and_20best_20practices_10',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md187',1,'']]],
  ['flexibility_20and_20safety_11',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md64',1,'']]],
  ['flexible_20address_20allocation_12',['CIDR in IPv6: Flexible Address Allocation',['../group__mastering__ipv6.html#autotoc_md47',1,'']]],
  ['footprint_13',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md520',1,'']]],
  ['for_205_20seconds_20on_20close_14',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1025',1,'']]],
  ['for_20all_20sockets_15',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md350',1,'']]],
  ['for_20conan_20center_20index_20cci_20submission_16',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['for_20cross_20platform_3a_17',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['for_20jsocketpp_18',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md135',1,'']]],
  ['for_20library_20authors_19',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md143',1,'']]],
  ['for_20modern_20c_2020_20',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['for_20multicast_3a_21',['For Multicast:',['../group__socket-options.html#autotoc_md355',1,'']]],
  ['for_20platform_20specific_20tests_3a_22',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md481',1,'']]],
  ['for_20readiness_23',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md182',1,'']]],
  ['for_20the_20socket’s_20lifetime_24',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['for_20unit_20testing_20in_20c_2020_3a_25',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['for_20unit_20tests_3a_26',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md482',1,'']]],
  ['for_20vcpkg_27',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md491',1,'']]],
  ['format_28',['Format',['../group__tcp.html#autotoc_md876',1,'Format'],['../group__tcp.html#autotoc_md892',1,'Format'],['../group__tcp.html#autotoc_md922',1,'Protocol Format'],['../group__tcp.html#autotoc_md925',1,'Protocol Format'],['../group__tcp.html#autotoc_md949',1,'Protocol Format'],['../group__tcp.html#autotoc_md952',1,'Protocol Format']]],
  ['foundation_29',['Foundation',['../group__mastering__ipv4.html#autotoc_md37',1,'IPv4 Address Structure: The Foundation'],['../group__mastering__ipv6.html#autotoc_md46',1,'IPv6 Address Structure: The Foundation']]],
  ['foundations_3a_20network_20models_20and_20data_20encapsulation_30',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md314',1,'']]],
  ['friendly_31',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md207',1,'']]],
  ['from_20posix_20bsd_32',['Differences from POSIX/BSD',['../group__multicast__sockets.html#autotoc_md299',1,'']]],
  ['full_20ipv4_20picture_33',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['full_20ipv6_20picture_34',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['fully_20step_20by_20step_20posix_20style_35',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md70',1,'']]],
  ['function_36',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md83',1,'']]],
  ['functions_37',['Functions',['../group__underlying__socket__api.html#autotoc_md443',1,'2.1 Key Functions'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md272',1,'5. Related Functions'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md224',1,'Overview of Functions']]],
  ['fundamentals_38',['IP Multicast Fundamentals',['../group__multicast__sockets.html#autotoc_md284',1,'']]],
  ['further_20reading_39',['Further Reading',['../group__socket-options.html#autotoc_md367',1,'']]]
];
