var searchData=
[
  ['data_0',['Data',['../group__multicast__sockets.html#autotoc_md295',1,'Receiving Multicast Data'],['../group__multicast__sockets.html#autotoc_md294',1,'Sending Multicast Data']]],
  ['data_20encapsulation_1',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md314',1,'']]],
  ['data_20transfer_2',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['datagram_20sockets_20udp_3',['Datagram Sockets UDP',['../group__sockets__theory.html#autotoc_md408',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md416',1,'Datagram Sockets (UDP)']]],
  ['datagrams_20and_20segments_4',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md318',1,'']]],
  ['datagrams_3a_20the_20connectionless_20approach_5',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md316',1,'']]],
  ['datagramsocket_20multicastsocket_6',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md354',1,'']]],
  ['datagramsocket_20specific_20notes_7',['DatagramSocket specific Notes',['../group__socketopts.html#autotoc_md1018',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1028',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1038',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md1049',1,'📡 DatagramSocket-specific Notes']]],
  ['dedicated_20methods_20vs_20generic_20methods_8',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md361',1,'']]],
  ['deep_20dive_3a_20multicast_20addresses_20and_20224_200_200_200_204_9',['Deep Dive: Multicast Addresses and 224.0.0.0/4',['../group__mastering__ipv4.html#autotoc_md41',1,'']]],
  ['default_20buffer_20size_10',['What is the default buffer size?',['../index.html#autotoc_md564',1,'']]],
  ['default_20in_20jsocketpp_20_3a_11',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md123',1,'']]],
  ['default_20style_12',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md69',1,'']]],
  ['default_3a_208192_208_20kib_13',['Rationale (default: 8192 / 8 KiB)',['../group__core.html#autotoc_md605',1,'']]],
  ['defaults_14',['Constructor Defaults',['../group__address__reuse.html#autotoc_md137',1,'']]],
  ['definition_15',['🔐 Definition',['../group__address__reuse.html#autotoc_md106',1,'']]],
  ['demonstrating_20binding_20behavior_16',['Example: Demonstrating Binding Behavior',['../group__socket__binding.html#autotoc_md91',1,'']]],
  ['depth_17',['Depth',['../group__sockets__theory.html#autotoc_md406',1,'2. Types of Sockets (In-Depth)'],['../group__mastering__ipv6.html#autotoc_md50',1,'Multicast Addresses: &lt;span class=&quot;tt&quot;&gt;ff00::/8&lt;/span&gt; in Depth']]],
  ['depth_20overview_20of_20address_20reuse_20options_18',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['description_19',['Description',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md227',1,'Description'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md240',1,'Description'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md251',1,'Description'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md262',1,'Description']]],
  ['design_20rationale_20',['Design Rationale',['../group__async__io.html#autotoc_md164',1,'']]],
  ['design_20recommendations_21',['Design Recommendations',['../group__socket-options.html#autotoc_md365',1,'']]],
  ['design_20trade_20off_22',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['designs_3a_20pros_20and_20cons_23',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md68',1,'']]],
  ['detailed_20notes_24',['Detailed Notes',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md279',1,'']]],
  ['details_25',['Details',['../group__udp.html#autotoc_md686',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md697',1,'Implementation Details'],['../group__tcp.html#autotoc_md845',1,'Implementation Details'],['../group__tcp.html#autotoc_md899',1,'Implementation Details'],['../group__tcp.html#autotoc_md902',1,'Implementation Details'],['../group__tcp.html#autotoc_md907',1,'Implementation Details'],['../group__tcp.html#autotoc_md909',1,'Implementation Details'],['../group__tcp.html#autotoc_md912',1,'Implementation Details'],['../group__tcp.html#autotoc_md914',1,'Implementation Details'],['../group__tcp.html#autotoc_md916',1,'Implementation Details'],['../group__tcp.html#autotoc_md918',1,'Implementation Details'],['../group__tcp.html#autotoc_md920',1,'Implementation Details'],['../group__tcp.html#autotoc_md923',1,'Implementation Details'],['../group__tcp.html#autotoc_md926',1,'Implementation Details'],['../group__tcp.html#autotoc_md928',1,'Implementation Details'],['../group__tcp.html#autotoc_md932',1,'Implementation Details'],['../group__tcp.html#autotoc_md934',1,'Implementation Details'],['../group__tcp.html#autotoc_md936',1,'Implementation Details'],['../group__tcp.html#autotoc_md942',1,'Implementation Details'],['../group__tcp.html#autotoc_md943',1,'Implementation Details'],['../group__tcp.html#autotoc_md945',1,'Implementation Details'],['../group__tcp.html#autotoc_md947',1,'Implementation Details'],['../group__tcp.html#autotoc_md950',1,'Implementation Details'],['../group__tcp.html#autotoc_md953',1,'Implementation Details'],['../group__tcp.html#autotoc_md955',1,'Implementation Details'],['../group__tcp.html#autotoc_md957',1,'Implementation Details'],['../group__tcp.html#autotoc_md961',1,'Implementation Details'],['../group__tcp.html#autotoc_md963',1,'Implementation Details'],['../group__tcp.html#autotoc_md967',1,'Implementation Details'],['../group__tcp.html#autotoc_md970',1,'Implementation Details'],['../group__tcp.html#autotoc_md972',1,'Implementation Details'],['../group__tcp.html#autotoc_md982',1,'Implementation Details']]],
  ['developer_20control_26',['Developer Control',['../group__address__reuse.html#autotoc_md138',1,'']]],
  ['developer_20tooling_27',['🛠 Developer Tooling',['../index.html#autotoc_md546',1,'']]],
  ['device_20driver_20linux_28',['Example: Custom Device Driver (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md235',1,'']]],
  ['deviceiocontrol_20windows_29',['DeviceIoControl (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md275',1,'']]],
  ['differences_20from_20posix_20bsd_30',['Differences from POSIX/BSD',['../group__multicast__sockets.html#autotoc_md299',1,'']]],
  ['differences_3a_20packets_20datagrams_20and_20segments_31',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md318',1,'']]],
  ['disable_20nagle’s_20algorithm_20to_20reduce_20latency_32',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['disadvantages_33',['Advantages and Disadvantages',['../group__network__data__units.html#autotoc_md321',1,'']]],
  ['dive_3a_20multicast_20addresses_20and_20224_200_200_200_204_34',['Deep Dive: Multicast Addresses and 224.0.0.0/4',['../group__mastering__ipv4.html#autotoc_md41',1,'']]],
  ['documentation_35',['Documentation',['../index.html#autotoc_md542',1,'📚 Documentation'],['../md_CONTRIBUTING.html#autotoc_md581',1,'6. Documentation']]],
  ['does_36',['Does',['../group__address__reuse.html#autotoc_md133',1,'A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does'],['../group__address__reuse.html#autotoc_md128',1,'What Java Does']]],
  ['does_37',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['does_20“binding_20to_20all_20interfaces”_20mean_38',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['does_20all_20java_20default_20style_39',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md69',1,'']]],
  ['does_20all_20steps_40',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md58',1,'']]],
  ['does_20connect_20bind_20to_20a_20local_20address_41',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['does_20error_20handling_20work_42',['How does error handling work?',['../index.html#autotoc_md558',1,'']]],
  ['does_20it_20work_20on_20windows_43',['Does it work on Windows?',['../index.html#autotoc_md562',1,'']]],
  ['does_20the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_44',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['domain_20socket_20ipc_45',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md538',1,'']]],
  ['domain_20sockets_46',['Unix Domain Sockets',['../group__sockets__theory.html#autotoc_md418',1,'']]],
  ['domain_20sockets_20local_20ipc_47',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md410',1,'']]],
  ['domain_20sockets_20unixsocket_48',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md357',1,'']]],
  ['drawbacks_20of_20select_49',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md327',1,'']]],
  ['driver_20linux_50',['Example: Custom Device Driver (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md235',1,'']]]
];
