var searchData=
[
  ['⚙️_20behavior_0',['⚙️ Behavior',['../group__address__reuse.html#autotoc_md90',1,'⚙️ Behavior'],['../group__internal.html#autotoc_md591',1,'⚙️ Behavior'],['../group__internal.html#autotoc_md596',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md614',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md644',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md656',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md691',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md755',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md759',1,'⚙️ Behavior'],['../group__udp.html#autotoc_md763',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md831',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md849',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md860',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1027',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1032',1,'⚙️ Behavior'],['../group__tcp.html#autotoc_md1037',1,'⚙️ Behavior']]],
  ['⚙️_20configuration_1',['⚙️ Configuration',['../group__tcp.html#autotoc_md842',1,'']]],
  ['⚙️_20configuration_20of_20accepted_20socket_2',['⚙️ Configuration of Accepted Socket',['../group__tcp.html#autotoc_md793',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md802',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md811',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md822',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md855',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md868',1,'⚙️ Configuration of Accepted Socket']]],
  ['⚙️_20core_20behavior_3',['⚙️ Core Behavior',['../group__udp.html#autotoc_md661',1,'⚙️ Core Behavior'],['../group__udp.html#autotoc_md680',1,'⚙️ Core Behavior'],['../group__udp.html#autotoc_md739',1,'⚙️ Core Behavior']]],
  ['⚙️_20core_20behaviors_4',['⚙️ Core Behaviors',['../group__udp.html#autotoc_md709',1,'']]],
  ['⚙️_20implementation_20details_5',['⚙️ Implementation Details',['../group__udp.html#autotoc_md734',1,'']]],
  ['⚙️_20platform_20behavior_6',['⚙️ Platform Behavior',['../group__udp.html#autotoc_md725',1,'']]]
];
