var searchData=
[
  ['a_203_20second_20receive_20timeout_0',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1058',1,'']]],
  ['a_205_20second_20send_20timeout_1',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1063',1,'']]],
  ['a_20better_20alternative_3a_20what_20jsocketpp_20does_2',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['a_20client_20socket_3',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1084',1,'']]],
  ['a_20constructor_20does_20all_20java_20default_20style_4',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['a_20flexibility_20and_20safety_5',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'']]],
  ['a_20glance_6',['✨ Features at a Glance',['../index.html#autotoc_md395',1,'']]],
  ['a_20local_20address_7',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['a_20pull_20request_20to_20cci_8',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['a_20simple_20server_20client_20integration_20test_3a_9',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md360',1,'']]],
  ['a_20socket_10',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md285',1,'']]],
  ['a_20socket_20state_11',['What is a Socket State?',['../group__socket__states.html#autotoc_md267',1,'']]],
  ['a_20vcpkg_20portfile_12',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md374',1,'']]],
  ['about_20udp_20and_20unix_20sockets_13',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md274',1,'']]],
  ['accept_14',['📞 &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;',['../group__async__io.html#autotoc_md153',1,'']]],
  ['accept_20recv_20and_20send_15',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['acceptance_16',['Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md382',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md198',1,'7. After Acceptance']]],
  ['accepted_20socket_17',['Accepted Socket',['../group__tcp.html#autotoc_md721',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md730',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md739',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md750',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md783',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md796',1,'⚙️ Configuration of Accepted Socket']]],
  ['acceptnonblocking_18',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md761',1,'']]],
  ['acknowledgements_19',['🙏 Acknowledgements',['../index.html#autotoc_md434',1,'']]],
  ['action_3a_20practical_20examples_20',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md332',1,'']]],
  ['actually_20does_21',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['address_22',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['address_20and_20name_20resolution_23',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['address_20binding_20and_20connection_24',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['address_20families_25',['Address Families',['../group__underlying__socket__api.html#autotoc_md325',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md303',1,'3. Socket Address Families']]],
  ['address_20resolution_26',['🌐 Address Resolution',['../group__udp.html#autotoc_md629',1,'']]],
  ['address_20reuse_20options_27',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['addresses_28',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md175',1,'']]],
  ['adjust_29',['When to Adjust',['../group__core.html#autotoc_md483',1,'']]],
  ['advanced_20scenarios_30',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md55',1,'']]],
  ['advanced_20socket_20api_20features_31',['Advanced Socket API Features',['../group__underlying__socket__api.html#autotoc_md335',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md345',1,'Advanced Socket API Features']]],
  ['advanced_20topics_32',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md315',1,'']]],
  ['advanced_20usage_33',['Advanced Usage',['../classjsocketpp_1_1Socket.html#autotoc_md813',1,'']]],
  ['advantages_20and_20rationale_34',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md45',1,'']]],
  ['advantages_20of_20epoll_35',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md212',1,'']]],
  ['advantages_20of_20poll_36',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md210',1,'']]],
  ['advice_37',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md222',1,'']]],
  ['af_5finet_38',['AF_INET',['../group__underlying__socket__api.html#autotoc_md333',1,'5.1 TCP Server and Client (Python, AF_INET)'],['../group__underlying__socket__api.html#autotoc_md334',1,'5.2 UDP Server and Client (C, AF_INET)']]],
  ['after_20acceptance_39',['After Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md382',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md198',1,'7. After Acceptance']]],
  ['algorithm_20to_20reduce_20latency_40',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1098',1,'']]],
  ['all_20interfaces”_20mean_41',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['all_20interfaces_42',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['all_20java_20default_20style_43',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['all_20sockets_44',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md231',1,'']]],
  ['all_20steps_45',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['also_46',['Also',['../index.html#autotoc_md449',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md714',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md814',1,'See Also']]],
  ['alternative_20designs_3a_20pros_20and_20cons_47',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['alternative_3a_20what_20jsocketpp_20does_48',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['and_20applications_49',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md341',1,'']]],
  ['and_20asynchronous_20i_20o_50',['6. Non-Blocking and Asynchronous I/O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'']]],
  ['and_20best_20practices_51',['and Best Practices',['../group__async__io.html#autotoc_md169',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md384',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices']]],
  ['and_20broadcast_52',['and Broadcast',['../group__underlying__socket__api.html#autotoc_md338',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md348',1,'6.3 Multicast and Broadcast']]],
  ['and_20caveats_53',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['and_20cleanup_3a_54',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md357',1,'']]],
  ['and_20client_55',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md525',1,'']]],
  ['and_20client_20c_20af_5finet_56',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md334',1,'']]],
  ['and_20client_20python_20af_5finet_57',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md333',1,'']]],
  ['and_20client_3a_58',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md359',1,'']]],
  ['and_20configuration_59',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['and_20connection_60',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['and_20cons_61',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['and_20handling_20socket_20exceptions_62',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md971',1,'']]],
  ['and_20its_20limitations_63',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['and_20management_64',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['and_20name_20resolution_65',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['and_20performance_20considerations_66',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md301',1,'']]],
  ['and_20rationale_67',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md45',1,'']]],
  ['and_20running_20tests_68',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['and_20safety_69',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'']]],
  ['and_20send_70',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['and_20send_3a_71',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md356',1,'']]],
  ['and_20testing_72',['🧪 Building and Testing',['../index.html#autotoc_md425',1,'']]],
  ['and_20the_20socket_20api_73',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md331',1,'']]],
  ['and_20timeouts_74',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md145',1,'']]],
  ['and_20udp_75',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['and_20unix_20sockets_76',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md274',1,'']]],
  ['api_77',['API',['../group__underlying__socket__api.html#autotoc_md322',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md323',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md331',1,'4. Protocols and the Socket API'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md713',1,'Basic API'],['../group__ServerSocket__Lifecycle.html#autotoc_md48',1,'c) Clear API']]],
  ['api_20considerations_78',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md216',1,'']]],
  ['api_20features_79',['API Features',['../group__underlying__socket__api.html#autotoc_md335',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md345',1,'Advanced Socket API Features']]],
  ['api_20for_20unit_20tests_3a_80',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md363',1,'']]],
  ['api_20in_20action_3a_20practical_20examples_81',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md332',1,'']]],
  ['api_20notes_82',['jsocketpp API Notes',['../group__bind__interfaces.html#autotoc_md180',1,'']]],
  ['apis_83',['APIs',['../group__socket__library__comparison.html#autotoc_md260',1,'5. Native BSD/POSIX/WinSock APIs'],['../group__sockets__theory.html#autotoc_md311',1,'6. Platform-Specific APIs']]],
  ['applicability_84',['Applicability',['../group__socketopts.html#autotoc_md582',1,'🌍 Applicability'],['../group__udp.html#autotoc_md588',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1108',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1138',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1145',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1042',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1045',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1048',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1052',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1101',1,'🔍 Applicability'],['../group__socketopts.html#autotoc_md1030',1,'Applicability'],['../group__socketopts.html#autotoc_md1033',1,'Applicability'],['../group__socketopts.html#autotoc_md1036',1,'Applicability'],['../group__socketopts.html#autotoc_md1039',1,'Applicability'],['../group__socketopts.html#autotoc_md1117',1,'Applicability'],['../group__socketopts.html#autotoc_md1028',1,'Protocol Applicability']]],
  ['applicability_20by_20socket_20type_85',['Applicability by Socket Type',['../group__socketopts.html#autotoc_md1122',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1131',1,'🌍 Applicability by Socket Type']]],
  ['applicable_20socket_20types_86',['📦 Applicable Socket Types',['../group__socketopts.html#autotoc_md1078',1,'']]],
  ['applications_87',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md341',1,'']]],
  ['applies_20to_88',['Applies to',['../group__core.html#autotoc_md480',1,'']]],
  ['approach_89',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['approach_20and_20its_20limitations_90',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_91',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['are_20socket_20options_92',['What Are Socket Options?',['../group__socket-options.html#autotoc_md226',1,'']]],
  ['asio_93',['Asio',['../index.html#autotoc_md399',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md254',1,'2. Boost.Asio']]],
  ['assignment_94',['Example: Move assignment',['../group__socketopts.html#autotoc_md1152',1,'']]],
  ['async_95',['Is jsocketpp async?',['../index.html#autotoc_md437',1,'']]],
  ['asynchronous_20i_20o_96',['Asynchronous I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md339',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md349',1,'6.4 Asynchronous I/O']]],
  ['at_20a_20glance_97',['✨ Features at a Glance',['../index.html#autotoc_md395',1,'']]],
  ['authors_98',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md125',1,'']]],
  ['autobind_20true_99',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md829',1,'']]]
];
