var searchData=
[
  ['waiting_20for_20readiness_0',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['warning_1',['Warning',['../group__tcp.html#autotoc_md667',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md680',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md638',1,'⚠️ Race Condition Warning']]],
  ['what_20about_20udp_20and_20unix_20sockets_2',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md251',1,'']]],
  ['what_20are_20socket_20options_3',['What Are Socket Options?',['../group__socket-options.html#autotoc_md203',1,'']]],
  ['what_20does_20“binding_20to_20all_20interfaces”_20mean_4',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['what_20happens_20when_20multiple_20sockets_20bind_20to_20the_20same_20port_5',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['what_20is_20a_20socket_6',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['what_20is_20a_20socket_20state_7',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['what_20is_20blocking_8',['What is Blocking?',['../group__async__io.html#autotoc_md115',1,'']]],
  ['what_20is_20multicast_9',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md591',1,'']]],
  ['what_20is_20non_20blocking_10',['What is Non-Blocking?',['../group__async__io.html#autotoc_md116',1,'']]],
  ['what_20is_20the_20default_20buffer_20size_11',['What is the default buffer size?',['../index.html#autotoc_md422',1,'']]],
  ['what_20is_20transferred_12',['What Is Transferred',['../group__udp.html#autotoc_md494',1,'']]],
  ['what_20is_20udp_13',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md464',1,'']]],
  ['what_20it_20actually_20does_14',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['what_20java_20does_15',['What Java Does',['../group__address__reuse.html#autotoc_md87',1,'']]],
  ['what_20jsocketpp_20does_16',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['what_20jsocketpp_20gets_20right_17',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md107',1,'']]],
  ['when_20multiple_20sockets_20bind_20to_20the_20same_20port_18',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['when_20to_20adjust_19',['When to Adjust',['../group__core.html#autotoc_md460',1,'']]],
  ['when_20to_20use_20',['When to Use',['../group__socketopts.html#autotoc_md1022',1,'']]],
  ['when_20true_20matters_21',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md689',1,'']]],
  ['why_20jsocketpp_22',['💡 Why jsocketpp?',['../index.html#autotoc_md370',1,'']]],
  ['why_20not_20expose_20windows_20so_5freuseaddr_23',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['why_20require_20the_20port_20in_20the_20constructor_24',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['why_20select_20is_20used_25',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['why_20this_20is_20problematic_20on_20windows_26',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['wildcard_20addresses_27',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md152',1,'']]],
  ['windows_28',['Windows',['../index.html#autotoc_md420',1,'Does it work on Windows?'],['../group__address__reuse.html#autotoc_md88',1,'Why This is Problematic on Windows'],['../group__address__reuse.html#autotoc_md80',1,'Windows']]],
  ['windows_20counterparts_29',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md191',1,'']]],
  ['windows_20only_30',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md64',1,'']]],
  ['windows_20so_5freuseaddr_31',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['windows_20winsock_32',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md290',1,'']]],
  ['windows_3a_33',['Windows:',['../group__address__reuse.html#autotoc_md62',1,'On Windows:'],['../group__address__reuse.html#autotoc_md63',1,'On Windows:']]],
  ['winsock_34',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md290',1,'']]],
  ['winsock_20apis_35',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['with_20acceptnonblocking_36',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md647',1,'']]],
  ['with_20extreme_20care_37',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md850',1,'']]],
  ['with_20google_20mock_3a_38',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md341',1,'']]],
  ['with_20mocking_3a_39',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['with_20select_40',['Example: Use with &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__socketopts.html#autotoc_md854',1,'']]],
  ['with_20so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_41',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['with_20so_5freuseaddr_20only_3a_42',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['with_20so_5freuseaddr_20so_5freuseport_3a_43',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['with_20so_5freuseaddr_3a_44',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['with_20so_5freuseport_45',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['work_46',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['work_47',['How does error handling work?',['../index.html#autotoc_md416',1,'']]],
  ['work_20on_20windows_48',['Does it work on Windows?',['../index.html#autotoc_md420',1,'']]],
  ['work_3a_20the_20lifecycle_49',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'']]],
  ['works_20internally_50',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['write_51',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md137',1,'']]]
];
