var searchData=
[
  ['datagram_20sockets_20udp_0',['Datagram Sockets UDP',['../group__sockets__theory.html#autotoc_md278',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md286',1,'Datagram Sockets (UDP)']]],
  ['datagramsocket_20multicastsocket_1',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md224',1,'']]],
  ['datagramsocket_20specific_20notes_2',['DatagramSocket specific Notes',['../group__socketopts.html#autotoc_md937',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md947',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md957',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md968',1,'📡 DatagramSocket-specific Notes']]],
  ['dedicated_20methods_20vs_20generic_20methods_3',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md231',1,'']]],
  ['default_20buffer_20size_4',['What is the default buffer size?',['../index.html#autotoc_md434',1,'']]],
  ['default_20in_20jsocketpp_20_3a_5',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['default_20style_6',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['defaults_7',['Constructor Defaults',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['definition_8',['🔐 Definition',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['demonstrating_20binding_20behavior_9',['Example: Demonstrating Binding Behavior',['../group__socket__binding.html#autotoc_md62',1,'']]],
  ['depth_10',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md276',1,'']]],
  ['depth_20overview_20of_20address_20reuse_20options_11',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md65',1,'']]],
  ['design_20rationale_12',['Design Rationale',['../group__async__io.html#autotoc_md135',1,'']]],
  ['design_20recommendations_13',['Design Recommendations',['../group__socket-options.html#autotoc_md235',1,'']]],
  ['design_20trade_20off_14',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md102',1,'']]],
  ['designs_3a_20pros_20and_20cons_15',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['details_16',['Details',['../group__udp.html#autotoc_md618',1,'⚙️ Implementation Details'],['../group__udp.html#autotoc_md609',1,'Implementation Details'],['../group__udp.html#autotoc_md629',1,'Implementation Details'],['../group__tcp.html#autotoc_md764',1,'Implementation Details'],['../group__tcp.html#autotoc_md818',1,'Implementation Details'],['../group__tcp.html#autotoc_md821',1,'Implementation Details'],['../group__tcp.html#autotoc_md826',1,'Implementation Details'],['../group__tcp.html#autotoc_md828',1,'Implementation Details'],['../group__tcp.html#autotoc_md831',1,'Implementation Details'],['../group__tcp.html#autotoc_md833',1,'Implementation Details'],['../group__tcp.html#autotoc_md835',1,'Implementation Details'],['../group__tcp.html#autotoc_md837',1,'Implementation Details'],['../group__tcp.html#autotoc_md839',1,'Implementation Details'],['../group__tcp.html#autotoc_md842',1,'Implementation Details'],['../group__tcp.html#autotoc_md845',1,'Implementation Details'],['../group__tcp.html#autotoc_md847',1,'Implementation Details'],['../group__tcp.html#autotoc_md851',1,'Implementation Details'],['../group__tcp.html#autotoc_md853',1,'Implementation Details'],['../group__tcp.html#autotoc_md855',1,'Implementation Details'],['../group__tcp.html#autotoc_md861',1,'Implementation Details'],['../group__tcp.html#autotoc_md862',1,'Implementation Details'],['../group__tcp.html#autotoc_md864',1,'Implementation Details'],['../group__tcp.html#autotoc_md866',1,'Implementation Details'],['../group__tcp.html#autotoc_md869',1,'Implementation Details'],['../group__tcp.html#autotoc_md872',1,'Implementation Details'],['../group__tcp.html#autotoc_md874',1,'Implementation Details'],['../group__tcp.html#autotoc_md876',1,'Implementation Details'],['../group__tcp.html#autotoc_md880',1,'Implementation Details'],['../group__tcp.html#autotoc_md882',1,'Implementation Details'],['../group__tcp.html#autotoc_md886',1,'Implementation Details'],['../group__tcp.html#autotoc_md889',1,'Implementation Details'],['../group__tcp.html#autotoc_md891',1,'Implementation Details'],['../group__tcp.html#autotoc_md901',1,'Implementation Details']]],
  ['developer_20control_17',['Developer Control',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['developer_20tooling_18',['🛠 Developer Tooling',['../index.html#autotoc_md416',1,'']]],
  ['disable_20nagle’s_20algorithm_20to_20reduce_20latency_19',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1046',1,'']]],
  ['documentation_20',['Documentation',['../index.html#autotoc_md412',1,'📚 Documentation'],['../md_CONTRIBUTING.html#autotoc_md451',1,'6. Documentation']]],
  ['does_21',['Does',['../group__address__reuse.html#autotoc_md104',1,'A Better Alternative: What <span class="tt">jsocketpp</span> Does'],['../group__address__reuse.html#autotoc_md99',1,'What Java Does']]],
  ['does_22',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md68',1,'']]],
  ['does_20“binding_20to_20all_20interfaces”_20mean_23',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md163',1,'']]],
  ['does_20all_20java_20default_20style_24',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['does_20all_20steps_25',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['does_20connect_20bind_20to_20a_20local_20address_26',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md57',1,'']]],
  ['does_20error_20handling_20work_27',['How does error handling work?',['../index.html#autotoc_md428',1,'']]],
  ['does_20it_20work_20on_20windows_28',['Does it work on Windows?',['../index.html#autotoc_md432',1,'']]],
  ['does_20the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_29',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md61',1,'']]],
  ['domain_20socket_20ipc_30',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md408',1,'']]],
  ['domain_20sockets_31',['Unix Domain Sockets',['../group__sockets__theory.html#autotoc_md288',1,'']]],
  ['domain_20sockets_20local_20ipc_32',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md280',1,'']]],
  ['domain_20sockets_20unixsocket_33',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md227',1,'']]],
  ['drawbacks_20of_20select_34',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md197',1,'']]]
];
