var searchData=
[
  ['udp_0',['UDP',['../group__sockets__theory.html#autotoc_md266',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md274',1,'Datagram Sockets (UDP)'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md415',1,'What is UDP?']]],
  ['udp_20and_20unix_20sockets_1',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md251',1,'']]],
  ['udp_20echo_20server_20and_20client_2',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md417',1,'']]],
  ['udp_20example_3',['UDP Example',['../index.html#autotoc_md378',1,'']]],
  ['udp_20server_20and_20client_20c_20af_5finet_4',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['udp_20sockets_20datagramsocket_20multicastsocket_5',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md212',1,'']]],
  ['under_20the_20hood_3a_20how_20socket_20types_20work_6',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['under_20the_20hood_3a_20how_20sockets_20operate_7',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['unit_20testing_20in_20c_2017_3a_8',['Tools for Unit Testing in C++17:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['unit_20tests_3a_9',['Unit Tests:',['../group__unit__tests.html#autotoc_md330',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md340',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['unix_10',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md289',1,'']]],
  ['unix_20domain_20sockets_11',['Unix Domain Sockets',['../group__sockets__theory.html#autotoc_md276',1,'']]],
  ['unix_20domain_20sockets_20local_20ipc_12',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['unix_20domain_20sockets_20unixsocket_13',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md215',1,'']]],
  ['unix_20linux_14',['Unix/Linux',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['unix_20linux_20only_15',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md72',1,'']]],
  ['unix_20linux_3a_16',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md55',1,'']]],
  ['unix_20sockets_17',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md251',1,'']]],
  ['unixsocket_18',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md215',1,'']]],
  ['up_20real_20server_20and_20client_3a_19',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['usage_20',['Usage',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'7. Example Usage'],['../classjsocketpp_1_1Socket.html#autotoc_md449',1,'Advanced Usage'],['../group__tcp.html#autotoc_md453',1,'Example Usage'],['../group__tcp.html#autotoc_md455',1,'Example Usage'],['../group__tcp.html#autotoc_md462',1,'Example Usage'],['../group__tcp.html#autotoc_md464',1,'Example Usage'],['../group__tcp.html#autotoc_md465',1,'Example Usage'],['../group__tcp.html#autotoc_md467',1,'Example Usage'],['../group__tcp.html#autotoc_md469',1,'Example Usage'],['../group__tcp.html#autotoc_md471',1,'Example Usage'],['../group__tcp.html#autotoc_md473',1,'Example Usage'],['../group__tcp.html#autotoc_md475',1,'Example Usage'],['../group__tcp.html#autotoc_md478',1,'Example Usage'],['../group__tcp.html#autotoc_md481',1,'Example Usage'],['../group__tcp.html#autotoc_md483',1,'Example Usage'],['../group__tcp.html#autotoc_md485',1,'Example Usage'],['../group__tcp.html#autotoc_md487',1,'Example Usage'],['../group__tcp.html#autotoc_md488',1,'Example Usage'],['../group__tcp.html#autotoc_md491',1,'Example Usage'],['../group__tcp.html#autotoc_md494',1,'Example Usage'],['../group__tcp.html#autotoc_md496',1,'Example Usage'],['../group__tcp.html#autotoc_md498',1,'Example Usage'],['../group__tcp.html#autotoc_md501',1,'Example Usage'],['../group__tcp.html#autotoc_md503',1,'Example Usage'],['../group__tcp.html#autotoc_md505',1,'Example Usage'],['../group__tcp.html#autotoc_md507',1,'Example Usage'],['../group__tcp.html#autotoc_md510',1,'Example Usage'],['../group__tcp.html#autotoc_md512',1,'Example Usage'],['../group__tcp.html#autotoc_md514',1,'Example Usage'],['../group__tcp.html#autotoc_md517',1,'Example Usage'],['../group__tcp.html#autotoc_md520',1,'Example Usage'],['../classjsocketpp_1_1Socket.html#autotoc_md522',1,'Example Usage'],['../classjsocketpp_1_1Socket.html#autotoc_md523',1,'Example Usage'],['../classjsocketpp_1_1Socket.html#autotoc_md525',1,'Example Usage'],['../group__tcp.html#autotoc_md527',1,'Example Usage'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md424',1,'Typical Usage']]],
  ['usage_20example_21',['Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md444',1,'Typical Usage Example'],['../group__BUILD__AND__USAGE.html#autotoc_md16',1,'Usage Example'],['../group__tcp.html#autotoc_md430',1,'Usage Example'],['../group__tcp.html#autotoc_md436',1,'Usage Example'],['../group__tcp.html#autotoc_md457',1,'Usage Example']]],
  ['usage_20example_20receiving_22',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md420',1,'']]],
  ['usage_20example_20sending_23',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md421',1,'']]],
  ['use_20case_24',['✅ Use Case',['../group__address__reuse.html#autotoc_md69',1,'']]],
  ['use_20cases_25',['Common Use Cases',['../group__tcp.html#autotoc_md515',1,'']]],
  ['use_20cases_26',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['use_20cases_20and_20applications_27',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md318',1,'']]],
  ['use_3a_28',['Example Use:',['../group__async__io.html#autotoc_md147',1,'']]],
  ['used_29',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['using_20cmake_20for_20platform_20specific_20tests_3a_30',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['using_20cmake_20presets_20recommended_31',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['using_20google_20mock_20to_20mock_20recv_20and_20send_3a_32',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['using_20the_20makefile_33',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]]
];
