var searchData=
[
  ['nagle’s_20algorithm_20to_20reduce_20latency_0',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md747',1,'']]],
  ['native_20bsd_20posix_20winsock_20apis_1',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['nesting_2',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md621',1,'']]],
  ['network_20module_3',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md235',1,'']]],
  ['non_20blocking_4',['What is Non-Blocking?',['../group__async__io.html#autotoc_md116',1,'']]],
  ['non_20blocking_20mode_20on_20a_20client_20socket_5',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md733',1,'']]],
  ['non_20blocking_20mode_3a_6',['Non blocking mode:',['../group__async__io.html#autotoc_md128',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md132',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md136',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md139',1,'Non-blocking mode:']]],
  ['non_20blocking_20sockets_7',['Non Blocking Sockets',['../group__async__io.html#autotoc_md114',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md313',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md323',1,'6.1 Non-Blocking Sockets']]],
  ['not_20expose_20windows_20so_5freuseaddr_8',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['notes_9',['Notes',['../group__socketopts.html#autotoc_md636',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md647',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md656',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md667',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md638',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md648',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md658',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md669',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md640',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md649',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md660',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md671',1,'🧿 UnixSocket-specific Notes'],['../group__udp.html#autotoc_md469',1,'Buffer Size Notes'],['../group__tcp.html#autotoc_md610',1,'Implementation Notes'],['../group__bind__interfaces.html#autotoc_md157',1,'jsocketpp API Notes'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md467',1,'Notes'],['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__udp.html#autotoc_md484',1,'Platform Notes'],['../group__tcp.html#autotoc_md536',1,'Platform Notes'],['../group__socketopts.html#autotoc_md683',1,'Platform Notes'],['../group__socketopts.html#autotoc_md689',1,'Platform Notes']]],
  ['notes_20for_20library_20authors_10',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md102',1,'']]]
];
