var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md100',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md217',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md197',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md294',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md84',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md239',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md270',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['tcp_4',['TCP',['../group__sockets__theory.html#autotoc_md265',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md273',1,'Stream Sockets (TCP)']]],
  ['tcp_20example_5',['TCP Example',['../index.html#autotoc_md377',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_6',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['tcp_20socket_20lifecycle_7',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md246',1,'']]],
  ['tcp_20socket_20states_8',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['tcp_20sockets_20socket_20serversocket_9',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['tcp_20state_20transitions_10',['TCP State Transitions',['../group__socket__states.html#autotoc_md249',1,'']]],
  ['test_20cases_20to_20consider_3a_11',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_12',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['test_20the_20port_20locally_13',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md355',1,'']]],
  ['test_20the_20recipe_20locally_14',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md168',1,'']]],
  ['test_20with_20mocking_3a_15',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['test_3a_16',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['test_5fpackage_17',['test_package',['../group__conan__publish__guide.html#autotoc_md171',1,'']]],
  ['testing_18',['Testing',['../md_CONTRIBUTING.html#autotoc_md401',1,'5. Testing'],['../index.html#autotoc_md384',1,'Building &amp; Testing']]],
  ['testing_20in_20c_2020_3a_19',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_20',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['tests_21',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_22',['Tests:',['../group__unit__tests.html#autotoc_md330',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md335',1,'2. <b>Integration Tests</b>:'],['../group__unit__tests.html#autotoc_md339',1,'3.1 <b>Using CMake for Platform-Specific Tests</b>:'],['../group__unit__tests.html#autotoc_md340',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['the_20basics_23',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md108',1,'']]],
  ['the_20constructor_24',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_25',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_26',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_27',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['the_20library_28',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_29',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'']]],
  ['the_20makefile_30',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20port_20in_20the_20constructor_31',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['the_20port_20locally_32',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md355',1,'']]],
  ['the_20recipe_20locally_33',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md168',1,'']]],
  ['the_20same_20port_34',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['the_20socket_20api_35',['the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md300',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md308',1,'4. Protocols and the Socket API']]],
  ['the_20vcpkg_20registry_36',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'']]],
  ['this_20is_20problematic_20on_20windows_37',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['this_20library_38',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md229',1,'']]],
  ['this_20relates_20to_20jsocketpp_39',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md255',1,'']]],
  ['thoughts_20and_20best_20practices_40',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md146',1,'']]],
  ['thread_20safety_41',['Thread Safety',['../group__tcp.html#autotoc_md447',1,'Thread Safety'],['../group__tcp.html#autotoc_md450',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md455',1,'Thread Safety'],['../group__tcp.html#autotoc_md471',1,'Thread Safety']]],
  ['timeout_20behavior_42',['Timeout Behavior',['../group__tcp.html#autotoc_md549',1,'']]],
  ['timeout_20semantics_43',['Timeout Semantics',['../group__tcp.html#autotoc_md449',1,'']]],
  ['timeouts_44',['Timeouts',['../group__async__io.html#autotoc_md122',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md118',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md119',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_45',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md120',1,'']]],
  ['tips_20and_20best_20practices_46',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md361',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md177',1,'8. Tips and Best Practices']]],
  ['to_20adjust_47',['When to Adjust',['../group__core.html#autotoc_md423',1,'']]],
  ['to_20all_20interfaces”_20mean_48',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['to_20all_20interfaces_49',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md153',1,'']]],
  ['to_20cci_50',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['to_20consider_3a_51',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['to_20jsocketpp_52',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md255',1,'How This Relates to <span class="tt">jsocketpp</span>']]],
  ['to_20mock_20recv_20and_20send_3a_53',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['to_20peer_20model_54',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md306',1,'']]],
  ['to_20the_20same_20port_55',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['to_20the_20socket_20api_56',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'']]],
  ['to_20the_20vcpkg_20registry_57',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_58',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['topics_59',['7. Advanced Topics',['../group__sockets__theory.html#autotoc_md292',1,'']]],
  ['trade_20off_60',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_61',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['transitions_62',['TCP State Transitions',['../group__socket__states.html#autotoc_md249',1,'']]],
  ['troubleshooting_63',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['type_64',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['types_65',['Types',['../group__underlying__socket__api.html#autotoc_md303',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md270',1,'2.5. Comparison Table: Socket Types'],['../group__tcp.html#autotoc_md470',1,'Supported Types']]],
  ['types_20of_20sockets_20in_20depth_66',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['types_20work_67',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['typical_20usage_68',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md442',1,'']]],
  ['typical_20usage_20example_69',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md452',1,'']]]
];
