var searchData=
[
  ['waiting_20for_20readiness_0',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md182',1,'']]],
  ['warning_1',['Warning',['../group__tcp.html#autotoc_md810',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md823',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md781',1,'⚠️ Race Condition Warning']]],
  ['what_20about_20udp_20and_20unix_20sockets_2',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md393',1,'']]],
  ['what_20are_20socket_20options_3',['What Are Socket Options?',['../group__socket-options.html#autotoc_md345',1,'']]],
  ['what_20does_20“binding_20to_20all_20interfaces”_20mean_4',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['what_20happens_20when_20multiple_20sockets_20bind_20to_20the_20same_20port_5',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['what_20is_20a_20packet_6',['What is a Packet?',['../group__network__data__units.html#autotoc_md315',1,'']]],
  ['what_20is_20a_20socket_7',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md404',1,'']]],
  ['what_20is_20a_20socket_20state_8',['What is a Socket State?',['../group__socket__states.html#autotoc_md386',1,'']]],
  ['what_20is_20blocking_9',['What is Blocking?',['../group__async__io.html#autotoc_md156',1,'']]],
  ['what_20is_20multicast_10',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md734',1,'']]],
  ['what_20is_20non_20blocking_11',['What is Non-Blocking?',['../group__async__io.html#autotoc_md157',1,'']]],
  ['what_20is_20socket_20binding_12',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md82',1,'']]],
  ['what_20is_20the_20default_20buffer_20size_13',['What is the default buffer size?',['../index.html#autotoc_md564',1,'']]],
  ['what_20is_20the_20mtu_14',['🔍 What is the MTU?',['../group__udp.html#autotoc_md677',1,'']]],
  ['what_20is_20transferred_15',['What Is Transferred',['../group__udp.html#autotoc_md663',1,'']]],
  ['what_20is_20udp_16',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md652',1,'']]],
  ['what_20it_20actually_20does_17',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['what_20java_20does_18',['What Java Does',['../group__address__reuse.html#autotoc_md128',1,'']]],
  ['what_20jsocketpp_20does_19',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['what_20jsocketpp_20gets_20right_20',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md148',1,'']]],
  ['when_20multiple_20sockets_20bind_20to_20the_20same_20port_21',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['when_20to_20adjust_22',['When to Adjust',['../group__core.html#autotoc_md602',1,'']]],
  ['when_20to_20use_23',['When to Use',['../group__socketopts.html#autotoc_md1180',1,'']]],
  ['when_20true_20matters_24',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md835',1,'']]],
  ['why_20a_20safe_20cap_25',['Why a &quot;safe&quot; cap?',['../group__core.html#autotoc_md608',1,'']]],
  ['why_20jsocketpp_26',['💡 Why jsocketpp?',['../index.html#autotoc_md512',1,'']]],
  ['why_20not_20expose_20windows_20so_5freuseaddr_27',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md139',1,'']]],
  ['why_20require_20the_20port_20in_20the_20constructor_28',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['why_20select_20is_20used_29',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md325',1,'']]],
  ['why_20this_20is_20problematic_20on_20windows_30',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['why_20this_20matters_31',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md635',1,'']]],
  ['wildcard_20addresses_32',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md193',1,'']]],
  ['window_20size_20linux_33',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md234',1,'']]],
  ['windows_34',['Windows',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md250',1,'3. ioctlsocket (Windows)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md261',1,'4. WSAIoctl (Windows)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md275',1,'DeviceIoControl (Windows)'],['../index.html#autotoc_md562',1,'Does it work on Windows?'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md268',1,'Example: Get Interface List (Windows)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md257',1,'Example: Non-Blocking Socket (Windows)'],['../group__address__reuse.html#autotoc_md129',1,'Why This is Problematic on Windows'],['../group__address__reuse.html#autotoc_md121',1,'Windows'],['../group__multicast__sockets.html#autotoc_md298',1,'Winsock API (Windows)']]],
  ['windows_20counterparts_35',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md333',1,'']]],
  ['windows_20only_36',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['windows_20so_5freuseaddr_37',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md139',1,'']]],
  ['windows_20support_38',['Windows Support',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md236',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md247',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md258',1,'Windows Support'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md269',1,'Windows Support']]],
  ['windows_20version_20support_20summary_39',['Windows Version Support Summary',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md277',1,'']]],
  ['windows_20winsock_40',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md432',1,'']]],
  ['windows_3a_41',['Windows:',['../group__address__reuse.html#autotoc_md103',1,'On Windows:'],['../group__address__reuse.html#autotoc_md104',1,'On Windows:']]],
  ['winsock_42',['Winsock',['../group__sockets__theory.html#autotoc_md432',1,'6.2. Windows (Winsock)'],['../group__multicast__sockets.html#autotoc_md302',1,'Example: Receiver in C++ (Winsock)'],['../group__multicast__sockets.html#autotoc_md301',1,'Example: Sender in C++ (Winsock)']]],
  ['winsock_20api_20windows_43',['Winsock API (Windows)',['../group__multicast__sockets.html#autotoc_md298',1,'']]],
  ['winsock_20apis_44',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md379',1,'']]],
  ['with_20acceptnonblocking_45',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md790',1,'']]],
  ['with_20extreme_20care_46',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md1008',1,'']]],
  ['with_20google_20mock_3a_47',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md483',1,'']]],
  ['with_20mocking_3a_48',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md484',1,'']]],
  ['with_20select_49',['Example: Use with &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__socketopts.html#autotoc_md1012',1,'']]],
  ['with_20so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_50',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md123',1,'']]],
  ['with_20so_5freuseaddr_20only_3a_51',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md118',1,'']]],
  ['with_20so_5freuseaddr_20so_5freuseport_3a_52',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md119',1,'']]],
  ['with_20so_5freuseaddr_3a_53',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md122',1,'']]],
  ['with_20so_5freuseport_54',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md102',1,'']]],
  ['work_55',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md414',1,'']]],
  ['work_56',['How does error handling work?',['../index.html#autotoc_md558',1,'']]],
  ['work_20on_20windows_57',['Does it work on Windows?',['../index.html#autotoc_md562',1,'']]],
  ['work_3a_20the_20lifecycle_58',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md424',1,'']]],
  ['works_20internally_59',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['wrapping_20it_20up_3a_20the_20full_20ipv4_20picture_60',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['wrapping_20it_20up_3a_20the_20full_20ipv6_20picture_61',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['write_62',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md178',1,'']]],
  ['wsaioctl_20windows_63',['4. WSAIoctl (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md261',1,'']]]
];
