var searchData=
[
  ['nagle’s_20algorithm_20to_20reduce_20latency_0',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1046',1,'']]],
  ['native_20bsd_20posix_20winsock_20apis_1',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md249',1,'']]],
  ['nesting_2',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md920',1,'']]],
  ['network_20module_3',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md247',1,'']]],
  ['non_20blocking_4',['What is Non-Blocking?',['../group__async__io.html#autotoc_md128',1,'']]],
  ['non_20blocking_20mode_20on_20a_20client_20socket_5',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1032',1,'']]],
  ['non_20blocking_20mode_3a_6',['Non blocking mode:',['../group__async__io.html#autotoc_md140',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md144',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md148',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md151',1,'Non-blocking mode:']]],
  ['non_20blocking_20sockets_7',['Non Blocking Sockets',['../group__async__io.html#autotoc_md126',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md325',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md335',1,'6.1 Non-Blocking Sockets']]],
  ['not_20expose_20windows_20so_5freuseaddr_8',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['notes_9',['Notes',['../group__tcp.html#autotoc_md720',1,'⚠️ Notes'],['../group__socketopts.html#autotoc_md935',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md946',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md955',1,'⚠️ ServerSocket-specific Notes'],['../group__socketopts.html#autotoc_md966',1,'⚠️ ServerSocket-specific Notes'],['../group__udp.html#autotoc_md644',1,'⚠️ Usage Notes'],['../group__tcp.html#autotoc_md915',1,'⚠️ Usage Notes'],['../group__tcp.html#autotoc_md691',1,'💡 Notes'],['../group__udp.html#autotoc_md625',1,'💡 Platform Notes'],['../group__socketopts.html#autotoc_md937',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md947',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md957',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md968',1,'📡 DatagramSocket-specific Notes'],['../group__socketopts.html#autotoc_md939',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md948',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md959',1,'🧿 UnixSocket-specific Notes'],['../group__socketopts.html#autotoc_md970',1,'🧿 UnixSocket-specific Notes'],['../group__tcp.html#autotoc_md893',1,'Implementation Notes'],['../group__bind__interfaces.html#autotoc_md169',1,'jsocketpp API Notes'],['../group__internal.html#autotoc_md489',1,'Notes'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md493',1,'Notes'],['../group__udp.html#autotoc_md527',1,'Notes'],['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md819',1,'Platform Notes'],['../group__socketopts.html#autotoc_md982',1,'Platform Notes'],['../group__socketopts.html#autotoc_md988',1,'Platform Notes']]],
  ['notes_20for_20library_20authors_10',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md114',1,'']]]
];
