var searchData=
[
  ['parameters_0',['Parameters',['../group__tcp.html#autotoc_md887',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md611',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md881',1,'Configuration Parameters'],['../group__internal.html#autotoc_md552',1,'Parameters'],['../group__udp.html#autotoc_md721',1,'Parameters']]],
  ['parameters_20used_20only_20if_20autobind_20true_1',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md889',1,'']]],
  ['peer_20model_2',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md389',1,'']]],
  ['peer_20to_20peer_20model_3',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md389',1,'']]],
  ['performance_20considerations_4',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md361',1,'']]],
  ['performance_20footprint_5',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md461',1,'']]],
  ['persist_20for_20the_20socket’s_20lifetime_6',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['platform_20api_20considerations_7',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md276',1,'']]],
  ['platform_20behavior_8',['Platform Behavior',['../group__udp.html#autotoc_md716',1,'⚙️ Platform Behavior'],['../group__socketopts.html#autotoc_md1193',1,'⚠️ Platform Behavior'],['../group__socketopts.html#autotoc_md1116',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1121',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1126',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1131',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1136',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1147',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1156',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1184',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1170',1,'🔐 Platform Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md762',1,'Platform Behavior'],['../group__tcp.html#autotoc_md860',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1084',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1087',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1091',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1097',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1109',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1113',1,'Platform Behavior']]],
  ['platform_20notes_9',['Platform Notes',['../group__udp.html#autotoc_md732',1,'💡 Platform Notes'],['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md931',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1094',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1100',1,'Platform Notes']]],
  ['platform_20socket_20library_20for_20modern_20c_2020_10',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['platform_20specific_20apis_11',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md371',1,'']]],
  ['platform_20specific_20considerations_12',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md402',1,'']]],
  ['platform_20specific_20tests_3a_13',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md422',1,'']]],
  ['platform_20support_14',['Platform Support',['../group__socketopts.html#autotoc_md1200',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1207',1,'🔀 Platform Support'],['../group__socket-options.html#autotoc_md288',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md872',1,'Platform Support']]],
  ['platform_20toolchain_20support_15',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md457',1,'']]],
  ['platform_3a_16',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md421',1,'']]],
  ['pledge_17',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md528',1,'']]],
  ['poco_3a_3anet_18',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md316',1,'']]],
  ['poll_19',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md270',1,'']]],
  ['port_20',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['port_20binding_21',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1202',1,'']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_22',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['port_20in_20the_20constructor_23',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['port_20locally_24',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md438',1,'']]],
  ['portability_25',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md47',1,'']]],
  ['portfile_26',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md434',1,'']]],
  ['portfile_20cmake_27',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md436',1,'']]],
  ['posix_20approach_28',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['posix_20linux_20macos_20unix_29',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md372',1,'']]],
  ['posix_20style_30',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['posix_20winsock_20apis_31',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md320',1,'']]],
  ['practical_20considerations_32',['Practical Considerations',['../group__underlying__socket__api.html#autotoc_md410',1,'7. Practical Considerations'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md263',1,'Practical Considerations']]],
  ['practical_20examples_33',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md392',1,'']]],
  ['practical_20implications_34',['Practical Implications',['../group__socket__states.html#autotoc_md336',1,'']]],
  ['practical_20implications_35',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['practical_20recommendations_36',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md278',1,'']]],
  ['practices_37',['Practices',['../group__async__io.html#autotoc_md169',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md444',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md178',1,'Best Practices']]],
  ['practices_20recap_38',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['pre_20commit_20hooks_39',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md518',1,'']]],
  ['pre_20commit_20hooks_40',['Pre-commit hooks',['../index.html#autotoc_md488',1,'']]],
  ['preconditions_41',['Preconditions',['../group__core.html#autotoc_md544',1,'']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_42',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_43',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md432',1,'']]],
  ['prerequisites_44',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md185',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md430',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md4',1,'Prerequisites']]],
  ['presets_20recommended_45',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['problematic_20on_20windows_46',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['production_47',['Can I use jsocketpp in production?',['../index.html#autotoc_md501',1,'']]],
  ['project_48',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['project_20conan_20friendly_49',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['pros_20and_20cons_50',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['protocol_20applicability_51',['Protocol Applicability',['../group__socketopts.html#autotoc_md1088',1,'']]],
  ['protocol_20behavior_52',['Protocol Behavior',['../group__tcp.html#autotoc_md1007',1,'']]],
  ['protocol_20format_53',['Protocol Format',['../group__tcp.html#autotoc_md953',1,'Protocol Format'],['../group__tcp.html#autotoc_md956',1,'Protocol Format'],['../group__tcp.html#autotoc_md980',1,'Protocol Format'],['../group__tcp.html#autotoc_md983',1,'Protocol Format']]],
  ['protocol_20use_20cases_54',['Protocol Use Cases',['../group__socketopts.html#autotoc_md1085',1,'']]],
  ['protocols_20and_20the_20socket_20api_55',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md391',1,'']]],
  ['pull_20request_20to_20cci_56',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['pull_20requests_57',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md514',1,'']]],
  ['purpose_58',['Purpose',['../group__address__reuse.html#autotoc_md89',1,'🎯 Purpose'],['../group__udp.html#autotoc_md723',1,'🧠 Purpose'],['../namespacejsocketpp_1_1net.html#autotoc_md537',1,'Purpose'],['../group__tcp.html#autotoc_md1000',1,'Purpose']]],
  ['py_59',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md187',1,'']]],
  ['python_20af_5finet_60',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md393',1,'']]]
];
