var searchData=
[
  ['waiting_20for_20readiness_0',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['warning_1',['Warning',['../group__tcp.html#autotoc_md775',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md788',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md746',1,'⚠️ Race Condition Warning']]],
  ['what_20about_20udp_20and_20unix_20sockets_2',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md274',1,'']]],
  ['what_20are_20socket_20options_3',['What Are Socket Options?',['../group__socket-options.html#autotoc_md226',1,'']]],
  ['what_20does_20“binding_20to_20all_20interfaces”_20mean_4',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['what_20happens_20when_20multiple_20sockets_20bind_20to_20the_20same_20port_5',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['what_20is_20a_20socket_6',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md285',1,'']]],
  ['what_20is_20a_20socket_20state_7',['What is a Socket State?',['../group__socket__states.html#autotoc_md267',1,'']]],
  ['what_20is_20blocking_8',['What is Blocking?',['../group__async__io.html#autotoc_md138',1,'']]],
  ['what_20is_20connected_20udp_9',['🔌 What Is Connected UDP?',['../group__udp.html#autotoc_md560',1,'']]],
  ['what_20is_20multicast_10',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md698',1,'']]],
  ['what_20is_20non_20blocking_11',['What is Non-Blocking?',['../group__async__io.html#autotoc_md139',1,'']]],
  ['what_20is_20socket_20binding_12',['What is Socket Binding?',['../group__socket__binding.html#autotoc_md64',1,'']]],
  ['what_20is_20the_20default_20buffer_20size_13',['What is the default buffer size?',['../index.html#autotoc_md445',1,'']]],
  ['what_20is_20the_20mtu_14',['🔍 What is the MTU?',['../group__udp.html#autotoc_md647',1,'']]],
  ['what_20is_20transferred_15',['What Is Transferred',['../group__udp.html#autotoc_md547',1,'']]],
  ['what_20is_20udp_16',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md513',1,'']]],
  ['what_20it_20actually_20does_17',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['what_20java_20does_18',['What Java Does',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['what_20jsocketpp_20does_19',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['what_20jsocketpp_20gets_20right_20',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md130',1,'']]],
  ['when_20multiple_20sockets_20bind_20to_20the_20same_20port_21',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['when_20to_20adjust_22',['When to Adjust',['../group__core.html#autotoc_md483',1,'']]],
  ['when_20to_20use_23',['When to Use',['../group__socketopts.html#autotoc_md1145',1,'']]],
  ['when_20true_20matters_24',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md800',1,'']]],
  ['why_20jsocketpp_25',['💡 Why jsocketpp?',['../index.html#autotoc_md393',1,'']]],
  ['why_20not_20expose_20windows_20so_5freuseaddr_26',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md121',1,'']]],
  ['why_20require_20the_20port_20in_20the_20constructor_27',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['why_20select_20is_20used_28',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md206',1,'']]],
  ['why_20this_20is_20problematic_20on_20windows_29',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['why_20this_20matters_30',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md509',1,'']]],
  ['wildcard_20addresses_31',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md175',1,'']]],
  ['windows_32',['Windows',['../index.html#autotoc_md443',1,'Does it work on Windows?'],['../group__address__reuse.html#autotoc_md111',1,'Why This is Problematic on Windows'],['../group__address__reuse.html#autotoc_md103',1,'Windows']]],
  ['windows_20counterparts_33',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md214',1,'']]],
  ['windows_20only_34',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md87',1,'']]],
  ['windows_20so_5freuseaddr_35',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md121',1,'']]],
  ['windows_20winsock_36',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md313',1,'']]],
  ['windows_3a_37',['Windows:',['../group__address__reuse.html#autotoc_md85',1,'On Windows:'],['../group__address__reuse.html#autotoc_md86',1,'On Windows:']]],
  ['winsock_38',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md313',1,'']]],
  ['winsock_20apis_39',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md260',1,'']]],
  ['with_20acceptnonblocking_40',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md755',1,'']]],
  ['with_20extreme_20care_41',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md973',1,'']]],
  ['with_20google_20mock_3a_42',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md364',1,'']]],
  ['with_20mocking_3a_43',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md365',1,'']]],
  ['with_20select_44',['Example: Use with &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__socketopts.html#autotoc_md977',1,'']]],
  ['with_20so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_45',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['with_20so_5freuseaddr_20only_3a_46',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['with_20so_5freuseaddr_20so_5freuseport_3a_47',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md101',1,'']]],
  ['with_20so_5freuseaddr_3a_48',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md104',1,'']]],
  ['with_20so_5freuseport_49',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md84',1,'']]],
  ['work_50',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md295',1,'']]],
  ['work_51',['How does error handling work?',['../index.html#autotoc_md439',1,'']]],
  ['work_20on_20windows_52',['Does it work on Windows?',['../index.html#autotoc_md443',1,'']]],
  ['work_3a_20the_20lifecycle_53',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md305',1,'']]],
  ['works_20internally_54',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md93',1,'']]],
  ['write_55',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md160',1,'']]]
];
