var searchData=
[
  ['o_0',['O',['../group__underlying__socket__api.html#autotoc_md316',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md326',1,'6.4 Asynchronous I/O']]],
  ['of_20a_20simple_20server_20client_20integration_20test_3a_1',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['of_20address_20reuse_20options_2',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['of_20conduct_3',['of Conduct',['../md_CONTRIBUTING.html#autotoc_md405',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['of_20contents_4',['of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['of_20epoll_5',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md189',1,'']]],
  ['of_20java’s_20design_20trade_20off_6',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['of_20operation_7',['Modes of Operation',['../group__tcp.html#autotoc_md557',1,'']]],
  ['of_20poll_8',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md187',1,'']]],
  ['of_20select_9',['2. &lt;b&gt;Drawbacks of &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md185',1,'']]],
  ['of_20sockets_20in_20depth_10',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['of_20the_20socket_20api_11',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['off_12',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['on_20unix_20linux_3a_13',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md55',1,'']]],
  ['on_20windows_14',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['on_20windows_3a_15',['On Windows:',['../group__address__reuse.html#autotoc_md62',1,'On Windows:'],['../group__address__reuse.html#autotoc_md63',1,'On Windows:']]],
  ['only_16',['only',['../group__address__reuse.html#autotoc_md64',1,'<span class="tt">SO_EXCLUSIVEADDRUSE</span> (Windows only)'],['../group__address__reuse.html#autotoc_md72',1,'<span class="tt">SO_REUSEPORT</span> (Unix/Linux only)']]],
  ['only_3a_17',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['operate_18',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['operation_19',['Modes of Operation',['../group__tcp.html#autotoc_md557',1,'']]],
  ['operation_20specific_20behavior_3a_20connect_20accept_20recv_20and_20send_20',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['options_21',['Options',['../group__address__reuse.html#autotoc_md53',1,'🔍 In-Depth Overview of Address Reuse Options'],['../group__underlying__socket__api.html#autotoc_md314',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md324',1,'6.2 Socket Options'],['../group__socket-options.html#autotoc_md203',1,'What Are Socket Options?']]],
  ['options_20by_20socket_20type_22',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['options_20for_20all_20sockets_23',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md208',1,'']]],
  ['or_20stubbing_20socket_20api_20for_20unit_20tests_3a_24',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['os_20level_20timeouts_25',['OS-Level Timeouts',['../group__async__io.html#autotoc_md119',1,'']]],
  ['our_20pledge_26',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md409',1,'']]],
  ['our_20responsibilities_27',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md411',1,'']]],
  ['our_20standards_28',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md410',1,'']]],
  ['overview_29',['Overview',['../index.html#autotoc_md367',1,'Overview'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md439',1,'Overview']]],
  ['overview_20of_20address_20reuse_20options_30',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]]
];
