var searchData=
[
  ['safety_0',['Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md35',1,'a) Flexibility and Safety'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md471',1,'Safety'],['../group__tcp.html#autotoc_md483',1,'Thread Safety'],['../group__tcp.html#autotoc_md486',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md491',1,'Thread Safety'],['../group__tcp.html#autotoc_md509',1,'Thread Safety']]],
  ['same_20port_1',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['scenarios_2',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md44',1,'']]],
  ['scope_3',['Scope',['../md_CODE__OF__CONDUCT.html#autotoc_md448',1,'']]],
  ['security_20and_20performance_20considerations_4',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md278',1,'']]],
  ['security_20considerations_5',['7. Security Considerations',['../group__underlying__socket__api.html#autotoc_md317',1,'']]],
  ['see_20also_6',['See Also',['../index.html#autotoc_md426',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md481',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md494',1,'See Also']]],
  ['select_7',['select',['../group__select__poll__epoll__iocp.html#autotoc_md185',1,'2. <b>Drawbacks of <span class="tt">select</span></b>'],['../group__async__io.html#autotoc_md120',1,'Custom Timeouts via <span class="tt">select()</span>']]],
  ['select_20is_20used_8',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['semantics_9',['Timeout Semantics',['../group__tcp.html#autotoc_md485',1,'']]],
  ['send_10',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['send_20write_11',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md137',1,'']]],
  ['send_3a_12',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['sending_13',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md475',1,'']]],
  ['server_14',['Server',['../index.html#autotoc_md392',1,'📡 UDP Echo Server'],['../index.html#autotoc_md390',1,'🧵 TCP Echo Server'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md608',1,'Example: Simple Echo Server']]],
  ['server_20and_20client_15',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md465',1,'']]],
  ['server_20and_20client_20c_20af_5finet_16',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['server_20and_20client_20python_20af_5finet_17',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['server_20and_20client_3a_18',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['server_20client_20integration_20test_3a_19',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['server_20model_20',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md305',1,'']]],
  ['server_20side_21',['4.1. Server Side',['../group__sockets__theory.html#autotoc_md283',1,'']]],
  ['serversocket_22',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['serversocket_3a_20constructor_20does_20all_20steps_23',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['setting_20up_20real_20server_20and_20client_3a_24',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['shutdown_20modes_25',['Shutdown Modes',['../group__tcp.html#autotoc_md543',1,'']]],
  ['side_26',['Side',['../group__sockets__theory.html#autotoc_md283',1,'4.1. Server Side'],['../group__sockets__theory.html#autotoc_md284',1,'4.2. Client Side']]],
  ['simple_20client_27',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md609',1,'']]],
  ['simple_20echo_20server_28',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md608',1,'']]],
  ['simple_20server_20client_20integration_20test_3a_29',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['simple_20udp_20echo_20server_20and_20client_30',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md465',1,'']]],
  ['size_31',['What is the default buffer size?',['../index.html#autotoc_md422',1,'']]],
  ['smarter_20strategy_20for_20jsocketpp_32',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_33',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['so_5fexclusiveaddruse_20windows_20only_34',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md64',1,'']]],
  ['so_5freuseaddr_35',['SO_REUSEADDR',['../group__address__reuse.html#autotoc_md54',1,'<span class="tt">SO_REUSEADDR</span>'],['../group__address__reuse.html#autotoc_md98',1,'Why Not Expose Windows <span class="tt">SO_REUSEADDR</span>?']]],
  ['so_5freuseaddr_20only_3a_36',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['so_5freuseaddr_20so_5freuseport_3a_37',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['so_5freuseaddr_3a_38',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['so_5freuseport_39',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['so_5freuseport_20unix_20linux_20only_40',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md72',1,'']]],
  ['so_5freuseport_3a_41',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['socket_42',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['socket_20address_20families_43',['3. Socket Address Families',['../group__sockets__theory.html#autotoc_md280',1,'']]],
  ['socket_20api_44',['Socket API',['../group__underlying__socket__api.html#autotoc_md299',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md300',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md308',1,'4. Protocols and the Socket API']]],
  ['socket_20api_20features_45',['Socket API Features',['../group__underlying__socket__api.html#autotoc_md312',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md322',1,'Advanced Socket API Features']]],
  ['socket_20api_20for_20unit_20tests_3a_46',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['socket_20api_20in_20action_3a_20practical_20examples_47',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md309',1,'']]],
  ['socket_20behavior_3a_48',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md332',1,'']]],
  ['socket_20communication_49',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md307',1,'']]],
  ['socket_20exceptions_50',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md605',1,'']]],
  ['socket_20initialization_20and_20cleanup_3a_51',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['socket_20initialization_3a_20posix_20approach_52',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md27',1,'']]],
  ['socket_20ipc_53',['🧷 UNIX Domain Socket (IPC)',['../index.html#autotoc_md396',1,'']]],
  ['socket_20library_20for_20modern_20c_2020_54',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['socket_20lifecycle_55',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md246',1,'']]],
  ['socket_20options_56',['Socket Options',['../group__underlying__socket__api.html#autotoc_md314',1,'6.2 Socket Options'],['../group__underlying__socket__api.html#autotoc_md324',1,'6.2 Socket Options'],['../group__socket-options.html#autotoc_md203',1,'What Are Socket Options?']]],
  ['socket_20serversocket_57',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['socket_20state_58',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['socket_20state_20handling_59',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md60',1,'']]],
  ['socket_20states_60',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['socket_20timeouts_61',['🕐 Socket Timeouts',['../group__async__io.html#autotoc_md118',1,'']]],
  ['socket_20type_62',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['socket_20types_63',['Socket Types',['../group__underlying__socket__api.html#autotoc_md303',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md270',1,'2.5. Comparison Table: Socket Types']]],
  ['socket_20types_20work_64',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['sockets_65',['Sockets',['../group__async__io.html#autotoc_md114',1,'🚦 Blocking vs Non-Blocking Sockets'],['../group__socket-options.html#autotoc_md208',1,'1. Options for All Sockets'],['../group__sockets__theory.html#autotoc_md267',1,'2.3. Raw Sockets'],['../group__underlying__socket__api.html#autotoc_md313',1,'6.1 Non-Blocking Sockets'],['../group__underlying__socket__api.html#autotoc_md323',1,'6.1 Non-Blocking Sockets'],['../group__sockets__theory.html#autotoc_md275',1,'Raw Sockets'],['../group__sockets__theory.html#autotoc_md276',1,'Unix Domain Sockets'],['../group__socket__states.html#autotoc_md251',1,'What About UDP and UNIX Sockets?']]],
  ['sockets_20bind_20to_20the_20same_20port_66',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['sockets_20datagramsocket_20multicastsocket_67',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md212',1,'']]],
  ['sockets_20in_20depth_68',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md264',1,'']]],
  ['sockets_20local_20ipc_69',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md268',1,'']]],
  ['sockets_20operate_70',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md286',1,'']]],
  ['sockets_20socket_20serversocket_71',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md210',1,'']]],
  ['sockets_20tcp_72',['Sockets TCP',['../group__sockets__theory.html#autotoc_md265',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md273',1,'Stream Sockets (TCP)']]],
  ['sockets_20udp_73',['Sockets UDP',['../group__sockets__theory.html#autotoc_md266',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md274',1,'Datagram Sockets (UDP)']]],
  ['sockets_20unixsocket_74',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md215',1,'']]],
  ['sockets_20work_3a_20the_20lifecycle_75',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'']]],
  ['specific_20apis_76',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md288',1,'']]],
  ['specific_20behavior_3a_20connect_20accept_20recv_20and_20send_77',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['specific_20considerations_78',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md319',1,'']]],
  ['specific_20details_79',['Platform-Specific Details',['../group__tcp.html#autotoc_md600',1,'']]],
  ['specific_20tests_3a_80',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['standards_81',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md446',1,'']]],
  ['start_20examples_82',['🚀 Quick Start Examples',['../index.html#autotoc_md389',1,'']]],
  ['state_83',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['state_20handling_84',['🧪 Socket state handling',['../group__address__reuse.html#autotoc_md60',1,'']]],
  ['state_20transitions_85',['TCP State Transitions',['../group__socket__states.html#autotoc_md249',1,'']]],
  ['states_86',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['step_20by_20step_20posix_20style_87',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['step_20posix_20style_88',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'']]],
  ['steps_89',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['strategy_20for_20jsocketpp_90',['✅ Smarter Strategy for jsocketpp',['../group__address__reuse.html#autotoc_md94',1,'']]],
  ['stream_20sockets_20tcp_91',['Stream Sockets TCP',['../group__sockets__theory.html#autotoc_md265',1,'2.1. Stream Sockets (TCP)'],['../group__sockets__theory.html#autotoc_md273',1,'Stream Sockets (TCP)']]],
  ['stubbing_20socket_20api_20for_20unit_20tests_3a_92',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['style_93',['Style',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'<b>a) Constructor Does All (Java Default Style)</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md41',1,'<b>b) Fully Step-by-Step (POSIX Style)</b>']]],
  ['style_20cross_20platform_20socket_20library_20for_20modern_20c_2020_94',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['style_20guidelines_95',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md433',1,'']]],
  ['submission_96',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['submit_20a_20pull_20request_20to_20cci_97',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['submit_20to_20the_20vcpkg_20registry_98',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'']]],
  ['submitting_20pull_20requests_99',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md431',1,'']]],
  ['summary_100',['Summary',['../group__address__reuse.html#autotoc_md71',1,'🧠 Summary'],['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'9. Summary']]],
  ['summary_20of_20java’s_20design_20trade_20off_101',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md90',1,'']]],
  ['summary_20table_102',['Summary Table',['../group__address__reuse.html#autotoc_md100',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md217',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md197',1,'8. <b>Summary Table</b>'],['../group__sockets__theory.html#autotoc_md294',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md84',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md239',1,'Summary Table']]],
  ['summary_20table_3a_20waiting_20for_20readiness_103',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['support_104',['Support',['../index.html#autotoc_md374',1,'🔧 Platform &amp; Toolchain Support'],['../group__socket-options.html#autotoc_md205',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md492',1,'Platform Support']]],
  ['supported_20types_105',['Supported Types',['../group__tcp.html#autotoc_md507',1,'']]]
];
