var searchData=
[
  ['raii_20guarantees_0',['RAII Guarantees',['../group__udp.html#autotoc_md493',1,'']]],
  ['rationale_1',['Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md34',1,'4. Advantages and Rationale'],['../group__async__io.html#autotoc_md123',1,'Design Rationale'],['../group__core.html#autotoc_md458',1,'Rationale'],['../group__udp.html#autotoc_md489',1,'Rationale'],['../group__udp.html#autotoc_md495',1,'Rationale'],['../group__udp.html#autotoc_md595',1,'Rationale'],['../group__tcp.html#autotoc_md601',1,'Rationale'],['../group__tcp.html#autotoc_md644',1,'Rationale'],['../group__socketopts.html#autotoc_md782',1,'Rationale'],['../group__socketopts.html#autotoc_md783',1,'Rationale'],['../group__socketopts.html#autotoc_md784',1,'Rationale']]],
  ['raw_20socket_20communication_2',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md307',1,'']]],
  ['raw_20sockets_3',['Raw Sockets',['../group__sockets__theory.html#autotoc_md267',1,'2.3. Raw Sockets'],['../group__sockets__theory.html#autotoc_md275',1,'Raw Sockets']]],
  ['read_4',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md134',1,'']]],
  ['read_20configured_20receive_20buffer_20size_5',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md812',1,'']]],
  ['read_20so_5flinger_20setting_6',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md823',1,'']]],
  ['readiness_7',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['reading_8',['Further Reading',['../group__socket-options.html#autotoc_md225',1,'']]],
  ['real_20server_20and_20client_3a_9',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['recap_10',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md110',1,'']]],
  ['receive_20buffer_20size_11',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md812',1,'']]],
  ['receive_20timeout_12',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md865',1,'']]],
  ['receiver_13',['🌐 Multicast Receiver',['../index.html#autotoc_md394',1,'']]],
  ['receiving_14',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md592',1,'']]],
  ['recipe_20conanfile_20py_15',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['recipe_20locally_16',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md168',1,'']]],
  ['recommendations_17',['Recommendations',['../group__select__poll__epoll__iocp.html#autotoc_md195',1,'7. <b>Practical Recommendations</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md48',1,'8. Recommendations'],['../group__socket-options.html#autotoc_md223',1,'Design Recommendations']]],
  ['recommended_18',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['recommended_20behavior_19',['Recommended Behavior',['../group__address__reuse.html#autotoc_md95',1,'']]],
  ['recommended_20use_20',['Recommended Use',['../namespacejsocketpp_1_1net.html#autotoc_md456',1,'']]],
  ['recv_20and_20send_21',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['recv_20and_20send_3a_22',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['recv_20read_23',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md134',1,'']]],
  ['reduce_20latency_24',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md905',1,'']]],
  ['references_25',['References',['../group__address__reuse.html#autotoc_md104',1,'🔗 References'],['../group__sockets__theory.html#autotoc_md296',1,'9. References'],['../group__conan__publish__guide.html#autotoc_md179',1,'References'],['../group__vcpkg__publish__guide.html#autotoc_md363',1,'References']]],
  ['registry_26',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md357',1,'']]],
  ['relates_20to_20jsocketpp_27',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md255',1,'']]],
  ['reporting_20issues_28',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md429',1,'']]],
  ['request_20to_20cci_29',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['requests_30',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md431',1,'']]],
  ['require_20the_20port_20in_20the_20constructor_31',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['requirements_32',['Requirements',['../group__udp.html#autotoc_md559',1,'']]],
  ['resource_20cleanup_33',['Resource Cleanup',['../group__tcp.html#autotoc_md602',1,'']]],
  ['resource_20management_34',['Resource Management',['../group__tcp.html#autotoc_md727',1,'']]],
  ['resources_35',['More Resources',['../group__socket__states.html#autotoc_md257',1,'']]],
  ['responsibilities_36',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md447',1,'']]],
  ['return_20value_37',['Return Value',['../group__socketopts.html#autotoc_md853',1,'']]],
  ['reuse_20options_38',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md53',1,'']]],
  ['right_39',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md107',1,'']]],
  ['roadmap_40',['🛣️ Roadmap',['../index.html#autotoc_md424',1,'']]],
  ['running_20tests_41',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]]
];
