var searchData=
[
  ['udp_0',['UDP',['../group__sockets__theory.html#autotoc_md323',1,'2.2. Datagram Sockets (UDP)'],['../group__sockets__theory.html#autotoc_md331',1,'Datagram Sockets (UDP)'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md422',1,'What is UDP?']]],
  ['udp_20and_20unix_20sockets_1',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md308',1,'']]],
  ['udp_20echo_20server_20and_20client_2',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['udp_20example_3',['UDP Example',['../index.html#autotoc_md37',1,'']]],
  ['udp_20server_20and_20client_20c_20af_5finet_4',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md368',1,'']]],
  ['udp_20sockets_20datagramsocket_20multicastsocket_5',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md269',1,'']]],
  ['under_20the_20hood_3a_20how_20socket_20types_20work_6',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md329',1,'']]],
  ['under_20the_20hood_3a_20how_20sockets_20operate_7',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md343',1,'']]],
  ['understanding_20bind_20_3a_20binding_20to_20all_20interfaces_20vs_20specific_20interfaces_8',['Understanding &lt;span class=&quot;tt&quot;&gt;bind()&lt;/span&gt;: Binding to All Interfaces vs Specific Interfaces',['../group__bind__interfaces.html#autotoc_md207',1,'']]],
  ['understanding_20socket_20states_9',['Understanding Socket States',['../group__socket__states.html#autotoc_md299',1,'']]],
  ['unit_20testing_20and_20integration_20guide_10',['Unit Testing and Integration Guide',['../group__unit__tests.html#autotoc_md386',1,'']]],
  ['unit_20testing_20in_20c_2017_3a_11',['Tools for Unit Testing in C++17:',['../group__unit__tests.html#autotoc_md388',1,'']]],
  ['unit_20tests_3a_12',['Unit Tests:',['../group__unit__tests.html#autotoc_md387',1,'1. <b>Unit Tests</b>:'],['../group__unit__tests.html#autotoc_md397',1,'4. <b>Mocking or Stubbing Socket API for Unit Tests</b>:']]],
  ['unix_13',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md346',1,'']]],
  ['unix_20domain_20sockets_14',['Unix Domain Sockets',['../group__sockets__theory.html#autotoc_md333',1,'']]],
  ['unix_20domain_20sockets_20local_20ipc_15',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md325',1,'']]],
  ['unix_20domain_20sockets_20unixsocket_16',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md272',1,'']]],
  ['unix_20linux_17',['Unix/Linux',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['unix_20linux_20only_18',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['unix_20linux_3a_19',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md105',1,'']]],
  ['unix_20sockets_20',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md308',1,'']]],
  ['unixsocket_21',['4. Unix Domain Sockets (&lt;span class=&quot;tt&quot;&gt;UnixSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md272',1,'']]],
  ['up_20real_20server_20and_20client_3a_22',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md393',1,'']]],
  ['usage_23',['Usage',['../group__ServerSocket__Lifecycle.html#autotoc_md96',1,'7. Example Usage'],['../classjsocketpp_1_1Socket.html#autotoc_md454',1,'Advanced Usage'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md431',1,'Typical Usage']]],
  ['usage_20example_24',['Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md449',1,'Typical Usage Example'],['../group__BUILD__AND__USAGE.html#autotoc_md66',1,'Usage Example'],['../group__tcp.html#autotoc_md435',1,'Usage Example'],['../group__tcp.html#autotoc_md441',1,'Usage Example']]],
  ['usage_20example_20receiving_25',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md427',1,'']]],
  ['usage_20example_20sending_26',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md428',1,'']]],
  ['usage_20guide_27',['jsocketpp: Build, Test, and Usage Guide',['../group__BUILD__AND__USAGE.html#autotoc_md50',1,'']]],
  ['use_20case_28',['✅ Use Case',['../group__address__reuse.html#autotoc_md126',1,'']]],
  ['use_20cases_29',['📦 Common use cases',['../group__address__reuse.html#autotoc_md107',1,'']]],
  ['use_20cases_20and_20applications_30',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md375',1,'']]],
  ['use_20select_20for_20asynchronous_20i_20o_20operations_20does_20it_20make_20sense_20to_20provide_20poll_20and_20epoll_20as_20alternatives_31',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'']]],
  ['use_3a_32',['Example Use:',['../group__async__io.html#autotoc_md204',1,'']]],
  ['used_33',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md240',1,'']]],
  ['using_20cmake_20for_20platform_20specific_20tests_3a_34',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md396',1,'']]],
  ['using_20cmake_20presets_20recommended_35',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md57',1,'']]],
  ['using_20google_20mock_20to_20mock_20recv_20and_20send_3a_36',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['using_20the_20makefile_37',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md59',1,'']]]
];
