var searchData=
[
  ['latency_0',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['level_20timeouts_1',['OS-Level Timeouts',['../group__async__io.html#autotoc_md160',1,'']]],
  ['library_2',['Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['library_3',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md371',1,'']]],
  ['library_20authors_4',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md143',1,'']]],
  ['library_20for_20modern_20c_2020_5',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['library_20for_20vcpkg_6',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md491',1,'']]],
  ['license_7',['License',['../index.html#autotoc_md551',1,'⚖️ License'],['../group__BUILD__AND__USAGE.html#autotoc_md24',1,'License']]],
  ['lifecycle_8',['Lifecycle',['../group__sockets__theory.html#autotoc_md424',1,'4. How Sockets Work: The Lifecycle'],['../group__socket__states.html#autotoc_md388',1,'TCP Socket Lifecycle']]],
  ['lifetime_9',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['lifetime_20warning_10',['Lifetime Warning',['../group__tcp.html#autotoc_md810',1,'⚠️ Lifetime Warning'],['../group__tcp.html#autotoc_md823',1,'⚠️ Lifetime Warning']]],
  ['limitations_11',['Limitations',['../group__address__reuse.html#autotoc_md127',1,'⚠️ Java’s Approach and Its Limitations'],['../index.html#autotoc_md522',1,'⚠️ Limitations'],['../group__tcp.html#autotoc_md905',1,'Limitations'],['../classjsocketpp_1_1UnixSocket.html#autotoc_md1187',1,'Limitations']]],
  ['limitations_3a_12',['Limitations:',['../group__async__io.html#autotoc_md185',1,'']]],
  ['linger_20for_205_20seconds_20on_20close_13',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1025',1,'']]],
  ['linking_20the_20library_14',['Linking the Library',['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'']]],
  ['linux_15',['Linux',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md226',1,'1. ioctl (Unix/Linux)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md239',1,'2. fcntl (Unix/Linux)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md235',1,'Example: Custom Device Driver (Linux)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md246',1,'Example: Set Non-Blocking Socket (Linux)'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md234',1,'Example: Terminal Window Size (Linux)'],['../group__address__reuse.html#autotoc_md117',1,'Unix/Linux']]],
  ['linux_20macos_16',['POSIX/BSD API (Unix/Linux/MacOS)',['../group__multicast__sockets.html#autotoc_md291',1,'']]],
  ['linux_20macos_20unix_17',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md431',1,'']]],
  ['linux_20only_18',['&lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt; (Unix/Linux only)',['../group__address__reuse.html#autotoc_md113',1,'']]],
  ['linux_3a_19',['On Unix/Linux:',['../group__address__reuse.html#autotoc_md96',1,'']]],
  ['list_20windows_20',['Example: Get Interface List (Windows)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md268',1,'']]],
  ['listen_20explicit_21',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['local_20address_22',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['local_20addresses_3a_20private_20networking_23',['Unique Local Addresses: Private Networking',['../group__mastering__ipv6.html#autotoc_md52',1,'']]],
  ['local_20binding_20parameters_20used_20only_20if_20autobind_20true_24',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['local_20binding_20persist_20for_20the_20socket’s_20lifetime_25',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['local_20ipc_26',['2.4. Unix Domain Sockets (Local IPC)',['../group__sockets__theory.html#autotoc_md410',1,'']]],
  ['locally_27',['Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'4. Test the Port Locally'],['../group__conan__publish__guide.html#autotoc_md209',1,'4. Test the Recipe Locally']]],
  ['loopback_20and_20testing_28',['Loopback and Testing',['../group__multicast__sockets.html#autotoc_md306',1,'']]]
];
