var searchData=
[
  ['c_2020_0',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['c_2020_3a_1',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['c_20af_5finet_2',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['c_20clear_20api_3',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'']]],
  ['c_20jsocketpp_20hybrid_4',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['callback_20signature_5',['🔁 Callback Signature',['../group__tcp.html#autotoc_md676',1,'']]],
  ['can_20i_20use_20jsocketpp_20in_20production_6',['Can I use jsocketpp in production?',['../index.html#autotoc_md418',1,'']]],
  ['care_7',['⚠️ HANDLE WITH EXTREME CARE',['../group__socketopts.html#autotoc_md850',1,'']]],
  ['case_8',['Case',['../group__address__reuse.html#autotoc_md69',1,'✅ Use Case'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md587',1,'Use Case']]],
  ['cases_9',['Cases',['../group__socketopts.html#autotoc_md953',1,'✅ Use Cases'],['../group__socketopts.html#autotoc_md965',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md997',1,'💡 Use Cases'],['../group__socketopts.html#autotoc_md856',1,'🔧 Common Use Cases'],['../group__socketopts.html#autotoc_md874',1,'🔧 Use Cases'],['../group__socketopts.html#autotoc_md885',1,'🔧 Use Cases'],['../group__tcp.html#autotoc_md702',1,'🛠 Use Cases'],['../group__socketopts.html#autotoc_md865',1,'🧩 Use Cases'],['../index.html#autotoc_md368',1,'🧰 Typical Use Cases'],['../group__udp.html#autotoc_md499',1,'Common Use Cases'],['../group__udp.html#autotoc_md501',1,'Common Use Cases'],['../group__udp.html#autotoc_md503',1,'Common Use Cases'],['../group__socketopts.html#autotoc_md896',1,'Protocol Use Cases'],['../group__udp.html#autotoc_md525',1,'Use Cases'],['../group__udp.html#autotoc_md540',1,'Use Cases'],['../group__udp.html#autotoc_md570',1,'Use Cases'],['../group__udp.html#autotoc_md580',1,'Use Cases'],['../group__tcp.html#autotoc_md720',1,'Use Cases'],['../group__tcp.html#autotoc_md724',1,'Use Cases'],['../group__tcp.html#autotoc_md730',1,'Use Cases'],['../group__tcp.html#autotoc_md736',1,'Use Cases'],['../group__tcp.html#autotoc_md740',1,'Use Cases'],['../group__tcp.html#autotoc_md746',1,'Use Cases'],['../group__tcp.html#autotoc_md830',1,'Use Cases'],['../group__tcp.html#autotoc_md831',1,'Use Cases'],['../group__socketopts.html#autotoc_md960',1,'Use Cases'],['../group__socketopts.html#autotoc_md974',1,'Use Cases'],['../group__socketopts.html#autotoc_md983',1,'Use Cases']]],
  ['cases_10',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['cases_20and_20applications_11',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md318',1,'']]],
  ['cases_20to_20consider_3a_12',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['cases_3a_13',['Common Use Cases:',['../group__tcp.html#autotoc_md714',1,'']]],
  ['catching_20and_20handling_20socket_20exceptions_14',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md842',1,'']]],
  ['caveats_15',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md58',1,'']]],
  ['cci_16',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['cci_20submission_17',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['center_20index_20cci_20submission_18',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['chaining_19',['Exception Chaining',['../classjsocketpp_1_1SocketException.html#autotoc_md841',1,'']]],
  ['characteristics_20',['Behavior &amp;amp; Characteristics',['../group__udp.html#autotoc_md471',1,'']]],
  ['check_20if_20socket_20is_20ipv6_20only_21',['Example: Check if socket is IPv6-only',['../group__socketopts.html#autotoc_md1006',1,'']]],
  ['class_20mapping_22',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md398',1,'']]],
  ['classes_23',['Supported Classes',['../classjsocketpp_1_1SocketOptions.html#autotoc_md845',1,'']]],
  ['cleanup_24',['Resource Cleanup',['../group__tcp.html#autotoc_md602',1,'']]],
  ['cleanup_3a_25',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['clear_20api_26',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'']]],
  ['client_27',['Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1028',1,'Example: Simple Client'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md466',1,'Example: Simple UDP Echo Server and Client']]],
  ['client_20c_20af_5finet_28',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['client_20integration_20test_3a_29',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['client_20python_20af_5finet_30',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['client_20server_20model_31',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md305',1,'']]],
  ['client_20side_32',['4.2. Client Side',['../group__sockets__theory.html#autotoc_md284',1,'']]],
  ['client_20socket_33',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md955',1,'']]],
  ['client_3a_34',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['close_35',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md867',1,'']]],
  ['cmake_36',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md353',1,'']]],
  ['cmake_20build_37',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['cmake_20for_20platform_20specific_20tests_3a_38',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['cmake_20integration_20in_20your_20project_39',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['cmake_20presets_20recommended_40',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['cmake_20project_20conan_20friendly_41',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['code_20of_20conduct_42',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20style_20guidelines_43',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md433',1,'']]],
  ['combining_20with_20so_5freuseport_44',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['commit_20hooks_45',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md435',1,'']]],
  ['commit_20hooks_46',['Pre-commit hooks',['../index.html#autotoc_md405',1,'']]],
  ['common_20options_20by_20socket_20type_47',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['common_20scenarios_48',['Common Scenarios',['../group__tcp.html#autotoc_md583',1,'']]],
  ['common_20use_20cases_49',['Common Use Cases',['../group__socketopts.html#autotoc_md856',1,'🔧 Common Use Cases'],['../group__udp.html#autotoc_md499',1,'Common Use Cases'],['../group__udp.html#autotoc_md501',1,'Common Use Cases'],['../group__udp.html#autotoc_md503',1,'Common Use Cases']]],
  ['common_20use_20cases_50',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['common_20use_20cases_3a_51',['Common Use Cases:',['../group__tcp.html#autotoc_md714',1,'']]],
  ['communication_52',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md307',1,'']]],
  ['communication_20models_53',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md304',1,'']]],
  ['comparison_54',['📚 Java Comparison',['../group__async__io.html#autotoc_md143',1,'']]],
  ['comparison_20table_3a_20socket_20types_55',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md270',1,'']]],
  ['comparison_20with_20acceptnonblocking_56',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md647',1,'']]],
  ['compilation_57',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['components_20of_20the_20socket_20api_58',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['conan_59',['✅ Conan',['../index.html#autotoc_md385',1,'']]],
  ['conan_20center_20index_20cci_20submission_60',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['conan_20friendly_61',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['conan_20recipe_20conanfile_20py_62',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['conanfile_20py_63',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['conclusion_64',['Conclusion',['../group__address__reuse.html#autotoc_md106',1,'✅ Conclusion'],['../group__underlying__socket__api.html#autotoc_md320',1,'10. Conclusion'],['../group__underlying__socket__api.html#autotoc_md328',1,'8. Conclusion'],['../group__bind__interfaces.html#autotoc_md159',1,'Conclusion'],['../group__socket__library__comparison.html#autotoc_md241',1,'Conclusion']]],
  ['conclusion_20advice_65',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md199',1,'']]],
  ['conclusion_3a_66',['Conclusion:',['../group__unit__tests.html#autotoc_md344',1,'']]],
  ['condition_20warning_67',['⚠️ Race Condition Warning',['../group__tcp.html#autotoc_md638',1,'']]],
  ['conduct_68',['Conduct',['../md_CONTRIBUTING.html#autotoc_md441',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['configuration_69',['⚙️ Configuration',['../group__tcp.html#autotoc_md656',1,'']]],
  ['configuration_20of_20accepted_20socket_70',['Configuration of Accepted Socket',['../group__tcp.html#autotoc_md607',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md616',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md625',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md636',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md669',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md682',1,'⚙️ Configuration of Accepted Socket']]],
  ['configuration_20parameters_71',['Configuration Parameters',['../group__tcp.html#autotoc_md710',1,'🔧 Configuration Parameters'],['../group__tcp.html#autotoc_md704',1,'Configuration Parameters']]],
  ['configured_20receive_20buffer_20size_72',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md876',1,'']]],
  ['connect_73',['🔌 &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;',['../group__async__io.html#autotoc_md126',1,'']]],
  ['connect_20accept_20recv_20and_20send_74',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['connection_20mode_75',['Connection Mode',['../group__udp.html#autotoc_md531',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md545',1,'Behavior by Connection Mode']]],
  ['connection_20modes_76',['Connection Modes',['../group__udp.html#autotoc_md469',1,'🔁 Connection Modes'],['../group__udp.html#autotoc_md566',1,'🔁 Connection Modes'],['../group__udp.html#autotoc_md506',1,'Connection Modes'],['../group__tcp.html#autotoc_md750',1,'Connection Modes']]],
  ['cons_77',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['consider_3a_78',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['considerations_79',['Considerations',['../group__sockets__theory.html#autotoc_md278',1,'2.7. Security and Performance Considerations'],['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'6. <b>Cross-Platform API Considerations</b>'],['../group__underlying__socket__api.html#autotoc_md327',1,'7. Practical Considerations'],['../group__underlying__socket__api.html#autotoc_md317',1,'7. Security Considerations'],['../group__underlying__socket__api.html#autotoc_md319',1,'9. Platform-Specific Considerations']]],
  ['constraints_80',['Constraints',['../group__udp.html#autotoc_md476',1,'Constraints'],['../group__udp.html#autotoc_md483',1,'Constraints'],['../group__udp.html#autotoc_md552',1,'Constraints']]],
  ['constructor_81',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['constructor_20bind_20listen_20explicit_82',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['constructor_20defaults_83',['Constructor Defaults',['../group__address__reuse.html#autotoc_md96',1,'']]],
  ['constructor_20does_20all_20java_20default_20style_84',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['constructor_20does_20all_20steps_85',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['contents_86',['Contents',['../namespacejsocketpp_1_1internal.html#autotoc_md585',1,'Contents'],['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['contributing_87',['🤝 Contributing',['../index.html#autotoc_md407',1,'']]],
  ['contributing_20to_20jsocketpp_88',['Contributing to jsocketpp',['../md_CONTRIBUTING.html',1,'']]],
  ['control_89',['Developer Control',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['core_20components_20of_20the_20socket_20api_90',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['counterparts_91',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md191',1,'']]],
  ['coverage_20for_20cross_20platform_3a_92',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['create_20a_20vcpkg_20portfile_93',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md351',1,'']]],
  ['cross_20platform_20api_20considerations_94',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'']]],
  ['cross_20platform_20socket_20library_20for_20modern_20c_2020_95',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['cross_20platform_20support_96',['Cross-Platform Support',['../group__socket-options.html#autotoc_md205',1,'']]],
  ['cross_20platform_3a_97',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['custom_20timeouts_20via_20select_98',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md120',1,'']]],
  ['customization_99',['Customization',['../group__core.html#autotoc_md459',1,'']]]
];
