var searchData=
[
  ['parameters_0',['Parameters',['../group__tcp.html#autotoc_md821',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md542',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md815',1,'Configuration Parameters'],['../group__internal.html#autotoc_md492',1,'Parameters'],['../group__udp.html#autotoc_md654',1,'Parameters']]],
  ['parameters_20used_20only_20if_20autobind_20true_1',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md823',1,'']]],
  ['peer_20model_2',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md329',1,'']]],
  ['peer_20to_20peer_20model_3',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md329',1,'']]],
  ['performance_20considerations_4',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md301',1,'']]],
  ['performance_20footprint_5',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md401',1,'']]],
  ['persist_20for_20the_20socket’s_20lifetime_6',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md72',1,'']]],
  ['platform_20api_20considerations_7',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md216',1,'']]],
  ['platform_20behavior_8',['Platform Behavior',['../group__udp.html#autotoc_md649',1,'⚙️ Platform Behavior'],['../group__socketopts.html#autotoc_md1127',1,'⚠️ Platform Behavior'],['../group__socketopts.html#autotoc_md1050',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1055',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1060',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1065',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1070',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1081',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1090',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1118',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1104',1,'🔐 Platform Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md695',1,'Platform Behavior'],['../group__tcp.html#autotoc_md794',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1018',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1021',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1025',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1031',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1043',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1047',1,'Platform Behavior']]],
  ['platform_20notes_9',['Platform Notes',['../group__udp.html#autotoc_md665',1,'💡 Platform Notes'],['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md865',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1028',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1034',1,'Platform Notes']]],
  ['platform_20socket_20library_20for_20modern_20c_2020_10',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['platform_20specific_20apis_11',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md311',1,'']]],
  ['platform_20specific_20considerations_12',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md342',1,'']]],
  ['platform_20specific_20tests_3a_13',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md362',1,'']]],
  ['platform_20support_14',['Platform Support',['../group__socketopts.html#autotoc_md1134',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1141',1,'🔀 Platform Support'],['../group__socket-options.html#autotoc_md228',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md806',1,'Platform Support']]],
  ['platform_20toolchain_20support_15',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md397',1,'']]],
  ['platform_3a_16',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md361',1,'']]],
  ['pledge_17',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md468',1,'']]],
  ['poco_3a_3anet_18',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md256',1,'']]],
  ['poll_19',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md210',1,'']]],
  ['port_20',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['port_20binding_21',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1136',1,'']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_22',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['port_20in_20the_20constructor_23',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['port_20locally_24',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md378',1,'']]],
  ['portability_25',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md47',1,'']]],
  ['portfile_26',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md374',1,'']]],
  ['portfile_20cmake_27',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md376',1,'']]],
  ['posix_20approach_28',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'']]],
  ['posix_20linux_20macos_20unix_29',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md312',1,'']]],
  ['posix_20style_30',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md52',1,'']]],
  ['posix_20winsock_20apis_31',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md260',1,'']]],
  ['practical_20considerations_32',['7. Practical Considerations',['../group__underlying__socket__api.html#autotoc_md350',1,'']]],
  ['practical_20examples_33',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md332',1,'']]],
  ['practical_20implications_34',['Practical Implications',['../group__socket__states.html#autotoc_md276',1,'']]],
  ['practical_20implications_35',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['practical_20recommendations_36',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md218',1,'']]],
  ['practices_37',['Practices',['../group__async__io.html#autotoc_md169',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md384',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md178',1,'Best Practices']]],
  ['practices_20recap_38',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['pre_20commit_20hooks_39',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md458',1,'']]],
  ['pre_20commit_20hooks_40',['Pre-commit hooks',['../index.html#autotoc_md428',1,'']]],
  ['preconditions_41',['Preconditions',['../group__core.html#autotoc_md484',1,'']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_42',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md193',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_43',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md372',1,'']]],
  ['prerequisites_44',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md185',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md370',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md4',1,'Prerequisites']]],
  ['presets_20recommended_45',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['problematic_20on_20windows_46',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md111',1,'']]],
  ['production_47',['Can I use jsocketpp in production?',['../index.html#autotoc_md441',1,'']]],
  ['project_48',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['project_20conan_20friendly_49',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['pros_20and_20cons_50',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['protocol_20applicability_51',['Protocol Applicability',['../group__socketopts.html#autotoc_md1022',1,'']]],
  ['protocol_20behavior_52',['Protocol Behavior',['../group__tcp.html#autotoc_md941',1,'']]],
  ['protocol_20format_53',['Protocol Format',['../group__tcp.html#autotoc_md887',1,'Protocol Format'],['../group__tcp.html#autotoc_md890',1,'Protocol Format'],['../group__tcp.html#autotoc_md914',1,'Protocol Format'],['../group__tcp.html#autotoc_md917',1,'Protocol Format']]],
  ['protocol_20use_20cases_54',['Protocol Use Cases',['../group__socketopts.html#autotoc_md1019',1,'']]],
  ['protocols_20and_20the_20socket_20api_55',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md331',1,'']]],
  ['pull_20request_20to_20cci_56',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['pull_20requests_57',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md454',1,'']]],
  ['purpose_58',['Purpose',['../group__address__reuse.html#autotoc_md89',1,'🎯 Purpose'],['../group__udp.html#autotoc_md656',1,'🧠 Purpose'],['../namespacejsocketpp_1_1net.html#autotoc_md477',1,'Purpose'],['../group__tcp.html#autotoc_md934',1,'Purpose']]],
  ['py_59',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md187',1,'']]],
  ['python_20af_5finet_60',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md333',1,'']]]
];
