var searchData=
[
  ['race_20condition_20warning_0',['⚠️ Race Condition Warning',['../group__tcp.html#autotoc_md763',1,'']]],
  ['rationale_1',['Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md45',1,'4. Advantages and Rationale'],['../group__async__io.html#autotoc_md146',1,'Design Rationale'],['../group__core.html#autotoc_md582',1,'Rationale'],['../group__udp.html#autotoc_md646',1,'Rationale'],['../group__udp.html#autotoc_md703',1,'Rationale'],['../group__tcp.html#autotoc_md726',1,'Rationale'],['../group__tcp.html#autotoc_md836',1,'Rationale'],['../group__socketopts.html#autotoc_md986',1,'Rationale'],['../group__socketopts.html#autotoc_md987',1,'Rationale'],['../group__socketopts.html#autotoc_md988',1,'Rationale']]],
  ['rationale_20default_3a_208192_208_20kib_2',['Rationale (default: 8192 / 8 KiB)',['../group__core.html#autotoc_md587',1,'']]],
  ['raw_20socket_20communication_3',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md431',1,'']]],
  ['raw_20sockets_4',['Raw Sockets',['../group__sockets__theory.html#autotoc_md391',1,'2.3. Raw Sockets'],['../group__sockets__theory.html#autotoc_md399',1,'Raw Sockets']]],
  ['read_5',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md157',1,'']]],
  ['read_20configured_20receive_20buffer_20size_6',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md1016',1,'']]],
  ['read_20so_5flinger_20setting_7',['Example: Read &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; setting',['../group__socketopts.html#autotoc_md1027',1,'']]],
  ['readiness_8',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md164',1,'']]],
  ['reading_9',['Further Reading',['../group__socket-options.html#autotoc_md349',1,'']]],
  ['real_20server_20and_20client_3a_10',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md460',1,'']]],
  ['recap_11',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md133',1,'']]],
  ['receive_20buffer_20size_12',['Example: Read configured receive buffer size',['../group__socketopts.html#autotoc_md1016',1,'']]],
  ['receive_20timeout_13',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1069',1,'']]],
  ['receiver_14',['🌐 Multicast Receiver',['../index.html#autotoc_md518',1,'']]],
  ['receiver_20in_20c_15',['Example: Receiver in C',['../group__multicast__sockets.html#autotoc_md279',1,'']]],
  ['receiver_20in_20c_20winsock_16',['Example: Receiver in C++ (Winsock)',['../group__multicast__sockets.html#autotoc_md284',1,'']]],
  ['receiving_17',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md717',1,'']]],
  ['receiving_20multicast_20data_18',['Receiving Multicast Data',['../group__multicast__sockets.html#autotoc_md277',1,'']]],
  ['recipe_20conanfile_20py_19',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md187',1,'']]],
  ['recipe_20locally_20',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md191',1,'']]],
  ['recommendations_21',['Recommendations',['../group__select__poll__epoll__iocp.html#autotoc_md319',1,'7. <b>Practical Recommendations</b>'],['../group__ServerSocket__Lifecycle.html#autotoc_md59',1,'8. Recommendations'],['../group__socket-options.html#autotoc_md347',1,'Design Recommendations']]],
  ['recommended_22',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['recommended_20behavior_23',['Recommended Behavior',['../group__address__reuse.html#autotoc_md118',1,'']]],
  ['recommended_20use_24',['Recommended Use',['../namespacejsocketpp_1_1net.html#autotoc_md580',1,'']]],
  ['recv_20and_20send_25',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['recv_20and_20send_3a_26',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md457',1,'']]],
  ['recv_20read_27',['📥 &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;read&lt;/span&gt;',['../group__async__io.html#autotoc_md157',1,'']]],
  ['reduce_20latency_28',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1109',1,'']]],
  ['references_29',['References',['../group__address__reuse.html#autotoc_md127',1,'🔗 References'],['../group__sockets__theory.html#autotoc_md420',1,'9. References'],['../group__conan__publish__guide.html#autotoc_md202',1,'References'],['../group__vcpkg__publish__guide.html#autotoc_md487',1,'References']]],
  ['registry_30',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md481',1,'']]],
  ['related_20concepts_31',['Related Concepts',['../group__network__data__units.html#autotoc_md301',1,'']]],
  ['related_20functions_32',['5. Related Functions',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md254',1,'']]],
  ['relates_20to_20jsocketpp_33',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md379',1,'']]],
  ['reliable_20counterpart_20in_20tcp_34',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md299',1,'']]],
  ['reporting_20issues_35',['1. Reporting Issues',['../md_CONTRIBUTING.html#autotoc_md553',1,'']]],
  ['request_20code_20structure_36',['Request Code Structure',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md211',1,'']]],
  ['request_20to_20cci_37',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['requests_38',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md555',1,'']]],
  ['require_20the_20port_20in_20the_20constructor_39',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md43',1,'']]],
  ['resolution_40',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['resource_20cleanup_41',['Resource Cleanup',['../group__tcp.html#autotoc_md727',1,'']]],
  ['resource_20management_42',['Resource Management',['../group__tcp.html#autotoc_md921',1,'']]],
  ['resources_43',['More Resources',['../group__socket__states.html#autotoc_md381',1,'']]],
  ['responsibilities_44',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md571',1,'']]],
  ['return_20value_45',['Return Value',['../group__internal.html#autotoc_md602',1,'Return Value'],['../group__socketopts.html#autotoc_md1057',1,'Return Value']]],
  ['return_20values_46',['Return Values',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md212',1,'Return Values'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md225',1,'Return Values'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md236',1,'Return Values'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md247',1,'Return Values']]],
  ['reuse_20options_47',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['right_48',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md130',1,'']]],
  ['roadmap_49',['🛣️ Roadmap',['../index.html#autotoc_md548',1,'']]],
  ['role_20of_20the_20connect_20function_50',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md65',1,'']]],
  ['routing_51',['Multicast Routing',['../group__multicast__sockets.html#autotoc_md269',1,'']]],
  ['running_20tests_52',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]]
];
