var searchData=
[
  ['a_203_20second_20receive_20timeout_0',['Example: Set a 3-second receive timeout',['../group__socketopts.html#autotoc_md1069',1,'']]],
  ['a_205_20second_20send_20timeout_1',['Example: Set a 5-second send timeout',['../group__socketopts.html#autotoc_md1074',1,'']]],
  ['a_20better_20alternative_3a_20what_20jsocketpp_20does_2',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['a_20client_20socket_3',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1095',1,'']]],
  ['a_20constructor_20does_20all_20java_20default_20style_4',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['a_20flexibility_20and_20safety_5',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'']]],
  ['a_20glance_6',['✨ Features at a Glance',['../index.html#autotoc_md496',1,'']]],
  ['a_20local_20address_7',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['a_20multicast_20socket_8',['Creating a Multicast Socket',['../group__multicast__sockets.html#autotoc_md274',1,'']]],
  ['a_20packet_9',['What is a Packet?',['../group__network__data__units.html#autotoc_md297',1,'']]],
  ['a_20pull_20request_20to_20cci_10',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md196',1,'']]],
  ['a_20safe_20cap_11',['Why a &quot;safe&quot; cap?',['../group__core.html#autotoc_md590',1,'']]],
  ['a_20simple_20server_20client_20integration_20test_3a_12',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md461',1,'']]],
  ['a_20socket_13',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md386',1,'']]],
  ['a_20socket_20state_14',['What is a Socket State?',['../group__socket__states.html#autotoc_md368',1,'']]],
  ['a_20vcpkg_20portfile_15',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md475',1,'']]],
  ['about_20udp_20and_20unix_20sockets_16',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md375',1,'']]],
  ['accept_17',['📞 &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;',['../group__async__io.html#autotoc_md153',1,'']]],
  ['accept_20recv_20and_20send_18',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['acceptance_19',['Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md483',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md198',1,'7. After Acceptance']]],
  ['accepted_20socket_20',['Accepted Socket',['../group__tcp.html#autotoc_md732',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md741',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md750',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md761',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md794',1,'⚙️ Configuration of Accepted Socket'],['../group__tcp.html#autotoc_md807',1,'⚙️ Configuration of Accepted Socket']]],
  ['acceptnonblocking_21',['🧪 Comparison with &lt;span class=&quot;tt&quot;&gt;acceptNonBlocking()&lt;/span&gt;',['../group__tcp.html#autotoc_md772',1,'']]],
  ['acknowledgements_22',['🙏 Acknowledgements',['../index.html#autotoc_md535',1,'']]],
  ['action_3a_20practical_20examples_23',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md433',1,'']]],
  ['actually_20does_24',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md79',1,'']]],
  ['address_25',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md68',1,'']]],
  ['address_20and_20name_20resolution_26',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['address_20binding_20and_20connection_27',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['address_20families_28',['Address Families',['../group__underlying__socket__api.html#autotoc_md426',1,'2.2 Address Families'],['../group__sockets__theory.html#autotoc_md404',1,'3. Socket Address Families']]],
  ['address_20reuse_20options_29',['🔍 In-Depth Overview of Address Reuse Options',['../group__address__reuse.html#autotoc_md76',1,'']]],
  ['addresses_30',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md175',1,'']]],
  ['addressing_31',['Multicast Addressing',['../group__multicast__sockets.html#autotoc_md267',1,'']]],
  ['adjust_32',['When to Adjust',['../group__core.html#autotoc_md584',1,'']]],
  ['advanced_20scenarios_33',['6. Advanced Scenarios',['../group__ServerSocket__Lifecycle.html#autotoc_md55',1,'']]],
  ['advanced_20socket_20api_20features_34',['Advanced Socket API Features',['../group__underlying__socket__api.html#autotoc_md436',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md446',1,'Advanced Socket API Features']]],
  ['advanced_20topics_35',['Advanced Topics',['../group__sockets__theory.html#autotoc_md416',1,'7. Advanced Topics'],['../group__multicast__sockets.html#autotoc_md285',1,'Advanced Topics']]],
  ['advanced_20usage_36',['Advanced Usage',['../classjsocketpp_1_1Socket.html#autotoc_md824',1,'']]],
  ['advantages_20and_20disadvantages_37',['Advantages and Disadvantages',['../group__network__data__units.html#autotoc_md303',1,'']]],
  ['advantages_20and_20rationale_38',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md45',1,'']]],
  ['advantages_20of_20epoll_39',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md313',1,'']]],
  ['advantages_20of_20poll_40',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md311',1,'']]],
  ['advice_41',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md323',1,'']]],
  ['af_5finet_42',['AF_INET',['../group__underlying__socket__api.html#autotoc_md434',1,'5.1 TCP Server and Client (Python, AF_INET)'],['../group__underlying__socket__api.html#autotoc_md435',1,'5.2 UDP Server and Client (C, AF_INET)']]],
  ['after_20acceptance_43',['After Acceptance',['../group__vcpkg__publish__guide.html#autotoc_md483',1,'6. After Acceptance'],['../group__conan__publish__guide.html#autotoc_md198',1,'7. After Acceptance']]],
  ['algorithm_20to_20reduce_20latency_44',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1109',1,'']]],
  ['all_20interfaces”_20mean_45',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['all_20interfaces_46',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md176',1,'']]],
  ['all_20java_20default_20style_47',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md51',1,'']]],
  ['all_20sockets_48',['1. Options for All Sockets',['../group__socket-options.html#autotoc_md332',1,'']]],
  ['all_20steps_49',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['also_50',['Also',['../index.html#autotoc_md550',1,'🧭 See Also'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md725',1,'See Also'],['../classjsocketpp_1_1Socket.html#autotoc_md825',1,'See Also']]],
  ['alternative_20designs_3a_20pros_20and_20cons_51',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['alternative_3a_20what_20jsocketpp_20does_52',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['and_20applications_53',['and Applications',['../group__underlying__socket__api.html#autotoc_md442',1,'8. Use Cases and Applications'],['../group__network__data__units.html#autotoc_md302',1,'Use Cases and Applications']]],
  ['and_20asynchronous_20i_20o_54',['6. Non-Blocking and Asynchronous I/O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'']]],
  ['and_20best_20practices_55',['and Best Practices',['../group__async__io.html#autotoc_md169',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md485',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md200',1,'8. Tips and Best Practices']]],
  ['and_20broadcast_56',['and Broadcast',['../group__underlying__socket__api.html#autotoc_md439',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md449',1,'6.3 Multicast and Broadcast']]],
  ['and_20caveats_57',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['and_20cleanup_3a_58',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md458',1,'']]],
  ['and_20client_59',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md636',1,'']]],
  ['and_20client_20c_20af_5finet_60',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md435',1,'']]],
  ['and_20client_20python_20af_5finet_61',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md434',1,'']]],
  ['and_20client_3a_62',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md460',1,'']]],
  ['and_20configuration_63',['5. Socket Information and Configuration',['../group__list__bsd__socket__functions.html#autotoc_md30',1,'']]],
  ['and_20connection_64',['2. Address Binding and Connection',['../group__list__bsd__socket__functions.html#autotoc_md27',1,'']]],
  ['and_20cons_65',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md50',1,'']]],
  ['and_20data_20encapsulation_66',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md296',1,'']]],
  ['and_20disadvantages_67',['Advantages and Disadvantages',['../group__network__data__units.html#autotoc_md303',1,'']]],
  ['and_20handling_20socket_20exceptions_68',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md982',1,'']]],
  ['and_20its_20limitations_69',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['and_20management_70',['1. Core Socket Creation and Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'']]],
  ['and_20name_20resolution_71',['4. Address and Name Resolution',['../group__list__bsd__socket__functions.html#autotoc_md29',1,'']]],
  ['and_20performance_20considerations_72',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md402',1,'']]],
  ['and_20rationale_73',['4. Advantages and Rationale',['../group__ServerSocket__Lifecycle.html#autotoc_md45',1,'']]],
  ['and_20running_20tests_74',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['and_20safety_75',['a) Flexibility and Safety',['../group__ServerSocket__Lifecycle.html#autotoc_md46',1,'']]],
  ['and_20scaling_76',['Performance and Scaling',['../group__multicast__sockets.html#autotoc_md290',1,'']]],
  ['and_20scope_20control_77',['TTL and Scope Control',['../group__multicast__sockets.html#autotoc_md287',1,'']]],
  ['and_20segments_78',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md300',1,'']]],
  ['and_20send_79',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md148',1,'']]],
  ['and_20send_3a_80',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md457',1,'']]],
  ['and_20testing_81',['and Testing',['../index.html#autotoc_md526',1,'🧪 Building and Testing'],['../group__multicast__sockets.html#autotoc_md288',1,'Loopback and Testing']]],
  ['and_20the_20socket_20api_82',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md432',1,'']]],
  ['and_20timeouts_83',['⏱ How jsocketpp Handles Blocking and Timeouts',['../group__async__io.html#autotoc_md145',1,'']]],
  ['and_20udp_84',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md69',1,'']]],
  ['and_20unix_20sockets_85',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md375',1,'']]],
  ['and_20use_20cases_86',['Applications and Use Cases',['../group__multicast__sockets.html#autotoc_md293',1,'']]],
  ['api_87',['API',['../group__underlying__socket__api.html#autotoc_md423',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md424',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md432',1,'4. Protocols and the Socket API'],['../classjsocketpp_1_1ServerSocket.html#autotoc_md724',1,'Basic API'],['../group__ServerSocket__Lifecycle.html#autotoc_md48',1,'c) Clear API']]],
  ['api_20considerations_88',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md317',1,'']]],
  ['api_20features_89',['API Features',['../group__underlying__socket__api.html#autotoc_md436',1,'6. Advanced Socket API Features'],['../group__underlying__socket__api.html#autotoc_md446',1,'Advanced Socket API Features']]],
  ['api_20for_20unit_20tests_3a_90',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md464',1,'']]],
  ['api_20in_20action_3a_20practical_20examples_91',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md433',1,'']]],
  ['api_20notes_92',['jsocketpp API Notes',['../group__bind__interfaces.html#autotoc_md180',1,'']]],
  ['api_20unix_20linux_20macos_93',['POSIX/BSD API (Unix/Linux/MacOS)',['../group__multicast__sockets.html#autotoc_md273',1,'']]],
  ['api_20windows_94',['Winsock API (Windows)',['../group__multicast__sockets.html#autotoc_md280',1,'']]],
  ['apis_95',['APIs',['../group__socket__library__comparison.html#autotoc_md361',1,'5. Native BSD/POSIX/WinSock APIs'],['../group__sockets__theory.html#autotoc_md412',1,'6. Platform-Specific APIs']]],
  ['applicability_96',['Applicability',['../group__socketopts.html#autotoc_md1119',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1149',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1156',1,'🌍 Applicability'],['../group__socketopts.html#autotoc_md1053',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1056',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1059',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1063',1,'🔁 Applicability'],['../group__socketopts.html#autotoc_md1112',1,'🔍 Applicability'],['../group__socketopts.html#autotoc_md1041',1,'Applicability'],['../group__socketopts.html#autotoc_md1044',1,'Applicability'],['../group__socketopts.html#autotoc_md1047',1,'Applicability'],['../group__socketopts.html#autotoc_md1050',1,'Applicability'],['../group__socketopts.html#autotoc_md1128',1,'Applicability'],['../group__socketopts.html#autotoc_md1039',1,'Protocol Applicability']]],
  ['applicability_20by_20socket_20type_97',['Applicability by Socket Type',['../group__socketopts.html#autotoc_md1133',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1142',1,'🌍 Applicability by Socket Type']]],
  ['applicable_20socket_20types_98',['📦 Applicable Socket Types',['../group__socketopts.html#autotoc_md1089',1,'']]],
  ['applications_99',['Applications',['../group__underlying__socket__api.html#autotoc_md442',1,'8. Use Cases and Applications'],['../group__network__data__units.html#autotoc_md302',1,'Use Cases and Applications']]],
  ['applications_20and_20use_20cases_100',['Applications and Use Cases',['../group__multicast__sockets.html#autotoc_md293',1,'']]],
  ['applies_20to_101',['Applies to',['../group__core.html#autotoc_md581',1,'Applies to'],['../group__core.html#autotoc_md585',1,'Applies to']]],
  ['approach_102',['Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md38',1,'1. Traditional Socket Initialization: POSIX Approach'],['../group__network__data__units.html#autotoc_md298',1,'Datagrams: The Connectionless Approach']]],
  ['approach_20and_20its_20limitations_103',['⚠️ Java’s Approach and Its Limitations',['../group__address__reuse.html#autotoc_md109',1,'']]],
  ['approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_104',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['are_20socket_20options_105',['What Are Socket Options?',['../group__socket-options.html#autotoc_md327',1,'']]],
  ['asio_106',['Asio',['../index.html#autotoc_md500',1,'🔁 jsocketpp vs Boost.Asio'],['../group__socket__library__comparison.html#autotoc_md355',1,'2. Boost.Asio']]],
  ['assignment_107',['Example: Move assignment',['../group__socketopts.html#autotoc_md1163',1,'']]],
  ['async_108',['Is jsocketpp async?',['../index.html#autotoc_md538',1,'']]],
  ['asynchronous_20i_20o_109',['Asynchronous I O',['../group__list__bsd__socket__functions.html#autotoc_md31',1,'6. Non-Blocking and Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md440',1,'6.4 Asynchronous I/O'],['../group__underlying__socket__api.html#autotoc_md450',1,'6.4 Asynchronous I/O']]],
  ['at_20a_20glance_110',['✨ Features at a Glance',['../index.html#autotoc_md496',1,'']]],
  ['authors_111',['📌 Notes for Library Authors',['../group__address__reuse.html#autotoc_md125',1,'']]],
  ['autobind_20true_112',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md840',1,'']]]
];
