var searchData=
[
  ['waiting_20for_20readiness_0',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md141',1,'']]],
  ['what_20about_20udp_20and_20unix_20sockets_1',['What About UDP and UNIX Sockets?',['../group__socket__states.html#autotoc_md251',1,'']]],
  ['what_20are_20socket_20options_2',['What Are Socket Options?',['../group__socket-options.html#autotoc_md203',1,'']]],
  ['what_20does_20“binding_20to_20all_20interfaces”_20mean_3',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['what_20happens_20when_20multiple_20sockets_20bind_20to_20the_20same_20port_4',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['what_20is_20a_20socket_5',['1. What is a Socket?',['../group__sockets__theory.html#autotoc_md262',1,'']]],
  ['what_20is_20a_20socket_20state_6',['What is a Socket State?',['../group__socket__states.html#autotoc_md244',1,'']]],
  ['what_20is_20blocking_7',['What is Blocking?',['../group__async__io.html#autotoc_md115',1,'']]],
  ['what_20is_20multicast_8',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md435',1,'']]],
  ['what_20is_20non_20blocking_9',['What is Non-Blocking?',['../group__async__io.html#autotoc_md116',1,'']]],
  ['what_20is_20udp_10',['What is UDP?',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md425',1,'']]],
  ['what_20it_20actually_20does_11',['🔄 What it actually does',['../group__address__reuse.html#autotoc_md56',1,'']]],
  ['what_20java_20does_12',['What Java Does',['../group__address__reuse.html#autotoc_md87',1,'']]],
  ['what_20jsocketpp_20does_13',['A Better Alternative: What &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt; Does',['../group__address__reuse.html#autotoc_md92',1,'']]],
  ['what_20jsocketpp_20gets_20right_14',['✔ What jsocketpp Gets Right',['../group__address__reuse.html#autotoc_md107',1,'']]],
  ['when_20multiple_20sockets_20bind_20to_20the_20same_20port_15',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]],
  ['when_20to_20adjust_16',['When to Adjust',['../group__core.html#autotoc_md423',1,'']]],
  ['why_20not_20expose_20windows_20so_5freuseaddr_17',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['why_20require_20the_20port_20in_20the_20constructor_18',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['why_20select_20is_20used_19',['1. &lt;b&gt;Why &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; is Used&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md183',1,'']]],
  ['why_20this_20is_20problematic_20on_20windows_20',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md88',1,'']]],
  ['wildcard_20addresses_21',['Wildcard Addresses',['../group__bind__interfaces.html#autotoc_md152',1,'']]],
  ['windows_22',['Windows',['../group__address__reuse.html#autotoc_md88',1,'Why This is Problematic on Windows'],['../group__address__reuse.html#autotoc_md80',1,'Windows']]],
  ['windows_20counterparts_23',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md191',1,'']]],
  ['windows_20only_24',['&lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (Windows only)',['../group__address__reuse.html#autotoc_md64',1,'']]],
  ['windows_20so_5freuseaddr_25',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md98',1,'']]],
  ['windows_20winsock_26',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md290',1,'']]],
  ['windows_3a_27',['Windows:',['../group__address__reuse.html#autotoc_md62',1,'On Windows:'],['../group__address__reuse.html#autotoc_md63',1,'On Windows:']]],
  ['winsock_28',['6.2. Windows (Winsock)',['../group__sockets__theory.html#autotoc_md290',1,'']]],
  ['winsock_20apis_29',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md237',1,'']]],
  ['with_20google_20mock_3a_30',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md341',1,'']]],
  ['with_20mocking_3a_31',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['with_20so_5fexclusiveaddruse_20default_20in_20jsocketpp_20_3a_32',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_EXCLUSIVEADDRUSE&lt;/span&gt; (default in jsocketpp)&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md82',1,'']]],
  ['with_20so_5freuseaddr_20only_3a_33',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; only&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md77',1,'']]],
  ['with_20so_5freuseaddr_20so_5freuseport_3a_34',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md78',1,'']]],
  ['with_20so_5freuseaddr_3a_35',['&lt;b&gt;With &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;&lt;/b&gt;:',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['with_20so_5freuseport_36',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['work_37',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md272',1,'']]],
  ['work_3a_20the_20lifecycle_38',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md282',1,'']]],
  ['works_20internally_39',['🛠️ How it works internally',['../group__address__reuse.html#autotoc_md70',1,'']]],
  ['write_40',['📤 &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;write&lt;/span&gt;',['../group__async__io.html#autotoc_md137',1,'']]]
];
