var searchData=
[
  ['packet_0',['What is a Packet?',['../group__network__data__units.html#autotoc_md315',1,'']]],
  ['packets_20datagrams_20and_20segments_1',['Key Differences: Packets, Datagrams, and Segments',['../group__network__data__units.html#autotoc_md318',1,'']]],
  ['parameters_2',['Parameters',['../group__tcp.html#autotoc_md856',1,'🔧 Configuration Parameters'],['../group__udp.html#autotoc_md659',1,'Configuration Parameters'],['../group__tcp.html#autotoc_md850',1,'Configuration Parameters'],['../group__internal.html#autotoc_md618',1,'Parameters']]],
  ['parameters_20used_20only_20if_20autobind_20true_3',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['peer_20model_4',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md448',1,'']]],
  ['peer_20to_20peer_20model_5',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md448',1,'']]],
  ['performance_20and_20scaling_6',['Performance and Scaling',['../group__multicast__sockets.html#autotoc_md308',1,'']]],
  ['performance_20considerations_7',['2.7. Security and Performance Considerations',['../group__sockets__theory.html#autotoc_md420',1,'']]],
  ['performance_20footprint_8',['🚀 Performance &amp;amp; Footprint',['../index.html#autotoc_md520',1,'']]],
  ['persist_20for_20the_20socket’s_20lifetime_9',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['picture_10',['Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'Wrapping It Up: The Full IPv4 Picture'],['../group__mastering__ipv6.html#autotoc_md53',1,'Wrapping It Up: The Full IPv6 Picture']]],
  ['platform_20api_20considerations_11',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md335',1,'']]],
  ['platform_20behavior_12',['Platform Behavior',['../group__udp.html#autotoc_md679',1,'⚙️ Platform Behavior'],['../group__socketopts.html#autotoc_md1162',1,'⚠️ Platform Behavior'],['../group__socketopts.html#autotoc_md1085',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1090',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1095',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1100',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1105',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1116',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1125',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1153',1,'🔀 Platform Behavior'],['../group__socketopts.html#autotoc_md1139',1,'🔐 Platform Behavior'],['../classjsocketpp_1_1internal_1_1ScopedBlockingMode.html#autotoc_md731',1,'Platform Behavior'],['../group__tcp.html#autotoc_md829',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1053',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1056',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1060',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1066',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1078',1,'Platform Behavior'],['../group__socketopts.html#autotoc_md1082',1,'Platform Behavior']]],
  ['platform_20notes_13',['Platform Notes',['../group__BUILD__AND__USAGE.html#autotoc_md22',1,'Platform Notes'],['../group__tcp.html#autotoc_md900',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1063',1,'Platform Notes'],['../group__socketopts.html#autotoc_md1069',1,'Platform Notes']]],
  ['platform_20socket_20library_20for_20modern_20c_2020_14',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['platform_20specific_20apis_15',['6. Platform-Specific APIs',['../group__sockets__theory.html#autotoc_md430',1,'']]],
  ['platform_20specific_20considerations_16',['9. Platform-Specific Considerations',['../group__underlying__socket__api.html#autotoc_md461',1,'']]],
  ['platform_20specific_20tests_3a_17',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md481',1,'']]],
  ['platform_20support_18',['Platform Support',['../group__socketopts.html#autotoc_md1169',1,'🔀 Platform Support'],['../group__socketopts.html#autotoc_md1176',1,'🔀 Platform Support'],['../group__socket-options.html#autotoc_md347',1,'Cross-Platform Support'],['../classjsocketpp_1_1Socket.html#autotoc_md841',1,'Platform Support']]],
  ['platform_20toolchain_20support_19',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md516',1,'']]],
  ['platform_3a_20',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['pledge_21',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md587',1,'']]],
  ['poco_3a_3anet_22',['3. Poco::Net',['../group__socket__library__comparison.html#autotoc_md375',1,'']]],
  ['policy_23',['Semantics &amp;amp; policy',['../group__core.html#autotoc_md604',1,'']]],
  ['poll_24',['3. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md329',1,'']]],
  ['port_25',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['port_20binding_26',['Example: Enable shared port binding',['../group__socketopts.html#autotoc_md1171',1,'']]],
  ['port_20in_20constructor_20bind_20listen_20explicit_27',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['port_20in_20the_20constructor_28',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['port_20locally_29',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'']]],
  ['portability_30',['b) Portability',['../group__ServerSocket__Lifecycle.html#autotoc_md65',1,'']]],
  ['portfile_31',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md493',1,'']]],
  ['portfile_20cmake_32',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md495',1,'']]],
  ['posix_20approach_33',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'']]],
  ['posix_20bsd_34',['Differences from POSIX/BSD',['../group__multicast__sockets.html#autotoc_md299',1,'']]],
  ['posix_20bsd_20api_20unix_20linux_20macos_35',['POSIX/BSD API (Unix/Linux/MacOS)',['../group__multicast__sockets.html#autotoc_md291',1,'']]],
  ['posix_20linux_20macos_20unix_36',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md431',1,'']]],
  ['posix_20style_37',['&lt;b&gt;b) Fully Step-by-Step (POSIX Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md70',1,'']]],
  ['posix_20winsock_20apis_38',['5. Native BSD/POSIX/WinSock APIs',['../group__socket__library__comparison.html#autotoc_md379',1,'']]],
  ['practical_20considerations_39',['Practical Considerations',['../group__underlying__socket__api.html#autotoc_md469',1,'7. Practical Considerations'],['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md281',1,'Practical Considerations']]],
  ['practical_20examples_40',['5. Socket API in Action: Practical Examples',['../group__underlying__socket__api.html#autotoc_md451',1,'']]],
  ['practical_20implications_41',['Practical Implications',['../group__socket__states.html#autotoc_md395',1,'']]],
  ['practical_20implications_42',['🧠 Practical implications',['../group__address__reuse.html#autotoc_md100',1,'']]],
  ['practical_20recommendations_43',['7. &lt;b&gt;Practical Recommendations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md337',1,'']]],
  ['practices_44',['Practices',['../group__async__io.html#autotoc_md187',1,'🧠 Final Thoughts and Best Practices'],['../group__vcpkg__publish__guide.html#autotoc_md503',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md218',1,'8. Tips and Best Practices'],['../group__bind__interfaces.html#autotoc_md196',1,'Best Practices']]],
  ['practices_20recap_45',['✅ Best Practices Recap',['../group__address__reuse.html#autotoc_md151',1,'']]],
  ['pre_20commit_20hooks_46',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md577',1,'']]],
  ['pre_20commit_20hooks_47',['Pre-commit hooks',['../index.html#autotoc_md547',1,'']]],
  ['preconditions_48',['Preconditions',['../group__core.html#autotoc_md610',1,'']]],
  ['prepare_20for_20conan_20center_20index_20cci_20submission_49',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md211',1,'']]],
  ['prepare_20your_20library_20for_20vcpkg_50',['2. Prepare Your Library for vcpkg',['../group__vcpkg__publish__guide.html#autotoc_md491',1,'']]],
  ['prerequisites_51',['Prerequisites',['../group__conan__publish__guide.html#autotoc_md203',1,'1. Prerequisites'],['../group__vcpkg__publish__guide.html#autotoc_md489',1,'1. Prerequisites'],['../group__BUILD__AND__USAGE.html#autotoc_md4',1,'Prerequisites']]],
  ['presets_20recommended_52',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['primary_20traits_53',['Primary Traits',['../buffer__traits_8hpp.html#autotoc_md726',1,'']]],
  ['private_20networking_54',['Unique Local Addresses: Private Networking',['../group__mastering__ipv6.html#autotoc_md52',1,'']]],
  ['private_20vs_20public_20ip_20addresses_55',['Private vs. Public IP Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'']]],
  ['problematic_20on_20windows_56',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['production_57',['Can I use jsocketpp in production?',['../index.html#autotoc_md560',1,'']]],
  ['programming_58',['Programming',['../group__multicast__sockets.html#autotoc_md309',1,'IPv6 Multicast Programming'],['../group__multicast__sockets.html#autotoc_md290',1,'Multicast Socket Programming']]],
  ['project_59',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['project_20conan_20friendly_60',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md207',1,'']]],
  ['pros_20and_20cons_61',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md68',1,'']]],
  ['protocol_20applicability_62',['Protocol Applicability',['../group__socketopts.html#autotoc_md1057',1,'']]],
  ['protocol_20behavior_63',['Protocol Behavior',['../group__tcp.html#autotoc_md976',1,'']]],
  ['protocol_20format_64',['Protocol Format',['../group__tcp.html#autotoc_md922',1,'Protocol Format'],['../group__tcp.html#autotoc_md925',1,'Protocol Format'],['../group__tcp.html#autotoc_md949',1,'Protocol Format'],['../group__tcp.html#autotoc_md952',1,'Protocol Format']]],
  ['protocol_20igmp_65',['Internet Group Management Protocol (IGMP)',['../group__multicast__sockets.html#autotoc_md286',1,'']]],
  ['protocol_20use_20cases_66',['Protocol Use Cases',['../group__socketopts.html#autotoc_md1054',1,'']]],
  ['protocols_20and_20the_20socket_20api_67',['4. Protocols and the Socket API',['../group__underlying__socket__api.html#autotoc_md450',1,'']]],
  ['public_20ip_20addresses_68',['Private vs. Public IP Addresses',['../group__mastering__ipv4.html#autotoc_md43',1,'']]],
  ['pull_20request_20to_20cci_69',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md214',1,'']]],
  ['pull_20requests_70',['2. Submitting Pull Requests',['../md_CONTRIBUTING.html#autotoc_md573',1,'']]],
  ['purpose_71',['Purpose',['../group__address__reuse.html#autotoc_md107',1,'🎯 Purpose'],['../group__udp.html#autotoc_md684',1,'🧠 Purpose'],['../namespacejsocketpp_1_1net.html#autotoc_md596',1,'Purpose'],['../group__tcp.html#autotoc_md969',1,'Purpose']]],
  ['py_72',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md205',1,'']]],
  ['python_20af_5finet_73',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md452',1,'']]]
];
