var searchData=
[
  ['c_2017_20cross_20platform_20socket_20library_0',['jsocketpp: Modern C++17 Cross-Platform Socket Library',['../index.html',1,'']]],
  ['c_2017_3a_1',['Tools for Unit Testing in C++17:',['../group__unit__tests.html#autotoc_md331',1,'']]],
  ['c_20af_5finet_2',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['c_20clear_20api_3',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'']]],
  ['c_20jsocketpp_20hybrid_4',['&lt;b&gt;c) jsocketpp Hybrid&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md42',1,'']]],
  ['callback_20details_5',['Callback Details',['../group__tcp.html#autotoc_md436',1,'']]],
  ['case_6',['✅ Use Case',['../group__address__reuse.html#autotoc_md69',1,'']]],
  ['cases_7',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['cases_20and_20applications_8',['8. Use Cases and Applications',['../group__underlying__socket__api.html#autotoc_md318',1,'']]],
  ['cases_20to_20consider_3a_9',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['catching_20and_20handling_20socket_20exceptions_10',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md449',1,'']]],
  ['caveats_11',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md58',1,'']]],
  ['cci_12',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md173',1,'']]],
  ['cci_20submission_13',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['center_20index_20cci_20submission_14',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['cleanup_3a_15',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md334',1,'']]],
  ['clear_20api_16',['c) Clear API',['../group__ServerSocket__Lifecycle.html#autotoc_md37',1,'']]],
  ['client_17',['Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md453',1,'Example: Simple Client'],['../classjsocketpp_1_1DatagramSocket.html#autotoc_md417',1,'Example: Simple UDP Echo Server and Client']]],
  ['client_20c_20af_5finet_18',['5.2 UDP Server and Client (C, AF_INET)',['../group__underlying__socket__api.html#autotoc_md311',1,'']]],
  ['client_20integration_20test_3a_19',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md337',1,'']]],
  ['client_20python_20af_5finet_20',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md310',1,'']]],
  ['client_20server_20model_21',['3.1 Client-Server Model',['../group__underlying__socket__api.html#autotoc_md305',1,'']]],
  ['client_20side_22',['4.2. Client Side',['../group__sockets__theory.html#autotoc_md284',1,'']]],
  ['client_3a_23',['2.1 &lt;b&gt;Setting Up Real Server and Client&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md336',1,'']]],
  ['cmake_24',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md353',1,'']]],
  ['cmake_20build_25',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['cmake_20for_20platform_20specific_20tests_3a_26',['3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md339',1,'']]],
  ['cmake_20integration_20in_20your_20project_27',['CMake Integration in Your Project',['../group__BUILD__AND__USAGE.html#autotoc_md18',1,'']]],
  ['cmake_20presets_20recommended_28',['Using CMake Presets (Recommended)',['../group__BUILD__AND__USAGE.html#autotoc_md7',1,'']]],
  ['cmake_20project_20conan_20friendly_29',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['code_20of_20conduct_30',['Code of Conduct',['../md_CONTRIBUTING.html#autotoc_md405',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['code_20style_20guidelines_31',['3. Code Style Guidelines',['../md_CONTRIBUTING.html#autotoc_md397',1,'']]],
  ['combining_20with_20so_5freuseport_32',['🚀 Combining with &lt;span class=&quot;tt&quot;&gt;SO_REUSEPORT&lt;/span&gt;',['../group__address__reuse.html#autotoc_md61',1,'']]],
  ['commit_20hooks_33',['4. Pre-commit Hooks',['../md_CONTRIBUTING.html#autotoc_md399',1,'']]],
  ['common_20options_20by_20socket_20type_34',['Common Options by Socket Type',['../group__socket-options.html#autotoc_md207',1,'']]],
  ['common_20use_20cases_35',['📦 Common use cases',['../group__address__reuse.html#autotoc_md57',1,'']]],
  ['communication_36',['3.3 Raw Socket Communication',['../group__underlying__socket__api.html#autotoc_md307',1,'']]],
  ['communication_20models_37',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md304',1,'']]],
  ['comparison_38',['📚 Java Comparison',['../group__async__io.html#autotoc_md143',1,'']]],
  ['comparison_20table_3a_20socket_20types_39',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md270',1,'']]],
  ['compilation_40',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['components_20of_20the_20socket_20api_41',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['conan_42',['Conan',['../index.html#autotoc_md373',1,'']]],
  ['conan_20center_20index_20cci_20submission_43',['5. Prepare for Conan Center Index (CCI) Submission',['../group__conan__publish__guide.html#autotoc_md170',1,'']]],
  ['conan_20friendly_44',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['conan_20recipe_20conanfile_20py_45',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['conanfile_20py_46',['2. Conan Recipe (&lt;span class=&quot;tt&quot;&gt;conanfile.py&lt;/span&gt;)',['../group__conan__publish__guide.html#autotoc_md164',1,'']]],
  ['conclusion_47',['Conclusion',['../group__address__reuse.html#autotoc_md106',1,'✅ Conclusion'],['../group__underlying__socket__api.html#autotoc_md320',1,'10. Conclusion'],['../group__underlying__socket__api.html#autotoc_md328',1,'8. Conclusion'],['../group__bind__interfaces.html#autotoc_md159',1,'Conclusion'],['../group__socket__library__comparison.html#autotoc_md241',1,'Conclusion']]],
  ['conclusion_20advice_48',['9. &lt;b&gt;Conclusion / Advice&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md199',1,'']]],
  ['conclusion_3a_49',['Conclusion:',['../group__unit__tests.html#autotoc_md344',1,'']]],
  ['conduct_50',['Conduct',['../md_CONTRIBUTING.html#autotoc_md405',1,'7. Branching &amp; Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Code of Conduct']]],
  ['connect_51',['🔌 &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;',['../group__async__io.html#autotoc_md126',1,'']]],
  ['connect_20accept_20recv_20and_20send_52',['🔄 Operation-Specific Behavior: &lt;span class=&quot;tt&quot;&gt;connect&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;accept&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt;, and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;',['../group__async__io.html#autotoc_md125',1,'']]],
  ['cons_53',['5. Alternative Designs: Pros and Cons',['../group__ServerSocket__Lifecycle.html#autotoc_md39',1,'']]],
  ['consider_3a_54',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md343',1,'']]],
  ['considerations_55',['Considerations',['../group__sockets__theory.html#autotoc_md278',1,'2.7. Security and Performance Considerations'],['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'6. <b>Cross-Platform API Considerations</b>'],['../group__underlying__socket__api.html#autotoc_md327',1,'7. Practical Considerations'],['../group__underlying__socket__api.html#autotoc_md317',1,'7. Security Considerations'],['../group__underlying__socket__api.html#autotoc_md319',1,'9. Platform-Specific Considerations']]],
  ['constructor_56',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md32',1,'']]],
  ['constructor_20bind_20listen_20explicit_57',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md31',1,'']]],
  ['constructor_20defaults_58',['Constructor Defaults',['../group__address__reuse.html#autotoc_md96',1,'']]],
  ['constructor_20does_20all_20java_20default_20style_59',['&lt;b&gt;a) Constructor Does All (Java Default Style)&lt;/b&gt;',['../group__ServerSocket__Lifecycle.html#autotoc_md40',1,'']]],
  ['constructor_20does_20all_20steps_60',['2. Java ServerSocket: Constructor Does All Steps',['../group__ServerSocket__Lifecycle.html#autotoc_md29',1,'']]],
  ['contents_61',['Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md201',1,'Table of Contents']]],
  ['contributing_62',['Contributing',['../index.html#autotoc_md388',1,'']]],
  ['contributing_20to_20jsocketpp_63',['Contributing to jsocketpp',['../md_CONTRIBUTING.html',1,'']]],
  ['control_64',['Developer Control',['../group__address__reuse.html#autotoc_md97',1,'']]],
  ['core_20components_20of_20the_20socket_20api_65',['2. Core Components of the Socket API',['../group__underlying__socket__api.html#autotoc_md300',1,'']]],
  ['counterparts_66',['5. &lt;b&gt;Windows Counterparts&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md191',1,'']]],
  ['coverage_20for_20cross_20platform_3a_67',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['create_20a_20vcpkg_20portfile_68',['3. Create a vcpkg Portfile',['../group__vcpkg__publish__guide.html#autotoc_md351',1,'']]],
  ['cross_20platform_20api_20considerations_69',['6. &lt;b&gt;Cross-Platform API Considerations&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md193',1,'']]],
  ['cross_20platform_20socket_20library_70',['jsocketpp: Modern C++17 Cross-Platform Socket Library',['../index.html',1,'']]],
  ['cross_20platform_20support_71',['Cross-Platform Support',['../group__socket-options.html#autotoc_md205',1,'']]],
  ['cross_20platform_3a_72',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md338',1,'']]],
  ['custom_20timeouts_20via_20select_73',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md120',1,'']]]
];
