var searchData=
[
  ['table_0',['Table',['../group__address__reuse.html#autotoc_md141',1,'💡 Summary Table'],['../group__socket-options.html#autotoc_md359',1,'5. Summary Table'],['../group__select__poll__epoll__iocp.html#autotoc_md339',1,'8. &lt;b&gt;Summary Table&lt;/b&gt;'],['../group__sockets__theory.html#autotoc_md436',1,'8. Summary Table'],['../group__address__reuse.html#autotoc_md125',1,'Summary Table'],['../group__socket__library__comparison.html#autotoc_md381',1,'Summary Table']]],
  ['table_20of_20contents_1',['Table of Contents',['../group__BUILD__AND__USAGE.html#autotoc_md2',1,'Table of Contents'],['../group__socket-options.html#autotoc_md343',1,'Table of Contents']]],
  ['table_3a_20socket_20types_2',['2.5. Comparison Table: Socket Types',['../group__sockets__theory.html#autotoc_md412',1,'']]],
  ['table_3a_20waiting_20for_20readiness_3',['✅ Summary Table: Waiting for Readiness',['../group__async__io.html#autotoc_md182',1,'']]],
  ['tcgetattr_4',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md274',1,'']]],
  ['tcp_5',['TCP',['../group__sockets__theory.html#autotoc_md407',1,'2.1. Stream Sockets (TCP)'],['../group__network__data__units.html#autotoc_md317',1,'Segments: The Reliable Counterpart in TCP'],['../group__sockets__theory.html#autotoc_md415',1,'Stream Sockets (TCP)']]],
  ['tcp_20and_20udp_6',['Implicit Binding in TCP and UDP',['../group__socket__binding.html#autotoc_md87',1,'']]],
  ['tcp_20echo_20server_7',['🧵 TCP Echo Server',['../index.html#autotoc_md532',1,'']]],
  ['tcp_20server_20and_20client_20python_20af_5finet_8',['5.1 TCP Server and Client (Python, AF_INET)',['../group__underlying__socket__api.html#autotoc_md452',1,'']]],
  ['tcp_20socket_20lifecycle_9',['TCP Socket Lifecycle',['../group__socket__states.html#autotoc_md388',1,'']]],
  ['tcp_20socket_20states_10',['Main TCP Socket States',['../group__socket__states.html#autotoc_md389',1,'']]],
  ['tcp_20sockets_11',['TCP Sockets',['../group__socket__binding.html#autotoc_md84',1,'TCP Sockets'],['../group__socket__binding.html#autotoc_md88',1,'TCP Sockets']]],
  ['tcp_20sockets_20socket_20serversocket_12',['2. TCP Sockets (&lt;span class=&quot;tt&quot;&gt;Socket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ServerSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md352',1,'']]],
  ['tcp_20state_20transitions_13',['TCP State Transitions',['../group__socket__states.html#autotoc_md391',1,'']]],
  ['tcsetattr_20tcgetattr_14',['tcsetattr/tcgetattr',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md274',1,'']]],
  ['terminal_20window_20size_20linux_15',['Example: Terminal Window Size (Linux)',['../group__ioctl__fcntl__ioctlsocket__guide.html#autotoc_md234',1,'']]],
  ['test_20cases_20to_20consider_3a_16',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md485',1,'']]],
  ['test_20coverage_20for_20cross_20platform_3a_17',['3. &lt;b&gt;Test Coverage for Cross-Platform&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md480',1,'']]],
  ['test_20the_20port_20locally_18',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'']]],
  ['test_20the_20recipe_20locally_19',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md209',1,'']]],
  ['test_20with_20mocking_3a_20',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md484',1,'']]],
  ['test_3a_21',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md479',1,'']]],
  ['test_5fpackage_22',['test_package',['../group__conan__publish__guide.html#autotoc_md212',1,'']]],
  ['testing_23',['Testing',['../index.html#autotoc_md544',1,'🧪 Building and Testing'],['../md_CONTRIBUTING.html#autotoc_md579',1,'5. Testing'],['../group__multicast__sockets.html#autotoc_md306',1,'Loopback and Testing']]],
  ['testing_20in_20c_2020_3a_24',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['testing_20socket_20initialization_20and_20cleanup_3a_25',['1.2 &lt;b&gt;Testing Socket Initialization and Cleanup&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md476',1,'']]],
  ['tests_26',['Building and Running Tests',['../group__BUILD__AND__USAGE.html#autotoc_md12',1,'']]],
  ['tests_3a_27',['Tests:',['../group__unit__tests.html#autotoc_md472',1,'1. &lt;b&gt;Unit Tests&lt;/b&gt;:'],['../group__unit__tests.html#autotoc_md477',1,'2. &lt;b&gt;Integration Tests&lt;/b&gt;:'],['../group__unit__tests.html#autotoc_md481',1,'3.1 &lt;b&gt;Using CMake for Platform-Specific Tests&lt;/b&gt;:'],['../group__unit__tests.html#autotoc_md482',1,'4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:']]],
  ['the_20basics_28',['🧠 Beyond the Basics',['../group__address__reuse.html#autotoc_md149',1,'']]],
  ['the_20connect_20function_29',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md83',1,'']]],
  ['the_20connectionless_20approach_30',['Datagrams: The Connectionless Approach',['../group__network__data__units.html#autotoc_md316',1,'']]],
  ['the_20constructor_31',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['the_20default_20buffer_20size_32',['What is the default buffer size?',['../index.html#autotoc_md564',1,'']]],
  ['the_20foundation_33',['The Foundation',['../group__mastering__ipv4.html#autotoc_md37',1,'IPv4 Address Structure: The Foundation'],['../group__mastering__ipv6.html#autotoc_md46',1,'IPv6 Address Structure: The Foundation']]],
  ['the_20foundations_3a_20network_20models_20and_20data_20encapsulation_34',['The Foundations: Network Models and Data Encapsulation',['../group__network__data__units.html#autotoc_md314',1,'']]],
  ['the_20full_20ipv4_20picture_35',['Wrapping It Up: The Full IPv4 Picture',['../group__mastering__ipv4.html#autotoc_md44',1,'']]],
  ['the_20full_20ipv6_20picture_36',['Wrapping It Up: The Full IPv6 Picture',['../group__mastering__ipv6.html#autotoc_md53',1,'']]],
  ['the_20hood_3a_20how_20socket_20types_20work_37',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md414',1,'']]],
  ['the_20hood_3a_20how_20sockets_20operate_38',['5. Under the Hood: How Sockets Operate',['../group__sockets__theory.html#autotoc_md428',1,'']]],
  ['the_20jsocketpp_20approach_3a_20port_20in_20constructor_20bind_20listen_20explicit_39',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md60',1,'']]],
  ['the_20library_40',['the Library',['../group__BUILD__AND__USAGE.html#autotoc_md6',1,'Building the Library'],['../group__BUILD__AND__USAGE.html#autotoc_md14',1,'Linking the Library']]],
  ['the_20lifecycle_41',['4. How Sockets Work: The Lifecycle',['../group__sockets__theory.html#autotoc_md424',1,'']]],
  ['the_20local_20binding_20persist_20for_20the_20socket’s_20lifetime_42',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['the_20makefile_43',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['the_20mtu_44',['🔍 What is the MTU?',['../group__udp.html#autotoc_md677',1,'']]],
  ['the_20port_20in_20the_20constructor_45',['Why require the port in the constructor?',['../group__ServerSocket__Lifecycle.html#autotoc_md61',1,'']]],
  ['the_20port_20locally_46',['4. Test the Port Locally',['../group__vcpkg__publish__guide.html#autotoc_md497',1,'']]],
  ['the_20recipe_20locally_47',['4. Test the Recipe Locally',['../group__conan__publish__guide.html#autotoc_md209',1,'']]],
  ['the_20reliable_20counterpart_20in_20tcp_48',['Segments: The Reliable Counterpart in TCP',['../group__network__data__units.html#autotoc_md317',1,'']]],
  ['the_20role_20of_20the_20connect_20function_49',['The Role of the &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Function',['../group__socket__binding.html#autotoc_md83',1,'']]],
  ['the_20same_20port_50',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['the_20shift_20to_20classless_20routing_51',['CIDR: The Shift to Classless Routing',['../group__mastering__ipv4.html#autotoc_md38',1,'']]],
  ['the_20socket’s_20lifetime_52',['Does the Local Binding Persist for the Socket’s Lifetime?',['../group__socket__binding.html#autotoc_md90',1,'']]],
  ['the_20socket_20api_53',['the Socket API',['../group__underlying__socket__api.html#autotoc_md441',1,'1. Introduction to the Socket API'],['../group__underlying__socket__api.html#autotoc_md442',1,'2. Core Components of the Socket API'],['../group__underlying__socket__api.html#autotoc_md450',1,'4. Protocols and the Socket API']]],
  ['the_20vcpkg_20registry_54',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md499',1,'']]],
  ['this_20is_20problematic_20on_20windows_55',['Why This is Problematic on Windows',['../group__address__reuse.html#autotoc_md129',1,'']]],
  ['this_20library_56',['1. jsocketpp (this library)',['../group__socket__library__comparison.html#autotoc_md371',1,'']]],
  ['this_20matters_57',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md635',1,'']]],
  ['this_20relates_20to_20jsocketpp_58',['How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;',['../group__socket__states.html#autotoc_md397',1,'']]],
  ['thoughts_20and_20best_20practices_59',['🧠 Final Thoughts and Best Practices',['../group__async__io.html#autotoc_md187',1,'']]],
  ['thread_20safety_60',['Thread Safety',['../group__tcp.html#autotoc_md752',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md761',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md770',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md783',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md792',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md808',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md821',1,'⚠️ Thread Safety'],['../group__tcp.html#autotoc_md746',1,'Thread Safety'],['../group__tcp.html#autotoc_md831',1,'Thread Safety'],['../classjsocketpp_1_1Socket.html#autotoc_md840',1,'Thread Safety'],['../group__tcp.html#autotoc_md906',1,'Thread Safety']]],
  ['throws_61',['Throws',['../group__internal.html#autotoc_md622',1,'Throws'],['../group__udp.html#autotoc_md661',1,'Throws']]],
  ['timeout_62',['timeout',['../group__socketopts.html#autotoc_md1087',1,'Example: Set a 3-second receive timeout'],['../group__socketopts.html#autotoc_md1092',1,'Example: Set a 5-second send timeout']]],
  ['timeout_20behavior_63',['Timeout Behavior',['../group__tcp.html#autotoc_md748',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md757',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md766',1,'⏱ Timeout Behavior'],['../group__tcp.html#autotoc_md777',1,'⏱ Timeout Behavior']]],
  ['timeout_20semantics_64',['Timeout Semantics',['../group__tcp.html#autotoc_md830',1,'']]],
  ['timeouts_65',['Timeouts',['../group__async__io.html#autotoc_md163',1,'⏱ How jsocketpp Handles Blocking and Timeouts'],['../group__async__io.html#autotoc_md159',1,'🕐 Socket Timeouts'],['../group__async__io.html#autotoc_md160',1,'OS-Level Timeouts']]],
  ['timeouts_20via_20select_66',['Custom Timeouts via &lt;span class=&quot;tt&quot;&gt;select()&lt;/span&gt;',['../group__async__io.html#autotoc_md161',1,'']]],
  ['tips_20and_20best_20practices_67',['Tips and Best Practices',['../group__vcpkg__publish__guide.html#autotoc_md503',1,'7. Tips and Best Practices'],['../group__conan__publish__guide.html#autotoc_md218',1,'8. Tips and Best Practices']]],
  ['to_68',['to',['../group__core.html#autotoc_md599',1,'Applies to'],['../group__core.html#autotoc_md603',1,'Applies to']]],
  ['to_20a_20local_20address_69',['Does &lt;span class=&quot;tt&quot;&gt;connect()&lt;/span&gt; Bind to a Local Address?',['../group__socket__binding.html#autotoc_md86',1,'']]],
  ['to_20adjust_70',['When to Adjust',['../group__core.html#autotoc_md602',1,'']]],
  ['to_20all_20interfaces”_20mean_71',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md192',1,'']]],
  ['to_20all_20interfaces_72',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md194',1,'']]],
  ['to_20cci_73',['6. Submit a Pull Request to CCI',['../group__conan__publish__guide.html#autotoc_md214',1,'']]],
  ['to_20classless_20routing_74',['CIDR: The Shift to Classless Routing',['../group__mastering__ipv4.html#autotoc_md38',1,'']]],
  ['to_20consider_3a_75',['5. &lt;b&gt;Test Cases to Consider&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md485',1,'']]],
  ['to_20ioctl_20fcntl_20ioctlsocket_76',['Comprehensive Guide to &lt;span class=&quot;tt&quot;&gt;ioctl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;fcntl&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;ioctlsocket&lt;/span&gt;,',['../md_docs_2markdown_2ioctl__fcntl__ioctlsocket__guide.html',1,'']]],
  ['to_20jsocketpp_77',['to jsocketpp',['../md_CONTRIBUTING.html',1,'Contributing to jsocketpp'],['../group__socket__states.html#autotoc_md397',1,'How This Relates to &lt;span class=&quot;tt&quot;&gt;jsocketpp&lt;/span&gt;']]],
  ['to_20linger_20for_205_20seconds_20on_20close_78',['Example: Set &lt;span class=&quot;tt&quot;&gt;SO_LINGER&lt;/span&gt; to linger for 5 seconds on close',['../group__socketopts.html#autotoc_md1025',1,'']]],
  ['to_20mock_20recv_20and_20send_3a_79',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md475',1,'']]],
  ['to_20multicast_20sockets_80',['Introduction to Multicast Sockets',['../group__multicast__sockets.html#autotoc_md283',1,'']]],
  ['to_20peer_20model_81',['3.2 Peer-to-Peer Model',['../group__underlying__socket__api.html#autotoc_md448',1,'']]],
  ['to_20reduce_20latency_82',['Example: Disable Nagle’s algorithm to reduce latency',['../group__socketopts.html#autotoc_md1127',1,'']]],
  ['to_20the_20same_20port_83',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md115',1,'']]],
  ['to_20the_20socket_20api_84',['1. Introduction to the Socket API',['../group__underlying__socket__api.html#autotoc_md441',1,'']]],
  ['to_20the_20vcpkg_20registry_85',['5. Submit to the vcpkg Registry',['../group__vcpkg__publish__guide.html#autotoc_md499',1,'']]],
  ['to_20use_86',['When to Use',['../group__socketopts.html#autotoc_md1180',1,'']]],
  ['toolchain_20support_87',['🔧 Platform &amp;amp; Toolchain Support',['../index.html#autotoc_md516',1,'']]],
  ['tooling_88',['🛠 Developer Tooling',['../index.html#autotoc_md546',1,'']]],
  ['tools_20for_20unit_20testing_20in_20c_2020_3a_89',['Tools for Unit Testing in C++20:',['../group__unit__tests.html#autotoc_md473',1,'']]],
  ['topics_90',['Topics',['../group__sockets__theory.html#autotoc_md434',1,'7. Advanced Topics'],['../group__multicast__sockets.html#autotoc_md303',1,'Advanced Topics']]],
  ['trade_20off_91',['Summary of Java’s Design Trade-Off',['../group__address__reuse.html#autotoc_md131',1,'']]],
  ['traditional_20socket_20initialization_3a_20posix_20approach_92',['1. Traditional Socket Initialization: POSIX Approach',['../group__ServerSocket__Lifecycle.html#autotoc_md56',1,'']]],
  ['traits_93',['Primary Traits',['../buffer__traits_8hpp.html#autotoc_md726',1,'']]],
  ['transfer_94',['3. Data Transfer',['../group__list__bsd__socket__functions.html#autotoc_md28',1,'']]],
  ['transferred_95',['Transferred',['../group__udp.html#autotoc_md665',1,'Ownership Transferred'],['../group__udp.html#autotoc_md663',1,'What Is Transferred']]],
  ['transitions_96',['TCP State Transitions',['../group__socket__states.html#autotoc_md391',1,'']]],
  ['troubleshooting_97',['Troubleshooting',['../group__BUILD__AND__USAGE.html#autotoc_md20',1,'']]],
  ['troubleshooting_20common_20issues_98',['Troubleshooting Common Issues',['../group__multicast__sockets.html#autotoc_md310',1,'']]],
  ['true_99',['🌐 Local Binding Parameters (used only if &lt;span class=&quot;tt&quot;&gt;autoBind == true&lt;/span&gt;)',['../group__tcp.html#autotoc_md858',1,'']]],
  ['true_20matters_100',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md835',1,'']]],
  ['ttl_20and_20scope_20control_101',['TTL and Scope Control',['../group__multicast__sockets.html#autotoc_md305',1,'']]],
  ['type_102',['Type',['../group__socketopts.html#autotoc_md1151',1,'🌍 Applicability by Socket Type'],['../group__socketopts.html#autotoc_md1160',1,'🌍 Applicability by Socket Type'],['../group__socket-options.html#autotoc_md349',1,'Common Options by Socket Type']]],
  ['types_103',['Types',['../group__socketopts.html#autotoc_md1107',1,'📦 Applicable Socket Types'],['../group__underlying__socket__api.html#autotoc_md445',1,'2.3 Socket Types'],['../group__sockets__theory.html#autotoc_md412',1,'2.5. Comparison Table: Socket Types'],['../group__tcp.html#autotoc_md904',1,'Supported Types']]],
  ['types_20of_20ip_20addresses_3a_20unicast_20multicast_20broadcast_20and_20anycast_104',['Types of IP Addresses: Unicast, Multicast, Broadcast, and Anycast',['../group__mastering__ipv4.html#autotoc_md40',1,'']]],
  ['types_20of_20sockets_20in_20depth_105',['2. Types of Sockets (In-Depth)',['../group__sockets__theory.html#autotoc_md406',1,'']]],
  ['types_20work_106',['2.6. Under the Hood: How Socket Types Work',['../group__sockets__theory.html#autotoc_md414',1,'']]],
  ['types_3a_20unicast_20multicast_20anycast_20and_20more_107',['Address Types: Unicast, Multicast, Anycast, and More',['../group__mastering__ipv6.html#autotoc_md49',1,'']]],
  ['typical_20usage_108',['Typical Usage',['../classjsocketpp_1_1ServerSocket.html#autotoc_md740',1,'']]],
  ['typical_20usage_20example_109',['Typical Usage Example',['../classjsocketpp_1_1Socket.html#autotoc_md837',1,'']]],
  ['typical_20use_20cases_110',['🧰 Typical Use Cases',['../index.html#autotoc_md510',1,'']]]
];
