var searchData=
[
  ['echo_20server_0',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md459',1,'']]],
  ['echo_20server_20and_20client_1',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['enforcement_2',['Enforcement',['../md_build_2md__files_2CODE__OF__CONDUCT.html#autotoc_md5',1,'']]],
  ['epoll_3',['4. &lt;b&gt;Advantages of &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt;&lt;/b&gt;',['../group__select__poll__epoll__iocp.html#autotoc_md246',1,'']]],
  ['epoll_20as_20alternatives_4',['We use &lt;span class=&quot;tt&quot;&gt;select&lt;/span&gt; for asynchronous I/O operations. Does it make sense to provide &lt;span class=&quot;tt&quot;&gt;poll&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;epoll&lt;/span&gt; as alternatives?',['../group__select__poll__epoll__iocp.html#autotoc_md238',1,'']]],
  ['error_20handling_5',['Error Handling',['../group__tcp.html#autotoc_md440',1,'Error Handling'],['../classjsocketpp_1_1Socket.html#autotoc_md451',1,'Error Handling']]],
  ['example_6',['Example',['../classjsocketpp_1_1SocketTimeoutException.html#autotoc_md457',1,'Example'],['../index.html#autotoc_md36',1,'TCP Example'],['../classjsocketpp_1_1Socket.html#autotoc_md449',1,'Typical Usage Example'],['../index.html#autotoc_md37',1,'UDP Example'],['../group__BUILD__AND__USAGE.html#autotoc_md66',1,'Usage Example'],['../group__tcp.html#autotoc_md435',1,'Usage Example'],['../group__tcp.html#autotoc_md441',1,'Usage Example']]],
  ['example_20behavior_7',['🛠️ Example behavior',['../group__address__reuse.html#autotoc_md118',1,'']]],
  ['example_20of_20a_20simple_20server_20client_20integration_20test_3a_8',['Example of a Simple Server-Client Integration Test:',['../group__unit__tests.html#autotoc_md394',1,'']]],
  ['example_20portfile_20cmake_9',['Example &lt;span class=&quot;tt&quot;&gt;portfile.cmake&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md410',1,'']]],
  ['example_20receiving_10',['Usage Example (Receiving)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md427',1,'']]],
  ['example_20sending_11',['Usage Example (Sending)',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md428',1,'']]],
  ['example_20usage_12',['7. Example Usage',['../group__ServerSocket__Lifecycle.html#autotoc_md96',1,'']]],
  ['example_20use_3a_13',['Example Use:',['../group__async__io.html#autotoc_md204',1,'']]],
  ['example_20vcpkg_20json_14',['Example &lt;span class=&quot;tt&quot;&gt;vcpkg.json&lt;/span&gt;',['../group__vcpkg__publish__guide.html#autotoc_md409',1,'']]],
  ['example_20with_20google_20mock_3a_15',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md398',1,'']]],
  ['example_3a_20binding_20to_20all_20interfaces_16',['Example: Binding to All Interfaces',['../group__bind__interfaces.html#autotoc_md210',1,'']]],
  ['example_3a_20catching_20and_20handling_20socket_20exceptions_17',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md456',1,'']]],
  ['example_3a_20simple_20client_18',['Example: Simple Client',['../classjsocketpp_1_1UnixSocket.html#autotoc_md460',1,'']]],
  ['example_3a_20simple_20echo_20server_19',['Example: Simple Echo Server',['../classjsocketpp_1_1UnixSocket.html#autotoc_md459',1,'']]],
  ['example_3a_20simple_20udp_20echo_20server_20and_20client_20',['Example: Simple UDP Echo Server and Client',['../classjsocketpp_1_1DatagramSocket.html#autotoc_md424',1,'']]],
  ['example_3a_20using_20google_20mock_20to_20mock_20recv_20and_20send_3a_21',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md390',1,'']]],
  ['examples_22',['Examples',['../group__underlying__socket__api.html#autotoc_md366',1,'5. Socket API in Action: Practical Examples'],['../group__socket-options.html#autotoc_md278',1,'Examples']]],
  ['exceptions_23',['Example: Catching and Handling Socket Exceptions',['../classjsocketpp_1_1SocketException.html#autotoc_md456',1,'']]],
  ['explicit_24',['3. The jsocketpp Approach: Port in Constructor, Bind/Listen Explicit',['../group__ServerSocket__Lifecycle.html#autotoc_md81',1,'']]],
  ['expose_20windows_20so_5freuseaddr_25',['Why Not Expose Windows &lt;span class=&quot;tt&quot;&gt;SO_REUSEADDR&lt;/span&gt;?',['../group__address__reuse.html#autotoc_md155',1,'']]]
];
