var searchData=
[
  ['macos_20unix_0',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md312',1,'']]],
  ['main_20features_1',['Main Features',['../classjsocketpp_1_1UnixSocket.html#autotoc_md1149',1,'']]],
  ['main_20tcp_20socket_20states_2',['Main TCP Socket States',['../group__socket__states.html#autotoc_md270',1,'']]],
  ['make_20your_20cmake_20project_20conan_20friendly_3',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md189',1,'']]],
  ['makefile_4',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['management_5',['Management',['../group__list__bsd__socket__functions.html#autotoc_md26',1,'1. Core Socket Creation and Management'],['../group__tcp.html#autotoc_md904',1,'Resource Management']]],
  ['manual_20cmake_20build_6',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['manual_20compilation_7',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['manual_20integration_8',['🔧 Manual Integration',['../index.html#autotoc_md410',1,'']]],
  ['manual_20nesting_9',['Example: Manual nesting',['../classjsocketpp_1_1SocketException.html#autotoc_md966',1,'']]],
  ['mapped_20ipv6_20behavior_10',['IPv4-Mapped IPv6 Behavior',['../group__tcp.html#autotoc_md831',1,'']]],
  ['mapping_11',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md421',1,'']]],
  ['matters_12',['Why This Matters',['../namespacejsocketpp_1_1internal.html#autotoc_md509',1,'']]],
  ['matters_13',['When &lt;span class=&quot;tt&quot;&gt;true&lt;/span&gt; matters',['../group__socketopts.html#autotoc_md800',1,'']]],
  ['mean_14',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md174',1,'']]],
  ['mechanism_15',['🔧 Internal Mechanism',['../group__internal.html#autotoc_md502',1,'']]],
  ['methods_16',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md242',1,'']]],
  ['methods_20vs_20generic_20methods_17',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md242',1,'']]],
  ['miscellaneous_18',['7. Miscellaneous',['../group__list__bsd__socket__functions.html#autotoc_md32',1,'']]],
  ['misconceptions_20and_20caveats_19',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md81',1,'']]],
  ['mock_20example_20with_20google_20mock_3a_20',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md364',1,'']]],
  ['mock_20recv_20and_20send_3a_21',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md356',1,'']]],
  ['mock_20to_20mock_20recv_20and_20send_3a_22',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md356',1,'']]],
  ['mock_3a_23',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md364',1,'']]],
  ['mocking_20or_20stubbing_20socket_20api_20for_20unit_20tests_3a_24',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md363',1,'']]],
  ['mocking_20socket_20behavior_3a_25',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md355',1,'']]],
  ['mocking_3a_26',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md365',1,'']]],
  ['mode_27',['Mode',['../group__udp.html#autotoc_md590',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md604',1,'🔁 Behavior Based on Connection Mode'],['../group__udp.html#autotoc_md597',1,'🔁 Behavior Based on Mode'],['../group__udp.html#autotoc_md674',1,'🔁 Behavior Based on Mode'],['../group__udp.html#autotoc_md594',1,'Example (Unconnected Mode)'],['../group__udp.html#autotoc_md601',1,'Example (Unconnected Mode)'],['../group__udp.html#autotoc_md608',1,'Example (Unconnected Mode)']]],
  ['mode_20on_20a_20client_20socket_28',['Example: Enable non-blocking mode on a client socket',['../group__socketopts.html#autotoc_md1078',1,'']]],
  ['mode_3a_29',['mode:',['../group__async__io.html#autotoc_md150',1,'Blocking mode:'],['../group__async__io.html#autotoc_md154',1,'Blocking mode:'],['../group__async__io.html#autotoc_md158',1,'Blocking mode:'],['../group__async__io.html#autotoc_md161',1,'Blocking mode:'],['../group__async__io.html#autotoc_md151',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md155',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md159',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md162',1,'Non-blocking mode:']]],
  ['model_30',['Model',['../group__underlying__socket__api.html#autotoc_md328',1,'3.1 Client-Server Model'],['../group__underlying__socket__api.html#autotoc_md329',1,'3.2 Peer-to-Peer Model']]],
  ['models_31',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md327',1,'']]],
  ['modern_20c_2020_32',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['modes_33',['Modes',['../group__udp.html#autotoc_md518',1,'🔁 Connection Modes'],['../group__udp.html#autotoc_md630',1,'🔁 Connection Modes'],['../group__tcp.html#autotoc_md863',1,'Connection Modes'],['../group__tcp.html#autotoc_md905',1,'Shutdown Modes'],['../group__udp.html#autotoc_md540',1,'Usage Modes']]],
  ['modes_20of_20operation_34',['Modes of Operation',['../group__tcp.html#autotoc_md945',1,'']]],
  ['module_35',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md258',1,'']]],
  ['more_20resources_36',['More Resources',['../group__socket__states.html#autotoc_md280',1,'']]],
  ['move_20assignment_37',['Example: Move assignment',['../group__socketopts.html#autotoc_md1146',1,'']]],
  ['mtu_38',['🔍 What is the MTU?',['../group__udp.html#autotoc_md647',1,'']]],
  ['multicast_39',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md698',1,'']]],
  ['multicast_20and_20broadcast_40',['Multicast and Broadcast',['../group__underlying__socket__api.html#autotoc_md338',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md348',1,'6.3 Multicast and Broadcast']]],
  ['multicast_20receiver_41',['🌐 Multicast Receiver',['../index.html#autotoc_md417',1,'']]],
  ['multicast_3a_42',['For Multicast:',['../group__socket-options.html#autotoc_md236',1,'']]],
  ['multicastsocket_43',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md235',1,'']]],
  ['multiple_20sockets_20bind_20to_20the_20same_20port_44',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md97',1,'']]]
];
