var searchData=
[
  ['macos_20unix_0',['6.1. POSIX (Linux, macOS, Unix)',['../group__sockets__theory.html#autotoc_md289',1,'']]],
  ['main_20features_1',['Main Features',['../classjsocketpp_1_1UnixSocket.html#autotoc_md607',1,'']]],
  ['main_20tcp_20socket_20states_2',['Main TCP Socket States',['../group__socket__states.html#autotoc_md247',1,'']]],
  ['make_20your_20cmake_20project_20conan_20friendly_3',['3. Make Your CMake Project Conan-Friendly',['../group__conan__publish__guide.html#autotoc_md166',1,'']]],
  ['makefile_4',['Using the Makefile',['../group__BUILD__AND__USAGE.html#autotoc_md9',1,'']]],
  ['management_5',['Resource Management',['../group__tcp.html#autotoc_md542',1,'']]],
  ['manual_20cmake_20build_6',['Manual CMake Build',['../group__BUILD__AND__USAGE.html#autotoc_md8',1,'']]],
  ['manual_20compilation_7',['Manual Compilation',['../group__BUILD__AND__USAGE.html#autotoc_md10',1,'']]],
  ['manual_20integration_8',['🔧 Manual Integration',['../index.html#autotoc_md387',1,'']]],
  ['mapping_9',['🔄 Java ↔ jsocketpp Class Mapping',['../index.html#autotoc_md398',1,'']]],
  ['mean_10',['What Does “Binding to All Interfaces” Mean?',['../group__bind__interfaces.html#autotoc_md151',1,'']]],
  ['methods_11',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md219',1,'']]],
  ['methods_20vs_20generic_20methods_12',['Dedicated Methods vs. Generic Methods',['../group__socket-options.html#autotoc_md219',1,'']]],
  ['misconceptions_20and_20caveats_13',['⚠️ Misconceptions and caveats',['../group__address__reuse.html#autotoc_md58',1,'']]],
  ['mock_20example_20with_20google_20mock_3a_14',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md341',1,'']]],
  ['mock_20recv_20and_20send_3a_15',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['mock_20to_20mock_20recv_20and_20send_3a_16',['Example: Using Google Mock to Mock &lt;span class=&quot;tt&quot;&gt;recv&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;send&lt;/span&gt;:',['../group__unit__tests.html#autotoc_md333',1,'']]],
  ['mock_3a_17',['Mock Example with Google Mock:',['../group__unit__tests.html#autotoc_md341',1,'']]],
  ['mocking_20or_20stubbing_20socket_20api_20for_20unit_20tests_3a_18',['4. &lt;b&gt;Mocking or Stubbing Socket API for Unit Tests&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md340',1,'']]],
  ['mocking_20socket_20behavior_3a_19',['1.1 &lt;b&gt;Mocking Socket Behavior&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md332',1,'']]],
  ['mocking_3a_20',['4.1 &lt;b&gt;Integration Test with Mocking&lt;/b&gt;:',['../group__unit__tests.html#autotoc_md342',1,'']]],
  ['mode_3a_21',['mode:',['../group__async__io.html#autotoc_md127',1,'Blocking mode:'],['../group__async__io.html#autotoc_md131',1,'Blocking mode:'],['../group__async__io.html#autotoc_md135',1,'Blocking mode:'],['../group__async__io.html#autotoc_md138',1,'Blocking mode:'],['../group__async__io.html#autotoc_md128',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md132',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md136',1,'Non-blocking mode:'],['../group__async__io.html#autotoc_md139',1,'Non-blocking mode:']]],
  ['model_22',['Model',['../group__underlying__socket__api.html#autotoc_md305',1,'3.1 Client-Server Model'],['../group__underlying__socket__api.html#autotoc_md306',1,'3.2 Peer-to-Peer Model']]],
  ['models_23',['3. Communication Models',['../group__underlying__socket__api.html#autotoc_md304',1,'']]],
  ['modern_20c_2020_24',['jsocketpp: Java-Style Cross-Platform Socket Library for Modern C++20',['../index.html',1,'']]],
  ['modes_25',['Modes',['../group__tcp.html#autotoc_md501',1,'Connection Modes'],['../group__tcp.html#autotoc_md543',1,'Shutdown Modes']]],
  ['modes_20of_20operation_26',['Modes of Operation',['../group__tcp.html#autotoc_md602',1,'']]],
  ['module_27',['4. Qt Network Module',['../group__socket__library__comparison.html#autotoc_md235',1,'']]],
  ['more_20resources_28',['More Resources',['../group__socket__states.html#autotoc_md257',1,'']]],
  ['multicast_29',['What is Multicast?',['../classjsocketpp_1_1MulticastSocket.html#autotoc_md473',1,'']]],
  ['multicast_20and_20broadcast_30',['Multicast and Broadcast',['../group__underlying__socket__api.html#autotoc_md315',1,'6.3 Multicast and Broadcast'],['../group__underlying__socket__api.html#autotoc_md325',1,'6.3 Multicast and Broadcast']]],
  ['multicast_20receiver_31',['🌐 Multicast Receiver',['../index.html#autotoc_md394',1,'']]],
  ['multicast_3a_32',['For Multicast:',['../group__socket-options.html#autotoc_md213',1,'']]],
  ['multicastsocket_33',['3. UDP Sockets (&lt;span class=&quot;tt&quot;&gt;DatagramSocket&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;MulticastSocket&lt;/span&gt;)',['../group__socket-options.html#autotoc_md212',1,'']]],
  ['multiple_20sockets_20bind_20to_20the_20same_20port_34',['🧪 What Happens When Multiple Sockets Bind to the Same Port?',['../group__address__reuse.html#autotoc_md74',1,'']]]
];
